import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('components/assess-v2/AssessV2ReviewWorkspace.tsx', 'utf8');
assert.match(source, /Assigned-review queue/);
assert.match(source, /Exact claims:/);
assert.match(source, /Accept evidence/);
assert.match(source, /Request more information/);
assert.match(source, /Reject evidence/);
assert.match(source, /Approve reviewed decision/);
assert.match(source, /Request changes/);
assert.match(source, /Avala Govern action and control review/);
assert.match(source, /Create durable Studio handoff/);
for (const state of ['Offline', 'stale', 'revoked', 'conflicted', 'Read-only mode', 'Persistence failed']) assert.match(source, new RegExp(state, 'i'));
assert.ok(source.indexOf('const committed = await action()') < source.indexOf('setMessage(success)'), 'success must render only after a committed response');
assert.doesNotMatch(source, /reviewerId\s*:/);
assert.match(source, /Browser-supplied handoff content is never accepted/);
assert.match(source, /aria-live="polite"/);
assert.match(source, /aria-label="Assigned-review queue"/);
assert.match(source, /sm:grid-cols-2/);
console.log('Assess V2 enterprise review workspace source suite passed.');
