import { strict as assert } from 'assert';
import { renderEconomicsWorkspaceModel } from './AssessV2EconomicsWorkspace';
import { ECONOMIC_FORMULA_VERSION, ECONOMIC_MODEL_VERSION, EconomicVersion } from '../../services/assessV2/economics/domain';
const ev={id:'e',fresh:true,independent:true};
const version:EconomicVersion={organizationId:'o',workspaceId:'w',caseId:'c',sourceAuthoringVersionId:'s',decisionVersionId:'d',approvedReviewId:'r',modelVersion:ECONOMIC_MODEL_VERSION,formulaVersion:ECONOMIC_FORMULA_VERSION,status:'approved',authorId:'a',reviewerId:'b',currency:'USD',baselinePeriod:'2026',analysisHorizonYears:1,implementationHorizonMonths:3,benefits:[{id:'cap',category:'capacity_released',range:{low:1,base:2,high:3,unit:'hours',period:'annual'},evidence:[ev],owner:'ops',confidence:'Verified',includeInCash:false},{id:'cash',category:'avoidable_cash_expenditure',range:{low:10,base:20,high:30,unit:'USD',period:'annual'},evidence:[ev],owner:'fin',confidence:'Verified',includeInCash:true}],costs:[{id:'cost',category:'engineering_integration',range:{low:1,base:2,high:3,unit:'USD',period:'one_time'},evidence:[ev],owner:'eng',confidence:'Verified',includeInCash:true}]};
assert.equal(renderEconomicsWorkspaceModel({offline:true,technicalReady:true,governanceApproved:true}).state,'offline');
assert.equal(renderEconomicsWorkspaceModel({technicalReady:true,governanceApproved:true}).state,'empty');
const model=renderEconomicsWorkspaceModel({version,technicalReady:true,governanceApproved:true,persisted:true});
assert.equal(model.state,'insufficient-calibration-data');assert.match(model.banner,/Capacity release is not guaranteed savings/);assert.equal(model.scenarios?.[1].annualAvoidableCashBenefit,20);assert.equal(model.disposition?.disposition,'Proceed to controlled design');
console.log('PR 1F economics workspace tests passed');
