import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import AssessApplicationPortfolioWorkspace,{ committedAssessment, parseApplicationImportRows, renderApplicationPortfolioState, syntheticApplicationPortfolioFixture } from './AssessApplicationPortfolioWorkspace';
assert.equal(renderApplicationPortfolioState({loading:true,applications:[]}).state,'loading');
assert.equal(renderApplicationPortfolioState({offline:true,applications:[]}).state,'offline');
assert.equal(renderApplicationPortfolioState({readOnly:true,applications:[]}).state,'read-only');
assert.equal(renderApplicationPortfolioState({failedPersistence:true,applications:[]}).state,'failed-persistence');
assert.equal(renderApplicationPortfolioState({applications:[]}).state,'empty');
const fixture=syntheticApplicationPortfolioFixture();assert.equal(fixture.length,3);assert.equal(fixture[0].version,1);assert.equal(fixture[0].metadata.synthetic,true);
const parsed=parseApplicationImportRows(JSON.stringify([{name:'valid'},{name:''},{unexpected:true}]));assert.equal(parsed.length,3,'invalid domain rows remain server input');
assert.throws(()=>parseApplicationImportRows(JSON.stringify(Array.from({length:501},()=>({name:'x'})))),/IMPORT_ROW_LIMIT/);
const projection:any={inventory:[],metadataVersions:[],processLinks:[],dependencies:[],dimensions:[],recommendations:[],reviews:[],waves:[],economicsReferences:[],rowOutcomes:[],assessments:[{id:'draft-id',applicationId:'app-id',orgId:'org',workspaceId:'workspace',metadataVersion:2,version:1,status:'draft',authorId:'author',decisionModelVersion:'model'},{id:'reviewer-ready-id',application_id:'app-id',org_id:'org',workspace_id:'workspace',metadata_version:2,version:2,lifecycle:'reviewer_ready',author_id:'author',decision_model_version:'model'}]};
assert.equal(committedAssessment(projection,['reviewer_ready'])?.id,'reviewer-ready-id');assert.equal(committedAssessment(projection,['reviewer_ready'])?.version,2);
const tenant={userId:'u',organizationId:'o',organizationName:'Org',workspaceId:'w',workspaceName:'Ws',authorizationVersion:1,capabilities:['assess.applications.read','assess.applications.write','assess.applications.import','assess.applications.finalize','assess.applications.review','assess.applications.portfolio.read']};
const html=renderToStaticMarkup(React.createElement(AssessApplicationPortfolioWorkspace,{tenantContext:tenant as any,transport:{loadProjection:async()=>projection,invoke:async()=>({outcome:'committed' as const,resource:{id:'server',version:1,status:'draft'}})}}));
for(const name of ['Create portfolio application','Save portfolio metadata','Import portfolio rows','Save portfolio assessment','Submit portfolio assessment for review','Record portfolio review decision','Create revised portfolio assessment','Generate application modernization snapshot','Show synthetic AP fixture'])assert.match(html,new RegExp(name));
for(const stale of ['Create manual application','Save metadata version','>Import rows<','>Finalize<','>Approve<','>Review<','>Start revision<','Create portfolio snapshot'])assert.doesNotMatch(html,new RegExp(stale));
console.log('PR 1G application portfolio workspace authority tests passed.');
