import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';

const open=async(page:import('@playwright/test').Page,state='ready')=>{await page.goto(`/tests/browser/pilotOperationsHarness.html?state=${state}`);await page.getByRole('button',{name:/Pilot Operations/}).click()};
// This multi-command flow plus whole-panel Axe scan is functional, not a performance gate.
test('actual Admin Workbench projects safe server truth and governed command success',async({page})=>{test.setTimeout(60_000);await open(page);await expect(page.getByRole('heading',{name:'Admin Workbench'})).toBeVisible();const panel=page.getByRole('region',{name:'Pilot Operations',exact:true});await expect(panel).toBeVisible();await expect(panel.getByRole('heading',{name:'Pilot Operations',exact:true})).toBeVisible();await expect(panel.getByText(/Hosted\/live activation is not authorized/)).toBeVisible();await expect(panel.getByText(/Eligible to the exact prior candidate Candidate 66666666/)).toBeVisible();await expect(page.getByRole('button',{name:'rollback'})).toBeEnabled();await page.getByRole('button',{name:'rollback'}).click();await expect(page.getByRole('status')).toContainText('Authoritative command committed');await expect(page.getByRole('button',{name:'simulate promotion'})).toBeEnabled();await page.getByRole('button',{name:'simulate promotion'}).click();await expect(page.getByRole('status')).toContainText('Authoritative command committed');await page.getByRole('button',{name:'read only'}).click();await expect(page.getByRole('status')).toContainText('Authoritative command committed');await expect(page.getByText(/Read-only on/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter(item=>['serious','critical'].includes(item.impact||''))).toEqual([])});
test('actual Admin Workbench owns loading, error, revoked and control states',async({page})=>{await open(page,'loading');await expect(page.getByText(/Loading authoritative/)).toBeVisible();await expect(page.getByRole('heading',{name:'Pilot Operations',exact:true})).toBeVisible();for(const state of ['error','revoked'] as const){await open(page,state);await expect(page.getByRole('alert')).toContainText(state==='error'?'PERSISTENCE_UNAVAILABLE':'ACCESS_DENIED')}for(const state of ['read_only','maintenance'] as const){await open(page,state);await expect(page.getByText(new RegExp(state==='read_only'?'Read-only on':'Maintenance on'))).toBeVisible()}await open(page,'global_read_only');await expect(page.getByText(/Backup: passed/)).toBeVisible();await expect(page.getByRole('button',{name:'simulate promotion'})).toBeDisabled();await page.keyboard.press('Tab');await expect(page.locator(':focus')).toBeVisible()});
test('actual Admin Workbench shows stale, revoked and blocked command denial without false success',async({page})=>{for(const [state,code] of [['stale','VERSION_CONFLICT'],['denied','ACCESS_DENIED'],['blocked','ENVIRONMENT_BLOCKED']] as const){await open(page,state);await expect(page.getByRole('heading',{name:'Pilot Operations',exact:true,level:2})).toBeVisible();await page.getByRole('button',{name:'read only'}).click();await expect(page.getByText(code)).toBeVisible();await expect(page.getByText(/Authoritative command committed/)).toHaveCount(0)}});
test('actual Admin Workbench preserves a valid environment with no release and blocks targetless commands',async({page})=>{await open(page,'no_release');const panel=page.getByRole('region',{name:'Pilot Operations',exact:true});await expect(panel.getByText('No release candidate registered.')).toBeVisible();await expect(panel.getByText(/Read-only on/)).toBeVisible();await expect(panel.getByText(/Backup: not_run/)).toBeVisible();await expect(panel.getByText(/Restore: not_run/)).toBeVisible();for(const name of ['validate','approve','simulate promotion','rollback'])await expect(panel.getByRole('button',{name})).toBeDisabled();await expect(panel.getByRole('button',{name:'maintenance'})).toBeEnabled();await expect(panel.getByRole('button',{name:'read only'})).toBeEnabled();await panel.getByRole('button',{name:'validate'}).evaluate((button:HTMLButtonElement)=>button.click());expect(await page.evaluate(()=>(window as unknown as {__pilotOperationsCalls:{command:number}}).__pilotOperationsCalls.command)).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)});
test('actual Admin Workbench removes every command when the observer lacks action capabilities',async({page})=>{await open(page,'observer');const panel=page.getByRole('region',{name:'Pilot Operations',exact:true});for(const name of ['validate','approve','simulate promotion','maintenance','read only','rollback'])await expect(panel.getByRole('button',{name})).toBeDisabled();await panel.getByRole('button',{name:'maintenance'}).evaluate((button:HTMLButtonElement)=>button.click());expect(await page.evaluate(()=>(window as unknown as {__pilotOperationsCalls:{query:number;command:number}}).__pilotOperationsCalls)).toEqual({query:1,command:0})});
