import AxeBuilder from '@axe-core/playwright';
import { expect, Page, test } from '@playwright/test';
import { assessApplication, APPLICATION_PORTFOLIO_MODEL_VERSION, type ApplicationMetadata, type ApplicationRecord } from '../../services/assessV2/applicationPortfolio';
import type { ApplicationProjection, AssessmentVersionDto } from '../../services/assessV2ApplicationPortfolioClient';

const AUTHOR='11111111-1111-4111-8111-111111111111',REVIEWER='11111111-1111-4111-8111-111111111112',ORG='22222222-2222-4222-8222-222222222222',WS='33333333-3333-4333-8333-333333333333';
const API='http://127.0.0.1:59999';
const PREVIEW_ORIGINS=new Set(['http://127.0.0.1:4186','http://127.0.0.1:4173']);
const headers={'access-control-allow-origin':'*','access-control-allow-headers':'*','content-type':'application/json'};
const metadata=(name:string):ApplicationMetadata=>({name,description:`${name} committed application`,businessOwner:'Finance Operations',technicalOwner:'Enterprise Platforms',vendor:'Avala Synthetic',businessCapabilities:['Accounts payable','Exception management'],supportedProcesses:['Invoice exception handling','Supplier reconciliation'],businessCriticality:'mission_critical',lifecycleState:'maintenance',product:'API Suite',version:'2026.7',eolStatus:'eol_announced',hostingModel:'private-cloud',platform:['web','linux'],languages:['TypeScript','SQL'],frameworks:['Express','React'],sourceCode:'available_legal_access',documentationQuality:'high',automatedTestMaturity:'executable_acceptance',deploymentRepeatability:'deterministic',observability:'strong',dataClassifications:['Internal','Financial'],regulatedData:true,operatingRegions:['US','EU'],interfaces:['REST/GraphQL','messaging/event'],upstreamDependencies:['Identity platform'],downstreamDependencies:['Payment orchestration'],realTime:true,eventDriven:true,synchronous:true,batch:true,bridgeEvidence:{stableInterface:true,controlAccessibility:true,deterministicErrorDetection:true,reversibilityOrCompensation:true,materialActionApproval:true,monitoring:true,humanOwner:true},aiControls:{legalSourceRights:true,executableAcceptanceTests:true,reproducibleBuild:true,controlledSecurityReview:true,humanEngineeringOwner:true,controlledDeploymentRollback:true},ageYears:11,synthetic:true});
const evidenceClaims=['integration_accessibility','semantic_and_data_clarity','state_and_execution','security_and_control','architecture_changeability','ui_automation_readiness','ai_assisted_engineering_readiness'] as const;
const completeEvidence=evidenceClaims.map((claim,index)=>({id:`browser-evidence-${index+1}`,claimIds:[claim],sourceType:'test' as const,fresh:true,independent:true,accepted:true,contradicts:false,synthetic:false}));
const caps=['assess.read','assess.v2.read','assess.applications.read','assess.applications.write','assess.applications.import','assess.applications.finalize','assess.applications.review','assess.applications.portfolio.read','assess.applications.portfolio.write'];

async function installFixture(page:Page){
 const user={id:AUTHOR,email:'pr1g@avala.test',role:'authenticated',aud:'authenticated',created_at:'2026-07-22T00:00:00.000Z'};let inventory:ApplicationRecord[]=[];let metadataVersions:ApplicationProjection['metadataVersions']=[];let importReceipts:ApplicationProjection['importReceipts']=[];let rowOutcomes:ApplicationProjection['rowOutcomes']=[];let processLinks:ApplicationProjection['processLinks']=[];let dependencies:ApplicationProjection['dependencies']=[];let assessments:AssessmentVersionDto[]=[];let dimensions:ApplicationProjection['dimensions']=[];let recommendations:ApplicationProjection['recommendations']=[];let reviews:ApplicationProjection['reviews']=[];let portfolioSnapshot:ApplicationProjection['portfolioSnapshot']=null;let waves:ApplicationProjection['waves']=[];let economicsReferences:ApplicationProjection['economicsReferences']=[];let failNext=false;let reviewAttempts=0;let holdProjectionReload=false;let projectionReloadRequested=false;let releaseProjectionReload=()=>{};const commands:any[]=[];
 await page.addInitScript(({user})=>{const now=Math.floor(Date.now()/1000);localStorage.setItem('sb-127-auth-token',JSON.stringify({access_token:'browser-fixture-token',refresh_token:'browser-fixture-refresh',token_type:'bearer',expires_in:3600,expires_at:now+3600,user}));localStorage.setItem('avalaos-core-v1-view',JSON.stringify('process_catalog'));localStorage.setItem('avalaos-core-v1-scope',JSON.stringify({type:'my_work'}));},{user});
 const ok=(route:any,body:any)=>route.fulfill({status:200,headers,body:JSON.stringify(body)});const projection=()=>({inventory,metadataVersions,importReceipts,rowOutcomes,processLinks,dependencies,assessments,dimensions,recommendations,reviews,portfolioSnapshot,waves,economicsReferences});const reject=(route:any,code:string)=>route.fulfill({status:409,headers,body:JSON.stringify({ok:false,error:{code}})});
 await page.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(PREVIEW_ORIGINS.has(url.origin))return route.continue();if(url.origin!==API)return route.abort();if(request.method()==='OPTIONS')return route.fulfill({status:204,headers,body:''});if(url.pathname==='/auth/v1/user'||url.pathname==='/auth/v1/token')return ok(route,user);if(url.pathname==='/functions/v1/tenant-session')return ok(route,{contexts:[{userId:AUTHOR,organizationId:ORG,organizationName:'Avala Enterprise',workspaceId:WS,workspaceName:'Assess Workspace',authorizationVersion:12,capabilities:caps}]});if(url.pathname==='/rest/v1/rpc/pr1g_read_application_portfolio_projection'){if(holdProjectionReload){projectionReloadRequested=true;await new Promise<void>(resolve=>{releaseProjectionReload=resolve});holdProjectionReload=false}return ok(route,projection())}if(url.pathname==='/functions/v1/assess-v2-command'){
   const body=request.postDataJSON() as any;if(failNext){failNext=false;return reject(route,'VERSION_CONFLICT')}const before=JSON.stringify(projection());const fail=(code:string)=>{expect(JSON.stringify(projection())).toBe(before);return reject(route,code)};commands.push(body);const p=body.payload;
   if(body.commandType==='application.create'){if(body.expectedVersion!==0)return fail('VERSION_CONFLICT');inventory=[...inventory,{id:p.applicationId,orgId:ORG,workspaceId:WS,version:1,metadataVersion:0,authorId:AUTHOR,status:'draft',evidence:completeEvidence,metadata:metadata(p.name)}];return ok(route,{ok:true,outcome:'committed',resource:{id:p.applicationId,version:1,status:'draft',name:p.name}})}
   if(body.commandType==='application.metadata.upsert'){const index=inventory.findIndex(a=>a.id===p.applicationId);if(index<0||body.expectedVersion!==inventory[index].metadataVersion||p.metadataVersion!==body.expectedVersion+1)return fail('VERSION_CONFLICT');const next={...inventory[index],metadataVersion:p.metadataVersion,metadata:p.metadata,evidence:p.evidence};inventory=inventory.map((a,i)=>i===index?next:a);metadataVersions=[...metadataVersions,{id:p.metadataVersionId,orgId:ORG,workspaceId:WS,applicationId:p.applicationId,version:p.metadataVersion,status:'draft',metadata:p.metadata,authorId:AUTHOR}];return ok(route,{ok:true,outcome:'committed',resource:{id:p.metadataVersionId,applicationId:p.applicationId,version:p.metadataVersion,status:'draft'}})}
   if(body.commandType==='application.import'){if(body.expectedVersion!==0)return fail('VERSION_CONFLICT');let accepted=0,rejected=0;const receipt=p.importReceiptId;const nextOutcomes=p.rows.map((row:any,index:number)=>{if(!row.name){rejected++;return{id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,importReceiptId:receipt,rowNumber:index+1,outcome:'rejected' as const,applicationId:null,errorCode:'MISSING_APPLICATION_NAME',errorMessage:'Application name is required.'}}const id=`77777777-7777-4777-8777-${String(inventory.length+index+1).padStart(12,'0')}`;accepted++;const importedMetadata={...metadata(row.name),...row};inventory=[...inventory,{id,orgId:ORG,workspaceId:WS,version:1,metadataVersion:1,authorId:AUTHOR,status:'draft',evidence:[],metadata:importedMetadata}];metadataVersions=[...metadataVersions,{id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,applicationId:id,version:1,status:'draft',metadata:importedMetadata,authorId:AUTHOR}];return{id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,importReceiptId:receipt,rowNumber:index+1,outcome:'success' as const,applicationId:id,errorCode:null,errorMessage:null}});rowOutcomes=[...rowOutcomes,...nextOutcomes];importReceipts=[...importReceipts,{id:receipt,orgId:ORG,workspaceId:WS,actorId:AUTHOR,successCount:accepted,rejectionCount:rejected}];return ok(route,{ok:true,outcome:'committed',resource:{id:receipt,version:1,status:'committed',successCount:accepted,rejectionCount:rejected}})}
   if(body.commandType==='application.assessment.save'){if(body.expectedVersion!==0)return fail('VERSION_CONFLICT');const app=inventory.find(a=>a.id===p.applicationId),metadataVersion=metadataVersions.find(m=>m.applicationId===p.applicationId&&m.version===p.metadataVersion);if(!app||!metadataVersion||p.metadataVersion!==app.metadataVersion||p.dimensions||p.recommendations)return fail('INVALID_COMMAND');const derived=assessApplication(app);const saved:AssessmentVersionDto={...derived,id:p.assessmentVersionId,metadataVersionId:metadataVersion.id,version:p.assessmentVersion,status:'draft',authorId:AUTHOR,reviewerId:null,authorizationVersion:12,receiptId:null,auditEventId:null,decisionModelVersion:APPLICATION_PORTFOLIO_MODEL_VERSION};assessments=[...assessments,saved];dimensions=saved.dimensions.map(d=>({id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,applicationId:saved.applicationId,metadataVersionId:metadataVersion.id,assessmentVersionId:saved.id,...d}));recommendations=saved.recommendations.map(r=>({id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,metadataVersionId:metadataVersion.id,assessmentVersionId:saved.id,...r}));processLinks=[{id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,processId:'44444444-4444-4444-8444-444444444444',primitiveId:'invoice-review',applicationId:p.applicationId,metadataVersionId:metadataVersion.id,assessmentVersionId:p.assessmentVersionId,interactionType:'read',governState:'approved',economicsRef:null,economicsCurrency:null}];dependencies=p.dependencies.map((d:any)=>({id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,upstreamApplicationId:d.upstreamApplicationId,downstreamApplicationId:d.downstreamApplicationId,dependencyType:d.dependencyType??'runtime',metadataVersionId:metadataVersion.id}));return ok(route,{ok:true,outcome:'committed',resource:{id:saved.id,applicationId:saved.applicationId,version:saved.version,status:saved.status}})}
   const source=assessments.find(a=>a.id===p.assessmentVersionId);if(['application.assessment.finalize','application.assessment.review.resolve','application.assessment.revision.start'].includes(body.commandType)){if(!source||body.expectedVersion!==source.version)return fail('VERSION_CONFLICT')}
   if(body.commandType==='application.assessment.finalize'){if(source!.status!=='draft')return fail('VERSION_CONFLICT');const next={...source!,id:crypto.randomUUID(),version:source!.version+1,status:'reviewer_ready' as const};assessments=[...assessments,next];return ok(route,{ok:true,outcome:'committed',resource:{id:next.id,applicationId:next.applicationId,version:next.version,status:next.status}})}
   if(body.commandType==='application.assessment.review.resolve'){if(source!.status!=='reviewer_ready')return fail('VERSION_CONFLICT');reviewAttempts++;if(reviewAttempts===1)return fail('PERMISSION_DENIED');const next={...source!,id:crypto.randomUUID(),version:source!.version+1,status:p.resolution,reviewerId:REVIEWER};reviews=[...reviews,{id:crypto.randomUUID(),orgId:ORG,workspaceId:WS,applicationId:source!.applicationId,metadataVersionId:source!.metadataVersionId,assessmentVersionId:source!.id,reviewerId:REVIEWER,authorizationVersion:12,resolution:p.resolution,rationale:p.rationale,conditions:p.conditions,receiptId:crypto.randomUUID(),auditEventId:crypto.randomUUID()}];assessments=[...assessments,next];return ok(route,{ok:true,outcome:'committed',resource:{id:next.id,applicationId:next.applicationId,version:next.version,status:next.status}})}
   if(body.commandType==='application.assessment.revision.start'){if(source!.status!=='changes_requested')return fail('VERSION_CONFLICT');const next={...source!,id:crypto.randomUUID(),version:source!.version+1,status:'draft' as const,authorId:AUTHOR,reviewerId:null};assessments=[...assessments,next];return ok(route,{ok:true,outcome:'committed',resource:{id:next.id,applicationId:next.applicationId,version:next.version,status:next.status}})}
   if(body.commandType==='application.portfolio.snapshot.create'){const expected=portfolioSnapshot?.version??0;if(body.expectedVersion!==expected)return fail('VERSION_CONFLICT');if(new Set(economicsReferences.map(x=>x.currency)).size>1)return fail('INCOMPATIBLE_CURRENCIES');waves=inventory.map((a,index)=>({wave:index+1,applicationId:a.id,approvedAutomatically:false,qualified:false}));portfolioSnapshot={id:p.portfolioSnapshotId,orgId:ORG,workspaceId:WS,version:expected+1,modelVersion:APPLICATION_PORTFOLIO_MODEL_VERSION,approvedAutomatically:false,inventoryCount:inventory.length,waves};return ok(route,{ok:true,outcome:'committed',resource:{id:portfolioSnapshot.id,version:portfolioSnapshot.version,status:'committed'}})}
   return fail('INVALID_COMMAND');
  }if(url.pathname==='/rest/v1/assess_processes')return ok(route,[{id:'44444444-4444-4444-8444-444444444444',org_id:ORG,workspace_id:WS,name:'Invoice exception handling',description:'Resolve invoice exceptions.',owner_id:AUTHOR,department:'Finance',criticality:'High',status:'Not Started'}]);if(url.pathname==='/rest/v1/assessments')return ok(route,[]);return ok(route,[])});
 return{commands,projection,failNext(){failNext=true},holdNextProjectionReload(){projectionReloadRequested=false;holdProjectionReload=true},projectionReloadRequested(){return projectionReloadRequested},releaseProjectionReload(){releaseProjectionReload()},setIncompatibleCurrencies(){economicsReferences=[{referenceId:crypto.randomUUID(),orgId:ORG,workspaceId:WS,currency:'USD'},{referenceId:crypto.randomUUID(),orgId:ORG,workspaceId:WS,currency:'EUR'}]},clearCurrencies(){economicsReferences=[]}};
}

test.describe.configure({timeout:120_000});
test('PR 1G application portfolio workspace committed-state journey',async({page})=>{const fixture=await installFixture(page);await page.goto('/');await expect(page.getByRole('heading',{name:'Process Catalog'})).toBeVisible({timeout:30000});await page.getByRole('button',{name:'View'}).first().click();const workspace=page.locator('[data-testid="application-portfolio-workspace"]');await expect(workspace.getByText('Empty committed application inventory.')).toBeVisible();
 await workspace.getByLabel('Application name').fill('ERP Browser App');await workspace.getByRole('button',{name:'Create portfolio application'}).click();await expect(workspace.getByText(/Application created from committed server response/)).toBeVisible();const app=fixture.projection().inventory[0];expect(app).toMatchObject({id:fixture.commands[0].payload.applicationId,orgId:ORG,workspaceId:WS,version:1,metadataVersion:0,authorId:AUTHOR,status:'draft',metadata:{name:'ERP Browser App',lifecycleState:'maintenance',sourceCode:'available_legal_access'}});
 fixture.holdNextProjectionReload();const saveClick=workspace.getByRole('button',{name:'Save portfolio metadata'}).click();await expect.poll(()=>fixture.projectionReloadRequested()).toBe(true);await expect(workspace.getByText(/Metadata saved and committed projection reloaded/)).toHaveCount(0);const saveCommand=fixture.commands.at(-1);expect(saveCommand).toMatchObject({commandType:'application.metadata.upsert',expectedVersion:0,payload:{applicationId:app.id,metadataVersion:1}});expect(saveCommand.payload.metadata).toEqual(app.metadata);expect(saveCommand.payload.evidence).toEqual(app.evidence);for(const [field,value] of Object.entries(app.metadata)){expect(saveCommand.payload.metadata[field],field).toEqual(value);expect(saveCommand.payload.metadata[field],`${field} regressed`).not.toBeUndefined()}expect(saveCommand.payload.evidence).toHaveLength(completeEvidence.length);fixture.releaseProjectionReload();await saveClick;await expect(workspace.getByText(/Metadata saved and committed projection reloaded/)).toBeVisible();await expect(workspace.getByText('Application v1 · Metadata v1')).toBeVisible();expect(fixture.projection().inventory[0].metadata).toEqual(app.metadata);expect(fixture.projection().inventory[0].evidence).toEqual(app.evidence);
 await workspace.getByLabel('CSV or JSON import').fill('name,description\nCSV Application,Valid CSV');await workspace.getByRole('button',{name:'Import portfolio rows'}).click();await expect(workspace.getByTestId('import-receipt')).toContainText('1 accepted, 0 rejected');
 await workspace.getByLabel('CSV or JSON import').fill(JSON.stringify([{...metadata('JSON Application')},{name:''}]));await workspace.getByRole('button',{name:'Import portfolio rows'}).click();await expect(workspace.getByTestId('import-row-outcomes')).toContainText('Row 2: rejected (MISSING_APPLICATION_NAME)');expect(fixture.commands.at(-1).payload.rows).toHaveLength(2);
 await workspace.getByLabel('Application name').fill('Dependency Application');await workspace.getByRole('button',{name:'Create portfolio application'}).click();await expect(workspace.getByText(/Application created from committed server response/)).toBeVisible();await workspace.getByRole('button',{name:'Save portfolio assessment'}).click();await expect(workspace.getByText(/Assessment saved from committed server response/)).toBeVisible();const saved=fixture.commands.at(-1);const savedIdentity=fixture.projection().assessments.at(-1);expect(saved.payload.dependencies.length).toBeGreaterThan(0);
 await workspace.getByRole('button',{name:'Submit portfolio assessment for review'}).click();await expect(workspace.getByText(/submitted for review and projection reloaded/)).toBeVisible();const ready=fixture.projection().assessments.at(-1);expect(fixture.commands.at(-1)).toMatchObject({payload:{assessmentVersionId:savedIdentity.id},expectedVersion:savedIdentity.version});
 await workspace.getByRole('button',{name:'Record portfolio review decision'}).click();await expect(workspace.getByRole('alert')).toContainText('PERMISSION_DENIED');expect(fixture.projection().reviews).toHaveLength(0);await workspace.getByRole('button',{name:'Record portfolio review decision'}).click();await expect(workspace.getByText(/review decision committed and projection reloaded/)).toBeVisible();expect(fixture.commands.at(-1)).toMatchObject({payload:{assessmentVersionId:ready.id,resolution:'changes_requested'},expectedVersion:ready.version});
 await workspace.getByRole('button',{name:'Create revised portfolio assessment'}).click();await expect(workspace.getByText(/Revised portfolio assessment created/)).toBeVisible();const revised=fixture.projection().assessments.at(-1);await workspace.getByRole('button',{name:'Submit portfolio assessment for review'}).click();await expect(workspace.getByText(/submitted for review and projection reloaded/)).toBeVisible();const revisedReady=fixture.projection().assessments.at(-1);expect(revisedReady.version).toBe(revised.version+1);await workspace.getByRole('button',{name:'Record portfolio review decision'}).click();await expect(workspace.getByText(/review decision committed and projection reloaded/)).toBeVisible();expect(fixture.commands.at(-1)).toMatchObject({payload:{assessmentVersionId:revisedReady.id,resolution:'approved'},expectedVersion:revisedReady.version});
 await expect(workspace.getByText('Committed dimensions and recommendations')).toBeVisible();await expect(workspace.getByText('Process × Application matrix')).toBeVisible();fixture.clearCurrencies();await workspace.getByRole('button',{name:'Generate application modernization snapshot'}).click();await expect(workspace.getByText('Modernization waves')).toBeVisible();fixture.setIncompatibleCurrencies();await workspace.getByRole('button',{name:'Generate application modernization snapshot'}).click();await expect(workspace.getByRole('alert')).toContainText('INCOMPATIBLE_CURRENCIES');fixture.clearCurrencies();fixture.failNext();await workspace.getByRole('button',{name:'Generate application modernization snapshot'}).click();await expect(workspace.getByRole('alert')).toContainText('VERSION_CONFLICT');await expect(workspace.getByText(/snapshot committed/)).toHaveCount(0);
 await workspace.getByRole('button',{name:'Show synthetic AP fixture'}).click();await expect(workspace.getByText(/app-api/)).toBeVisible();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');const axe=await new AxeBuilder({page}).include('[data-testid="application-portfolio-workspace"]').analyze();expect(axe.violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
});
