import { getAuthUser, postgrest } from './supabase.ts';
import { ApplicationAtomicCommand, ApplicationPortfolioDependencies, ApplicationPortfolioError } from './assessV2ApplicationPortfolioCommand.ts';
import { resolveTenantAuthority, TenantAuthorityError } from './tenantAuthority.ts';
import { createTenantAuthorityDatabase } from './tenantAuthorityDb.ts';
export const mapApplicationRpcError=(error:unknown):ApplicationPortfolioError=>{const message=String((error as {message?:unknown;errorCode?:unknown})?.errorCode??(error as {message?:unknown})?.message??error);if(message.includes('READ_ONLY'))return new ApplicationPortfolioError('READ_ONLY');if(message.includes('FEATURE_DISABLED'))return new ApplicationPortfolioError('FEATURE_DISABLED');if(message.includes('AUTHORIZATION_STALE')||message.includes('AUTHORITY_STALE'))return new ApplicationPortfolioError('AUTHORITY_STALE');if(message.includes('VERSION_CONFLICT'))return new ApplicationPortfolioError('VERSION_CONFLICT');if(message.includes('IDEMPOTENCY_CONFLICT'))return new ApplicationPortfolioError('IDEMPOTENCY_CONFLICT');if(message.includes('PERMISSION_DENIED'))return new ApplicationPortfolioError('PERMISSION_DENIED');if(message.includes('NOT_FOUND'))return new ApplicationPortfolioError('RESOURCE_NOT_AVAILABLE');if(message.includes('INVALID_COMMAND'))return new ApplicationPortfolioError('INVALID_COMMAND');return new ApplicationPortfolioError('COMMAND_UNAVAILABLE')};
export const assessV2ApplicationPortfolioDependencies:ApplicationPortfolioDependencies={
 authenticate:getAuthUser,
 async loadFreshAuthority(input){try{const a=await resolveTenantAuthority(input.actorId,{organizationId:input.organizationId,workspaceId:input.workspaceId},createTenantAuthorityDatabase(input.request));return{actorId:a.userId,organizationId:a.organizationId,workspaceId:a.workspaceId,authorizationVersion:a.authorizationVersion,capabilities:a.capabilities}}catch(e){if(e instanceof TenantAuthorityError&&e.code==='TENANT_ACCESS_DENIED')return null;throw e}},
 async executeAtomicApplicationCommand(command:ApplicationAtomicCommand){try{const result=await postgrest<{outcome:'committed'|'replayed';resource:Record<string,unknown>;errorCode?:string}>('rpc/pr1g_execute_application_command',{method:'POST',body:JSON.stringify({p_actor_id:command.actorId,p_org_id:command.organizationId,p_workspace_id:command.workspaceId,p_request_id:command.requestId,p_idempotency_key:command.idempotencyKey,p_authorization_version:command.authorizationVersion,p_expected_version:command.expectedVersion,p_command_type:command.commandType,p_payload:command.payload})});if(result?.errorCode)throw mapApplicationRpcError(result.errorCode);return result}catch(e){if(e instanceof ApplicationPortfolioError)throw e;throw mapApplicationRpcError(e)}},
 async loadApplicationProjection(input){try{return await postgrest<Record<string,unknown>>('rpc/pr1g_read_application_portfolio_projection',{method:'POST',body:JSON.stringify({p_org_id:input.organizationId,p_workspace_id:input.workspaceId})})}catch(e){throw mapApplicationRpcError(e)}}
};
