import { strict as assert } from 'assert';
import { executeEconomicsCommand, parseEconomicsEnvelope, EconomicsDependencies } from './assessV2EconomicsCommand';
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555'];
const [org,ws,caseId,decisionId,econId]=ids;const reqId='66666666-6666-4666-8666-666666666666';
const base={requestId:reqId,idempotencyKey:'econ-key-001',organizationId:org,workspaceId:ws,authorizationVersion:7,expectedVersion:1};
const deps=(caps:string[],actor='author'):EconomicsDependencies=>({authenticate:async()=>({id:actor}),loadFreshAuthority:async()=>({actorId:actor,organizationId:org,workspaceId:ws,authorizationVersion:7,capabilities:caps}),executeAtomicEconomicsCommand:async c=>({outcome:'committed',resource:{id:(c.payload.economicVersionId??c.payload.outcomeId) as string,status:'committed',version:c.expectedVersion+1}})});
async function main(){
const create={...base,commandType:'assessment_v2.economics.create',payload:{caseId,decisionId,economicVersionId:econId,currency:'USD',baselinePeriod:'2026'}};
assert.equal(parseEconomicsEnvelope(create).payload.currency,'USD');
await assert.rejects(()=>executeEconomicsCommand(new Request('http://x'),parseEconomicsEnvelope(create),deps([])),/PERMISSION_DENIED/);
const ok=await executeEconomicsCommand(new Request('http://x'),parseEconomicsEnvelope(create),deps(['assess.v2.economics.write']));assert.equal(ok.resource.id,econId);
const draft={...base,idempotencyKey:'econ-key-002',commandType:'assessment_v2.economics.draft.upsert',payload:{economicVersionId:econId,caseId,decisionId,benefits:[{id:'cash',category:'avoidable_cash_expenditure',range:{low:1,base:2,high:3,unit:'USD',period:'annual'},evidenceIds:['evidence'],owner:'finance',confidence:'Verified',includeInCash:true,nonOverlapExplanation:null}],costs:[],analysisHorizonYears:3,implementationHorizonMonths:6,discountRate:.1}};assert.equal(parseEconomicsEnvelope(draft).payload.analysisHorizonYears,3);
for(const [type,cap] of [['assessment_v2.economics.finalize','assess.v2.economics.finalize'],['assessment_v2.economics.review.resolve','assess.v2.economics.review'],['assessment_v2.economics.revision.start','assess.v2.economics.write']] as const){const payload=type==='assessment_v2.economics.review.resolve'?{economicVersionId:econId,caseId,decisionId,resolution:'changes_requested',rationale:'fix evidence',conditions:['cash evidence']}:{economicVersionId:econId,caseId,decisionId,rationale:'ready'};const result=await executeEconomicsCommand(new Request('http://x'),parseEconomicsEnvelope({...base,idempotencyKey:`${type}-key`,commandType:type,payload}),deps([cap],'reviewer'));assert.equal(result.outcome,'committed')}
const out={...base,idempotencyKey:'outcome-key',commandType:'assessment_v2.outcomes.record',payload:{economicVersionId:econId,caseId,observationPeriod:'2026-Q4',projectReference:'internal-project',actuals:{netAnnualBenefit:10},evidenceIds:['ev'],collectionMethod:'finance ledger',observationCompleteness:1}};assert.equal(parseEconomicsEnvelope(out).payload.observationPeriod,'2026-Q4');
const outReview={...base,idempotencyKey:'outcome-review-key',commandType:'assessment_v2.outcomes.review',payload:{outcomeId:'88888888-8888-4888-8888-888888888888',economicVersionId:econId,caseId,resolution:'accepted',rationale:'reviewed'}};assert.equal(parseEconomicsEnvelope(outReview).payload.resolution,'accepted');
const cal={...base,idempotencyKey:'cal-key-001',commandType:'assessment_v2.calibration.snapshot.create',payload:{cohortDefinition:{processFamilies:['invoice']},formulaVersion:'assess-v2-economics-formulas-2026-07'}};assert.equal(parseEconomicsEnvelope(cal).payload.formulaVersion,'assess-v2-economics-formulas-2026-07');
assert.throws(()=>parseEconomicsEnvelope({...create,payload:{...create.payload,currency:'US'}}),/INVALID_COMMAND/);assert.throws(()=>parseEconomicsEnvelope({...draft,payload:{...draft.payload,benefits:[{...draft.payload.benefits[0],range:{low:3,base:2,high:1,unit:'USD',period:'annual'}}]}}),/INVALID_COMMAND/);
console.log('Assess V2 economics command tests passed');
}
main().catch(error=>{console.error(error);process.exit(1)});
