import type { AssessmentCaseV2, ImmutableDecisionVersionV2 } from '../../../services/assessV2/index.ts';
export const ASSESS_V2_COMMAND_TYPES=['assessment_v2.create','assessment_v2.clone_from_v1','assessment_v2.draft.upsert','assessment_v2.finalize'] as const;
export type AssessV2CommandType=typeof ASSESS_V2_COMMAND_TYPES[number]; export type JsonObject=Record<string,unknown>;
export type AssessV2Envelope={requestId:string;idempotencyKey:string;commandType:AssessV2CommandType;organizationId:string;workspaceId:string;authorizationVersion:number;expectedVersion?:number;payload:JsonObject};
export type AssessV2Authority={actorId:string;organizationId:string;workspaceId:string;authorizationVersion:number;capabilities:readonly string[]};
export type AssessV2AtomicCommand=AssessV2Envelope&{actorId:string;serverDecision?:ImmutableDecisionVersionV2};
export interface AssessV2Dependencies{authenticate(r:Request):Promise<{id:string}>;loadFreshAuthority(i:{request:Request;actorId:string;organizationId:string;workspaceId:string}):Promise<AssessV2Authority|null>;loadLockedCaseForFinalize(i:{caseId:string;organizationId:string;workspaceId:string;expectedVersion:number}):Promise<AssessmentCaseV2|null>;executeAtomicCommand(c:AssessV2AtomicCommand):Promise<{outcome:'committed'|'replayed';resource:JsonObject}>}
export type AssessV2ErrorCode='METHOD_NOT_ALLOWED'|'AUTHENTICATION_REQUIRED'|'INVALID_COMMAND'|'COMMAND_NOT_SUPPORTED'|'RESOURCE_NOT_AVAILABLE'|'AUTHORITY_STALE'|'PERMISSION_DENIED'|'VERSION_CONFLICT'|'IDEMPOTENCY_CONFLICT'|'FEATURE_DISABLED'|'READ_ONLY'|'COMMAND_UNAVAILABLE';
const status:Record<AssessV2ErrorCode,number>={METHOD_NOT_ALLOWED:405,AUTHENTICATION_REQUIRED:401,INVALID_COMMAND:400,COMMAND_NOT_SUPPORTED:400,RESOURCE_NOT_AVAILABLE:404,AUTHORITY_STALE:409,PERMISSION_DENIED:403,VERSION_CONFLICT:409,IDEMPOTENCY_CONFLICT:409,FEATURE_DISABLED:503,READ_ONLY:503,COMMAND_UNAVAILABLE:503};
export class AssessV2Error extends Error{constructor(public readonly code:AssessV2ErrorCode){super(code)}get status(){return status[this.code]}}
const bad=():never=>{throw new AssessV2Error('INVALID_COMMAND')}, obj=(v:unknown):JsonObject=>typeof v==='object'&&v!==null&&!Array.isArray(v)?v as JsonObject:bad();
const exact=(o:JsonObject,keys:string[],required=keys)=>{if(Object.keys(o).some(k=>!keys.includes(k))||required.some(k=>!(k in o)))bad()};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, KEY=/^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/;
const uuid=(v:unknown)=>typeof v==='string'&&UUID.test(v)?v:bad(), text=(v:unknown,n:number,empty=false)=>typeof v==='string'&&v.length<=n&&(empty||v.trim())?v:bad(), integer=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>0?v:bad();
const list=<T>(v:unknown,n:number,p:(x:unknown)=>T):T[]=>Array.isArray(v)&&v.length<=n?v.map(p):bad(), enumOf=<T extends string>(v:unknown,x:readonly T[])=>typeof v==='string'&&x.includes(v as T)?v as T:bad();
const boolNull=(v:unknown)=>v===null||typeof v==='boolean'?v:bad(), numNull=(v:unknown,min:number,max:number)=>v===null?null:typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max?v:bad();
const uuids=(v:unknown)=>list(v,100,uuid), strings=(v:unknown)=>list(v,100,x=>text(x,1000,true));
const primitiveTypes=['Capture','Extract','Classify','Validate','Calculate','Reconcile','Retrieve','Investigate','Decide','Approve','Route','Execute','Communicate','Monitor','Audit'] as const;
const parseFact=(v:unknown)=>{const o=obj(v);exact(o,['fieldId','value','status','evidenceIds']);return{fieldId:text(o.fieldId,160),value:o.value??null,status:enumOf(o.status,['known','unknown','suggested','assumed'] as const),evidenceIds:uuids(o.evidenceIds)}};
const parsePrimitive=(v:unknown)=>{const o=obj(v);exact(o,['id','type','name','description','trigger','inputs','outputs','owner','volumeShare','manualEffort','rules','exceptionIds','evidenceIds','facts'],['id','type','name','description','inputs','outputs','volumeShare','manualEffort','rules','exceptionIds','evidenceIds','facts']);const f=obj(o.facts);if(Object.keys(f).length>200)bad();return{id:uuid(o.id),type:enumOf(o.type,primitiveTypes),name:text(o.name,200),description:text(o.description,4000,true),trigger:o.trigger===undefined?undefined:text(o.trigger,500,true),inputs:strings(o.inputs),outputs:strings(o.outputs),owner:o.owner===undefined?undefined:text(o.owner,200,true),volumeShare:numNull(o.volumeShare,0,1),manualEffort:numNull(o.manualEffort,0,1e7),rules:strings(o.rules),exceptionIds:uuids(o.exceptionIds),evidenceIds:uuids(o.evidenceIds),facts:Object.fromEntries(Object.entries(f).map(([k,v])=>{const x=parseFact(v);if(k!==x.fieldId)bad();return[k,x]}))}};
const parseEdge=(v:unknown)=>{const o=obj(v);exact(o,['id','fromPrimitiveId','toPrimitiveId','condition'],['id','fromPrimitiveId','toPrimitiveId']);return{id:uuid(o.id),fromPrimitiveId:uuid(o.fromPrimitiveId),toPrimitiveId:uuid(o.toPrimitiveId),condition:o.condition===undefined?undefined:text(o.condition,1000,true)}};
const parseAsset=(v:unknown)=>{const o=obj(v);exact(o,['id','name','strategicLifespan','technicalHealth','accountableOwner','evidenceIds'],['id','name','strategicLifespan','technicalHealth','evidenceIds']);return{id:uuid(o.id),name:text(o.name,200),strategicLifespan:enumOf(o.strategicLifespan,['short','medium','long','unknown'] as const),technicalHealth:enumOf(o.technicalHealth,['healthy','constrained','end-of-life','unknown'] as const),accountableOwner:o.accountableOwner===undefined?undefined:text(o.accountableOwner,200,true),evidenceIds:uuids(o.evidenceIds)}};
const parseEvidence=(v:unknown)=>{const o=obj(v);exact(o,['id','claimIds','sourceType','status','validated','owner','capturedAt','contradictory'],['id','claimIds','sourceType','status','validated']);return{id:uuid(o.id),claimIds:strings(o.claimIds),sourceType:enumOf(o.sourceType,['system-record','document','interview','observation','test','template'] as const),status:enumOf(o.status,['suggested','submitted','validated','rejected'] as const),validated:typeof o.validated==='boolean'?o.validated:bad(),owner:o.owner===undefined?undefined:text(o.owner,200,true),capturedAt:o.capturedAt===undefined?undefined:text(o.capturedAt,64),contradictory:o.contradictory===undefined?undefined:typeof o.contradictory==='boolean'?o.contradictory:bad()}};
const parseInteraction=(v:unknown)=>{const o=obj(v);exact(o,['id','assetId','primitiveId','operationName','mode','dataClassification','facts','evidenceIds']);const f=obj(o.facts),ks=['interfaceAvailable','operationCovered','apiDocumented','machineIdentity','leastPrivilege','dataQuality','dataClassified','auditable','idempotent','compensatable','rollback','testEnvironment','monitored','uiStable','eventSemantics','highImpact','financialAction','untrustedContentWithTools'];exact(f,ks);return{id:uuid(o.id),assetId:uuid(o.assetId),primitiveId:uuid(o.primitiveId),operationName:text(o.operationName,200),mode:enumOf(o.mode,['read','write','event','ui','operational'] as const),dataClassification:enumOf(o.dataClassification,['Public','Internal','Confidential','Restricted','Unknown'] as const),facts:Object.fromEntries(ks.map(k=>[k,['highImpact','financialAction','untrustedContentWithTools'].includes(k)?typeof f[k]==='boolean'?f[k]:bad():boolNull(f[k])])),evidenceIds:uuids(o.evidenceIds)}};
const parseDraft=(p:JsonObject)=>{exact(p,['caseId','name','description','primitives','edges','decisionPoints','exceptionPaths','applicationAssets','interactions','evidenceLinks','candidateEvaluations','gateResults','controlRequirements','modernizationDispositions']);const decisionPoints=list(p.decisionPoints,200,v=>{const o=obj(v);exact(o,['id','primitiveId','name','ruleDescription','outcomeLabels','evidenceIds']);return{id:uuid(o.id),primitiveId:uuid(o.primitiveId),name:text(o.name,200),ruleDescription:text(o.ruleDescription,2000),outcomeLabels:strings(o.outcomeLabels),evidenceIds:uuids(o.evidenceIds)}}),exceptionPaths=list(p.exceptionPaths,200,v=>{const o=obj(v);exact(o,['id','fromPrimitiveId','name','trigger','resolutionPrimitiveIds','evidenceIds']);return{id:uuid(o.id),fromPrimitiveId:uuid(o.fromPrimitiveId),name:text(o.name,200),trigger:text(o.trigger,2000),resolutionPrimitiveIds:uuids(o.resolutionPrimitiveIds),evidenceIds:uuids(o.evidenceIds)}});for(const key of ['candidateEvaluations','gateResults','controlRequirements','modernizationDispositions'])if(!Array.isArray(p[key])||p[key].length!==0)bad();const x={caseId:uuid(p.caseId),name:text(p.name,200),description:text(p.description,4000,true),primitives:list(p.primitives,200,parsePrimitive),edges:list(p.edges,400,parseEdge),decisionPoints,exceptionPaths,assets:list(p.applicationAssets,100,parseAsset),interactions:list(p.interactions,400,parseInteraction),evidence:list(p.evidenceLinks,500,parseEvidence),agentNecessity:{irreducibleAmbiguity:null,adaptiveNextStep:null,toolOrPathSelection:null,incrementalValue:null,controllable:null}};if(JSON.stringify(x).length>900000)bad();return x};
export const parseAssessV2Envelope=(v:unknown):AssessV2Envelope=>{const o=obj(v);exact(o,['requestId','idempotencyKey','commandType','organizationId','workspaceId','authorizationVersion','expectedVersion','payload'],['requestId','idempotencyKey','commandType','organizationId','workspaceId','authorizationVersion','payload']);if(!ASSESS_V2_COMMAND_TYPES.includes(o.commandType as AssessV2CommandType))throw new AssessV2Error(typeof o.commandType==='string'?'COMMAND_NOT_SUPPORTED':'INVALID_COMMAND');const commandType=o.commandType as AssessV2CommandType,p=obj(o.payload);let payload:JsonObject;if(commandType==='assessment_v2.create'){exact(p,['caseId','processId','name','description']);payload={caseId:uuid(p.caseId),processId:uuid(p.processId),name:text(p.name,200),description:text(p.description,4000,true)}}else if(commandType==='assessment_v2.clone_from_v1'){exact(p,['caseId','sourceAssessmentId','name','description']);payload={caseId:uuid(p.caseId),sourceAssessmentId:uuid(p.sourceAssessmentId),name:text(p.name,200),description:text(p.description,4000,true)}}else if(commandType==='assessment_v2.draft.upsert')payload=parseDraft(p);else{exact(p,['caseId']);payload={caseId:uuid(p.caseId)}}if(commandType!=='assessment_v2.create'&&commandType!=='assessment_v2.clone_from_v1'&&o.expectedVersion===undefined)bad();return{requestId:uuid(o.requestId),idempotencyKey:typeof o.idempotencyKey==='string'&&KEY.test(o.idempotencyKey)?o.idempotencyKey:bad(),commandType,organizationId:uuid(o.organizationId),workspaceId:uuid(o.workspaceId),authorizationVersion:integer(o.authorizationVersion),expectedVersion:o.expectedVersion===undefined?undefined:integer(o.expectedVersion),payload}};
export const asAssessV2Error=(e:unknown)=>e instanceof AssessV2Error?e:new AssessV2Error('COMMAND_UNAVAILABLE'); export const assessV2ErrorBody=(e:AssessV2Error)=>({ok:false,error:{code:e.code,message:'The command could not be completed.'}});
