import { getAuthUser, supabaseEnv } from './supabase.ts';
import { resolveTenantAuthority, TenantAuthorityError } from './tenantAuthority.ts';
import { createTenantAuthorityDatabase } from './tenantAuthorityDb.ts';
import { AssessV2ReviewAtomicCommand, AssessV2ReviewDependencies, AssessV2ReviewError } from './assessV2ReviewCommand.ts';

const rpc:Record<AssessV2ReviewAtomicCommand['commandType'],string>={
 'assessment_v2.review.assign':'pr1e_assign_assess_v2_review','assessment_v2.evidence.attest':'pr1e_attest_assess_v2_evidence','assessment_v2.review.resolve':'pr1e_resolve_assess_v2_review','assessment_v2.revision.start':'pr1e_start_assess_v2_revision','assessment_v2.govern.resolve':'pr1e_resolve_assess_v2_govern','assessment_v2.studio.handoff':'pr1e_handoff_assess_v2_studio'};
const serviceFetch=async(path:string,init:RequestInit={})=>{const{url,serviceRoleKey}=supabaseEnv();return fetch(`${url}/rest/v1/${path}`,{...init,redirect:'error',headers:{apikey:serviceRoleKey,Authorization:`Bearer ${serviceRoleKey}`,'Content-Type':'application/json',...(init.headers||{})}})};
const controlled=(value:unknown)=>{const v=(Array.isArray(value)?value[0]:value) as Record<string,unknown>|null;const map:Record<string,AssessV2ReviewError['code']>={NOT_FOUND:'RESOURCE_NOT_AVAILABLE',VERSION_CONFLICT:'VERSION_CONFLICT',IDEMPOTENCY_CONFLICT:'IDEMPOTENCY_CONFLICT',AUTHORIZATION_STALE:'AUTHORITY_STALE',FEATURE_DISABLED:'FEATURE_DISABLED',READ_ONLY:'READ_ONLY',INVALID_COMMAND:'INVALID_COMMAND'};if(v&&typeof v.errorCode==='string'&&map[v.errorCode])throw new AssessV2ReviewError(map[v.errorCode]);if(!v||(v.outcome!=='committed'&&v.outcome!=='replayed')||!v.resource||typeof v.resource!=='object')throw new AssessV2ReviewError('COMMAND_UNAVAILABLE');return {outcome:v.outcome,resource:v.resource} as {outcome:'committed'|'replayed';resource:Record<string,unknown>}};
export const buildAssessV2ReviewRpcBody=(c:AssessV2ReviewAtomicCommand)=>({p_actor_id:c.actorId,p_org_id:c.organizationId,p_workspace_id:c.workspaceId,p_case_id:c.payload.caseId,p_decision_id:c.payload.decisionId,p_expected_version:c.expectedVersion,p_request_id:c.requestId,p_idempotency_key:c.idempotencyKey,p_authorization_version:c.authorizationVersion,p_payload:c.payload});
export const assessV2ReviewDependencies:AssessV2ReviewDependencies={authenticate:getAuthUser,async loadFreshAuthority(input){try{const a=await resolveTenantAuthority(input.actorId,{organizationId:input.organizationId,workspaceId:input.workspaceId},createTenantAuthorityDatabase(input.request));return{actorId:a.userId,organizationId:a.organizationId,workspaceId:a.workspaceId,authorizationVersion:a.authorizationVersion,capabilities:a.capabilities}}catch(e){if(e instanceof TenantAuthorityError&&e.code==='TENANT_ACCESS_DENIED')return null;throw e}},async executeAtomicReviewCommand(command){try{const response=await serviceFetch(`rpc/${rpc[command.commandType]}`,{method:'POST',body:JSON.stringify(buildAssessV2ReviewRpcBody(command))});if(!response.ok)throw new AssessV2ReviewError('COMMAND_UNAVAILABLE');return controlled(await response.json())}catch(e){if(e instanceof AssessV2ReviewError)throw e;throw new AssessV2ReviewError('COMMAND_UNAVAILABLE')}}};
