import { getAuthUser, postgrest } from './supabase.ts';
import { EconomicsAtomicCommand, EconomicsDependencies, EconomicsError } from './assessV2EconomicsCommand.ts';
import { resolveTenantAuthority, TenantAuthorityError } from './tenantAuthority.ts';
import { createTenantAuthorityDatabase } from './tenantAuthorityDb.ts';
export const mapEconomicsRpcError=(error:unknown):EconomicsError=>{const message=String((error as {message?:unknown})?.message??error);if(message.includes('READ_ONLY'))return new EconomicsError('READ_ONLY');if(message.includes('FEATURE_DISABLED'))return new EconomicsError('FEATURE_DISABLED');if(message.includes('AUTHORITY_STALE'))return new EconomicsError('AUTHORITY_STALE');if(message.includes('VERSION_CONFLICT'))return new EconomicsError('VERSION_CONFLICT');if(message.includes('IDEMPOTENCY_CONFLICT'))return new EconomicsError('IDEMPOTENCY_CONFLICT');if(message.includes('PERMISSION_DENIED'))return new EconomicsError('PERMISSION_DENIED');if(message.includes('NOT_FOUND'))return new EconomicsError('RESOURCE_NOT_AVAILABLE');if(message.includes('INVALID_COMMAND'))return new EconomicsError('INVALID_COMMAND');return new EconomicsError('COMMAND_UNAVAILABLE')};
export const assessV2EconomicsDependencies:EconomicsDependencies={
 authenticate:getAuthUser,
 async loadFreshAuthority(input){try{const a=await resolveTenantAuthority(input.actorId,{organizationId:input.organizationId,workspaceId:input.workspaceId},createTenantAuthorityDatabase(input.request));return{actorId:a.userId,organizationId:a.organizationId,workspaceId:a.workspaceId,authorizationVersion:a.authorizationVersion,capabilities:a.capabilities}}catch(e){if(e instanceof TenantAuthorityError&&e.code==='TENANT_ACCESS_DENIED')return null;throw e}},
 async executeAtomicEconomicsCommand(command:EconomicsAtomicCommand){try{const result=await postgrest<{outcome:'committed'|'replayed';resource:Record<string,unknown>;errorCode?:string}>('rpc/pr1f_execute_assess_v2_economics_command',{method:'POST',body:JSON.stringify({p_actor_id:command.actorId,p_org_id:command.organizationId,p_workspace_id:command.workspaceId,p_request_id:command.requestId,p_idempotency_key:command.idempotencyKey,p_authorization_version:command.authorizationVersion,p_expected_version:command.expectedVersion,p_command_type:command.commandType,p_payload:command.payload})});if(result?.errorCode)throw mapEconomicsRpcError(result.errorCode);return result}catch(e){if(e instanceof EconomicsError)throw e;throw mapEconomicsRpcError(e)}}
};
