import assert from 'node:assert/strict';
import { authorizePilotOperationsCommand, canonicalPilotOperationsPayload, decodePilotOperationsCommand, PilotOperationsCommandError } from './pilotOperationsCommand.ts';
const id=(n:string)=>`00000000-0000-4000-8000-${n.padStart(12,'0')}`;
const base={operation:'simulate_promotion',organizationId:id('1'),workspaceId:id('2'),requestId:id('3'),idempotencyKey:'pilot:operation:123',expectedAuthorizationVersion:7,expectedVersion:2,payload:{candidateId:id('4'),target:'non_live'}};
const command=decodePilotOperationsCommand(base);
authorizePilotOperationsCommand(command,{userId:id('9'),organizationId:id('1'),workspaceId:id('2'),authorizationVersion:7,capabilities:['release.promote']});
assert.equal(canonicalPilotOperationsPayload(command),canonicalPilotOperationsPayload({...command,requestId:id('8')}));
for(const payload of [{...base,payload:{liveActivation:true}},{...base,payload:{target:'production'}},{...base,payload:{secretValue:'no'}}]) assert.throws(()=>decodePilotOperationsCommand(payload),PilotOperationsCommandError);
assert.throws(()=>authorizePilotOperationsCommand(command,{userId:id('9'),organizationId:id('1'),workspaceId:id('2'),authorizationVersion:8,capabilities:['release.promote']}),/AUTHORIZATION_STALE/);
assert.throws(()=>authorizePilotOperationsCommand(command,{userId:id('9'),organizationId:id('1'),workspaceId:id('2'),authorizationVersion:7,capabilities:[]}),/ACCESS_DENIED/);
assert.throws(()=>decodePilotOperationsCommand({...base,expectedVersion:undefined}),/VALIDATION_FAILED/);
assert.throws(()=>decodePilotOperationsCommand({...base,expectedVersion:null}),/VALIDATION_FAILED/);
console.log('pilot operations command tests passed');
