import { runProviderGovernedOperation, type ProviderGovernedOperationDeps } from './providerResolverIntegration.ts';
import type { JsonObject } from './studioArtifactCommand.ts';
import type { GenerationClaim } from './studioArtifactDb.ts';

export type StudioProviderOutput={content:unknown;providerOperationId?:string};
export const STUDIO_GENERATION_FAILURE_CODES=['PROVIDER_GOVERNANCE_BLOCKED','PROVIDER_REQUEST_FAILED','PROVIDER_OUTPUT_INVALID','PROVIDER_OUTPUT_OVERSIZED','GENERATION_COMPLETION_CONFLICT','GENERATION_START_CONFLICT'] as const;
export type StudioGenerationFailureCode=typeof STUDIO_GENERATION_FAILURE_CODES[number];
type GovernedResult={status:'blocked';body:{failureClass:string}}|{status:'allowed';value:StudioProviderOutput};
export interface StudioGenerationDependencies { runGoverned?(claim:GenerationClaim,run:()=>Promise<StudioProviderOutput>):Promise<GovernedResult>; runProvider(input:{apiKey:string;provider:'gemini'|'groq';sourcePackage:JsonObject;template:string;artifactType:'brd'|'frd'|'pdd';signal?:AbortSignal}):Promise<StudioProviderOutput>; start(attemptId:string):Promise<void>; complete(input:{attemptId:string;content:JsonObject;contentHash:string;providerOperationId?:string}):Promise<unknown>; fail(attemptId:string,failureCode:StudioGenerationFailureCode):Promise<void>; providerGovernance?:ProviderGovernedOperationDeps; }
export type StudioGenerationResult={state:'completed';resource:unknown}|{state:'failed';failureCode:StudioGenerationFailureCode};
const object=(v:unknown):v is JsonObject=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const validTree=(v:unknown,depth=0):boolean=>depth<=10&&(v===null||typeof v==='boolean'||typeof v==='number'&&Number.isFinite(v)||typeof v==='string'&&v.length<=20_000||Array.isArray(v)&&v.length<=200&&v.every(x=>validTree(x,depth+1))||object(v)&&Object.keys(v).length<=200&&Object.entries(v).every(([k,x])=>k.length>0&&k.length<=120&&validTree(x,depth+1)));
export const validateStudioDraft=(value:unknown):JsonObject=>{if(!object(value)||!validTree(value))throw new Error('invalid');const keys=Object.keys(value);if(keys.some(k=>!['title','summary','sections'].includes(k))||keys.length!==3||typeof value.title!=='string'||!value.title.trim()||value.title.length>300||typeof value.summary!=='string'||value.summary.length>5000||!Array.isArray(value.sections)||value.sections.length<1||value.sections.length>100)throw new Error('invalid');for(const section of value.sections){if(!object(section)||Object.keys(section).length!==2||typeof section.title!=='string'||!section.title.trim()||section.title.length>300||typeof section.content!=='string'||section.content.length>20_000)throw new Error('invalid');}return value;};
const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const recordFailure=async(deps:StudioGenerationDependencies,id:string,code:StudioGenerationFailureCode):Promise<StudioGenerationResult>=>{await deps.fail(id,code);return{state:'failed',failureCode:code};};

/** Runs only after the human request transaction committed. Browser callers cannot reach this operation directly. */
export const executeClaimedStudioGeneration=async(claim:GenerationClaim,deps:StudioGenerationDependencies):Promise<StudioGenerationResult>=>{
 try{await deps.start(claim.attemptId);}catch{return recordFailure(deps,claim.attemptId,'GENERATION_START_CONFLICT')}
 let governed;try{governed=deps.runGoverned?await deps.runGoverned(claim,()=>deps.runProvider({provider:'groq',apiKey:'',sourcePackage:claim.sourcePackage,template:claim.templatePayload,artifactType:claim.artifactType})):await runProviderGovernedOperation({operation:'generate_document',orgId:claim.organizationId,workspaceId:claim.workspaceId,actorId:claim.actorId,correlationId:claim.requestId,evidenceRef:claim.attemptId,scannerReference:`studio-template:${claim.templateHash}`,runAllowed:({provider,apiKey})=>deps.runProvider({provider,apiKey,sourcePackage:claim.sourcePackage,template:claim.templatePayload,artifactType:claim.artifactType})},deps.providerGovernance);}catch{return recordFailure(deps,claim.attemptId,'PROVIDER_REQUEST_FAILED')}
 if(governed.status==='blocked')return recordFailure(deps,claim.attemptId,governed.body.failureClass==='provider_call_blocked'?'PROVIDER_REQUEST_FAILED':'PROVIDER_GOVERNANCE_BLOCKED');
 let content:JsonObject;try{const serialized=JSON.stringify(governed.value.content);if(serialized.length>500_000)return recordFailure(deps,claim.attemptId,'PROVIDER_OUTPUT_OVERSIZED');content=validateStudioDraft(governed.value.content);}catch{return recordFailure(deps,claim.attemptId,'PROVIDER_OUTPUT_INVALID');}
 try{const resource=await deps.complete({attemptId:claim.attemptId,content,contentHash:await hash(JSON.stringify(content)),providerOperationId:governed.value.providerOperationId});return{state:'completed',resource};}catch{return recordFailure(deps,claim.attemptId,'GENERATION_COMPLETION_CONFLICT');}
};
