import { TRUST_OPERATIONS, trustOperationRequiresExpectedVersion, type TrustCommandRequest, type TrustCommandResponse } from '../../../services/trustAssurance/contracts.ts';
import { sha256Hex } from '../../../services/trustAssurance/domain.ts';
import type { TenantContext } from './tenantAuthority.ts';

export const TRUST_OPERATION_CAPABILITY: Record<TrustCommandRequest['operation'], string> = {
  'claim.create':'trust.manage','claim.revise':'trust.manage','evidence.register':'trust.manage','evidence.supersede':'trust.manage','evidence.withdraw':'trust.manage','evidence.link':'trust.manage',
  'resource.review':'trust.review','snapshot.create':'trust.manage','snapshot.review':'trust.review','snapshot.publish':'trust.publish','snapshot.withdraw':'trust.publish',
};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const allowed=['requestId','idempotencyKey','operation','organizationId','workspaceId','expectedAuthorizationVersion','expectedVersion','payload'];
const exact=(row:Record<string,unknown>,keys:readonly string[])=>{if(Object.keys(row).length!==keys.length||Object.keys(row).some(key=>!keys.includes(key)))throw new Error('VALIDATION_FAILED')};
const text=(value:unknown,max:number)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error('VALIDATION_FAILED');return value.trim()};
const id=(value:unknown)=>{const valueText=text(value,36);if(!uuid.test(valueText))throw new Error('VALIDATION_FAILED');return valueText};
const optionalIso=(value:unknown)=>{if(value===null)return null;const valueText=text(value,64);if(!Number.isFinite(Date.parse(valueText)))throw new Error('VALIDATION_FAILED');return valueText};
const stringList=(value:unknown,maxItems=30)=>{if(!Array.isArray(value)||value.length<1||value.length>maxItems)return (()=>{throw new Error('VALIDATION_FAILED')})();return value.map(item=>text(item,500))};
const payloadSchemas:Record<TrustCommandRequest['operation'],(row:Record<string,unknown>)=>Record<string,unknown>>={
 'claim.create':row=>{exact(row,['readinessDomain','claimText','proposedProofStatus','proofBoundary','buyerSafeWording','limitationDisclosure','doesNotProve']);return{readinessDomain:text(row.readinessDomain,40),claimText:text(row.claimText,4000),proposedProofStatus:text(row.proposedProofStatus,40),proofBoundary:text(row.proofBoundary,60),buyerSafeWording:text(row.buyerSafeWording,2000),limitationDisclosure:text(row.limitationDisclosure,4000),doesNotProve:stringList(row.doesNotProve)}} ,
 'claim.revise':row=>{exact(row,['claimId','claimText','proposedProofStatus','proofBoundary','buyerSafeWording','limitationDisclosure','doesNotProve']);return{claimId:id(row.claimId),claimText:text(row.claimText,4000),proposedProofStatus:text(row.proposedProofStatus,40),proofBoundary:text(row.proofBoundary,60),buyerSafeWording:text(row.buyerSafeWording,2000),limitationDisclosure:text(row.limitationDisclosure,4000),doesNotProve:stringList(row.doesNotProve)}} ,
 'evidence.register':row=>{exact(row,['evidenceType','referenceType','referenceValue','digest','summary','evidenceBoundary','result','observedAt','reviewDueAt','expiresAt']);return{evidenceType:text(row.evidenceType,80),referenceType:text(row.referenceType,40),referenceValue:text(row.referenceValue,512),digest:row.digest===null?null:text(row.digest,64),summary:text(row.summary,2000),evidenceBoundary:text(row.evidenceBoundary,60),result:text(row.result,20),observedAt:optionalIso(row.observedAt),reviewDueAt:optionalIso(row.reviewDueAt),expiresAt:optionalIso(row.expiresAt)}} ,
 'evidence.supersede':row=>{exact(row,['evidenceId']);return{evidenceId:id(row.evidenceId)}},'evidence.withdraw':row=>{exact(row,['evidenceId']);return{evidenceId:id(row.evidenceId)}},
 'evidence.link':row=>{exact(row,['claimVersionId','evidenceVersionId','relationship','rationale']);return{claimVersionId:id(row.claimVersionId),evidenceVersionId:id(row.evidenceVersionId),relationship:text(row.relationship,20),rationale:text(row.rationale,2000)}},
 'resource.review':row=>{exact(row,['resourceType','resourceId','decision','rationale']);return{resourceType:text(row.resourceType,30),resourceId:id(row.resourceId),decision:text(row.decision,30),rationale:text(row.rationale,2000)}},
 'snapshot.create':row=>{exact(row,['claimIds']);return{claimIds:stringList(row.claimIds).map(id)}},
 'snapshot.review':row=>{exact(row,['snapshotId','decision','rationale']);return{snapshotId:id(row.snapshotId),decision:text(row.decision,30),rationale:text(row.rationale,2000)}},
 'snapshot.publish':row=>{exact(row,['snapshotId']);return{snapshotId:id(row.snapshotId)}},'snapshot.withdraw':row=>{exact(row,['snapshotId','rationale']);return{snapshotId:id(row.snapshotId),rationale:text(row.rationale,2000)}},
};
export const decodeTrustCommandRequest=(value:unknown):TrustCommandRequest=>{
 if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('VALIDATION_FAILED');const row=value as Record<string,unknown>;if(Object.keys(row).some(key=>!allowed.includes(key))||['requestId','idempotencyKey','operation','organizationId','workspaceId','expectedAuthorizationVersion','payload'].some(key=>!(key in row)))throw new Error('VALIDATION_FAILED');
 if(typeof row.requestId!=='string'||!uuid.test(row.requestId)||typeof row.idempotencyKey!=='string'||row.idempotencyKey.length<1||row.idempotencyKey.length>200||typeof row.operation!=='string'||!TRUST_OPERATIONS.includes(row.operation as TrustCommandRequest['operation'])||typeof row.organizationId!=='string'||!uuid.test(row.organizationId)||typeof row.workspaceId!=='string'||!uuid.test(row.workspaceId)||!Number.isSafeInteger(row.expectedAuthorizationVersion)||(row.expectedAuthorizationVersion as number)<1||(row.expectedVersion!==undefined&&(!Number.isSafeInteger(row.expectedVersion)||(row.expectedVersion as number)<1))||!row.payload||typeof row.payload!=='object'||Array.isArray(row.payload))throw new Error('VALIDATION_FAILED');
 const operation=row.operation as TrustCommandRequest['operation'];if(trustOperationRequiresExpectedVersion(operation)&&(!Number.isSafeInteger(row.expectedVersion)||(row.expectedVersion as number)<1))throw new Error('VALIDATION_FAILED');return{...row,operation,payload:payloadSchemas[operation](row.payload as Record<string,unknown>)} as TrustCommandRequest;
};
export const canonicalTrustRequestHash=(request:TrustCommandRequest)=>sha256Hex({operation:request.operation,organizationId:request.organizationId,workspaceId:request.workspaceId,expectedVersion:request.expectedVersion??null,payload:request.payload});
export type TrustCommandDependencies={resolveAuthority:(request:TrustCommandRequest)=>Promise<TenantContext>;execute:(input:TrustCommandRequest&{actorId:string;requestHash:string})=>Promise<TrustCommandResponse>;featureEnabled:boolean;readOnly:boolean};
export const executeTrustCommand=async(value:unknown,deps:TrustCommandDependencies):Promise<TrustCommandResponse>=>{
  if(!deps.featureEnabled||deps.readOnly)return{ok:false,code:'FEATURE_DISABLED',message:'Trust Assurance mutations are disabled.'};
  let request:TrustCommandRequest;try{request=decodeTrustCommandRequest(value)}catch{return{ok:false,code:'VALIDATION_FAILED',message:'Request is invalid.'}}
  let authority:TenantContext;try{authority=await deps.resolveAuthority(request)}catch(error){return{ok:false,code:error instanceof Error&&error.message==='AUTHORIZATION_STALE'?'AUTHORIZATION_STALE':'ACCESS_DENIED',message:'The requested resource is unavailable.'}}
  if(authority.organizationId!==request.organizationId||(request.workspaceId!==null&&authority.workspaceId!==request.workspaceId)||!authority.capabilities.includes(TRUST_OPERATION_CAPABILITY[request.operation]))return{ok:false,code:'ACCESS_DENIED',message:'The requested resource is unavailable.'};
  try{return await deps.execute({...request,actorId:authority.userId,requestHash:await canonicalTrustRequestHash(request)})}catch(error){const message=error instanceof Error?error.message:'';const codes=['VERSION_CONFLICT','IDEMPOTENCY_CONFLICT','REVIEW_REQUIRED','PUBLICATION_BLOCKED'] as const;const code=codes.find(value=>message.includes(value))??'PERSISTENCE_UNAVAILABLE';return{ok:false,code,message:code==='PERSISTENCE_UNAVAILABLE'?'Trust Assurance is unavailable.':'The command could not be committed.'}}
};
