import React, { useState } from 'react';
import type { BuyerSafeProjection, InternalAssuranceProjection } from '../../../services/trustAssurance/contracts';

export type TrustAssuranceView='overview'|'claims'|'evidence'|'reviews'|'snapshot'|'buyer_preview'|'history';
export type TrustAssuranceState={kind:'loading'|'empty'|'offline'|'error'|'stale_authorization'|'revoked'|'blocked'}|{kind:'ready';projection:InternalAssuranceProjection};
const views:[TrustAssuranceView,string][]= [['overview','Assurance overview'],['claims','Claims'],['evidence','Evidence'],['reviews','Review queue'],['snapshot','Snapshot builder'],['buyer_preview','Buyer-safe preview'],['history','Publication history']];
const message:Record<Exclude<TrustAssuranceState['kind'],'ready'>,string>={loading:'Loading server-authoritative assurance evidence…',empty:'No governed assurance claims exist.',offline:'Assurance authority is unavailable while offline.',error:'Assurance evidence could not be loaded.',stale_authorization:'Authorization changed. Refresh your tenant session.',revoked:'Access was revoked. No assurance data is available.',blocked:'Trust Assurance is disabled or read-only pending configuration.'};
export const TrustAssuranceWorkspace:React.FC<{state:TrustAssuranceState;buyerProjection?:BuyerSafeProjection|null}>=({state,buyerProjection=null})=>{const[view,setView]=useState<TrustAssuranceView>('overview');return <section className="premium-surface overflow-hidden rounded-3xl border border-[#002C4B]/10" aria-labelledby="trust-assurance-title">
  <header className="border-b border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><p className="text-[11px] font-black uppercase tracking-[.18em] text-[#ffbc03]">Avala Admin · Prove</p><h2 id="trust-assurance-title" className="mt-2 text-2xl font-black text-[#002C4B] dark:text-white">Trust and Assurance Evidence Hub</h2><p className="mt-2 max-w-3xl text-sm font-semibold text-slate-600 dark:text-slate-300">Governed claims, immutable evidence metadata, independent reviews, and buyer-safe published snapshots. Authored metadata and CI results do not prove hosted, production, security, or compliance readiness.</p></header>
  <div className="p-4 sm:p-6"><nav aria-label="Trust Assurance views" className="flex max-w-full gap-2 overflow-x-auto pb-2">{views.map(([key,label])=><button key={key} type="button" onClick={()=>setView(key)} aria-pressed={view===key} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-black ${view===key?'bg-[#002C4B] text-white':'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-200'}`}>{label}</button>)}</nav>
  {state.kind!=='ready'?<div role={state.kind==='error'||state.kind==='revoked'?'alert':'status'} className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-semibold text-amber-950">{message[state.kind]}</div>:<ReadyView view={view} projection={state.projection} buyerProjection={buyerProjection}/>}</div></section>};
const ReadyView:React.FC<{view:TrustAssuranceView;projection:InternalAssuranceProjection;buyerProjection:BuyerSafeProjection|null}>=({view,projection,buyerProjection})=>{if(projection.claims.length===0)return <div className="mt-5 rounded-2xl border p-8 text-center text-sm font-semibold text-slate-500">No governed assurance claims exist.</div>;return <div className="mt-5 space-y-4">{projection.readOnly&&<p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold">Read-only mode: history and projections remain available; mutations are disabled.</p>}{view==='overview'&&<><div className="grid gap-3 sm:grid-cols-3"><Metric label="Claims" value={projection.claims.length}/><Metric label="Evidence versions" value={projection.evidence.length}/><Metric label="Review queue" value={projection.reviewQueueCount}/></div><div className="rounded-2xl border p-4"><p className="text-xs font-black uppercase text-slate-500">Current claim</p><p className="mt-2 text-sm font-black">{projection.claims[0].buyerSafeWording}</p></div></>}{view==='claims'&&projection.claims.map(claim=><article key={claim.claimVersionId} className="rounded-2xl border p-4"><h3 className="font-black">{claim.buyerSafeWording}</h3><p className="mt-2 text-sm">Effective: {claim.effectiveProofStatus} · {claim.proofBoundary}</p>{claim.blockedReasons.length>0&&<p className="mt-2 text-sm font-bold text-rose-700">Blocked: {claim.blockedReasons.join(', ')}</p>}<p className="mt-2 text-xs text-slate-500">Limitation: {claim.limitationDisclosure}</p></article>)}{view==='evidence'&&projection.evidence.map(item=><article key={item.evidenceVersionId} className="rounded-2xl border p-4"><h3 className="font-black">{item.summary}</h3><p className="mt-2 text-sm">{item.lifecycle} · {item.freshness} · {item.referenceType}: {item.referenceValue}</p></article>)}{view==='reviews'&&<p className="rounded-2xl border p-5">{projection.reviewQueueCount} exact-hash reviews require an independent human.</p>}{view==='snapshot'&&<p className="rounded-2xl border p-5">Snapshot changes invalidate prior review. Creator, reviewer, and publisher must be distinct active humans.</p>}{view==='buyer_preview'&&(buyerProjection?buyerProjection.claims.map((claim,index)=><article key={`${claim.wording}-${index}`} className="rounded-2xl border p-5"><h3 className="font-black">{claim.wording}</h3><p className="mt-2 text-sm">{claim.effectiveProofStatus} · {claim.proofBoundary}</p><p className="mt-2 text-sm">Limitation: {claim.limitationDisclosure}</p><p className="mt-2 text-xs">Does not prove: {claim.doesNotProve.join(', ')}</p></article>):<p className="rounded-2xl border p-5">No published snapshot. Draft content is not buyer-visible.</p>)}{view==='history'&&projection.snapshotHistory.map(item=><p key={item.snapshotId} className="rounded-xl border p-3 text-sm">{item.createdAt} · {item.lifecycle} · {item.snapshotHash}</p>)}</div>};
const Metric:React.FC<{label:string;value:number}>=({label,value})=><div className="rounded-2xl border p-4"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>;
