import { strict as assert } from 'node:assert';
import './workspaceModel.test.ts';
import type { TenantContextProjection } from '../../types';
import { adaptStudioWorkspaceRpcProjection, StudioWorkspaceRpcAdapterError } from './workspaceRpcAdapter.ts';
const U=Array.from({length:15},(_,i)=>`${String(i+1).padStart(8,'0')}-0000-4000-8000-${String(i+1).padStart(12,'0')}`);
const context={userId:U[0],organizationId:U[1],organizationName:'Synthetic',workspaceId:U[2],workspaceName:'Studio',authorizationVersion:3,capabilities:['studio.sources.read','studio.templates.read','studio.handoffs.read']} satisfies TenantContextProjection;
const source={mode:'server_authoritative',organizationId:U[1],workspaceId:U[2],ownerModule:'studio',flags:{studioMultisourceEnabled:true,studioTenantTemplatesEnabled:true,moduleHandoffsEnabled:true,directStudioPlanningEnabled:true},sourceVersions:[{sourceId:U[4],sourceVersionId:U[5],version:3,label:'Studio transcript',sourceKind:'transcript',mimeType:'text/vtt',characterCount:120,createdAt:'2026-08-28T00:00:00Z'},{sourceId:U[10],sourceVersionId:U[11],version:1,label:'Unselected Studio notes',sourceKind:'document',mimeType:'text/markdown',characterCount:80,createdAt:'2026-08-28T00:00:00Z'}],sourceSets:[{sourceSetId:U[3],ownerModule:'studio',displayLabel:'Studio set',description:'Independent',currentVersion:2,currentVersionId:U[9],manifestHash:'c'.repeat(64),status:'locked',sourceCount:1,extractedCharacterCount:120,members:[{sourceId:U[4],sourceVersionId:U[5],ordinal:1,role:'primary',note:null}],createdAt:'2026-08-28T00:00:00Z',updatedAt:'2026-08-28T00:00:00Z'},{sourceSetId:U[12],ownerModule:'studio',displayLabel:'Unselected set',description:null,currentVersion:1,currentVersionId:U[13],manifestHash:'d'.repeat(64),status:'locked',sourceCount:1,extractedCharacterCount:80,members:[{sourceId:U[10],sourceVersionId:U[11],ordinal:1,role:'supporting',note:null}],createdAt:'2026-08-28T00:00:00Z',updatedAt:'2026-08-28T00:00:00Z'}],inputBundles:[]};
const templates={organizationId:U[1],workspaceId:U[2],templates:[{ownership:'system',templateId:U[6],templateVersionId:U[7],version:'studio-brd-1',name:'System BRD',description:'Governed system template',artifactClass:'brd',lifecycle:'approved',templateHash:'a'.repeat(64),rendererVersion:'studio-markdown-1',contentSchemaVersion:'studio-artifact-1',sections:[{id:'scope',title:'Scope',required:true,fieldKind:'narrative'}],replacement:null,actions:['studio.generation.request']},{ownership:'tenant',templateId:U[3],templateVersionId:U[4],version:2,name:'Tenant BRD',description:'Governed tenant template',artifactClass:'brd',lifecycle:'approved',templateHash:'b'.repeat(64),rendererVersion:'studio-markdown-1',contentSchemaVersion:'studio-artifact-1',sections:[{id:'controls',title:'Controls',required:true,fieldKind:'controls'}],replacement:null,actions:['studio.generation.request','studio.template.deprecate']}]};
const handoffs={organizationId:U[1],workspaceId:U[2],eligibleHandoffs:[],handoffs:[{handoffId:U[8],handoffVersionId:U[7],upstreamHandoffId:U[6],direction:'inbox',lifecycle:'approved',status:'approved',version:2,sourceModule:'assess',targetModule:'studio',artifactType:'brd',lineageClassification:'assessed',planningOnly:false,hasStudioTranscriptBundle:false,resourceLabel:'Assess BRD handoff v2',requestorLabel:'Independent requestor',targetWorkspaceLabel:'Studio workspace',requestedAt:'2026-08-28T00:00:00Z',updatedAt:'2026-08-28T00:00:00Z',expiresAt:'2026-08-29T00:00:00Z',actions:['studio.handoff.consume']}]};
const decoded=adaptStudioWorkspaceRpcProjection(source,templates,handoffs,context);
assert.equal(decoded.mode,'accepted_assess_handoff');assert.equal(decoded.selectedSources.length,0);assert.equal(decoded.sourceAuthority.sourceSets.length,2);assert.equal(decoded.sourceAuthority.sourceSets[1].displayLabel,'Unselected set');assert.equal(decoded.templates[0].version,'studio-brd-1');assert.equal(decoded.templates[1].version,2);assert.deepEqual(decoded.templates[0].actions,['studio.generation.request']);assert.equal(decoded.inbox[0].handoffVersionId,U[7]);assert.deepEqual(decoded.inbox[0].actions,['studio.handoff.consume']);
const sourceOnly=adaptStudioWorkspaceRpcProjection(source,null,null,{...context,capabilities:['studio.sources.read']});
assert.equal(sourceOnly.sourceAuthority.sourceSets.length,2);assert.equal(sourceOnly.templates.length,0);assert.equal(sourceOnly.inbox.length,0);
const templateOnly=adaptStudioWorkspaceRpcProjection(null,templates,null,{...context,capabilities:['studio.templates.read']});
assert.equal(templateOnly.sourceAuthority.sourceSets.length,0);assert.equal(templateOnly.templates.length,2);assert.equal(templateOnly.inbox.length,0);
const handoffOnly=adaptStudioWorkspaceRpcProjection(null,null,handoffs,{...context,capabilities:['studio.handoffs.read']});
assert.equal(handoffOnly.sourceAuthority.sourceSets.length,0);assert.equal(handoffOnly.templates.length,0);assert.equal(handoffOnly.inbox.length,1);
assert.throws(()=>adaptStudioWorkspaceRpcProjection(source,null,null,{...context,capabilities:['studio.templates.read']}),StudioWorkspaceRpcAdapterError);
assert.throws(()=>adaptStudioWorkspaceRpcProjection({...source,workspaceId:U[9]},templates,handoffs,context),StudioWorkspaceRpcAdapterError);
assert.throws(()=>adaptStudioWorkspaceRpcProjection({...source,sourceSets:[{...source.sourceSets[0],browserAuthority:true}]},templates,handoffs,context),StudioWorkspaceRpcAdapterError);
assert.throws(()=>adaptStudioWorkspaceRpcProjection(source,{...templates,templates:[{...templates.templates[0],actions:['studio.generation.request'],secretRef:'forbidden'}]},handoffs,context),StudioWorkspaceRpcAdapterError);
assert.throws(()=>adaptStudioWorkspaceRpcProjection(source,{...templates,templates:[{...templates.templates[0],actions:undefined}]},handoffs,context),StudioWorkspaceRpcAdapterError);
const eligible={upstreamHandoffId:U[10],direction:'inbox',lifecycle:'eligible',sourceModule:'assess',targetModule:'studio',sourceVersion:4,resourceLabel:'Eligible Assess v4',requestorLabel:'Assess owner',targetWorkspaceLabel:'Studio workspace',handedOffAt:'2026-08-28T00:00:00Z',artifactTypes:['brd','pdd'],actions:['studio.handoff.request']};
const outbox={...handoffs.handoffs[0],handoffId:U[9],handoffVersionId:U[10],direction:'outbox',lifecycle:'reviewer_ready',status:'reviewer_ready',actions:['studio.handoff.withdraw']};
const bundle={inputBundleId:U[8],ownerModule:'studio',currentVersion:1,inputBundleVersionId:U[9],bundleHash:'e'.repeat(64),status:'locked',sourceSetVersions:[{sourceSetId:U[3],sourceSetVersionId:U[10],sourceSetVersion:2,manifestHash:'c'.repeat(64),ordinal:1,purpose:'Primary governed set'}],createdAt:'2026-08-28T00:00:00Z',updatedAt:'2026-08-28T00:00:00Z'};
const tenantReplaced={...templates.templates[1],lifecycle:'replaced',replacement:{templateId:U[12],templateVersionId:U[13],version:3},actions:['studio.template.replace']};
const expanded=adaptStudioWorkspaceRpcProjection({...source,inputBundles:[bundle]},{...templates,templates:[templates.templates[0],tenantReplaced]},{...handoffs,eligibleHandoffs:[eligible],handoffs:[outbox]},context);
assert.equal(expanded.mode,'unconfigured');assert.equal(expanded.sourceAuthority.inputBundles[0].bundleHash,'e'.repeat(64));assert.equal(expanded.templates[1].replacementTemplateVersionId,U[13]);assert.equal(expanded.inbox[0].kind,'eligible');assert.equal(expanded.outbox[0].state,'reviewer_ready');
const disabled=adaptStudioWorkspaceRpcProjection({...source,flags:{...source.flags,directStudioPlanningEnabled:false}},templates,{...handoffs,handoffs:[]},context);
assert.equal(disabled.sourceAuthority.enabled,false);assert.equal(disabled.blockers.length,0);assert.equal(disabled.lineageLabel,'not_assessed');
const missingSourceProjection=adaptStudioWorkspaceRpcProjection(null,templates,handoffs,context);
assert.equal(missingSourceProjection.sourceAuthority.sourceVersions.length,0);assert.equal(missingSourceProjection.templates.length,2);assert.equal(missingSourceProjection.inbox.length,1);assert.equal(missingSourceProjection.mode,'accepted_assess_handoff');
const fails=(sourceValue:unknown=source,templateValue:unknown=templates,handoffValue:unknown=handoffs)=>assert.throws(()=>adaptStudioWorkspaceRpcProjection(sourceValue,templateValue,handoffValue,context),StudioWorkspaceRpcAdapterError);
fails({...source,ownerModule:'assess'});
fails({...source,mode:'client_authoritative'});
fails({...source,sourceVersions:[{...source.sourceVersions[0],characterCount:0}]});
fails({...source,sourceVersions:[{...source.sourceVersions[0],createdAt:'not-a-date'}]});
fails({...source,sourceSets:[{...source.sourceSets[0],ownerModule:'assess'}]});
fails({...source,sourceSets:[{...source.sourceSets[0],members:[{...source.sourceSets[0].members[0],sourceVersionId:U[14]}]}]});
fails({...source,sourceSets:[{...source.sourceSets[0],members:[{...source.sourceSets[0].members[0],role:'authority'}]}]});
fails({...source,inputBundles:[{...bundle,ownerModule:'assess'}]});
fails({...source,inputBundles:[{...bundle,sourceSetVersions:[{...bundle.sourceSetVersions[0],manifestHash:'short'}]}]});
fails(source,{...templates,organizationId:U[0]});
fails(source,{...templates,templates:[{...templates.templates[0],version:2}]});
fails(source,{...templates,templates:[{...templates.templates[1],version:'two'}]});
fails(source,{...templates,templates:[{...templates.templates[0],artifactClass:'memo'}]});
fails(source,{...templates,templates:[{...templates.templates[0],lifecycle:'draft'}]});
fails(source,{...templates,templates:[{...templates.templates[0],sections:[{...templates.templates[0].sections[0],fieldKind:'authority'}]}]});
fails(source,{...templates,templates:[{...templates.templates[1],replacement:{templateId:U[12],templateVersionId:U[13],version:'three'}}]});
fails(source,{...templates,templates:[{...templates.templates[1],actions:['studio.template.override']}]});
fails(source,templates,{...handoffs,workspaceId:U[0]});
fails(source,templates,{...handoffs,eligibleHandoffs:[{...eligible,direction:'outbox'}]});
fails(source,templates,{...handoffs,eligibleHandoffs:[{...eligible,artifactTypes:['memo']}]});
fails(source,templates,{...handoffs,handoffs:[{...handoffs.handoffs[0],lifecycle:'draft'}]});
fails(source,templates,{...handoffs,handoffs:[{...handoffs.handoffs[0],direction:'sideways'}]});
fails(source,templates,{...handoffs,handoffs:[{...handoffs.handoffs[0],lineageClassification:'unknown'}]});
fails(source,templates,{...handoffs,handoffs:[{...handoffs.handoffs[0],planningOnly:'false'}]});
fails(source,templates,{...handoffs,handoffs:[{...handoffs.handoffs[0],actions:['studio.handoff.override']}]});
console.log('studio PR B RPC adapter: 39 strict scope, source-family, action-eligibility and malformed-projection assertions passed');
