import type { TenantContextProjection } from '../../types';
import { decodeStudioWorkspaceProjection, type StudioTemplateLifecycle, type StudioWorkspaceProjection } from './workspaceModel.ts';

export class StudioWorkspaceRpcAdapterError extends Error { constructor(){super('RESOURCE_NOT_AVAILABLE');this.name='StudioWorkspaceRpcAdapterError';} }
const fail=():never=>{throw new StudioWorkspaceRpcAdapterError();};
const object=(value:unknown):Record<string,unknown>=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:fail();
const exact=(value:Record<string,unknown>,keys:readonly string[])=>{const actual=Object.keys(value);if(actual.length!==keys.length||actual.some(key=>!keys.includes(key)))fail();};
const uuid=(value:unknown):string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)?value:fail();
const positive=(value:unknown):number=>Number.isSafeInteger(value)&&Number(value)>0?Number(value):fail();
const text=(value:unknown):string=>typeof value==='string'&&value.trim()?value:fail();
const hash=(value:unknown):string=>typeof value==='string'&&/^[0-9a-f]{64}$/i.test(value)?value:fail();
const array=(value:unknown):unknown[]=>Array.isArray(value)?value:fail();
const sourceKeys=['mode','organizationId','workspaceId','ownerModule','flags','sourceVersions','sourceSets','inputBundles'] as const;
const sourceVersionKeys=['sourceId','sourceVersionId','version','label','sourceKind','mimeType','characterCount','createdAt'] as const;
const setKeys=['sourceSetId','ownerModule','displayLabel','description','currentVersion','currentVersionId','manifestHash','status','sourceCount','extractedCharacterCount','members','createdAt','updatedAt'] as const;
const memberKeys=['sourceId','sourceVersionId','ordinal','role','note'] as const;
const bundleKeys=['inputBundleId','ownerModule','currentVersion','inputBundleVersionId','bundleHash','status','sourceSetVersions','createdAt','updatedAt'] as const;
const bundleSetKeys=['sourceSetId','sourceSetVersionId','sourceSetVersion','manifestHash','ordinal','purpose'] as const;
const templateRootKeys=['organizationId','workspaceId','templates'] as const;
const templateKeys=['ownership','templateId','templateVersionId','version','name','description','artifactClass','lifecycle','templateHash','rendererVersion','contentSchemaVersion','sections','replacement','actions'] as const;
const templateSectionKeys=['id','title','required','fieldKind'] as const;
const replacementKeys=['templateId','templateVersionId','version'] as const;
const handoffRootKeys=['organizationId','workspaceId','eligibleHandoffs','handoffs'] as const;
const eligibleHandoffKeys=['upstreamHandoffId','direction','lifecycle','sourceModule','targetModule','sourceVersion','resourceLabel','requestorLabel','targetWorkspaceLabel','handedOffAt','artifactTypes','actions'] as const;
const persistedHandoffKeys=['handoffId','handoffVersionId','upstreamHandoffId','direction','lifecycle','status','version','sourceModule','targetModule','artifactType','lineageClassification','planningOnly','hasStudioTranscriptBundle','resourceLabel','requestorLabel','targetWorkspaceLabel','requestedAt','updatedAt','expiresAt','actions'] as const;

const templateLifecycle=(value:unknown):StudioTemplateLifecycle=>['draft','reviewer_ready','in_review','changes_requested','rejected','approval_ready','approved','deprecated','replaced'].includes(String(value))?value as StudioTemplateLifecycle:fail();
const governedTemplateActions=['studio.generation.request','studio.template.revise','studio.template.review.submit','studio.template.review.resolve','studio.template.approval.resolve','studio.template.deprecate','studio.template.replace'] as const;
const governedHandoffActions=['studio.handoff.request','studio.handoff.review.resolve','studio.handoff.approval.resolve','studio.handoff.withdraw','studio.handoff.consume'] as const;
const templateActionList=(value:unknown):readonly string[]=>array(value).map(text).map(action=>governedTemplateActions.includes(action as typeof governedTemplateActions[number])?action:fail()).sort();
const handoffActionList=(value:unknown):readonly string[]=>value===undefined?[]:array(value).map(text).map(action=>governedHandoffActions.includes(action as typeof governedHandoffActions[number])?action:fail()).sort();

export const adaptStudioWorkspaceRpcProjection=(sourceValue:unknown,templateValue:unknown,handoffValue:unknown,context:TenantContextProjection):StudioWorkspaceProjection=>{
  const canReadSources=context.capabilities.includes('studio.sources.read');
  const canReadTemplates=context.capabilities.includes('studio.templates.read');
  const canReadHandoffs=context.capabilities.includes('studio.handoffs.read');
  const source=sourceValue===null?null:object(sourceValue);
  if(source){exact(source,sourceKeys);if(!canReadSources||uuid(source.organizationId)!==context.organizationId||uuid(source.workspaceId)!==context.workspaceId||source.ownerModule!=='studio'||source.mode!=='server_authoritative')fail();}
  const flags=source?object(source.flags):{studioMultisourceEnabled:false,studioTenantTemplatesEnabled:false,moduleHandoffsEnabled:false,directStudioPlanningEnabled:false};
  exact(flags,['studioMultisourceEnabled','studioTenantTemplatesEnabled','moduleHandoffsEnabled','directStudioPlanningEnabled']);
  const sourceVersions=source?array(source.sourceVersions).map(value=>{const item=object(value);exact(item,sourceVersionKeys);return{sourceId:uuid(item.sourceId),sourceVersionId:uuid(item.sourceVersionId),version:positive(item.version),label:text(item.label),sourceKind:text(item.sourceKind),mimeType:text(item.mimeType),characterCount:positive(item.characterCount),createdAt:text(item.createdAt)};}):[];
  const sourceVersionById=new Map(sourceVersions.map(item=>[item.sourceVersionId,item]));
  const sourceSets=source?array(source.sourceSets).map(setValue=>{const set=object(setValue);exact(set,setKeys);if(set.ownerModule!=='studio')fail();const members=array(set.members).map(memberValue=>{const member=object(memberValue);exact(member,memberKeys);const role=String(member.role),sourceVersionId=uuid(member.sourceVersionId),sourceVersion=sourceVersionById.get(sourceVersionId);if(!sourceVersion||!['primary','supporting','contradictory','reference'].includes(role))fail();return{sourceId:uuid(member.sourceId),sourceVersionId,version:sourceVersion.version,label:sourceVersion.label,ordinal:positive(member.ordinal),role:role as 'primary'|'supporting'|'contradictory'|'reference',note:member.note===null?null:text(member.note)};});return{sourceSetId:uuid(set.sourceSetId),currentVersionId:uuid(set.currentVersionId),currentVersion:positive(set.currentVersion),displayLabel:text(set.displayLabel),description:set.description===null?null:text(set.description),manifestHash:hash(set.manifestHash),status:text(set.status),sourceCount:positive(set.sourceCount),extractedCharacterCount:positive(set.extractedCharacterCount),members,createdAt:text(set.createdAt),updatedAt:text(set.updatedAt)};}):[];
  const inputBundles=source?array(source.inputBundles).map(value=>{const bundle=object(value);exact(bundle,bundleKeys);if(bundle.ownerModule!=='studio')fail();const sourceSetVersions=array(bundle.sourceSetVersions).map(value=>{const set=object(value);exact(set,bundleSetKeys);return{sourceSetId:uuid(set.sourceSetId),sourceSetVersionId:uuid(set.sourceSetVersionId),sourceSetVersion:positive(set.sourceSetVersion),manifestHash:hash(set.manifestHash),ordinal:positive(set.ordinal),purpose:text(set.purpose)};});return{inputBundleId:uuid(bundle.inputBundleId),inputBundleVersionId:uuid(bundle.inputBundleVersionId),currentVersion:positive(bundle.currentVersion),bundleHash:hash(bundle.bundleHash),status:text(bundle.status),sourceSetVersions,createdAt:text(bundle.createdAt),updatedAt:text(bundle.updatedAt)};}):[];
  const selectedSources:StudioWorkspaceProjection['selectedSources']=[];
  if(selectedSources.length>50)fail();
  const templatesRoot=templateValue===null?null:object(templateValue);if(templatesRoot){exact(templatesRoot,templateRootKeys);if(!canReadTemplates||uuid(templatesRoot.organizationId)!==context.organizationId||uuid(templatesRoot.workspaceId)!==context.workspaceId)fail();}
  const templates=templatesRoot?array(templatesRoot.templates).map(value=>{const item=object(value);exact(item,templateKeys);const ownership=item.ownership==='system'?'system':item.ownership==='tenant'?'tenant':fail();const version=ownership==='system'?text(item.version):positive(item.version);const artifactType=String(item.artifactClass);if(!['brd','frd','pdd','custom'].includes(artifactType))fail();const lifecycle=templateLifecycle(item.lifecycle);if(ownership==='system'&&lifecycle!=='approved')fail();for(const sectionValue of array(item.sections)){const section=object(sectionValue);exact(section,templateSectionKeys);text(section.id);text(section.title);if(typeof section.required!=='boolean'||!['narrative','requirements','rules','controls','risks','interfaces','acceptance_criteria'].includes(String(section.fieldKind)))fail();}let replacementTemplateVersionId:null|string=null;if(item.replacement!==null){const replacement=object(item.replacement);exact(replacement,replacementKeys);uuid(replacement.templateId);replacementTemplateVersionId=uuid(replacement.templateVersionId);if(ownership==='system')text(replacement.version);else positive(replacement.version);}return{templateId:uuid(item.templateId),templateVersionId:uuid(item.templateVersionId),version,name:text(item.name),artifactType:artifactType as 'brd'|'frd'|'pdd'|'custom',ownership,lifecycle,templateHash:hash(item.templateHash),immutable:ownership==='system'||lifecycle==='approved'||lifecycle==='deprecated'||lifecycle==='replaced',replacementTemplateVersionId,actions:templateActionList(item.actions)};}):[];
  const handoffsRoot=handoffValue===null?null:object(handoffValue);if(handoffsRoot){exact(handoffsRoot,handoffRootKeys);if(!canReadHandoffs||uuid(handoffsRoot.organizationId)!==context.organizationId||uuid(handoffsRoot.workspaceId)!==context.workspaceId)fail();}
  const eligible=handoffsRoot?array(handoffsRoot.eligibleHandoffs).map(value=>{const item=object(value);exact(item,eligibleHandoffKeys);if(item.direction!=='inbox'||item.lifecycle!=='eligible'||item.sourceModule!=='assess'||item.targetModule!=='studio')fail();const artifactTypes=array(item.artifactTypes).map(value=>{const artifactType=String(value);return ['brd','frd','pdd'].includes(artifactType)?artifactType as 'brd'|'frd'|'pdd':fail();});return{kind:'eligible' as const,handoffId:null,handoffVersionId:null,upstreamHandoffId:uuid(item.upstreamHandoffId),version:null,direction:'inbox' as const,state:'eligible' as const,status:null,sourceModule:'assess' as const,targetModule:'studio' as const,artifactType:null,artifactTypes,sourceVersion:positive(item.sourceVersion),resourceLabel:text(item.resourceLabel),lineageLabel:null,planningOnly:null,hasStudioTranscriptBundle:null,requestorLabel:text(item.requestorLabel),targetWorkspaceLabel:text(item.targetWorkspaceLabel),requestedAt:null,updatedAt:null,handedOffAt:text(item.handedOffAt),expiresAt:null,actions:handoffActionList(item.actions)};}):[];
  const persisted=handoffsRoot?array(handoffsRoot.handoffs).map(value=>{const item=object(value);exact(item,persistedHandoffKeys);if(item.sourceModule!=='assess'||item.targetModule!=='studio')fail();const direction=item.direction==='inbox'?'inbox':item.direction==='outbox'?'outbox':fail();const state=String(item.lifecycle);if(!['reviewer_ready','changes_requested','rejected','approval_ready','approved','accepted','consumed','withdrawn','stale','expired'].includes(state))fail();const artifactType=String(item.artifactType);if(!['brd','frd','pdd'].includes(artifactType))fail();const lineageLabel=item.lineageClassification==='not_assessed'?'not_assessed' as const:item.lineageClassification==='mixed'?'mixed' as const:item.lineageClassification==='assessed'?'assessed' as const:fail();if(typeof item.planningOnly!=='boolean'||typeof item.hasStudioTranscriptBundle!=='boolean')fail();return{kind:'persisted' as const,handoffId:uuid(item.handoffId),handoffVersionId:uuid(item.handoffVersionId),upstreamHandoffId:uuid(item.upstreamHandoffId),version:positive(item.version),direction,state:state as StudioWorkspaceProjection['inbox'][number]['state'],status:text(item.status),sourceModule:'assess' as const,targetModule:'studio' as const,artifactType:artifactType as 'brd'|'frd'|'pdd',artifactTypes:[],sourceVersion:null,resourceLabel:text(item.resourceLabel),lineageLabel,planningOnly:item.planningOnly,hasStudioTranscriptBundle:item.hasStudioTranscriptBundle,requestorLabel:text(item.requestorLabel),targetWorkspaceLabel:text(item.targetWorkspaceLabel),requestedAt:text(item.requestedAt),updatedAt:text(item.updatedAt),handedOffAt:null,expiresAt:text(item.expiresAt),actions:handoffActionList(item.actions)};}):[];
  const inbox=[...eligible,...persisted.filter(item=>item.direction==='inbox')],outbox=persisted.filter(item=>item.direction==='outbox');
  const accepted=persisted.some(item=>['approved','accepted','consumed'].includes(item.state));const mode=accepted?'accepted_assess_handoff':'unconfigured';const planningOnly=false;
  return decodeStudioWorkspaceProjection({schemaVersion:'studio-workspace-projection-1',organizationId:context.organizationId,workspaceId:context.workspaceId,mode,sourcePackageId:null,sourcePackageVersionId:null,sourcePackageVersion:null,sourcePackageHash:null,inputBundleVersionId:null,inputBundleVersion:null,selectedSources,sourceAuthority:{enabled:flags.studioMultisourceEnabled===true&&flags.directStudioPlanningEnabled===true,disabledReason:flags.studioMultisourceEnabled===true&&flags.directStudioPlanningEnabled===true?null:'Direct multi-source Studio is disabled for this workspace.',sourceVersions,sourceSets,inputBundles},totalSelectedSourceCount:0,sourcePage:1,sourcePageCount:1,template:templates.find(item=>item.lifecycle==='approved')??null,lineageLabel:accepted?'assessed':'not_assessed',planningOnly,citations:0,uncoveredSections:0,conflicts:0,blockers:flags.studioMultisourceEnabled===true?[]:['Direct multi-source Studio is disabled for this workspace.'],provider:{available:false,label:'Provider availability requires an exact artifact generation projection',functionalBounds:'Maximum 20 sources and 2,000,000 extracted characters; no silent truncation'},templates,inbox,outbox,readOnly:false},context);
};
