export const APPLICATION_PORTFOLIO_MODEL_VERSION = 'assess-v2-application-portfolio-2026-07';
export type ReadinessBand = 'Ready' | 'Conditionally Ready' | 'Blocked' | 'Unknown';
export type EvidenceConfidence = 'Verified' | 'Partially Evidenced' | 'Assumption-Led' | 'Insufficient Evidence';
export type Criticality = 'low' | 'medium' | 'high' | 'mission_critical' | 'Unknown';
export type LifecycleState = 'current' | 'maintenance' | 'eol' | 'unsupported' | 'retiring' | 'Unknown';
export type ReviewState = 'draft' | 'reviewer_ready' | 'approved' | 'changes_requested' | 'rejected' | 'superseded';
export type IntegrationMode = 'native_api_event' | 'api_facade_semantic_translation' | 'event_cdc_bridge' | 'governed_workflow_rpa_bridge' | 'governed_ui_vision_bridge' | 'blocked_pending_prerequisite' | 'not_applicable';
export type ModernizationDisposition = 'Retain and monitor' | 'Enable native API/event integration' | 'Add API façade and semantic translation' | 'Add event or CDC bridge' | 'Use governed workflow/RPA bridge' | 'Use governed UI/vision bridge' | 'Refactor through strangler or modular decomposition' | 'Replatform' | 'Replace with supported product or SaaS' | 'Rebuild through controlled AI-assisted delivery' | 'Consolidate duplicate applications' | 'Retire' | 'Insufficient evidence';
export type PortfolioDisposition = 'Enable integration now' | 'Wrap before automation' | 'Refactor before expansion' | 'Replace or rebuild candidate' | 'Consolidate or retire candidate' | 'Validate evidence first' | 'Monitor';
export interface EvidenceRef { id: string; sourceType: 'manual' | 'document' | 'review' | 'synthetic_fixture'; fresh?: boolean; independent?: boolean; contradicts?: boolean; }
export interface ApplicationMetadata { name: string; description?: string; businessOwner?: string; technicalOwner?: string; vendor?: string; businessCapabilities: string[]; supportedProcesses: string[]; businessCriticality: Criticality; lifecycleState: LifecycleState; product?: string; version?: string; eolStatus?: 'supported' | 'eol_announced' | 'eol' | 'Unknown'; hostingModel?: string; platform?: string[]; languages?: string[]; frameworks?: string[]; sourceCode: 'available_legal_access' | 'available_no_legal_access' | 'unavailable' | 'Unknown'; documentationQuality: 'high' | 'medium' | 'low' | 'Unknown'; automatedTestMaturity: 'executable_acceptance' | 'unit_or_integration' | 'manual_only' | 'none' | 'Unknown'; deploymentRepeatability: 'deterministic' | 'repeatable_manual' | 'ad_hoc' | 'Unknown'; observability: 'strong' | 'partial' | 'weak' | 'Unknown'; incidentHistory?: string; dataClassifications: string[]; regulatedData: boolean | 'Unknown'; operatingRegions: string[]; interfaces: Array<'REST/GraphQL' | 'SOAP' | 'messaging/event' | 'database' | 'file/batch' | 'command-line' | 'UI-only' | 'desktop/mainframe/Citrix'>; upstreamDependencies: string[]; downstreamDependencies: string[]; realTime: boolean | 'Unknown'; eventDriven: boolean | 'Unknown'; synchronous: boolean | 'Unknown'; batch: boolean | 'Unknown'; recoveryRequirements?: string; availabilityRequirements?: string; transactionRequirements?: string; ageYears?: number; }
export interface ApplicationRecord { id: string; orgId: string; workspaceId: string; metadataVersion: number; metadata: ApplicationMetadata; authorId: string; status: ReviewState; evidence: EvidenceRef[]; }
export interface DimensionResult { dimension: string; band: ReadinessBand; confidence: EvidenceConfidence; hardGates: string[]; evidenceReferences: EvidenceRef[]; missingEvidence: string[]; rationale: string[]; contradictions: string[]; remediationRequirements: string[]; whatWouldChange: string[]; }
export interface AssessmentVersion { id: string; applicationId: string; metadataVersion: number; version: number; status: ReviewState; authorId: string; reviewerId?: string; decisionModelVersion: string; dimensions: DimensionResult[]; recommendations: Recommendation[]; receiptId?: string; auditEventId?: string; }
export interface Recommendation { disposition: ModernizationDisposition; applicationId: string; metadataVersion: number; affectedProcesses: string[]; affectedPrimitives: string[]; why: string[]; alternativesConsidered: string[]; alternativesRejected: string[]; prerequisites: string[]; requiredControls: string[]; migrationBoundary: string; dependencyImpacts: string[]; rollback: string; confidence: EvidenceConfidence; openEvidenceGaps: string[]; whatWouldChange: string[]; }
export interface ProcessApplicationLink { processId: string; primitiveId: string; applicationId: string; interactionType: string; processSuitability: 'suitable' | 'approval_bound' | 'prohibited' | 'Unknown'; allowedAction: 'allowed' | 'approval_bound' | 'prohibited'; economicsCurrency?: string; economicsRef?: string; }
const unknown = (v: unknown) => v === undefined || v === null || v === '' || v === 'Unknown';
const confidence = (missing: string[], ev: EvidenceRef[]): EvidenceConfidence => missing.length ? 'Insufficient Evidence' : ev.some(e => e.contradicts) ? 'Insufficient Evidence' : ev.every(e => e.fresh && e.independent) ? 'Verified' : 'Partially Evidenced';
function dimension(name: string, band: ReadinessBand, hardGates: string[], evidence: EvidenceRef[], missing: string[], rationale: string[], remediation: string[], what: string[], contradictions: string[] = []): DimensionResult { return { dimension: name, band, confidence: confidence([...missing, ...contradictions], evidence), hardGates, evidenceReferences: evidence, missingEvidence: missing, rationale, contradictions, remediationRequirements: remediation, whatWouldChange: what }; }
export function validateApplicationMetadata(m: ApplicationMetadata): string[] { const e: string[] = []; if (!m.name?.trim()) e.push('MISSING_APPLICATION_NAME'); if (unknown(m.businessCriticality)) e.push('UNKNOWN_BUSINESS_CRITICALITY'); if (unknown(m.lifecycleState)) e.push('UNKNOWN_LIFECYCLE'); if (!m.interfaces?.length) e.push('MISSING_INTERFACES'); if (unknown(m.sourceCode)) e.push('UNKNOWN_SOURCE_RIGHTS'); if (unknown(m.regulatedData)) e.push('UNKNOWN_REGULATED_DATA'); if (!m.dataClassifications?.length) e.push('MISSING_DATA_CLASSIFICATION'); return e; }
export function detectTenantDuplicate(candidate: ApplicationMetadata, existing: ApplicationRecord[]) { const key = candidate.name.trim().toLowerCase(); return existing.filter(a => a.metadata.name.trim().toLowerCase() === key).map(a => ({ applicationId: a.id, metadataVersion: a.metadataVersion })); }
export function assessApplication(app: ApplicationRecord): AssessmentVersion { const m = app.metadata; const ev = app.evidence; const dims: DimensionResult[] = [];
 const hasApi = m.interfaces.some(i => ['REST/GraphQL','SOAP','messaging/event'].includes(i)); const uiOnly = m.interfaces.includes('UI-only') || m.interfaces.includes('desktop/mainframe/Citrix'); const missing = validateApplicationMetadata(m);
 dims.push(dimension('integration_accessibility', hasApi ? 'Ready' : m.interfaces.includes('file/batch') || m.interfaces.includes('database') || m.interfaces.includes('command-line') ? 'Conditionally Ready' : uiOnly ? 'Blocked' : 'Unknown', uiOnly ? ['UI_ONLY_OR_VIRTUALIZED_SURFACE'] : [], ev, missing.filter(x => x === 'MISSING_INTERFACES'), [`Interfaces: ${m.interfaces.join(', ') || 'Unknown'}`], uiOnly ? ['Complete native API, event, façade, workflow/RPA, or governed UI bridge evidence before automation.'] : [], ['Document supported API/event contracts or prove governed bridge controls.']));
 dims.push(dimension('semantic_and_data_clarity', m.documentationQuality === 'high' ? 'Ready' : m.documentationQuality === 'medium' ? 'Conditionally Ready' : m.documentationQuality === 'low' ? 'Blocked' : 'Unknown', m.documentationQuality === 'low' ? ['UNDOCUMENTED_SEMANTICS'] : [], ev, unknown(m.documentationQuality) ? ['DOCUMENTATION_QUALITY'] : [], [`Documentation quality is ${m.documentationQuality}.`], ['Add schema, data dictionary, canonical identifiers, validation and source-of-truth evidence.'], ['Fresh schema and data-quality evidence would change this result.']));
 dims.push(dimension('state_and_execution', m.batch === true || m.realTime === false ? 'Conditionally Ready' : m.realTime === true ? 'Ready' : 'Unknown', m.batch === true ? ['BATCH_DELAYED_FEEDBACK'] : [], ev, unknown(m.realTime) || unknown(m.synchronous) ? ['EXECUTION_CHARACTERISTICS'] : [], ['State, feedback, reversibility and transaction boundaries are evaluated independently.'], ['Document transaction boundaries, compensation, reversibility and partial-failure visibility.'], ['Executable workflow evidence with compensation controls would change this result.']));
 dims.push(dimension('security_and_control', m.regulatedData === true ? 'Conditionally Ready' : m.regulatedData === false ? 'Ready' : 'Unknown', m.regulatedData === true ? ['REGULATED_DATA_REQUIRES_INDEPENDENT_REVIEW'] : [], ev, unknown(m.regulatedData) ? ['REGULATED_DATA_FLAGS'] : [], ['Security/control readiness never follows from API availability.'], ['Evidence authentication, authorization, service identities, SoD, audit and approval controls.'], ['Approved control evidence would change this result.']));
 dims.push(dimension('architecture_changeability', m.sourceCode === 'available_legal_access' && m.automatedTestMaturity !== 'none' && m.deploymentRepeatability === 'deterministic' ? 'Ready' : m.sourceCode === 'unavailable' || m.lifecycleState === 'unsupported' ? 'Blocked' : 'Conditionally Ready', m.sourceCode !== 'available_legal_access' ? ['NO_LEGAL_SOURCE_ACCESS'] : [], ev, [unknown(m.sourceCode) && 'SOURCE_RIGHTS', unknown(m.deploymentRepeatability) && 'DEPLOYMENT_REPEATABILITY'].filter(Boolean) as string[], ['Age alone is ignored; changeability depends on rights, tests, build, deployment and observability.'], ['Secure source rights, tests, reproducible build, deployment and observability.'], ['Legal source access plus executable tests and deterministic build would change this result.']));
 dims.push(dimension('ui_automation_readiness', uiOnly ? 'Conditionally Ready' : 'Blocked', m.interfaces.some(i => i !== 'UI-only') ? ['UI_AUTOMATION_NOT_DEFAULT_WHEN_API_ABSENT'] : [], ev, [], ['Missing APIs never automatically imply UI automation.'], ['Prove stable selectors/accessibility/error visibility/reversibility and material-action approval controls.'], ['Governed UI evidence may permit a bridge, never autonomous suitability.']));
 const aiGates = [m.sourceCode !== 'available_legal_access' && 'AI_REBUILD_REQUIRES_LEGAL_SOURCE_ACCESS', m.automatedTestMaturity !== 'executable_acceptance' && 'AI_REBUILD_REQUIRES_EXECUTABLE_ACCEPTANCE_TESTS', m.deploymentRepeatability !== 'deterministic' && 'AI_REBUILD_REQUIRES_REPRODUCIBLE_BUILD_AND_ROLLBACK'].filter(Boolean) as string[];
 dims.push(dimension('ai_assisted_engineering_readiness', aiGates.length ? 'Blocked' : 'Ready', aiGates, ev, [], ['AI may summarize evidence but cannot approve rebuild, rewrite or deploy.'], ['Add human engineering ownership, legal source access, executable acceptance tests, reproducible build, security review, controlled deploy/rollback.'], ['All AI-assisted delivery hard gates passing with independent review would change this result.']));
 return { id: `${app.id}-assessment-v${app.metadataVersion}`, applicationId: app.id, metadataVersion: app.metadataVersion, version: 1, status: 'draft', authorId: app.authorId, decisionModelVersion: APPLICATION_PORTFOLIO_MODEL_VERSION, dimensions: dims, recommendations: recommend(app, dims) }; }
export function recommend(app: ApplicationRecord, dims: DimensionResult[]): Recommendation[] { const m = app.metadata; const gates = dims.flatMap(d => d.hardGates); const affected = m.supportedProcesses; const base = (disposition: ModernizationDisposition, why: string[], prereq: string[] = []): Recommendation => ({ disposition, applicationId: app.id, metadataVersion: app.metadataVersion, affectedProcesses: affected, affectedPrimitives: [], why, alternativesConsidered: ['native API/event', 'API façade', 'event bridge', 'workflow/RPA bridge', 'governed UI bridge', 'refactor', 'replace', 'rebuild', 'retire'], alternativesRejected: gates.length ? gates : ['No rejected alternative without evidence.'], prerequisites: prereq, requiredControls: ['independent human review for material decisions', 'authorization version', 'privileged audit receipt'], migrationBoundary: 'Application-scoped modernization; no autonomous code rewrite or deployment.', dependencyImpacts: [...m.upstreamDependencies, ...m.downstreamDependencies], rollback: 'Disable new integration path and retain prior application/process behavior; immutable assessment history remains.', confidence: confidence(dims.flatMap(d => d.missingEvidence), app.evidence), openEvidenceGaps: dims.flatMap(d => d.missingEvidence), whatWouldChange: dims.flatMap(d => d.whatWouldChange) });
 if (dims.some(d => d.confidence === 'Insufficient Evidence')) return [base('Insufficient evidence', ['Unknown information remains Unknown.'], dims.flatMap(d => d.missingEvidence))];
 if (m.sourceCode === 'available_legal_access' && m.automatedTestMaturity === 'executable_acceptance' && m.deploymentRepeatability === 'deterministic' && m.lifecycleState === 'unsupported') return [base('Rebuild through controlled AI-assisted delivery', ['All AI-assisted engineering hard gates pass; human review is still required.'], ['controlled security review', 'controlled deployment and rollback'])];
 if (m.interfaces.some(i => ['REST/GraphQL','SOAP','messaging/event'].includes(i))) return [base('Enable native API/event integration', ['Native interface evidence exists; agent suitability still depends on process and Govern gates.'])];
 if (m.interfaces.includes('file/batch') || m.interfaces.includes('database')) return [base('Add API façade and semantic translation', ['Non-native or batch/data interface needs semantic and control boundary.'], ['schema/data dictionary', 'approval controls'])];
 if (m.interfaces.includes('UI-only')) return [base('Use governed workflow/RPA bridge', ['UI-only system blocks native integration; UI automation is not automatic and needs governed bridge evidence.'], ['selector/accessibility/error visibility evidence', 'material-action approval controls'])];
 return [base('Retain and monitor', ['No deterministic modernization trigger from age alone.'])]; }
export function buildProcessApplicationMatrix(apps: ApplicationRecord[], links: ProcessApplicationLink[], assessments: AssessmentVersion[]) { return links.map(l => { const app = apps.find(a => a.id === l.applicationId); const ass = assessments.find(a => a.applicationId === l.applicationId); if (!app || !ass) throw new Error('LINK_ANCESTRY_NOT_FOUND'); const gates = ass.dimensions.flatMap(d => d.hardGates); const rec = ass.recommendations[0]; const appReady = gates.length ? 'blocked' : 'ready'; return { processId: l.processId, primitiveId: l.primitiveId, applicationId: l.applicationId, interactionType: l.interactionType, processAutomationSuitability: l.processSuitability, applicationReadiness: appReady, technicalBlocker: gates.find(g => !g.includes('REGULATED')) ?? null, governanceBlocker: gates.find(g => g.includes('REGULATED')) ?? (l.allowedAction !== 'allowed' ? 'PROCESS_ACTION_REQUIRES_APPROVAL' : null), recommendedIntegrationMode: rec.disposition === 'Enable native API/event integration' ? 'native_api_event' as IntegrationMode : rec.disposition === 'Add API façade and semantic translation' ? 'api_facade_semantic_translation' as IntegrationMode : rec.disposition === 'Use governed workflow/RPA bridge' ? 'governed_workflow_rpa_bridge' as IntegrationMode : 'blocked_pending_prerequisite' as IntegrationMode, modernizationPrerequisite: gates.length ? `Complete application prerequisite before enabling process recommendation: ${gates.join(', ')}` : null, evidenceConfidence: rec.confidence, economicsReference: l.economicsRef, sequencingRecommendation: l.processSuitability === 'suitable' && gates.length ? `Process ${l.processId} may be suitable for AI-assisted workflow, but application ${app.metadata.name} is blocked. Complete the application prerequisite first.` : 'Sequence after hard gates, compatible economics and review approval.' }; }); }
export function createPortfolioSnapshot(apps: ApplicationRecord[], assessments: AssessmentVersion[], currencies: string[] = []) { if (new Set(currencies.filter(Boolean)).size > 1) throw new Error('INCOMPATIBLE_CURRENCIES'); const waves = assessments.slice().sort((a,b) => (apps.find(x=>x.id===a.applicationId)?.metadata.upstreamDependencies.length ?? 0) - (apps.find(x=>x.id===b.applicationId)?.metadata.upstreamDependencies.length ?? 0)).map((a, i) => ({ wave: i + 1, applicationId: a.applicationId, disposition: portfolioDisposition(a), prerequisites: a.dimensions.flatMap(d => d.hardGates), approvedAutomatically: false })); return { modelVersion: APPLICATION_PORTFOLIO_MODEL_VERSION, applicationCount: apps.length, dispositions: assessments.map(a => ({ applicationId: a.applicationId, disposition: portfolioDisposition(a) })), waves, nonClaims: ['no live CMDB integration', 'no live repository scanning', 'no database/network scanning', 'no autonomous code rewrite', 'no autonomous modernization approval', 'no deployment', 'no scientific-validation claim', 'no buyer-readiness claim'] }; }
export function portfolioDisposition(a: AssessmentVersion): PortfolioDisposition { const rec = a.recommendations[0]?.disposition; const gates = a.dimensions.flatMap(d => d.hardGates); if (a.dimensions.some(d => d.confidence === 'Insufficient Evidence')) return 'Validate evidence first'; if (rec === 'Enable native API/event integration' && !gates.length) return 'Enable integration now'; if (rec === 'Add API façade and semantic translation' || rec === 'Use governed workflow/RPA bridge') return 'Wrap before automation'; if (rec === 'Refactor through strangler or modular decomposition') return 'Refactor before expansion'; if (rec === 'Replace with supported product or SaaS' || rec === 'Rebuild through controlled AI-assisted delivery') return 'Replace or rebuild candidate'; if (rec === 'Consolidate duplicate applications' || rec === 'Retire') return 'Consolidate or retire candidate'; return 'Monitor'; }
export function resolveReview(a: AssessmentVersion, reviewerId: string, resolution: Exclude<ReviewState,'draft'|'reviewer_ready'|'superseded'>, authorizationVersion: number) { if (a.status !== 'reviewer_ready') throw new Error('INVALID_REVIEW_LIFECYCLE'); if (reviewerId === a.authorId) throw new Error('REVIEWER_MUST_DIFFER_FROM_AUTHOR'); const material = a.recommendations.some(r => ['Rebuild through controlled AI-assisted delivery','Replace with supported product or SaaS','Retire','Consolidate duplicate applications'].includes(r.disposition)); if (resolution === 'approved' && material && authorizationVersion <= 0) throw new Error('AUTHORIZATION_VERSION_REQUIRED'); return { ...a, status: resolution, reviewerId, receiptId: `receipt-${a.id}-${resolution}`, auditEventId: `audit-${a.id}-${resolution}` }; }
export function importApplications(params: { orgId: string; workspaceId: string; actorId: string; idempotencyKey: string; rows: unknown[]; existing: ApplicationRecord[]; priorReceipts?: Map<string, unknown>; }) { const prior = params.priorReceipts?.get(params.idempotencyKey); if (prior) return prior; const successes: ApplicationRecord[] = []; const rejections: Array<{ row: number; code: string; message: string }> = []; params.rows.forEach((row, i) => { const m = row as Partial<ApplicationMetadata>; const errs = validateApplicationMetadata(m as ApplicationMetadata); if (errs.length) { rejections.push({ row: i + 1, code: errs[0], message: 'Row rejected without defaulting Unknown evidence.' }); return; } if (detectTenantDuplicate(m as ApplicationMetadata, [...params.existing, ...successes]).length) { rejections.push({ row: i + 1, code: 'DUPLICATE_IN_WORKSPACE', message: 'Duplicate application in this workspace.' }); return; } successes.push({ id: `app-${params.actorId}-${params.idempotencyKey}-${i + 1}`, orgId: params.orgId, workspaceId: params.workspaceId, metadataVersion: 1, metadata: m as ApplicationMetadata, authorId: params.actorId, status: 'draft', evidence: [{ id: `import-${params.idempotencyKey}-${i + 1}`, sourceType: 'manual', fresh: true }] }); }); return { receipt: { idempotencyKey: params.idempotencyKey, actorId: params.actorId, committed: true }, successes, rejections }; }
