import type { TenantContextProjection } from '../types';
import { EconomicVersion, calculateScenarios, deriveConfidence, portfolioDisposition, calibrationSnapshot } from './assessV2/economics/domain';

export type EconomicsCommandType='assessment_v2.economics.create'|'assessment_v2.economics.draft.upsert'|'assessment_v2.economics.finalize'|'assessment_v2.economics.review.resolve'|'assessment_v2.economics.revision.start'|'assessment_v2.outcomes.record'|'assessment_v2.outcomes.review'|'assessment_v2.calibration.snapshot.create';
export type EconomicsCommandBody={requestId:string;idempotencyKey:string;commandType:EconomicsCommandType;organizationId:string;workspaceId:string;authorizationVersion:number;expectedVersion:number;payload:Record<string,unknown>};
export type EconomicsCommandResource={id:string;status:string;version:number;scenarioResults?:unknown;confidence?:string;outcomeId?:string};
export type EconomicsTransport={invoke(body:EconomicsCommandBody):Promise<{outcome:'committed'|'replayed';resource:EconomicsCommandResource}>;loadProjection?(caseId:string,decisionId:string):Promise<{version?:EconomicVersion;technicalReady?:boolean;governanceApproved?:boolean;readOnly?:boolean;stale?:boolean;revoked?:boolean}>};
export const defaultEconomicsTransport:EconomicsTransport={async invoke(body){const response=await fetch('/functions/v1/assess-v2-command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok||!data?.ok)throw new Error(data?.error?.code||'COMMAND_UNAVAILABLE');return{outcome:data.outcome,resource:data.resource}}};
export const stableEconomicsIdempotencyKey=(type:EconomicsCommandType,resourceId:string,expectedVersion:number,operation='default')=>`${type}:${resourceId}:${expectedVersion}:${operation}`;
export const buildEconomicsCommand=(context:TenantContextProjection,type:EconomicsCommandType,expectedVersion:number,payload:Record<string,unknown>,idempotencyKey?:string):EconomicsCommandBody=>({requestId:crypto.randomUUID(),idempotencyKey:idempotencyKey??stableEconomicsIdempotencyKey(type,String(payload.economicVersionId??payload.outcomeId??payload.caseId??'workspace'),expectedVersion),commandType:type,organizationId:context.organizationId,workspaceId:context.workspaceId,authorizationVersion:context.authorizationVersion,expectedVersion,payload});
export const sendEconomicsCommand=(context:TenantContextProjection,type:EconomicsCommandType,expectedVersion:number,payload:Record<string,unknown>,transport=defaultEconomicsTransport,idempotencyKey?:string)=>transport.invoke(buildEconomicsCommand(context,type,expectedVersion,payload,idempotencyKey));
export const buildEconomicsProjection=(version:EconomicVersion,technicalReady:boolean,governanceApproved:boolean)=>{const scenarios=Array.isArray((version as any).scenarioResults)&&(version as any).scenarioResults.length===3?(version as any).scenarioResults:calculateScenarios(version);const confidence=((version as any).confidenceDerived??deriveConfidence(version));return{scenarios,confidence,calibration:calibrationSnapshot(scenarios,[]),portfolio:portfolioDisposition({technicalReady,governanceApproved,confidence,scenario:scenarios[1],currency:version.currency,complexity:'medium',dependencies:[]})}};
