import { strict as assert } from 'assert';
import { approveEconomics, blockCrossCurrencyAggregation, calculateScenarios, calibrationSnapshot, deriveConfidence, ECONOMIC_FORMULA_VERSION, ECONOMIC_MODEL_VERSION, EconomicVersion, portfolioDisposition, qualifyOutcomesForCalibration } from './assessV2/economics/domain';
const evidence={id:'ev-1',fresh:true,independent:true};
function fixture():EconomicVersion{return{organizationId:'org',workspaceId:'ws',caseId:'case',sourceAuthoringVersionId:'srcv',decisionVersionId:'decv',approvedReviewId:'rev',modelVersion:ECONOMIC_MODEL_VERSION,formulaVersion:ECONOMIC_FORMULA_VERSION,status:'draft',authorId:'author',currency:'USD',baselinePeriod:'2026-annual',analysisHorizonYears:3,implementationHorizonMonths:6,discountRate:.1,benefits:[{id:'cap',category:'capacity_released',range:{low:100,base:200,high:300,unit:'hours',period:'annual'},evidence:[evidence],owner:'ops',confidence:'Verified',includeInCash:false},{id:'cash',category:'avoidable_cash_expenditure',range:{low:10000,base:20000,high:30000,unit:'USD',period:'annual'},evidence:[evidence],owner:'finance',confidence:'Verified',includeInCash:true},{id:'rev',category:'revenue_protected',range:{low:5000,base:10000,high:15000,unit:'USD',period:'annual'},evidence:[evidence],owner:'sales',confidence:'Verified',includeInCash:true},{id:'risk',category:'risk_avoided',range:{low:0,base:0,high:0,unit:'USD',period:'annual'},evidence:[evidence],owner:'risk',confidence:'Verified',includeInCash:true,risk:{probability:{low:.01,base:.02,high:.03,unit:'probability',period:'annual'},exposure:{low:100000,base:200000,high:300000,unit:'USD',period:'annual'},controlEffectiveness:{low:.25,base:.5,high:.75,unit:'ratio',period:'annual'}}},{id:'sla',category:'sla_cycle_time_value',range:{low:1000,base:2000,high:3000,unit:'USD',period:'annual'},evidence:[evidence],owner:'service',confidence:'Verified',includeInCash:true}],costs:[{id:'build',category:'engineering_integration',range:{low:40000,base:50000,high:70000,unit:'USD',period:'one_time'},evidence:[evidence],owner:'eng',confidence:'Verified',includeInCash:true},{id:'ops',category:'monitoring_operations',range:{low:1000,base:2000,high:3000,unit:'USD',period:'monthly'},evidence:[evidence],owner:'ops',confidence:'Verified',includeInCash:true}]}}
function throws(fn:()=>unknown,msg:string){assert.throws(fn,new RegExp(msg))}
const f=fixture();const scenarios=calculateScenarios(f);assert.equal(scenarios[1].capacityReleased,200);assert.equal(scenarios[1].annualAvoidableCashBenefit,20000);assert.equal(scenarios[1].annualExpectedRiskAdjustedValue,2000);assert.equal(scenarios[1].netAnnualBenefit,10000);assert.equal(scenarios[1].paybackPeriodMonths,60);assert.ok(scenarios[1].trace.includes('capacity hours are reported separately from cash'));
const badCap=fixture();badCap.benefits[0]={...badCap.benefits[0],includeInCash:true};throws(()=>calculateScenarios(badCap),'CAPACITY_CASH_NEEDS_NON_OVERLAP');
const badCash=fixture();badCash.benefits[1].evidence=[{id:'x',fresh:true}];throws(()=>calculateScenarios(badCash),'CASH_SAVINGS_REQUIRE_EVIDENCE');
const missing=fixture();missing.currency='US';throws(()=>calculateScenarios(missing),'INVALID_CURRENCY');
const dup=fixture();dup.costs[0].id='cash';throws(()=>calculateScenarios(dup),'DUPLICATE_VALUE');
const order=fixture();order.costs[0].range={low:5,base:4,high:6,unit:'USD',period:'one_time'};throws(()=>calculateScenarios(order),'RANGE_ORDER');
const neg=fixture();neg.costs[0].range.low=-1;throws(()=>calculateScenarios(neg),'NEGATIVE_VALUE');
const lowFreq=fixture();lowFreq.benefits[3].risk!.probability.base=.001;lowFreq.benefits[3].risk!.exposure.base=10000000;assert.equal(calculateScenarios(lowFreq)[1].annualExpectedRiskAdjustedValue,5000);
assert.equal(deriveConfidence(f),'Verified');const stale=fixture();stale.benefits[0].evidence=[{id:'old',fresh:false,independent:true}];assert.equal(deriveConfidence(stale),'Assumption-Led');
throws(()=>approveEconomics(f,'author',true),'SEPARATION_OF_DUTIES');throws(()=>approveEconomics(f,'reviewer',false),'STALE_OR_MISSING_PR1E_REVIEW');assert.equal(approveEconomics(f,'reviewer',true).status,'approved');
const cal=calibrationSnapshot(scenarios,[{economicVersionId:'e',synthetic:true,reviewedBy:'r',owner:'o',period:'p',actuals:{netAnnualBenefit:1}}]);assert.equal(cal.status,'Insufficient Data');assert.equal(cal.sampleCount,0);assert.equal(cal.syntheticExcluded,1);assert.equal(qualifyOutcomesForCalibration([{economicVersionId:'e',estimated:true,reviewedBy:'r',owner:'o',period:'p',actuals:{}}]).sampleCount,0);
throws(()=>blockCrossCurrencyAggregation(['USD','EUR']),'INCOMPATIBLE_CURRENCIES');
assert.equal(portfolioDisposition({technicalReady:false,governanceApproved:true,confidence:'Verified',scenario:scenarios[1],currency:'USD',complexity:'low',dependencies:[]}).disposition,'Redesign process first');
assert.equal(portfolioDisposition({technicalReady:true,governanceApproved:true,confidence:'Assumption-Led',scenario:scenarios[1],currency:'USD',complexity:'low',dependencies:[]}).disposition,'Validate assumptions first');
assert.equal(portfolioDisposition({technicalReady:true,governanceApproved:true,confidence:'Verified',scenario:scenarios[1],currency:'USD',complexity:'low',dependencies:[]}).disposition,'Proceed to controlled design');
console.log('PR 1F economics domain tests passed');
