import assert from 'node:assert/strict';
import { buildApplicationCommand, stableApplicationIdempotencyKey, sendApplicationCommand, defaultApplicationPortfolioTransport, decodeApplicationProjection } from './assessV2ApplicationPortfolioClient';
(async()=>{
const context={userId:'u',organizationId:'o',organizationName:'Org',workspaceId:'w',workspaceName:'Ws',authorizationVersion:4,capabilities:['assess.applications.write']};
const metadata={name:'ERP',businessCapabilities:[],supportedProcesses:[],businessCriticality:'Unknown',lifecycleState:'Unknown',platform:[],languages:[],frameworks:[],sourceCode:'Unknown',documentationQuality:'Unknown',automatedTestMaturity:'Unknown',deploymentRepeatability:'Unknown',observability:'Unknown',dataClassifications:[],regulatedData:'Unknown',operatingRegions:[],interfaces:[],upstreamDependencies:[],downstreamDependencies:[],realTime:'Unknown',eventDriven:'Unknown',synchronous:'Unknown',batch:'Unknown',synthetic:false};
const projectionDto={inventory:[{id:'server',orgId:'o',workspaceId:'w',version:1,metadataVersion:1,metadata,authorId:'u',status:'draft',evidence:[]}],metadataVersions:[],importReceipts:[],processLinks:[],dependencies:[],assessments:[],dimensions:[],recommendations:[],reviews:[],portfolioSnapshot:null,waves:[],economicsReferences:[],rowOutcomes:[]};
(globalThis as any).__pr1gSupabaseClient={functions:{invoke:async(_:string,input:any)=>input.body.commandType==='application.create'?{data:{ok:true,outcome:'committed',resource:{id:'server',version:1,status:'draft'}}}:{data:{ok:false,error:{code:'VERSION_CONFLICT'}}}},rpc:async()=>({data:projectionDto})};
const key=stableApplicationIdempotencyKey('application.create','app',0,'manual');assert.equal(key,'application.create:app:0:manual');
const command=buildApplicationCommand(context as any,'application.create',0,{applicationId:'app',name:'ERP'},key);assert.equal(command.authorizationVersion,4);assert.equal(command.idempotencyKey,key);
let invoked:any;const result=await sendApplicationCommand(context as any,'application.create',0,{applicationId:'app'}, {invoke:async body=>{invoked=body;return{outcome:'committed',resource:{id:'app',version:1,status:'draft'}}},loadProjection:async()=>({...projectionDto,inventory:[]})});
assert.equal(invoked.commandType,'application.create');assert.equal(result.resource.id,'app');
const defaultResult=await defaultApplicationPortfolioTransport.invoke({...(command as any),requestId:'11111111-1111-4111-8111-111111111111'});assert.equal(defaultResult.resource.id,'server');
const projection=await defaultApplicationPortfolioTransport.loadProjection(context as any);assert.equal(projection.inventory[0].id,'server');
assert.throws(()=>decodeApplicationProjection(null),/MALFORMED/);
assert.throws(()=>decodeApplicationProjection({...projectionDto,extra:true}),/MALFORMED/);
assert.throws(()=>decodeApplicationProjection({...projectionDto,inventory:'bad'}),/MALFORMED/);
assert.throws(()=>decodeApplicationProjection({...projectionDto,portfolioSnapshot:'bad'}),/MALFORMED/);
assert.deepEqual(decodeApplicationProjection({...projectionDto,portfolioSnapshot:{id:'snapshot'}}).portfolioSnapshot,{id:'snapshot'});
assert.throws(()=>decodeApplicationProjection({...projectionDto,inventory:[{...projectionDto.inventory[0],evidence:[{id:'e',claimIds:['bad'],sourceType:'test',fresh:true,independent:true,accepted:true}]}]}),/MALFORMED/);
assert.throws(()=>decodeApplicationProjection({...projectionDto,assessments:[{id:'a',applicationId:'server',orgId:'o',workspaceId:'w',metadataVersion:1,version:1,status:'draft',authorId:'u',decisionModelVersion:'wrong',dimensions:[],recommendations:[]}]}),/MALFORMED/);
const dimensionNames=['integration_accessibility','semantic_and_data_clarity','state_and_execution','security_and_control','architecture_changeability','ui_automation_readiness','ai_assisted_engineering_readiness'];const decodedAssessment=decodeApplicationProjection({...projectionDto,assessments:[{id:'a',applicationId:'server',orgId:'o',workspaceId:'w',metadataVersion:1,version:1,status:'draft',authorId:'u',reviewerId:'r',decisionModelVersion:'assess-v2-application-portfolio-2026-07',dimensions:dimensionNames.map(d=>({dimension:d})),recommendations:[{}]}]}).assessments[0];assert.equal(decodedAssessment.reviewerId,'r');assert.equal(decodedAssessment.dimensions.length,7);
await assert.rejects(async()=>{(globalThis as any).__pr1gSupabaseClient.rpc=async()=>({data:{...projectionDto,inventory:[{id:'server'}]}});await defaultApplicationPortfolioTransport.loadProjection(context as any)},/MALFORMED_APPLICATION_PROJECTION/);
await assert.rejects(()=>defaultApplicationPortfolioTransport.invoke({...command,commandType:'application.metadata.upsert' as any,requestId:'11111111-1111-4111-8111-111111111112'}),/VERSION_CONFLICT/);
(globalThis as any).__pr1gSupabaseClient={functions:{invoke:async()=>({error:{context:{clone:()=>({json:async()=>({ok:false,error:{code:'READ_ONLY'}})})}}})},rpc:async()=>({error:{code:'PROJECTION_UNAVAILABLE'}})};
await assert.rejects(()=>defaultApplicationPortfolioTransport.invoke(command as any),/READ_ONLY|COMMAND_UNAVAILABLE/);await assert.rejects(()=>defaultApplicationPortfolioTransport.loadProjection(context as any),/PROJECTION_UNAVAILABLE/);
console.log('PR 1G application portfolio client transport tests passed.');
})().catch(error=>{console.error(error);process.exit(1)});
