import type { TenantContextProjection } from '../types';
import { EconomicVersion, calculateScenarios, deriveConfidence, portfolioDisposition, calibrationSnapshot } from './assessV2/economics/domain';
import { supabase } from './supabaseClient';

export type EconomicsCommandType='assessment_v2.economics.create'|'assessment_v2.economics.draft.upsert'|'assessment_v2.economics.finalize'|'assessment_v2.economics.review.resolve'|'assessment_v2.economics.revision.start'|'assessment_v2.outcomes.record'|'assessment_v2.outcomes.review'|'assessment_v2.calibration.snapshot.create';
export type EconomicsCommandBody={requestId:string;idempotencyKey:string;commandType:EconomicsCommandType;organizationId:string;workspaceId:string;authorizationVersion:number;expectedVersion:number;payload:Record<string,unknown>};
export type EconomicsCommandResource={id:string;status:string;version:number;scenarioResults?:unknown;confidence?:string;outcomeId?:string};
export type EconomicsProjection={version?:EconomicVersion;technicalReady?:boolean;governanceApproved?:boolean;readOnly?:boolean;stale?:boolean;revoked?:boolean;latestOutcome?:{id:string};latestOutcomeReview?:{id:string;resolution:string};calibrationStatus?:string;portfolioDisposition?:string};
export type EconomicsTransport={invoke(body:EconomicsCommandBody):Promise<{outcome:'committed'|'replayed';resource:EconomicsCommandResource}>;loadProjection?(caseId:string,decisionId:string,context?:TenantContextProjection):Promise<EconomicsProjection>};
export const defaultEconomicsTransport:EconomicsTransport={async invoke(body){const{data,error}=await supabase.functions.invoke('assess-v2-command',{body});let payload=data;if(error){try{payload=await(error as any).context?.clone?.().json()}catch{payload=undefined}}if(error||!payload?.ok)throw new Error(payload?.error?.code||'COMMAND_UNAVAILABLE');return{outcome:payload.outcome,resource:payload.resource}},async loadProjection(caseId,decisionId,context){if(!context)throw new Error('TENANT_CONTEXT_REQUIRED');const{data,error}=await supabase.rpc('pr1f_read_assess_v2_economics_projection',{p_org_id:context.organizationId,p_workspace_id:context.workspaceId,p_case_id:caseId,p_decision_id:decisionId});if(error)throw new Error(error.code||'PROJECTION_UNAVAILABLE');return data as EconomicsProjection}};
export const stableEconomicsIdempotencyKey=(type:EconomicsCommandType,resourceId:string,expectedVersion:number,operation='default')=>`${type}:${resourceId}:${expectedVersion}:${operation}`;
export const buildEconomicsCommand=(context:TenantContextProjection,type:EconomicsCommandType,expectedVersion:number,payload:Record<string,unknown>,idempotencyKey?:string):EconomicsCommandBody=>({requestId:crypto.randomUUID(),idempotencyKey:idempotencyKey??stableEconomicsIdempotencyKey(type,String(payload.economicVersionId??payload.outcomeId??payload.caseId??'workspace'),expectedVersion),commandType:type,organizationId:context.organizationId,workspaceId:context.workspaceId,authorizationVersion:context.authorizationVersion,expectedVersion,payload});
export const sendEconomicsCommand=(context:TenantContextProjection,type:EconomicsCommandType,expectedVersion:number,payload:Record<string,unknown>,transport=defaultEconomicsTransport,idempotencyKey?:string)=>transport.invoke(buildEconomicsCommand(context,type,expectedVersion,payload,idempotencyKey));
export const buildEconomicsProjection=(version:EconomicVersion,technicalReady:boolean,governanceApproved:boolean)=>{const scenarios=Array.isArray((version as any).scenarioResults)&&(version as any).scenarioResults.length===3?(version as any).scenarioResults:calculateScenarios(version);const confidence=((version as any).confidenceDerived??deriveConfidence(version));return{scenarios,confidence,calibration:calibrationSnapshot(scenarios,[]),portfolio:portfolioDisposition({technicalReady,governanceApproved,confidence,scenario:scenarios[1],currency:version.currency,complexity:'medium',dependencies:[]})}};
