import type { TenantContextProjection } from '../types';
import {
  APPLICATION_DIMENSIONS,
  APPLICATION_PORTFOLIO_MODEL_VERSION,
  type ApplicationMetadata,
  type ApplicationRecord,
  type DimensionResult,
  type EvidenceConfidence,
  type EvidenceRef,
  type ModernizationDisposition,
  type Recommendation,
  type ReviewState,
} from './assessV2/applicationPortfolio';
import { supabase } from './supabaseClient';

export type ApplicationCommandType='application.create'|'application.import'|'application.metadata.upsert'|'application.assessment.save'|'application.assessment.finalize'|'application.assessment.review.resolve'|'application.assessment.revision.start'|'application.portfolio.snapshot.create';
export type ApplicationCommandBody={requestId:string;idempotencyKey:string;commandType:ApplicationCommandType;organizationId:string;workspaceId:string;authorizationVersion:number;expectedVersion:number;payload:Record<string,unknown>};
export type ApplicationCommandResource={id:string;applicationId?:string;version:number;status:string;successCount?:number;rejectionCount?:number;name?:string};
export type ProjectionContext={organizationId:string;workspaceId:string};

export interface MetadataVersionDto {id:string;orgId:string;workspaceId:string;applicationId:string;version:number;status:ReviewState;metadata:ApplicationMetadata;authorId:string}
export interface ImportReceiptDto {id:string;orgId:string;workspaceId:string;actorId:string;successCount:number;rejectionCount:number}
export interface ImportRowOutcomeDto {id:string;orgId:string;workspaceId:string;importReceiptId:string;rowNumber:number;outcome:'success'|'rejected';applicationId:string|null;errorCode:string|null;errorMessage:string|null}
export interface ProcessApplicationLinkDto {id:string;orgId:string;workspaceId:string;processId:string;primitiveId:string;applicationId:string;metadataVersionId:string;assessmentVersionId:string;interactionType:string;governState:'approved'|'approval_required'|'rejected'|'Unknown';economicsRef:string|null;economicsCurrency:string|null}
export interface ApplicationDependencyDto {id:string;orgId:string;workspaceId:string;upstreamApplicationId:string;downstreamApplicationId:string;dependencyType:string;metadataVersionId:string}
export interface AssessmentVersionDto {id:string;applicationId:string;orgId:string;workspaceId:string;metadataVersionId:string;metadataVersion:number;version:number;status:ReviewState;authorId:string;reviewerId:string|null;authorizationVersion:number;receiptId:string|null;auditEventId:string|null;decisionModelVersion:typeof APPLICATION_PORTFOLIO_MODEL_VERSION;dimensions:DimensionResult[];recommendations:Recommendation[]}
export interface DimensionResultDto extends DimensionResult {id:string;orgId:string;workspaceId:string;applicationId:string;metadataVersionId:string;assessmentVersionId:string}
export interface ModernizationRecommendationDto extends Recommendation {id:string;orgId:string;workspaceId:string;metadataVersionId:string;assessmentVersionId:string}
export interface ReviewResolutionDto {id:string;orgId:string;workspaceId:string;applicationId:string;metadataVersionId:string;assessmentVersionId:string;reviewerId:string;authorizationVersion:number;resolution:'approved'|'changes_requested'|'rejected';rationale:string;conditions:string[];receiptId:string;auditEventId:string}
export interface PortfolioWaveDto {applicationId:string;wave:number;approvedAutomatically:false;qualified:boolean}
export interface PortfolioSnapshotDto {id:string;orgId:string;workspaceId:string;version:number;modelVersion:typeof APPLICATION_PORTFOLIO_MODEL_VERSION;approvedAutomatically:false;inventoryCount:number;waves:PortfolioWaveDto[]}
export interface EconomicsReferenceDto {referenceId:string;orgId:string;workspaceId:string;currency:string}
export interface ApplicationProjection {inventory:ApplicationRecord[];metadataVersions:MetadataVersionDto[];importReceipts:ImportReceiptDto[];rowOutcomes:ImportRowOutcomeDto[];processLinks:ProcessApplicationLinkDto[];dependencies:ApplicationDependencyDto[];assessments:AssessmentVersionDto[];dimensions:DimensionResultDto[];recommendations:ModernizationRecommendationDto[];reviews:ReviewResolutionDto[];portfolioSnapshot:PortfolioSnapshotDto|null;waves:PortfolioWaveDto[];economicsReferences:EconomicsReferenceDto[]}
export type ApplicationPortfolioTransport={invoke(body:ApplicationCommandBody):Promise<{outcome:'committed'|'replayed';resource:ApplicationCommandResource}>;loadProjection(context:TenantContextProjection):Promise<ApplicationProjection>};

const fail=():never=>{throw new Error('MALFORMED_APPLICATION_PROJECTION')};
const isObject=(value:unknown):value is {[key:string]:unknown}=>value!==null&&typeof value==='object'&&!Array.isArray(value);
const object=(value:unknown)=>isObject(value)?value:fail();
const array=(value:unknown)=>Array.isArray(value)?value:fail();
const exact=(value:unknown,required:readonly string[],optional:readonly string[]=[]):{[key:string]:unknown}=>{
  const row=object(value),allowed=new Set([...required,...optional]),keys=Object.keys(row);
  if(required.some(key=>!Object.hasOwn(row,key))||keys.some(key=>!allowed.has(key)))fail();
  return row;
};
const text=(value:unknown)=>typeof value==='string'&&value.trim().length>0?value:fail();
const uuid=(value:unknown)=>{const result=text(value);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(result))fail();return result};
const integer=(value:unknown,min=0)=>Number.isSafeInteger(value)&&Number(value)>=min?Number(value):fail();
const boolean=(value:unknown)=>typeof value==='boolean'?value:fail();
const nullable=<T>(value:unknown,decode:(input:unknown)=>T):T|null=>value===null?null:decode(value);
const enumeration=<T extends string>(value:unknown,values:readonly T[]):T=>typeof value==='string'&&values.includes(value as T)?value as T:fail();
const strings=(value:unknown)=>array(value).map(text);
const unique=(values:string[])=>{if(new Set(values).size!==values.length)fail()};
const tenant=(row:{[key:string]:unknown},context:ProjectionContext)=>{if(uuid(row.orgId)!==context.organizationId||uuid(row.workspaceId)!==context.workspaceId)fail()};

const reviewStates:readonly ReviewState[]=['draft','reviewer_ready','approved','changes_requested','rejected','superseded'];
const bands=['Ready','Conditionally Ready','Blocked','Unknown'] as const;
const confidences:readonly EvidenceConfidence[]=['Verified','Partially Evidenced','Assumption-Led','Insufficient Evidence'];
const dispositions:readonly ModernizationDisposition[]=['Retain and monitor','Enable native API/event integration','Add API façade and semantic translation','Add event or CDC bridge','Use governed workflow/RPA bridge','Use governed UI/vision bridge','Refactor through strangler or modular decomposition','Replatform','Replace with supported product or SaaS','Rebuild through controlled AI-assisted delivery','Consolidate duplicate applications','Retire','Insufficient evidence','Blocked pending prerequisite'];

const evidence=(value:unknown):EvidenceRef=>{
  const row=exact(value,['id','claimIds','sourceType','fresh','independent','accepted','contradicts','synthetic']);
  const claimIds=strings(row.claimIds);
  if(claimIds.some(claim=>!APPLICATION_DIMENSIONS.includes(enumeration(claim,APPLICATION_DIMENSIONS))))fail();
  return{id:text(row.id),claimIds,sourceType:enumeration(row.sourceType,['manual','document','review','test','synthetic_fixture']),fresh:boolean(row.fresh),independent:boolean(row.independent),accepted:boolean(row.accepted),contradicts:boolean(row.contradicts),synthetic:boolean(row.synthetic)};
};
const evidenceList=(value:unknown)=>{const result=array(value).map(evidence);unique(result.map(item=>item.id));return result};
const optionalText=(row:{[key:string]:unknown},key:string)=>row[key]===undefined?undefined:text(row[key]);
const optionalStrings=(row:{[key:string]:unknown},key:string)=>row[key]===undefined?undefined:strings(row[key]);
const optionalBoolean=(row:{[key:string]:unknown},key:string)=>row[key]===undefined?undefined:boolean(row[key]);
const partialBooleans=(value:unknown,keys:readonly string[])=>{const row=exact(value,[],keys);const output:{[key:string]:boolean}={};for(const key of keys)if(row[key]!==undefined)output[key]=boolean(row[key]);return output};
const metadata=(value:unknown):ApplicationMetadata=>{
  const required=['name','businessCapabilities','supportedProcesses','businessCriticality','lifecycleState','sourceCode','documentationQuality','automatedTestMaturity','deploymentRepeatability','observability','dataClassifications','regulatedData','operatingRegions','interfaces','upstreamDependencies','downstreamDependencies','realTime','eventDriven','synchronous','batch','synthetic'];
  const optional=['description','businessOwner','technicalOwner','vendor','product','version','eolStatus','hostingModel','platform','languages','frameworks','bridgeEvidence','aiControls','ageYears'];
  const row=exact(value,required,optional);
  const triBoolean=(input:unknown)=>input==='Unknown'?'Unknown' as const:boolean(input);
  const result:ApplicationMetadata={
    name:text(row.name),businessCapabilities:strings(row.businessCapabilities),supportedProcesses:strings(row.supportedProcesses),
    businessCriticality:enumeration(row.businessCriticality,['low','medium','high','mission_critical','Unknown']),lifecycleState:enumeration(row.lifecycleState,['current','maintenance','eol','unsupported','retiring','Unknown']),
    sourceCode:enumeration(row.sourceCode,['available_legal_access','available_no_legal_access','unavailable','Unknown']),documentationQuality:enumeration(row.documentationQuality,['high','medium','low','Unknown']),
    automatedTestMaturity:enumeration(row.automatedTestMaturity,['executable_acceptance','unit_or_integration','manual_only','none','Unknown']),deploymentRepeatability:enumeration(row.deploymentRepeatability,['deterministic','repeatable_manual','ad_hoc','Unknown']),
    observability:enumeration(row.observability,['strong','partial','weak','Unknown']),dataClassifications:strings(row.dataClassifications),regulatedData:triBoolean(row.regulatedData),operatingRegions:strings(row.operatingRegions),
    interfaces:array(row.interfaces).map(item=>enumeration(item,['REST/GraphQL','SOAP','messaging/event','database','file/batch','command-line','UI-only','desktop/mainframe/Citrix'])),
    upstreamDependencies:strings(row.upstreamDependencies),downstreamDependencies:strings(row.downstreamDependencies),realTime:triBoolean(row.realTime),eventDriven:triBoolean(row.eventDriven),synchronous:triBoolean(row.synchronous),batch:triBoolean(row.batch),synthetic:boolean(row.synthetic),
  };
  for(const key of ['description','businessOwner','technicalOwner','vendor','product','version','hostingModel'] as const){const decoded=optionalText(row,key);if(decoded!==undefined)result[key]=decoded}
  if(row.eolStatus!==undefined)result.eolStatus=enumeration(row.eolStatus,['supported','eol_announced','eol','Unknown']);
  for(const key of ['platform','languages','frameworks'] as const){const decoded=optionalStrings(row,key);if(decoded!==undefined)result[key]=decoded}
  if(row.bridgeEvidence!==undefined)result.bridgeEvidence=partialBooleans(row.bridgeEvidence,['stableInterface','controlAccessibility','deterministicErrorDetection','reversibilityOrCompensation','materialActionApproval','monitoring','humanOwner']);
  if(row.aiControls!==undefined)result.aiControls=partialBooleans(row.aiControls,['legalSourceRights','executableAcceptanceTests','reproducibleBuild','controlledSecurityReview','humanEngineeringOwner','controlledDeploymentRollback']);
  if(row.ageYears!==undefined){const age=typeof row.ageYears==='number'?row.ageYears:fail();if(!Number.isFinite(age)||age<0)fail();result.ageYears=age}
  return result;
};
const dimension=(value:unknown):DimensionResult=>{
  const row=exact(value,['dimension','band','confidence','hardGates','evidenceReferences','missingEvidence','rationale','contradictions','remediationRequirements','whatWouldChange']);
  return{dimension:enumeration(row.dimension,APPLICATION_DIMENSIONS),band:enumeration(row.band,bands),confidence:enumeration(row.confidence,confidences),hardGates:strings(row.hardGates),evidenceReferences:evidenceList(row.evidenceReferences),missingEvidence:strings(row.missingEvidence),rationale:strings(row.rationale),contradictions:strings(row.contradictions),remediationRequirements:strings(row.remediationRequirements),whatWouldChange:strings(row.whatWouldChange)};
};
const recommendation=(value:unknown):Recommendation=>{
  const row=exact(value,['disposition','applicationId','metadataVersion','affectedProcesses','affectedPrimitives','why','alternativesConsidered','alternativesRejected','prerequisites','requiredControls','migrationBoundary','dependencyImpacts','rollback','confidence','openEvidenceGaps','whatWouldChange']);
  return{disposition:enumeration(row.disposition,dispositions),applicationId:uuid(row.applicationId),metadataVersion:integer(row.metadataVersion,1),affectedProcesses:strings(row.affectedProcesses),affectedPrimitives:strings(row.affectedPrimitives),why:strings(row.why),alternativesConsidered:strings(row.alternativesConsidered),alternativesRejected:strings(row.alternativesRejected),prerequisites:strings(row.prerequisites),requiredControls:strings(row.requiredControls),migrationBoundary:text(row.migrationBoundary),dependencyImpacts:strings(row.dependencyImpacts),rollback:text(row.rollback),confidence:enumeration(row.confidence,confidences),openEvidenceGaps:strings(row.openEvidenceGaps),whatWouldChange:strings(row.whatWouldChange)};
};
const dimensions=(value:unknown)=>{const result=array(value).map(dimension);if(result.length!==APPLICATION_DIMENSIONS.length)fail();unique(result.map(item=>item.dimension));if(APPLICATION_DIMENSIONS.some(name=>!result.some(item=>item.dimension===name)))fail();return result};
const recommendations=(value:unknown)=>array(value).map(recommendation);
const application=(value:unknown,context:ProjectionContext):ApplicationRecord=>{const row=exact(value,['id','orgId','workspaceId','version','metadataVersion','metadata','authorId','status','evidence']);tenant(row,context);return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),version:integer(row.version,1),metadataVersion:integer(row.metadataVersion),metadata:metadata(row.metadata),authorId:uuid(row.authorId),status:enumeration(row.status,reviewStates),evidence:evidenceList(row.evidence)}};
const wave=(value:unknown):PortfolioWaveDto=>{const row=exact(value,['applicationId','wave','approvedAutomatically','qualified']);if(boolean(row.approvedAutomatically)!==false)fail();return{applicationId:uuid(row.applicationId),wave:integer(row.wave,1),approvedAutomatically:false,qualified:boolean(row.qualified)}};

export function decodeApplicationProjection(value:unknown,expected?:ProjectionContext):ApplicationProjection{
  const context=expected??fail(),p=exact(value,['inventory','metadataVersions','importReceipts','rowOutcomes','processLinks','dependencies','assessments','dimensions','recommendations','reviews','portfolioSnapshot','waves','economicsReferences']);
  const inventory=array(p.inventory).map(item=>application(item,context));unique(inventory.map(item=>item.id));
  const metadataVersions=array(p.metadataVersions).map((item):MetadataVersionDto=>{const row=exact(item,['id','orgId','workspaceId','applicationId','version','status','metadata','authorId']);tenant(row,context);return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),applicationId:uuid(row.applicationId),version:integer(row.version,1),status:enumeration(row.status,reviewStates),metadata:metadata(row.metadata),authorId:uuid(row.authorId)}});unique(metadataVersions.map(item=>item.id));
  const importReceipts=array(p.importReceipts).map((item):ImportReceiptDto=>{const row=exact(item,['id','orgId','workspaceId','actorId','successCount','rejectionCount']);tenant(row,context);return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),actorId:uuid(row.actorId),successCount:integer(row.successCount),rejectionCount:integer(row.rejectionCount)}});unique(importReceipts.map(item=>item.id));
  const rowOutcomes=array(p.rowOutcomes).map((item):ImportRowOutcomeDto=>{const row=exact(item,['id','orgId','workspaceId','importReceiptId','rowNumber','outcome','applicationId','errorCode','errorMessage']);tenant(row,context);return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),importReceiptId:uuid(row.importReceiptId),rowNumber:integer(row.rowNumber,1),outcome:enumeration(row.outcome,['success','rejected']),applicationId:nullable(row.applicationId,uuid),errorCode:nullable(row.errorCode,text),errorMessage:nullable(row.errorMessage,text)}});unique(rowOutcomes.map(item=>item.id));unique(rowOutcomes.map(item=>`${item.importReceiptId}:${item.rowNumber}`));
  for(const receipt of importReceipts){const outcomes=rowOutcomes.filter(item=>item.importReceiptId===receipt.id);if(outcomes.filter(item=>item.outcome==='success').length!==receipt.successCount||outcomes.filter(item=>item.outcome==='rejected').length!==receipt.rejectionCount)fail()}
  const processLinks=array(p.processLinks).map((item):ProcessApplicationLinkDto=>{const row=exact(item,['id','orgId','workspaceId','processId','primitiveId','applicationId','metadataVersionId','assessmentVersionId','interactionType','governState','economicsRef','economicsCurrency']);tenant(row,context);const economicsRef=nullable(row.economicsRef,uuid),economicsCurrency=nullable(row.economicsCurrency,value=>{const currency=text(value);if(!/^[A-Z]{3}$/.test(currency))fail();return currency});if((economicsRef===null)!==(economicsCurrency===null))fail();return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),processId:uuid(row.processId),primitiveId:text(row.primitiveId),applicationId:uuid(row.applicationId),metadataVersionId:uuid(row.metadataVersionId),assessmentVersionId:uuid(row.assessmentVersionId),interactionType:text(row.interactionType),governState:enumeration(row.governState,['approved','approval_required','rejected','Unknown']),economicsRef,economicsCurrency}});unique(processLinks.map(item=>item.id));
  const dependencies=array(p.dependencies).map((item):ApplicationDependencyDto=>{const row=exact(item,['id','orgId','workspaceId','upstreamApplicationId','downstreamApplicationId','dependencyType','metadataVersionId']);tenant(row,context);const upstreamApplicationId=uuid(row.upstreamApplicationId),downstreamApplicationId=uuid(row.downstreamApplicationId);if(upstreamApplicationId===downstreamApplicationId)fail();return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),upstreamApplicationId,downstreamApplicationId,dependencyType:text(row.dependencyType),metadataVersionId:uuid(row.metadataVersionId)}});unique(dependencies.map(item=>item.id));
  const assessments=array(p.assessments).map((item):AssessmentVersionDto=>{const row=exact(item,['id','applicationId','orgId','workspaceId','metadataVersionId','metadataVersion','version','status','authorId','reviewerId','authorizationVersion','receiptId','auditEventId','decisionModelVersion','dimensions','recommendations']);tenant(row,context);const id=uuid(row.id),applicationId=uuid(row.applicationId),metadataVersion=integer(row.metadataVersion,1),decodedDimensions=dimensions(row.dimensions),decodedRecommendations=recommendations(row.recommendations);if(row.decisionModelVersion!==APPLICATION_PORTFOLIO_MODEL_VERSION||decodedRecommendations.some(item=>item.applicationId!==applicationId||item.metadataVersion!==metadataVersion))fail();return{id,applicationId,orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),metadataVersionId:uuid(row.metadataVersionId),metadataVersion,version:integer(row.version,1),status:enumeration(row.status,reviewStates),authorId:uuid(row.authorId),reviewerId:nullable(row.reviewerId,uuid),authorizationVersion:integer(row.authorizationVersion,1),receiptId:nullable(row.receiptId,uuid),auditEventId:nullable(row.auditEventId,uuid),decisionModelVersion:APPLICATION_PORTFOLIO_MODEL_VERSION,dimensions:decodedDimensions,recommendations:decodedRecommendations}});unique(assessments.map(item=>item.id));
  const dimensionRows=array(p.dimensions).map((item):DimensionResultDto=>{const row=exact(item,['id','orgId','workspaceId','applicationId','metadataVersionId','assessmentVersionId','dimension','band','confidence','hardGates','evidenceReferences','missingEvidence','rationale','contradictions','remediationRequirements','whatWouldChange']);tenant(row,context);return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),applicationId:uuid(row.applicationId),metadataVersionId:uuid(row.metadataVersionId),assessmentVersionId:uuid(row.assessmentVersionId),...dimension({dimension:row.dimension,band:row.band,confidence:row.confidence,hardGates:row.hardGates,evidenceReferences:row.evidenceReferences,missingEvidence:row.missingEvidence,rationale:row.rationale,contradictions:row.contradictions,remediationRequirements:row.remediationRequirements,whatWouldChange:row.whatWouldChange})}});unique(dimensionRows.map(item=>item.id));unique(dimensionRows.map(item=>`${item.assessmentVersionId}:${item.dimension}`));
  const recommendationRows=array(p.recommendations).map((item):ModernizationRecommendationDto=>{const row=exact(item,['id','orgId','workspaceId','applicationId','metadataVersionId','metadataVersion','assessmentVersionId','disposition','affectedProcesses','affectedPrimitives','why','alternativesConsidered','alternativesRejected','prerequisites','requiredControls','migrationBoundary','dependencyImpacts','rollback','confidence','openEvidenceGaps','whatWouldChange']);tenant(row,context);return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),metadataVersionId:uuid(row.metadataVersionId),assessmentVersionId:uuid(row.assessmentVersionId),...recommendation({disposition:row.disposition,applicationId:row.applicationId,metadataVersion:row.metadataVersion,affectedProcesses:row.affectedProcesses,affectedPrimitives:row.affectedPrimitives,why:row.why,alternativesConsidered:row.alternativesConsidered,alternativesRejected:row.alternativesRejected,prerequisites:row.prerequisites,requiredControls:row.requiredControls,migrationBoundary:row.migrationBoundary,dependencyImpacts:row.dependencyImpacts,rollback:row.rollback,confidence:row.confidence,openEvidenceGaps:row.openEvidenceGaps,whatWouldChange:row.whatWouldChange})}});unique(recommendationRows.map(item=>item.id));
  const reviews=array(p.reviews).map((item):ReviewResolutionDto=>{const row=exact(item,['id','orgId','workspaceId','applicationId','metadataVersionId','assessmentVersionId','reviewerId','authorizationVersion','resolution','rationale','conditions','receiptId','auditEventId']);tenant(row,context);return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),applicationId:uuid(row.applicationId),metadataVersionId:uuid(row.metadataVersionId),assessmentVersionId:uuid(row.assessmentVersionId),reviewerId:uuid(row.reviewerId),authorizationVersion:integer(row.authorizationVersion,1),resolution:enumeration(row.resolution,['approved','changes_requested','rejected']),rationale:text(row.rationale),conditions:strings(row.conditions),receiptId:uuid(row.receiptId),auditEventId:uuid(row.auditEventId)}});unique(reviews.map(item=>item.id));
  const waves=array(p.waves).map(wave);unique(waves.map(item=>item.applicationId));
  const portfolioSnapshot:PortfolioSnapshotDto|null=p.portfolioSnapshot===null?null:(()=>{const row=exact(p.portfolioSnapshot,['id','orgId','workspaceId','version','modelVersion','approvedAutomatically','inventoryCount','waves']);tenant(row,context);if(row.modelVersion!==APPLICATION_PORTFOLIO_MODEL_VERSION||boolean(row.approvedAutomatically)!==false)fail();const snapshotWaves=array(row.waves).map(wave);unique(snapshotWaves.map(item=>item.applicationId));if(integer(row.inventoryCount)!==inventory.length||JSON.stringify(snapshotWaves)!==JSON.stringify(waves))fail();return{id:uuid(row.id),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),version:integer(row.version,1),modelVersion:APPLICATION_PORTFOLIO_MODEL_VERSION,approvedAutomatically:false,inventoryCount:inventory.length,waves:snapshotWaves}})();
  if(portfolioSnapshot===null&&waves.length)fail();
  const economicsReferences=array(p.economicsReferences).map((item):EconomicsReferenceDto=>{const row=exact(item,['referenceId','orgId','workspaceId','currency']);tenant(row,context);const currency=text(row.currency);if(!/^[A-Z]{3}$/.test(currency))fail();return{referenceId:uuid(row.referenceId),orgId:uuid(row.orgId),workspaceId:uuid(row.workspaceId),currency}});unique(economicsReferences.map(item=>item.referenceId));
  const appById=new Map(inventory.map(item=>[item.id,item])),metadataById=new Map(metadataVersions.map(item=>[item.id,item])),assessmentById=new Map(assessments.map(item=>[item.id,item]));
  for(const item of metadataVersions)if(!appById.has(item.applicationId))fail();
  for(const item of assessments){const metadataRow=metadataById.get(item.metadataVersionId);if(!appById.has(item.applicationId)||!metadataRow||metadataRow.applicationId!==item.applicationId||metadataRow.version!==item.metadataVersion)fail()}
  for(const item of rowOutcomes){let receiptFound=false;for(const receipt of importReceipts)if(receipt.id===item.importReceiptId)receiptFound=true;if(!receiptFound||(item.outcome==='success'?item.applicationId===null||!appById.has(item.applicationId)||item.errorCode!==null||item.errorMessage!==null:item.applicationId!==null||item.errorCode===null))fail()}
  for(const item of processLinks){const metadataRow=metadataById.get(item.metadataVersionId),assessmentRow=assessmentById.get(item.assessmentVersionId);if(!appById.has(item.applicationId)||!metadataRow||metadataRow.applicationId!==item.applicationId||!assessmentRow||assessmentRow.applicationId!==item.applicationId||assessmentRow.metadataVersionId!==item.metadataVersionId)fail()}
  for(const item of dependencies){const metadataRow=metadataById.get(item.metadataVersionId);if(!appById.has(item.upstreamApplicationId)||!appById.has(item.downstreamApplicationId)||!metadataRow||metadataRow.applicationId!==item.downstreamApplicationId)fail()}
  for(const item of dimensionRows){const assessmentRow=assessmentById.get(item.assessmentVersionId);if(!assessmentRow||assessmentRow.applicationId!==item.applicationId||assessmentRow.metadataVersionId!==item.metadataVersionId)fail()}
  for(const item of recommendationRows){const assessmentRow=assessmentById.get(item.assessmentVersionId);if(!assessmentRow||assessmentRow.applicationId!==item.applicationId||assessmentRow.metadataVersionId!==item.metadataVersionId||assessmentRow.metadataVersion!==item.metadataVersion)fail()}
  for(const item of reviews){const assessmentRow=assessmentById.get(item.assessmentVersionId);if(!assessmentRow||assessmentRow.applicationId!==item.applicationId||assessmentRow.metadataVersionId!==item.metadataVersionId)fail()}
  for(const item of waves)if(!appById.has(item.applicationId))fail();
  if(portfolioSnapshot!==null){if(waves.length!==inventory.length)fail();for(const item of inventory){let found=false;for(const waveRow of waves)if(waveRow.applicationId===item.id)found=true;if(!found)fail()}}
  for(const item of economicsReferences){let found=false;for(const link of processLinks)if(link.economicsRef===item.referenceId&&link.economicsCurrency===item.currency)found=true;if(!found)fail()}
  return{inventory,metadataVersions,importReceipts,rowOutcomes,processLinks,dependencies,assessments,dimensions:dimensionRows,recommendations:recommendationRows,reviews,portfolioSnapshot,waves,economicsReferences};
}

export const defaultApplicationPortfolioTransport:ApplicationPortfolioTransport={async invoke(body){const{data,error}=await supabase.functions.invoke('assess-v2-command',{body});let payload=data;if(error){try{payload=await(error as any).context?.clone?.().json()}catch{payload=undefined}}if(error||!payload?.ok)throw new Error(payload?.error?.code||'COMMAND_UNAVAILABLE');return{outcome:payload.outcome,resource:payload.resource}},async loadProjection(context){const{data,error}=await supabase.rpc('pr1g_read_application_portfolio_projection',{p_org_id:context.organizationId,p_workspace_id:context.workspaceId});if(error)throw new Error(error.code||'PROJECTION_UNAVAILABLE');return decodeApplicationProjection(data,{organizationId:context.organizationId,workspaceId:context.workspaceId})}};
export const stableApplicationIdempotencyKey=(type:ApplicationCommandType,resourceId:string,expectedVersion:number,operation='default')=>`${type}:${resourceId}:${expectedVersion}:${operation}`;
export const buildApplicationCommand=(context:TenantContextProjection,type:ApplicationCommandType,expectedVersion:number,payload:Record<string,unknown>,idempotencyKey?:string):ApplicationCommandBody=>({requestId:crypto.randomUUID(),idempotencyKey:idempotencyKey??stableApplicationIdempotencyKey(type,String(payload.applicationId??payload.assessmentVersionId??payload.importReceiptId??payload.portfolioSnapshotId??'workspace'),expectedVersion),commandType:type,organizationId:context.organizationId,workspaceId:context.workspaceId,authorizationVersion:context.authorizationVersion,expectedVersion,payload});
export const sendApplicationCommand=(context:TenantContextProjection,type:ApplicationCommandType,expectedVersion:number,payload:Record<string,unknown>,transport=defaultApplicationPortfolioTransport,idempotencyKey?:string)=>transport.invoke(buildApplicationCommand(context,type,expectedVersion,payload,idempotencyKey));
