import type { TenantContextProjection } from '../types';
import { APPLICATION_DIMENSIONS, APPLICATION_PORTFOLIO_MODEL_VERSION, validateApplicationMetadata, validateEvidenceRefs, type ApplicationMetadata, type ApplicationRecord, type AssessmentVersion, type EvidenceRef } from './assessV2/applicationPortfolio';
import { supabase } from './supabaseClient';
export type ApplicationCommandType='application.create'|'application.import'|'application.metadata.upsert'|'application.assessment.save'|'application.assessment.finalize'|'application.assessment.review.resolve'|'application.assessment.revision.start'|'application.portfolio.snapshot.create';
export type ApplicationCommandBody={requestId:string;idempotencyKey:string;commandType:ApplicationCommandType;organizationId:string;workspaceId:string;authorizationVersion:number;expectedVersion:number;payload:Record<string,unknown>};
export type ApplicationCommandResource={id:string;applicationId?:string;version:number;status:string;successCount?:number;rejectionCount?:number;name?:string};
export type ApplicationProjection={inventory:ApplicationRecord[];metadataVersions:Record<string,unknown>[];importReceipts:Record<string,unknown>[];processLinks:Record<string,unknown>[];dependencies:Record<string,unknown>[];assessments:AssessmentVersion[];dimensions:Record<string,unknown>[];recommendations:Record<string,unknown>[];reviews:Record<string,unknown>[];portfolioSnapshot:Record<string,unknown>|null;waves:Record<string,unknown>[];economicsReferences:Record<string,unknown>[];rowOutcomes:Record<string,unknown>[]};
export type ApplicationPortfolioTransport={invoke(body:ApplicationCommandBody):Promise<{outcome:'committed'|'replayed';resource:ApplicationCommandResource}>;loadProjection(context:TenantContextProjection):Promise<ApplicationProjection>};
const fail=():never=>{throw new Error('MALFORMED_APPLICATION_PROJECTION')};const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:fail();const list=(v:unknown)=>Array.isArray(v)?v:fail();const str=(v:unknown)=>typeof v==='string'&&v.length?v:fail();const num=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>=0?Number(v):fail();const records=(v:unknown)=>list(v).map(obj);
const evidence=(v:unknown):EvidenceRef[]=>{if(validateEvidenceRefs(v).length)fail();return v as EvidenceRef[]};
const application=(v:unknown):ApplicationRecord=>{const r=obj(v),metadata=obj(r.metadata) as unknown as ApplicationMetadata;if(validateApplicationMetadata(metadata).length)fail();return{id:str(r.id),orgId:str(r.orgId),workspaceId:str(r.workspaceId),version:num(r.version),metadataVersion:num(r.metadataVersion),metadata,authorId:str(r.authorId),status:str(r.status) as ApplicationRecord['status'],evidence:evidence(r.evidence)}};
const assessment=(v:unknown):AssessmentVersion=>{const r=obj(v),dimensions=records(r.dimensions),recommendations=records(r.recommendations);if(r.decisionModelVersion!==APPLICATION_PORTFOLIO_MODEL_VERSION||dimensions.length!==7||new Set(dimensions.map(d=>d.dimension)).size!==7||dimensions.some(d=>!APPLICATION_DIMENSIONS.includes(d.dimension as typeof APPLICATION_DIMENSIONS[number])))fail();return{id:str(r.id),applicationId:str(r.applicationId),orgId:str(r.orgId),workspaceId:str(r.workspaceId),metadataVersion:num(r.metadataVersion),version:num(r.version),status:str(r.status) as AssessmentVersion['status'],authorId:str(r.authorId),reviewerId:r.reviewerId===undefined?undefined:str(r.reviewerId),decisionModelVersion:APPLICATION_PORTFOLIO_MODEL_VERSION,dimensions:dimensions as unknown as AssessmentVersion['dimensions'],recommendations:recommendations as unknown as AssessmentVersion['recommendations']}};
export function decodeApplicationProjection(value:unknown):ApplicationProjection{const p=obj(value);const required=['inventory','metadataVersions','importReceipts','rowOutcomes','processLinks','dependencies','assessments','dimensions','recommendations','reviews','portfolioSnapshot','waves','economicsReferences'];if(Object.keys(p).some(k=>!required.includes(k))||required.some(k=>!(k in p)))fail();return{inventory:list(p.inventory).map(application),metadataVersions:records(p.metadataVersions),importReceipts:records(p.importReceipts),rowOutcomes:records(p.rowOutcomes),processLinks:records(p.processLinks),dependencies:records(p.dependencies),assessments:list(p.assessments).map(assessment),dimensions:records(p.dimensions),recommendations:records(p.recommendations),reviews:records(p.reviews),portfolioSnapshot:p.portfolioSnapshot===null?null:obj(p.portfolioSnapshot),waves:records(p.waves),economicsReferences:records(p.economicsReferences)}}
export const defaultApplicationPortfolioTransport:ApplicationPortfolioTransport={async invoke(body){const{data,error}=await supabase.functions.invoke('assess-v2-command',{body});let payload=data;if(error){try{payload=await(error as any).context?.clone?.().json()}catch{payload=undefined}}if(error||!payload?.ok)throw new Error(payload?.error?.code||'COMMAND_UNAVAILABLE');return{outcome:payload.outcome,resource:payload.resource}},async loadProjection(context){const{data,error}=await supabase.rpc('pr1g_read_application_portfolio_projection',{p_org_id:context.organizationId,p_workspace_id:context.workspaceId});if(error)throw new Error(error.code||'PROJECTION_UNAVAILABLE');return decodeApplicationProjection(data)}};
export const stableApplicationIdempotencyKey=(type:ApplicationCommandType,resourceId:string,expectedVersion:number,operation='default')=>`${type}:${resourceId}:${expectedVersion}:${operation}`;
export const buildApplicationCommand=(context:TenantContextProjection,type:ApplicationCommandType,expectedVersion:number,payload:Record<string,unknown>,idempotencyKey?:string):ApplicationCommandBody=>({requestId:crypto.randomUUID(),idempotencyKey:idempotencyKey??stableApplicationIdempotencyKey(type,String(payload.applicationId??payload.assessmentVersionId??payload.importReceiptId??payload.portfolioSnapshotId??'workspace'),expectedVersion),commandType:type,organizationId:context.organizationId,workspaceId:context.workspaceId,authorizationVersion:context.authorizationVersion,expectedVersion,payload});
export const sendApplicationCommand=(context:TenantContextProjection,type:ApplicationCommandType,expectedVersion:number,payload:Record<string,unknown>,transport=defaultApplicationPortfolioTransport,idempotencyKey?:string)=>transport.invoke(buildApplicationCommand(context,type,expectedVersion,payload,idempotencyKey));
