import { escapePlainText } from './safeMarkdown';

export type SanitizedDocumentBodyHtml = string & { readonly __sanitizedDocumentBodyHtml: unique symbol };

export const markSanitizedDocumentBodyHtml = (html: string) => html as SanitizedDocumentBodyHtml;

const baseStyles = `
    body { font-family: Arial, sans-serif; color: #0f172a; line-height: 1.55; }
    h1 { color: #002c4b; font-size: 28px; margin-bottom: 6px; }
    h2 { color: #002c4b; font-size: 20px; margin-top: 28px; border-bottom: 1px solid #d9e2ec; padding-bottom: 8px; }
    h3 { color: #0f172a; font-size: 16px; margin-top: 18px; }
    table { border-collapse: collapse; width: 100%; margin: 12px 0 18px; }
    th, td { border: 1px solid #cbd5e1; padding: 8px 10px; vertical-align: top; }
    th { background: #eef3f7; color: #002c4b; }
    blockquote { border-left: 4px solid #ffbc03; margin: 12px 0; padding: 8px 12px; background: #fff8e1; }
    pre { background: #f8fafc; border: 1px solid #e2e8f0; padding: 12px; white-space: pre-wrap; }
    .section-actions, button { display: none !important; }`;

export const buildDocumentExportHtml = (input: {
  documentTitle: string;
  templateTitle: string;
  sanitizedBodyHtml: SanitizedDocumentBodyHtml;
  printOnLoad?: boolean;
}) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapePlainText(input.documentTitle)}</title>
  <style>${input.printOnLoad ? '@page { margin: 18mm; }' : ''}${baseStyles}</style>
</head>
<body>
  <h1>${escapePlainText(input.documentTitle)}</h1>
  <p><strong>Generated by AvalaOS Core</strong> using ${escapePlainText(input.templateTitle)}. Review and sign off before external distribution.</p>
  ${input.sanitizedBodyHtml}
  ${input.printOnLoad ? '<script>window.onload = () => { window.print(); };</script>' : ''}
</body>
</html>`;
