import assert from 'node:assert/strict';
import { announceProcessCreation, creationCompletionMatchesAuthority, processReadAuthorityKey, processScopeKey, subscribeProcessCreation, visibleProcessesForAuthority } from './processCreationServiceFence';

const actor='11111111-1111-4111-8111-111111111111', org='22222222-2222-4222-8222-222222222222', workspace='33333333-3333-4333-8333-333333333333';
const context={userId:actor,organizationId:org,organizationName:'Synthetic',workspaceId:workspace,workspaceName:'Controlled',authorizationVersion:7,capabilities:['assess.read','assess.process.create']};
const params={actorId:actor,organizationId:org,workspaceId:workspace,sessionState:'ready' as const,tenantContext:context,localAuthority:false};
const key=processReadAuthorityKey(params);
assert.ok(key);
const nextVersion=processReadAuthorityKey({...params,tenantContext:{...context,authorizationVersion:8}});
assert.notEqual(key,nextVersion);
assert.equal(creationCompletionMatchesAuthority(key,nextVersion),false);
assert.equal(creationCompletionMatchesAuthority(key,key),true);
const otherScope=processReadAuthorityKey({...params,workspaceId:org,tenantContext:{...context,workspaceId:org}});
assert.notEqual(key,otherScope);
assert.equal(creationCompletionMatchesAuthority(key,otherScope),false);
assert.notEqual(processReadAuthorityKey({...params,sessionState:'read_only'}),key);
assert.equal(processReadAuthorityKey({...params,tenantContext:{...context,capabilities:['assess.process.create']}}),null);
assert.equal(processReadAuthorityKey({...params,tenantContext:{...context,authorizationVersion:0}}),null);
assert.equal(processReadAuthorityKey({...params,tenantContext:{...context,authorizationVersion:-1}}),null);
assert.equal(processReadAuthorityKey({...params,tenantContext:{...context,workspaceId:org}}),null);
const list=[{id:'synthetic'}] as any;
assert.equal(visibleProcessesForAuthority(list,key,key).length,1);
assert.equal(visibleProcessesForAuthority(list,key,nextVersion).length,0);
assert.equal(visibleProcessesForAuthority(list,key,otherScope).length,0);
const scope=processScopeKey(actor,org,workspace);assert.ok(scope);
let current=0,foreign=0;
const unsubscribeCurrent=subscribeProcessCreation(event=>{if(event===scope)current++;});
const unsubscribeForeign=subscribeProcessCreation(event=>{if(event===processScopeKey(actor,org,org))foreign++;});
announceProcessCreation(scope);assert.equal(current,1);assert.equal(foreign,0);
unsubscribeCurrent();unsubscribeForeign();
announceProcessCreation(scope);assert.equal(current,1);
console.log('process creation service fence: epoch, scope, visible-cache and scope-only invalidation cases passed');
