import React, { useCallback, useEffect, useRef, useState } from 'react';
import type { EnterpriseSessionState, TenantContextProjection } from '../../types';
import { PilotOperationsClient } from '../../services/pilotOperations/client';
import type { PilotOperationsProjection } from '../../services/pilotOperations/operationsModel';
import type { PilotOperation, PilotOperationsCommand } from '../../supabase/functions/_shared/pilotOperationsContracts';
import PilotOperationsPanel, { type PilotOperationRequest } from './PilotOperationsPanel';

const resultKind=(code:string):'error'|'stale'|'revoked'|'blocked'=>code==='VERSION_CONFLICT'||code==='AUTHORIZATION_STALE'||code==='EVIDENCE_STALE'?'stale':code==='ACCESS_DENIED'||code==='TENANT_DEPROVISIONED'?'revoked':code==='FEATURE_DISABLED'||code==='ENVIRONMENT_BLOCKED'||code==='MAINTENANCE_ACTIVE'||code==='READ_ONLY_ACTIVE'||code==='MAINTENANCE_MODE'||code==='READ_ONLY_MODE'||code==='EVIDENCE_NOT_VERIFIED'||code==='PROVIDER_REFERENCE_STALE'||code==='PROVIDER_REFERENCE_INVALID'||code==='PREFLIGHT_BLOCKED'||code==='ROLLBACK_NOT_ELIGIBLE'||code==='SEPARATION_OF_DUTY_REQUIRED'||code==='LIVE_ACTIVATION_NOT_AUTHORIZED'?'blocked':'error';
const capabilityFor:Record<PilotOperationRequest['action'],string>={validate:'release.validate',approve:'release.approve',simulate_promotion:'release.promote',maintenance:'operations.manage',read_only:'operations.manage',rollback:'release.promote'};
export const canRequestPilotOperation=(action:PilotOperationRequest['action'],projection:PilotOperationsProjection,capabilities:readonly string[],selectionState:EnterpriseSessionState='ready')=>{
  if(selectionState!=='ready'||!capabilities.includes('operations.read')||!capabilities.includes(capabilityFor[action])||!projection.authority?.environmentId)return false;
  if(['validate','approve','simulate_promotion'].includes(action))return Boolean(projection.release&&projection.authority.releaseId&&projection.authority.releaseVersion&&(action!=='simulate_promotion'||projection.promotion.blockers.length===0));
  if(action==='rollback')return Boolean(projection.promotion.rollbackEligible&&projection.authority.rollbackCurrentCandidateId&&projection.authority.rollbackCurrentVersion&&projection.authority.rollbackTargetCandidateId&&projection.authority.rollbackTargetVersion);
  return true;
};
export const commandFor=(request:PilotOperationRequest,projection:PilotOperationsProjection,capabilities:readonly string[]):{operation:PilotOperation;payload:Record<string,unknown>}=>{
  const ids=projection.authority;
  if(!capabilities.includes('operations.read')||!capabilities.includes(capabilityFor[request.action]))throw new Error('ACCESS_DENIED');
  if(!canRequestPilotOperation(request.action,projection,capabilities))throw new Error(request.action==='rollback'?'ROLLBACK_NOT_ELIGIBLE':'PREFLIGHT_BLOCKED');
  if(!ids)throw new Error('OPERATIONS_PROJECTION_UNAVAILABLE');
  if(request.action==='validate')return{operation:'validate_release_candidate',payload:{candidateId:ids.releaseId,environmentId:ids.environmentId}};
  if(request.action==='approve')return{operation:'approve_promotion',payload:{candidateId:ids.releaseId,environmentId:ids.environmentId}};
  if(request.action==='rollback'){if(!ids.rollbackCurrentCandidateId||!ids.rollbackCurrentVersion||!ids.rollbackTargetCandidateId||!ids.rollbackTargetVersion)throw new Error('ROLLBACK_NOT_ELIGIBLE');return{operation:'rollback_non_live_promotion',payload:{candidateId:ids.rollbackCurrentCandidateId,environmentId:ids.environmentId,rollbackTargetCandidateId:ids.rollbackTargetCandidateId,rollbackTargetVersion:ids.rollbackTargetVersion}};}
  if(request.action==='simulate_promotion')return{operation:'simulate_promotion',payload:{candidateId:ids.releaseId,environmentId:ids.environmentId,target:'non_live'}};
  if(request.action==='maintenance')return{operation:'set_runtime_control',payload:{environmentId:ids.environmentId,maintenance:!projection.controls.maintenance,readOnly:projection.controls.readOnly,disabledFeatures:projection.controls.disabledFeatures}};
  if(request.action==='read_only')return{operation:'set_runtime_control',payload:{environmentId:ids.environmentId,maintenance:projection.controls.maintenance,readOnly:!projection.controls.readOnly,disabledFeatures:projection.controls.disabledFeatures}};
  throw new Error('PREFLIGHT_BLOCKED');
};

type PilotOperationsConnectedPanelProps={tenantContext:TenantContextProjection|null;selectionState?:EnterpriseSessionState;client?:PilotOperationsClient};
export const PilotOperationsConnectedPanel:React.FC<PilotOperationsConnectedPanelProps>=({tenantContext,selectionState='ready',client:providedClient}:PilotOperationsConnectedPanelProps)=>{
  const clientRef=useRef<PilotOperationsClient|null>(null);if(!clientRef.current)clientRef.current=providedClient??new PilotOperationsClient();const client=providedClient??clientRef.current;
  const [projection,setProjection]=useState<PilotOperationsProjection|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[pending,setPending]=useState<PilotOperationRequest['action']|null>(null),[actionResult,setActionResult]=useState<{kind:'success'|'error'|'stale'|'revoked'|'blocked';message:string}|null>(null);const generation=useRef(0),scopeRef=useRef('none');
  const load=useCallback(async(selected:TenantContextProjection,token:number)=>{setLoading(true);setError(null);try{const next=await client.projection({organizationId:selected.organizationId,workspaceId:selected.workspaceId,expectedAuthorizationVersion:selected.authorizationVersion});if(generation.current===token)setProjection(next)}catch(cause){if(generation.current===token){setProjection(null);setError(cause instanceof Error?cause.message:'PERSISTENCE_UNAVAILABLE')}}finally{if(generation.current===token)setLoading(false)}},[client]);
  const key=tenantContext?`${tenantContext.organizationId}:${tenantContext.workspaceId}:${tenantContext.authorizationVersion}`:'none';
  scopeRef.current=key;
  useEffect(()=>{const token=++generation.current;setPending(null);setActionResult(null);if(!['ready','read_only'].includes(selectionState)||!tenantContext||!tenantContext.capabilities.includes('operations.read')){setLoading(false);setProjection(null);setError(selectionState==='stale'?'AUTHORIZATION_STALE':selectionState==='blocked'?'ENVIRONMENT_BLOCKED':'ACCESS_DENIED');return}void load(tenantContext,token);return()=>{if(generation.current===token)generation.current++}},[key,selectionState,load,tenantContext]);
  const request=async(input:PilotOperationRequest)=>{if(selectionState!=='ready'||!tenantContext||!projection||pending)return;const selected=tenantContext;const token=generation.current;const selectedKey=key;setActionResult(null);if(!canRequestPilotOperation(input.action,projection,selected.capabilities,selectionState)){setActionResult({kind:'blocked',message:selected.capabilities.includes('operations.read')&&selected.capabilities.includes(capabilityFor[input.action])?'PREFLIGHT_BLOCKED':'ACCESS_DENIED'});return}setPending(input.action);try{const mapped=commandFor(input,projection,selected.capabilities);const command:PilotOperationsCommand={...mapped,organizationId:selected.organizationId,workspaceId:selected.workspaceId,requestId:crypto.randomUUID(),idempotencyKey:`pilot-ui-${mapped.operation}-${crypto.randomUUID()}`,expectedAuthorizationVersion:selected.authorizationVersion,expectedVersion:input.expectedVersion};await client.command(command);if(generation.current!==token||scopeRef.current!==selectedKey)return;await load(selected,token);if(generation.current===token&&scopeRef.current===selectedKey)setActionResult({kind:'success',message:'Authoritative command committed and server projection reloaded.'})}catch(cause){if(generation.current!==token||scopeRef.current!==selectedKey)return;const code=cause instanceof Error?cause.message:'PERSISTENCE_UNAVAILABLE';setActionResult({kind:resultKind(code),message:code})}finally{if(generation.current===token&&scopeRef.current===selectedKey)setPending(null)}};
  const actionAvailability=projection&&tenantContext?Object.fromEntries((['validate','approve','simulate_promotion','maintenance','read_only','rollback'] as const).map(action=>[action,canRequestPilotOperation(action,projection,tenantContext.capabilities,selectionState)])):undefined;
  return <PilotOperationsPanel projection={projection} loading={loading} error={error} pendingAction={pending} actionResult={actionResult} actionAvailability={actionAvailability} onRequest={selectionState==='ready'?input=>void request(input):undefined}/>;
};
