import fs from 'node:fs'; import path from 'node:path';
const root=process.cwd(), out=path.resolve(process.env.ACCEPTANCE_RESULTS_DIR||'acceptance-results'); fs.mkdirSync(out,{recursive:true});
const load=(name,fallback=[])=>{const p=path.resolve(name);if(!fs.existsSync(p))return fallback;const v=JSON.parse(fs.readFileSync(p,'utf8'));return Array.isArray(v)?v:v.cases??v.tests??v.branches??v.items??fallback};
const catalog=load(process.env.ACCEPTANCE_CATALOG||'tests/acceptance/catalog/test-catalog.json'); const inventory=load(process.env.ACCEPTANCE_INVENTORY||'tests/acceptance/inventory.json');
const pwPath=path.resolve(process.env.PLAYWRIGHT_JSON||'acceptance-results/playwright-results.json'); const pw=fs.existsSync(pwPath)?JSON.parse(fs.readFileSync(pwPath,'utf8')):null;
const flat=[]; const walk=s=>{for(const spec of s?.specs||[])for(const t of spec.tests||[])flat.push({title:spec.title,project:t.projectName,results:t.results||[],expected:t.expectedStatus});for(const child of s?.suites||[])walk(child)}; for(const suite of pw?.suites||[])walk(suite);
const normalize=r=>r==='passed'?'PASS':r==='failed'||r==='timedOut'||r==='interrupted'?'FAIL':r==='skipped'?'BLOCKED':'BLOCKED';
const releaseSha=process.env.RELEASE_SHA||process.env.GITHUB_SHA||'not-bound'; const deployId=process.env.NETLIFY_DEPLOY_ID||'not-available'; const runId=process.env.GITHUB_RUN_ID||'local'; const attempt=process.env.GITHUB_RUN_ATTEMPT||'local'; const timestamp=new Date().toISOString();
const results=catalog.map(tc=>{const binding=tc.automation?.testTitle??tc.playwrightTitle??tc.title;const found=flat.find(t=>t.title===binding||t.title.includes(`[${tc.testId}]`)||t.title.includes(tc.testId));let status,reason,artifacts=[];if(found){const last=found.results.at(-1);status=normalize(last?.status);reason=last?.error?.message??(status==='BLOCKED'?'Playwright did not execute the case':null);artifacts=(last?.attachments||[]).map(a=>a.path).filter(Boolean).map(p=>path.relative(root,p));}else if((tc.automation?.kind??tc.automationKind)==='retained'){status='BLOCKED';reason='Retained test result was not supplied to this execution aggregator.';}else{status='BLOCKED';reason='No matching deterministic execution result was supplied.';}return {...tc,releaseSha,netlifyDeployId:deployId,workflowRunId:runId,workflowAttempt:attempt,executionTimestamp:timestamp,actualResult:found?.results.at(-1)?.status??null,status,failureReason:reason,evidenceReferences:artifacts};});
const covered=new Set();for(const b of inventory){const refs=[...(Array.isArray(b.testIds)?b.testIds:b.testId?[b.testId]:[])];if(refs.some(id=>results.some(r=>r.testId===id)))covered.add(b.branchId??b.ruleId??b.id)}
const uncovered=inventory.filter(b=>!covered.has(b.branchId??b.ruleId??b.id)||(b.coverageDisposition??b.coverageStatus??b.status)==='UNCOVERED').map(b=>({...b,status:'UNCOVERED'}));
const counts={PASS:0,FAIL:0,BLOCKED:0,UNCOVERED:uncovered.length};for(const r of results)counts[r.status]++;const executed=counts.PASS+counts.FAIL;const pct=(n,d)=>d?Number((100*n/d).toFixed(2)):0;const overall=counts.FAIL?'FAILED':counts.BLOCKED||counts.UNCOVERED?'INCOMPLETE_COVERAGE':'PASSED';
const group=(items,key)=>Object.values(items.reduce((a,x)=>{const k=x[key]||'Unassigned';a[k]??={name:k,total:0,pass:0,fail:0,blocked:0};a[k].total++;a[k][x.status.toLowerCase()]++;return a},{}));const summary={overall,releaseSha,netlifyDeployId:deployId,target:process.env.HOSTED_PILOT_URL||'https://avalaos-pilot.netlify.app',workflowRunId:runId,workflowAttempt:attempt,executionTimestamp:timestamp,totalTests:results.length,...counts,passPercentage:pct(counts.PASS,executed),coveragePercentage:pct(inventory.length-uncovered.length,inventory.length),inventoryBranches:inventory.length,moduleSummary:group(results,'module'),personaSummary:group(results,'persona')};
fs.writeFileSync(path.join(out,'acceptance-results.json'),JSON.stringify({summary,results,uncovered},null,2)+'\n');fs.writeFileSync(path.join(out,'source-to-test-coverage.json'),JSON.stringify({releaseSha,totalBranches:inventory.length,coveredBranches:inventory.length-uncovered.length,uncoveredBranches:uncovered},null,2)+'\n');
const esc=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));let xml=`<?xml version="1.0" encoding="UTF-8"?>\n<testsuites name="Exhaustive AvalaOS Acceptance" tests="${results.length+uncovered.length}" failures="${counts.FAIL+counts.UNCOVERED}" skipped="${counts.BLOCKED}"><testsuite name="acceptance">`;for(const r of results){xml+=`<testcase classname="${esc(r.module)}" name="${esc(r.testId+' '+r.title)}">`;if(r.status==='FAIL')xml+=`<failure message="${esc(r.failureReason)}"/>`;if(r.status==='BLOCKED')xml+=`<skipped message="${esc(r.failureReason)}"/>`;xml+='</testcase>'}for(const b of uncovered)xml+=`<testcase classname="coverage" name="${esc(b.branchId??b.ruleId??b.id)}"><failure message="UNCOVERED: ${esc(b.uncoveredReason??b.reason??'No Test ID mapping')}"/></testcase>`;xml+='</testsuite></testsuites>\n';fs.writeFileSync(path.join(out,'acceptance-junit.xml'),xml);
let md=`# Exhaustive AvalaOS Hosted Product Acceptance\n\n## Executive Summary\n\n- Overall: **${overall}**\n- Release SHA: \`${releaseSha}\`\n- Netlify deploy: \`${deployId}\`\n- Target: ${summary.target}\n- Workflow: \`${runId}\` attempt \`${attempt}\`\n- Tests: ${results.length}; PASS ${counts.PASS}; FAIL ${counts.FAIL}; BLOCKED ${counts.BLOCKED}; UNCOVERED ${counts.UNCOVERED}\n- Pass percentage: ${summary.passPercentage}%\n- Source/business branch coverage: ${summary.coveragePercentage}% (${inventory.length-uncovered.length}/${inventory.length})\n\nA 100% executed pass rate is not a full pass while blocked or uncovered cases remain.\n\n## Module Summary\n\n| Module | Total | Pass | Fail | Blocked |\n|---|---:|---:|---:|---:|\n${summary.moduleSummary.map(x=>`| ${x.name} | ${x.total} | ${x.pass} | ${x.fail} | ${x.blocked} |`).join('\n')}\n\n## Persona Summary\n\n| Persona | Total | Pass | Fail | Blocked |\n|---|---:|---:|---:|---:|\n${summary.personaSummary.map(x=>`| ${x.name} | ${x.total} | ${x.pass} | ${x.fail} | ${x.blocked} |`).join('\n')}\n\n## Failures\n\n${results.filter(x=>x.status==='FAIL').map(x=>`- **${x.testId} — ${x.title}** (${x.module}; ${x.persona}): ${x.failureReason}`).join('\n')||'None executed.'}\n\n## Blocked\n\n${results.filter(x=>x.status==='BLOCKED').map(x=>`- **${x.testId}**: ${x.failureReason}`).join('\n')||'None.'}\n\n## Uncovered Branches\n\n${uncovered.map(x=>`- **${x.branchId??x.ruleId??x.id}** — ${x.rule??x.title??'Declared branch'} (${x.sourceReference??'source not recorded'}): ${x.uncoveredReason??x.reason??'No executable mapping'}`).join('\n')||'None.'}\n`;fs.writeFileSync(path.join(out,'acceptance-report.md'),md);
console.log(JSON.stringify(summary));if(overall!=='PASSED')process.exitCode=1;
