import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { parseWorkflowYaml } from './checkWorkflowYaml.mjs';
const PRIMARY='.github/workflows/transcript-flow-pr-c.yml',RECOVERY='.github/workflows/pr264-controlled-human-recover.yml',CA='node scripts/prCControlledHumanPostgresTls.mjs verify-ca';
const bindings={
 controlled_human_credentials_preflight:[['Verify protected credential transport with bounded read-only checks','Verify pinned Supabase CA without consuming credentials']],
 controlled_human_edge:[['Apply and verify exact additive migration on the dedicated database','Verify pinned Supabase CA for controlled migration']],
 controlled_human_prepare:[['Preflight dedicated synthetic target','Verify pinned Supabase CA for target preflight'],['Apply bounded synthetic seed','Verify pinned Supabase CA for seed apply'],['Verify exact seed and zero-egress boundary','Verify pinned Supabase CA for seed verification'],['Protected exact-bound abort recovery after failed seed or evidence assembly','Verify pinned Supabase CA for abort recovery']],
 controlled_human_quiesce:[['Reverify exact preview and active synthetic state','Verify pinned Supabase CA for active-state verification'],['Enter exact server-enforced read-only state before any read-only human observation','Verify pinned Supabase CA for read-only transition']],
 controlled_human_requester:[['Derive backend observer records from the exact synthetic read-only scope','Verify pinned Supabase CA for backend observer']],
 controlled_human_approver:[['Derive backend observer records from the exact synthetic read-only scope','Verify pinned Supabase CA for backend observer']],
 controlled_human_reviewer:[['Derive backend observer records from the exact synthetic read-only scope','Verify pinned Supabase CA for backend observer']],
 controlled_human_final:[['Deprovision exact synthetic exercise directly from frozen read-only state','Verify pinned Supabase CA for deprovision'],['Independently re-inspect post-deprovision state','Verify pinned Supabase CA for post-deprovision inspection']],
 controlled_human_recovery:[['Complete exact server-authorized abort or expiry recovery','Verify pinned Supabase CA for abort or expiry recovery']],
};
const recoveryBindings={recover:[['Complete exact server-authorized abort or expiry recovery','Verify pinned Supabase CA for abort or expiry recovery']]};
const parse=async p=>{const source=(await readFile(p,'utf8')).replaceAll('\r\n','\n');return{source,workflow:parseWorkflowYaml(source,p)}};
const ABORT_GUARD="${{ failure() && steps.apply.outcome != 'skipped' }}",ABORT_STEP="${{ failure() && steps.apply.outcome != 'skipped' && steps.verify_abort_recovery_ca.outcome == 'success' }}";
const validate=(workflow,source,contracts=bindings)=>{assert.doesNotMatch(source,/NODE_EXTRA_CA_CERTS|PGSSLROOTCERT|BEGIN CERTIFICATE|sslmode=(?:disable|allow|prefer|require)|rejectUnauthorized\s*[:=]\s*false/iu);for(const [jobName,pairs] of Object.entries(contracts)){const steps=workflow.jobs[jobName].steps;assert.equal(steps.filter(s=>s.run===CA).length,pairs.length);for(const [db,guard] of pairs){const i=steps.findIndex(s=>s.name===db);assert.ok(i>0,`${jobName}:${db}`);const guardStep=steps[i-1],databaseStep=steps[i];assert.equal(guardStep.name,guard);assert.equal(guardStep.run,CA);assert.equal(guardStep.env,undefined);if(db==='Protected exact-bound abort recovery after failed seed or evidence assembly'){assert.equal(guardStep.id,'verify_abort_recovery_ca');assert.equal(guardStep.if,ABORT_GUARD);assert.equal(guardStep['continue-on-error'],undefined);assert.equal(databaseStep.if,ABORT_STEP);assert.equal(databaseStep['continue-on-error'],true);}else{assert.equal(guardStep.id,undefined);assert.equal(guardStep.if,undefined);assert.equal(guardStep['continue-on-error'],undefined);assert.equal(databaseStep.if,undefined);assert.equal(databaseStep['continue-on-error'],undefined);}}}};
test('direct protected jobs retain exact adjacent pinned-CA guards',async()=>{const {workflow,source}=await parse(PRIMARY);validate(workflow,source);for(const [jobName,pairs] of Object.entries(bindings)){for(const [db] of pairs){const x=structuredClone(workflow),steps=x.jobs[jobName].steps,i=steps.findIndex(s=>s.name===db);steps[i-1].run='node scripts/prCControlledHumanPostgresTls.mjs describe-ca';assert.throws(()=>validate(x,source),assert.AssertionError);}}});
test('each ordinary CA and database step rejects skip or continue semantics',async()=>{const {workflow,source}=await parse(PRIMARY);for(const [jobName,pairs] of Object.entries(bindings))for(const [db] of pairs){if(db==='Protected exact-bound abort recovery after failed seed or evidence assembly')continue;for(const mutate of [step=>{step.if='${{ false }}'},step=>{step['continue-on-error']=true}])for(const offset of [-1,0]){const x=structuredClone(workflow),steps=x.jobs[jobName].steps,i=steps.findIndex(s=>s.name===db);mutate(steps[i+offset]);assert.throws(()=>validate(x,source),assert.AssertionError,`${jobName}:${db}:${offset}`);}}});
test('preparation abort CA and recovery retain exact distinct failure gates',async()=>{const {workflow,source}=await parse(PRIMARY),job='controlled_human_prepare',db='Protected exact-bound abort recovery after failed seed or evidence assembly';for(const mutate of [(g,d)=>{g.if='${{ failure() }}'},(g,d)=>{g['continue-on-error']=true},(g,d)=>{g.id='substituted'},(g,d)=>{d.if=ABORT_GUARD},(g,d)=>{d['continue-on-error']=false}]){const x=structuredClone(workflow),steps=x.jobs[job].steps,i=steps.findIndex(s=>s.name===db);mutate(steps[i-1],steps[i]);assert.throws(()=>validate(x,source),assert.AssertionError);}});
test('manual recovery executes only trusted current PR code with an unconditional adjacent CA guard',async()=>{const {source,workflow}=await parse(RECOVERY);validate(workflow,source,recoveryBindings);assert.equal(workflow.jobs.recover.environment,'hosted-nonproduction-pilot');assert.match(source,/pull\.head\.sha !== process\.env\.TRUSTED_EXECUTION_SHA/u);assert.match(source,/ref: \$\{\{ inputs\.trusted_execution_sha \}\}/u);assert.doesNotMatch(source,/ref: \$\{\{ inputs\.exact_head_sha \}\}/u);for(const offset of [-1,0])for(const mutate of [step=>{step.if='${{ false }}'},step=>{step['continue-on-error']=true}]){const x=structuredClone(workflow),steps=x.jobs.recover.steps,i=steps.findIndex(s=>s.name==='Complete exact server-authorized abort or expiry recovery');mutate(steps[i+offset]);assert.throws(()=>validate(x,source,recoveryBindings),assert.AssertionError);}});
