import assert from 'node:assert/strict';

const uuid=(n)=>`97000000-0000-4000-8000-${String(n).padStart(12,'0')}`;

export async function createCommittedStudioFixture(db){
 const x={requester:uuid(1),reviewer:uuid(2),approver:uuid(3),org:uuid(10),workspace:uuid(11),role:uuid(12),process:uuid(13),caseId:uuid(14),sourceVersion:uuid(15),decision:uuid(16),evidence:uuid(17),review:uuid(18),attestation:uuid(19),resolution:uuid(20),govern:uuid(21),handoff:uuid(22)};
 await db.query('INSERT INTO auth.users(id) VALUES($1),($2),($3)',[x.requester,x.reviewer,x.approver]);
 await db.query("INSERT INTO profiles(id,email) VALUES($1,'requester@fixture.invalid'),($2,'reviewer@fixture.invalid'),($3,'approver@fixture.invalid')",[x.requester,x.reviewer,x.approver]);
 await db.query("INSERT INTO organizations(id,name,slug) VALUES($1,'Studio fixture','studio-fixture')",[x.org]);
 await db.query("INSERT INTO workspaces(id,org_id,name,slug) VALUES($1,$2,'Studio fixture','studio-fixture')",[x.workspace,x.org]);
 await db.query("INSERT INTO roles(id,org_id,name,slug,scope,permissions) VALUES($1,$2,'Studio authority','studio-authority','organization','[]')",[x.role,x.org]);
 await db.query("INSERT INTO role_capabilities(role_id,capability_key) SELECT $1,capability_key FROM capabilities WHERE capability_key LIKE 'studio.artifacts.%'",[x.role]);
 for(const actor of [x.requester,x.reviewer,x.approver]){await db.query("INSERT INTO organization_members(org_id,user_id,role_id,status) VALUES($1,$2,$3,'active')",[x.org,actor,x.role]);await db.query("INSERT INTO workspace_memberships(org_id,workspace_id,user_id,status) VALUES($1,$2,$3,'active')",[x.org,x.workspace,actor]);await db.query('INSERT INTO authorization_versions(org_id,user_id,version) VALUES($1,$2,1) ON CONFLICT(org_id,user_id) DO UPDATE SET version=1',[x.org,actor])}
 await db.query("INSERT INTO assess_processes(id,org_id,workspace_id,name,status) VALUES($1,$2,$3,'Studio fixture process','Draft')",[x.process,x.org,x.workspace]);
 await db.query("INSERT INTO assess_v2_cases(id,org_id,workspace_id,process_id,owner_id,status,version) VALUES($1,$2,$3,$4,$5,'in_review',2)",[x.caseId,x.org,x.workspace,x.process,x.requester]);
 await db.query("INSERT INTO assess_v2_case_versions(id,case_id,org_id,workspace_id,version,name,source_kind,created_by) VALUES($1,$2,$3,$4,1,'Studio source','create',$5)",[x.sourceVersion,x.caseId,x.org,x.workspace,x.requester]);await db.query('UPDATE assess_v2_cases SET head_version_id=$1 WHERE id=$2',[x.sourceVersion,x.caseId]);
 const receipts=Array.from({length:6},(_,i)=>uuid(30+i));for(let i=0;i<receipts.length;i++)await db.query("INSERT INTO assess_command_receipts(id,org_id,workspace_id,actor_id,command_type,idempotency_key,request_id,request_hash,status,response,completed_at) VALUES($1,$2,$3,$4,'fixture',$5,$6,'fixture-hash','succeeded','{}',now())",[receipts[i],x.org,x.workspace,x.requester,`studio-fixture-${i}`,uuid(40+i)]);
 const hash='0'.repeat(64),output={trace:[{fieldIds:['claim.material'],evidenceIds:[x.evidence]}],controls:['Audit'],actionControls:[]};
 await db.query("INSERT INTO assess_v2_decision_versions(id,case_id,source_version_id,org_id,workspace_id,schema_version,rule_set_version,decision_version,validation_status,input_snapshot,evidence_snapshot,output_snapshot,input_hash,evidence_hash,output_hash,receipt_id,created_by,created_at) VALUES($1,$2,$3,$4,$5,'schema','rules','decision-1','reviewer-ready','{}','[]',$6,$7,$7,$7,$8,$9,now())",[x.decision,x.caseId,x.sourceVersion,x.org,x.workspace,output,hash,receipts[0],x.requester]);
 await db.query('INSERT INTO assess_v2_evidence_links(id,version_id,case_id,org_id,workspace_id,payload) VALUES($1,$2,$3,$4,$5,$6)',[x.evidence,x.sourceVersion,x.caseId,x.org,x.workspace,{claimIds:['claim.material'],status:'submitted',validated:false,owner:x.requester}]);
 await db.query("INSERT INTO assess_v2_review_assignments(id,org_id,workspace_id,case_id,source_version_id,source_case_version,decision_id,decision_version,review_schema_version,review_sequence,material_claims,reviewer_id,assigned_by,assigned_reviewer_authorization_version,assigned_by_authorization_version,request_id,receipt_id,audit_event_id) VALUES($1,$2,$3,$4,$5,1,$6,'decision-1','assess-v2-review-2026-07',1,$7,$8,$9,1,1,$10,$11,$12)",[x.review,x.org,x.workspace,x.caseId,x.sourceVersion,x.decision,[{claimId:'claim.material',evidenceIds:[x.evidence]}],x.reviewer,x.requester,uuid(50),receipts[1],uuid(51)]);
 await db.query("INSERT INTO assess_v2_evidence_attestations(id,org_id,workspace_id,case_id,source_version_id,source_case_version,decision_id,decision_version,review_id,review_schema_version,review_sequence,evidence_id,claim_ids,evidence_submitter_id,reviewer_id,reviewer_authorization_version,outcome,rationale,request_id,receipt_id,audit_event_id) VALUES($1,$2,$3,$4,$5,1,$6,'decision-1',$7,'assess-v2-review-2026-07',1,$8,ARRAY['claim.material'],$9,$10,1,'accepted','checked',$11,$12,$13)",[x.attestation,x.org,x.workspace,x.caseId,x.sourceVersion,x.decision,x.review,x.evidence,x.requester,x.reviewer,uuid(52),receipts[2],uuid(53)]);
 await db.query("INSERT INTO assess_v2_review_resolutions(id,org_id,workspace_id,case_id,source_version_id,source_case_version,decision_id,decision_version,review_id,review_schema_version,review_sequence,resolution,reviewed_confidence,rationale,reviewer_id,reviewer_authorization_version,request_id,receipt_id,audit_event_id) VALUES($1,$2,$3,$4,$5,1,$6,'decision-1',$7,'assess-v2-review-2026-07',1,'approved','Verified','complete',$8,1,$9,$10,$11)",[x.resolution,x.org,x.workspace,x.caseId,x.sourceVersion,x.decision,x.review,x.reviewer,uuid(54),receipts[3],uuid(55)]);
 await db.query("INSERT INTO assess_v2_govern_resolutions(id,org_id,workspace_id,case_id,source_version_id,source_case_version,decision_id,decision_version,review_resolution_id,review_schema_version,review_sequence,actions,required_controls,review_frequency,accountable_owner,rationale,resolver_id,resolver_authorization_version,request_id,receipt_id,audit_event_id) VALUES($1,$2,$3,$4,$5,1,$6,'decision-1',$7,'assess-v2-review-2026-07',1,'[]',$8,'annual','owner','resolved',$9,1,$10,$11,$12)",[x.govern,x.org,x.workspace,x.caseId,x.sourceVersion,x.decision,x.resolution,[{controlId:'Audit',status:'resolved',condition:'',owner:'',dueDate:'',conditionSatisfied:false}],x.approver,uuid(56),receipts[4],uuid(57)]);
 const sourcePackage={process:{name:'Studio fixture'},source:'accepted-pr1e'},packageHash=(await db.query("SELECT encode(digest(convert_to($1::jsonb::text,'UTF8'),'sha256'),'hex') hash",[sourcePackage])).rows[0].hash;
 await db.query("INSERT INTO assess_v2_studio_handoffs(id,org_id,workspace_id,case_id,source_version_id,source_case_version,decision_id,review_resolution_id,govern_resolution_id,package,package_hash,schema_version,rule_set_version,decision_version,review_schema_version,review_sequence,handed_off_by,handoff_authorization_version,request_id,receipt_id,audit_event_id) VALUES($1,$2,$3,$4,$5,1,$6,$7,$8,$9,$10,'schema','rules','decision-1','assess-v2-review-2026-07',1,$11,1,$12,$13,$14)",[x.handoff,x.org,x.workspace,x.caseId,x.sourceVersion,x.decision,x.resolution,x.govern,sourcePackage,packageHash,x.requester,uuid(58),receipts[5],uuid(59)]);await db.query("INSERT INTO assess_v2_studio_sources(org_id,workspace_id,case_id,decision_id,handoff_id,source_context) VALUES($1,$2,$3,$4,$5,'{}')",[x.org,x.workspace,x.caseId,x.decision,x.handoff]);
 const command={commandType:'studio.artifact.generation.request',requestId:uuid(60),idempotencyKey:'real-projection-fixture',organizationId:x.org,workspaceId:x.workspace,actorId:x.requester,authorizationVersion:1,expectedAggregateVersion:0,expectedArtifactVersion:null,payload:{studioHandoffId:x.handoff,artifactType:'brd'}};
 const first=(await db.query('SELECT public.studio_artifact_command_claim($1::jsonb) result',[command])).rows[0].result;assert.equal(first.outcome,'committed');assert.ok(first.generationClaim);
 const artifactId=first.resourceId,attemptId=first.resource.attemptId,receiptId=first.receiptId;await db.query('SELECT public.studio_artifact_generation_start($1)',[attemptId]);const content={title:'Fixture BRD',sections:[{heading:'Summary',body:'Committed structured content'}]};await db.query('SELECT public.studio_artifact_generation_complete($1,$2::jsonb,$3)',[attemptId,content,'fixture-provider-operation']);
 const attempt=(await db.query('SELECT state FROM studio_artifact_generation_attempts WHERE id=$1',[attemptId])).rows[0],aggregate=(await db.query('SELECT aggregate_version,current_version_id,lifecycle FROM studio_artifact_aggregates WHERE id=$1',[artifactId])).rows[0],version=(await db.query('SELECT id,version,content,content_hash FROM studio_artifact_versions WHERE artifact_id=$1',[artifactId])).rows[0];assert.equal(attempt.state,'completed');assert.equal(aggregate.current_version_id,version.id);assert.equal(String(version.version),'1');
 const expectedHash=(await db.query("SELECT encode(digest(convert_to($1::jsonb::text,'UTF8'),'sha256'),'hex') hash",[content])).rows[0].hash;assert.equal(version.content_hash,expectedHash);assert.equal(Number((await db.query('SELECT count(*) n FROM studio_artifact_versions WHERE artifact_id=$1',[artifactId])).rows[0].n),1);assert.equal(Number((await db.query("SELECT count(*) n FROM privileged_audit_events WHERE resource_id IN ($1,$2) AND action IN ('studio.artifact.generation.request','studio.artifact.generation.start','studio.artifact.generation.complete')",[artifactId,attemptId])).rows[0].n),3);
 const replay=(await db.query('SELECT public.studio_artifact_command_claim($1::jsonb) result',[command])).rows[0].result;assert.equal(replay.outcome,'replayed');assert.equal(replay.receiptId,receiptId);assert.equal(replay.resourceId,artifactId);assert.equal(Object.hasOwn(replay,'generationClaim'),false);const attemptCount=Number((await db.query('SELECT count(*) n FROM studio_artifact_generation_attempts WHERE artifact_id=$1',[artifactId])).rows[0].n),versionCount=Number((await db.query('SELECT count(*) n FROM studio_artifact_versions WHERE artifact_id=$1',[artifactId])).rows[0].n);assert.equal(attemptCount,1);assert.equal(versionCount,1);
 return {...x,artifactId,attemptId,receiptId,aggregate,version,attemptCount,versionCount};
}
