import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApprovedStudioFixture, privateCommand } from './studioPrivateArtifactPostgresFixture.mjs';

const uuid = ordinal => '61000000-0000-4000-8000-' + String(ordinal).padStart(12, '0');

export async function runStudioPrivateArtifactReconciliationEvidence(db, peer, deletionDb, storageDb, { scenario, names }) {
  const directory = await mkdtemp(join(tmpdir(), 'studio-private-reconciliation-'));
  let consumeOrdinal = 0; let requestOrdinal = 0;
  const consume = async (mode, input) => {
    consumeOrdinal += 1;
    const inputPath = join(directory, consumeOrdinal + '-' + mode + '-input.json');
    const outputPath = join(directory, consumeOrdinal + '-' + mode + '-output.json');
    await writeFile(inputPath, JSON.stringify(input) + '\n', 'utf8');
    execFileSync(process.execPath, ['scripts/runEdgeTypeScriptTest.mjs', 'types.ts', 'supabase/functions/deno.d.ts', 'supabase/functions/_shared/studioPrivateArtifactCrossLayerConsumer.test.ts'], { stdio: 'inherit', env: { ...process.env, STUDIO_PRIVATE_CROSS_LAYER_MODE: mode, STUDIO_PRIVATE_CROSS_LAYER_INPUT: inputPath, STUDIO_PRIVATE_CROSS_LAYER_OUTPUT: outputPath } });
    return JSON.parse(await readFile(outputPath, 'utf8'));
  };
  let renditionFixture;
  const prepareRendition = async format => {
    const fixture = renditionFixture ??= await createApprovedStudioFixture(db); requestOrdinal += 10;
    const generation = await privateCommand(db, { commandType: 'studio.rendition.generate', actorId: fixture.requester, organizationId: fixture.org, workspaceId: fixture.workspace, requestId: uuid(requestOrdinal), idempotencyKey: 'reconcile-render-' + requestOrdinal, authorizationVersion: fixture.authorizationVersions[fixture.requester], payload: { artifactVersionId: fixture.artifactVersionId, format } });
    const rendered = await consume('rendition', { claim: generation.renditionClaim }); const work = rendered.persisted;
    await db.query('SELECT public.studio_rendition_attempt_start($1::uuid)', [work.attemptId]);
    await db.query('SELECT public.studio_rendition_attempt_rendered($1::uuid,$2::text,$3::text,$4::bigint,$5::text,$6::text,$7::text,$8::text,$9::text)', [work.attemptId, work.objectKey, work.sha256, work.byteLength, work.mimeType, work.filename, work.rendererVersion, work.templateVersion, work.contentSchemaVersion]);
    await db.query("SELECT public.studio_rendition_attempt_fail($1::uuid,'UPLOAD_OUTCOME_UNKNOWN')", [work.attemptId]);
    return { fixture, generation, rendered, work };
  };
  const claimRendition = async (client, attemptId) => (await client.query('SELECT public.studio_rendition_reconciliation_claim($1::uuid) claim', [attemptId])).rows[0].claim;
  const prepareDeletion = async () => {
    const fixture = await createApprovedStudioFixture(deletionDb); requestOrdinal += 10;
    await privateCommand(deletionDb, { commandType: 'studio.retention.policy.publish', actorId: fixture.requester, organizationId: fixture.org, workspaceId: fixture.workspace, requestId: uuid(requestOrdinal), idempotencyKey: 'reconcile-retention-' + requestOrdinal, authorizationVersion: fixture.authorizationVersions[fixture.requester], payload: { artifactType: 'brd', indefinite: false, retentionDays: 0, rationale: 'disposable reconciliation evidence' } });
    const generation = await privateCommand(deletionDb, { commandType: 'studio.rendition.generate', actorId: fixture.requester, organizationId: fixture.org, workspaceId: fixture.workspace, requestId: uuid(requestOrdinal + 1), idempotencyKey: 'reconcile-delete-render-' + requestOrdinal, authorizationVersion: fixture.authorizationVersions[fixture.requester], payload: { artifactVersionId: fixture.artifactVersionId, format: 'markdown' } });
    const claim = generation.renditionClaim; const key = fixture.org + '/' + fixture.workspace + '/studio-artifacts/' + claim.opaqueObjectId + '.md';
    await deletionDb.query('SELECT public.studio_rendition_attempt_start($1::uuid)', [claim.attemptId]);
    await deletionDb.query('SELECT public.studio_rendition_attempt_rendered($1::uuid,$2::text,$3::text,$4::bigint,$5::text,$6::text,$7::text,$8::text,$9::text)', [claim.attemptId, key, 'a'.repeat(64), 128, 'text/markdown; charset=utf-8', 'fixture.md', claim.rendererVersion, claim.templateVersion, claim.contentSchemaVersion]);
    const complete = (await deletionDb.query('SELECT public.studio_rendition_attempt_complete($1::uuid) result', [claim.attemptId])).rows[0].result;
    const deletionRequest = await privateCommand(deletionDb, { commandType: 'studio.rendition.deletion.request', actorId: fixture.requester, organizationId: fixture.org, workspaceId: fixture.workspace, requestId: uuid(requestOrdinal + 2), idempotencyKey: 'reconcile-delete-request-' + requestOrdinal, authorizationVersion: fixture.authorizationVersions[fixture.requester], payload: { renditionId: complete.renditionId, rationale: 'disposable deletion reconciliation' } });
    const approval = await privateCommand(deletionDb, { commandType: 'studio.rendition.deletion.resolve', actorId: fixture.approver, organizationId: fixture.org, workspaceId: fixture.workspace, requestId: uuid(requestOrdinal + 3), idempotencyKey: 'reconcile-delete-approve-' + requestOrdinal, authorizationVersion: fixture.authorizationVersions[fixture.approver], payload: { deletionRequestId: deletionRequest.resource.deletionRequestId, outcome: 'approve', rationale: 'independent disposable approval' } });
    await deletionDb.query("SELECT public.studio_rendition_deletion_fail($1::uuid,'DELETE_OUTCOME_UNKNOWN')", [approval.deletionClaim.deletionAttemptId]);
    return { fixture, renditionId: complete.renditionId, deletionRequest, approval, attemptId: approval.deletionClaim.deletionAttemptId };
  };
  const claimDeletion = async (client, attemptId) => (await client.query('SELECT public.studio_deletion_reconciliation_claim($1::uuid) claim', [attemptId])).rows[0].claim;
  try {
    const missing = await prepareRendition('markdown'); const missingClaim = await claimRendition(db, missing.work.attemptId); const missingEvidence = await consume('renditionReconciliation', { claim: missingClaim, objectStatus: 'missing' }); await db.query('SELECT public.studio_rendition_attempt_complete($1::uuid)', [missing.work.attemptId]);
    await scenario(names[0], async () => { assert.ok(missingClaim); assert.equal(missingClaim.attemptId, missing.work.attemptId); assert.deepEqual(missingEvidence.provider, { probes: 1, uploads: 1 }); assert.equal((await db.query('SELECT state FROM studio_rendition_attempts WHERE id=$1::uuid', [missing.work.attemptId])).rows[0].state, 'available'); });
    const existing = await prepareRendition('pdf'); const existingClaim = await claimRendition(db, existing.work.attemptId); const existingEvidence = await consume('renditionReconciliation', { claim: existingClaim, objectStatus: 'exists' }); await db.query('SELECT public.studio_rendition_attempt_complete($1::uuid)', [existing.work.attemptId]);
    await scenario(names[1], async () => assert.deepEqual({ outcome: existingEvidence.outcome, ...existingEvidence.provider }, { outcome: 'available', probes: 1, uploads: 0 }));
    const mismatch = await prepareRendition('docx'); const mismatchClaim = await claimRendition(db, mismatch.work.attemptId); const mismatchEvidence = await consume('renditionReconciliation', { claim: mismatchClaim, objectStatus: 'mismatch' }); await db.query("SELECT public.studio_rendition_attempt_fail($1::uuid,'STORAGE_OBJECT_MISMATCH')", [mismatch.work.attemptId]);
    await scenario(names[2], async () => { assert.equal(mismatchEvidence.failureCode, 'STORAGE_OBJECT_MISMATCH'); assert.deepEqual(mismatchEvidence.provider, { probes: 1, uploads: 0 }); assert.equal((await db.query('SELECT state FROM studio_rendition_attempts WHERE id=$1::uuid', [mismatch.work.attemptId])).rows[0].state, 'failed'); });
    const pending = await prepareRendition('docx'); const pendingClaim = await claimRendition(db, pending.work.attemptId); const pendingFailure = await consume('renditionReconciliation', { claim: pendingClaim, objectStatus: 'exists', failCompletion: true }); await db.query("SELECT public.studio_rendition_attempt_fail($1::uuid,'AVAILABLE_COMPLETION_FAILED')", [pending.work.attemptId]); const retryClaim = await claimRendition(db, pending.work.attemptId); const pendingRetry = await consume('renditionReconciliation', { claim: retryClaim, objectStatus: 'exists' }); await db.query('SELECT public.studio_rendition_attempt_complete($1::uuid)', [pending.work.attemptId]);
    await scenario(names[3], async () => { assert.equal(pendingFailure.failureCode, 'AVAILABLE_COMPLETION_FAILED'); assert.deepEqual(pendingFailure.provider, { probes: 1, uploads: 0 }); assert.deepEqual(pendingRetry.provider, { probes: 1, uploads: 0 }); });
    const exhausted = await prepareRendition('markdown'); await claimRendition(db, exhausted.work.attemptId); await db.query("SELECT public.studio_rendition_attempt_fail($1::uuid,'UPLOAD_OUTCOME_UNKNOWN')", [exhausted.work.attemptId]); await claimRendition(db, exhausted.work.attemptId); await db.query("SELECT public.studio_rendition_attempt_fail($1::uuid,'UPLOAD_OUTCOME_UNKNOWN')", [exhausted.work.attemptId]); assert.equal(await claimRendition(db, exhausted.work.attemptId), null);
    await scenario(names[4], async () => assert.deepEqual((await db.query('SELECT state,failure_code,reconciliation_count FROM studio_rendition_attempts WHERE id=$1::uuid', [exhausted.work.attemptId])).rows[0], { state: 'failed', failure_code: 'RECONCILIATION_EXHAUSTED', reconciliation_count: 3 }));
    const raced = await prepareRendition('markdown'); const raceClaims = await Promise.all([claimRendition(db, raced.work.attemptId), claimRendition(peer, raced.work.attemptId)]);
    await scenario(names[5], async () => assert.deepEqual(raceClaims.map(Boolean).sort(), [false, true]));
    let deletionPresenceProbes = 0; let deletionProviderDeletes = 0;
    await scenario(names[6], async () => { await deletionDb.query('BEGIN'); try { const item = await prepareDeletion(); const claim = await claimDeletion(deletionDb, item.attemptId); const evidence = await consume('deletionReconciliation', { claim, objectStatus: 'missing' }); await deletionDb.query('SELECT public.studio_rendition_deletion_complete($1::uuid)', [item.attemptId]); deletionPresenceProbes += evidence.provider.presence; deletionProviderDeletes += evidence.provider.deletes; assert.deepEqual({ ...evidence.provider, tombstones: evidence.tombstones }, { presence: 1, deletes: 0, exists: false, tombstones: 1 }); } finally { await deletionDb.query('ROLLBACK'); } });
    await scenario(names[7], async () => { await deletionDb.query('BEGIN'); try { const item = await prepareDeletion(); const claim = await claimDeletion(deletionDb, item.attemptId); const evidence = await consume('deletionReconciliation', { claim, objectStatus: 'exists' }); await deletionDb.query('SELECT public.studio_rendition_deletion_complete($1::uuid)', [item.attemptId]); deletionPresenceProbes += evidence.provider.presence; deletionProviderDeletes += evidence.provider.deletes; assert.deepEqual({ ...evidence.provider, tombstones: evidence.tombstones }, { presence: 1, deletes: 1, exists: false, tombstones: 1 }); } finally { await deletionDb.query('ROLLBACK'); } });
    await scenario(names[8], async () => { await deletionDb.query('BEGIN'); try { const item = await prepareDeletion(); const claim = await claimDeletion(deletionDb, item.attemptId); const evidence = await consume('deletionReconciliation', { claim, objectStatus: 'missing' }); await deletionDb.query('SELECT public.studio_rendition_deletion_complete($1::uuid)', [item.attemptId]); deletionPresenceProbes += evidence.provider.presence; deletionProviderDeletes += evidence.provider.deletes; assert.deepEqual(evidence.provider, { presence: 1, deletes: 0, exists: false }); } finally { await deletionDb.query('ROLLBACK'); } });
    await scenario(names[9], async () => { await deletionDb.query('BEGIN'); try { const item = await prepareDeletion(); const claim = await claimDeletion(deletionDb, item.attemptId); await consume('deletionReconciliation', { claim, objectStatus: 'missing' }); await deletionDb.query('SELECT public.studio_rendition_deletion_complete($1::uuid)', [item.attemptId]); assert.equal(await claimDeletion(deletionDb, item.attemptId), null); assert.equal((await deletionDb.query('SELECT state FROM studio_rendition_deletion_attempts WHERE id=$1::uuid', [item.attemptId])).rows[0].state, 'completed'); } finally { await deletionDb.query('ROLLBACK'); } });
    await scenario(names[10], async () => { await deletionDb.query('BEGIN'); try { const item = await prepareDeletion(); await privateCommand(deletionDb, { commandType: 'studio.legal_hold.place', actorId: item.fixture.requester, organizationId: item.fixture.org, workspaceId: item.fixture.workspace, requestId: uuid(requestOrdinal + 4), idempotencyKey: 'reconcile-hold-' + requestOrdinal, authorizationVersion: item.fixture.authorizationVersions[item.fixture.requester], payload: { renditionId: item.renditionId, rationale: 'hold before reconciliation' } }); await assert.rejects(claimDeletion(deletionDb, item.attemptId), /STUDIO_DELETION_BLOCKED/); } finally { await deletionDb.query('ROLLBACK'); } });
    await scenario(names[11], async () => { await deletionDb.query('BEGIN'); try { const item = await prepareDeletion(); await privateCommand(deletionDb, { commandType: 'studio.rendition.retention.extend', actorId: item.fixture.requester, organizationId: item.fixture.org, workspaceId: item.fixture.workspace, requestId: uuid(requestOrdinal + 5), idempotencyKey: 'reconcile-retain-' + requestOrdinal, authorizationVersion: item.fixture.authorizationVersions[item.fixture.requester], payload: { renditionId: item.renditionId, indefinite: false, extendUntil: new Date(Date.now() + 86400000).toISOString(), rationale: 'retention before reconciliation' } }); await assert.rejects(claimDeletion(deletionDb, item.attemptId), /STUDIO_DELETION_BLOCKED/); } finally { await deletionDb.query('ROLLBACK'); } });
    await scenario(names[12], async () => { await deletionDb.query('BEGIN'); try { const item = await prepareDeletion(); await claimDeletion(deletionDb, item.attemptId); await deletionDb.query("SELECT public.studio_rendition_deletion_fail($1::uuid,'DELETE_OUTCOME_UNKNOWN')", [item.attemptId]); await claimDeletion(deletionDb, item.attemptId); await deletionDb.query("SELECT public.studio_rendition_deletion_fail($1::uuid,'DELETE_OUTCOME_UNKNOWN')", [item.attemptId]); assert.equal(await claimDeletion(deletionDb, item.attemptId), null); assert.deepEqual((await deletionDb.query('SELECT state,failure_code,reconciliation_count FROM studio_rendition_deletion_attempts WHERE id=$1::uuid', [item.attemptId])).rows[0], { state: 'failed', failure_code: 'DELETION_RECONCILIATION_EXHAUSTED', reconciliation_count: 3 }); assert.equal((await deletionDb.query('SELECT lifecycle FROM studio_renditions WHERE id=$1::uuid', [item.renditionId])).rows[0].lifecycle, 'deletion_failed'); } finally { await deletionDb.query('ROLLBACK'); } });
    await scenario(names[13], async () => { const constraints = (await db.query("SELECT pg_get_constraintdef(oid) definition FROM pg_constraint WHERE conrelid IN ('studio_rendition_attempts'::regclass,'studio_renditions'::regclass) AND pg_get_constraintdef(oid) LIKE '%studio-private-artifacts%'")).rows.map(row => row.definition); assert.equal(constraints.length, 2); assert.equal(constraints.every(value => value.includes('studio-private-artifacts')), true); });
    await scenario(names[14], async () => { assert.deepEqual((await storageDb.query("SELECT id,name,public FROM storage.buckets WHERE id LIKE 'studio-private-%'")).rows, [{ id: 'studio-private-artifacts', name: 'studio-private-artifacts', public: false }]); });
    await scenario(names[15], async () => { const first = await consume('bucketAuthority', { bucket: 'studio-private-archive', allowlist: 'studio-private-archive' }); const second = await consume('bucketAuthority', { bucket: 'studio-private-artifacts', allowlist: 'studio-private-artifacts,studio-private-archive' }); assert.deepEqual(first, { rejected: true, providerRequests: 0 }); assert.deepEqual(second, { rejected: true, providerRequests: 0 }); });
    const counts = { renditionProviderUploads: missingEvidence.provider.uploads + existingEvidence.provider.uploads + mismatchEvidence.provider.uploads + pendingFailure.provider.uploads + pendingRetry.provider.uploads, deletionPresenceProbes, deletionProviderDeletes };
    console.log('RECONCILIATION CROSS-LAYER COUNTS ' + JSON.stringify(counts)); return counts;
  } finally { await rm(directory, { recursive: true, force: true }); }
}
