import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {join} from 'node:path';import pg from 'pg';
const adminUrl=process.env.DATABASE_URL;if(!adminUrl){if(process.env.CI)throw Error('DATABASE_URL required');console.log('DATABASE_URL not set; PostgreSQL scenarios not run locally.');process.exit(0)}
const{Client}=pg,suffix=`${process.pid}_${Date.now()}`,names=['fresh','upgrade','populated','dirty','authority'].map(x=>`trust_${x}_${suffix}`),created=[],roles=[];let admin;const clients=[];const migrations=(await readdir('supabase/migrations')).filter(n=>n.endsWith('.sql')).sort(),trust=migrations.find(n=>/^\d{14}_trust_assurance_evidence_hub\.sql$/.test(n));assert.ok(trust);const baseline=migrations.filter(n=>n!==trust);
const urlFor=name=>{const u=new URL(adminUrl);u.pathname=`/${name}`;return u.toString()},connect=async url=>{const c=new Client({connectionString:url});await c.connect();clients.push(c);return c},tx=async(c,sql)=>{await c.query('BEGIN');try{await c.query(sql);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}},apply=async(c,list)=>{for(const n of list)await tx(c,await readFile(join('supabase/migrations',n),'utf8'))};
const bootstrap=async c=>tx(c,`CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULLIF(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;`);
const createDb=async name=>{await admin.query(`CREATE DATABASE ${name}`);created.push(name);const c=await connect(urlFor(name));await bootstrap(c);return c};let passed=0,failed=0;const scenario=async(name,fn)=>{try{await fn();passed++;console.log(`PASS ${name}`)}catch(e){failed++;console.error(`FAIL ${name}: ${e instanceof Error?e.message:String(e)}`)}};
const uid=n=>`88000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
try{admin=await connect(adminUrl);for(const[r,a]of[['anon','NOLOGIN'],['authenticated','NOLOGIN'],['service_role','NOLOGIN BYPASSRLS']])if(!(await admin.query('select 1 from pg_roles where rolname=$1',[r])).rowCount){await admin.query(`CREATE ROLE ${r} ${a}`);roles.push(r)}
 const fresh=await createDb(names[0]);await apply(fresh,migrations);await scenario('fresh full ordered chain',async()=>assert.ok((await fresh.query("select to_regclass('public.trust_claims') r")).rows[0].r));
 const upgrade=await createDb(names[1]);await apply(upgrade,baseline);await apply(upgrade,[trust]);await scenario('accepted-main upgrade',async()=>assert.ok((await upgrade.query("select to_regclass('public.trust_snapshots') r")).rows[0].r));
 const populated=await createDb(names[2]);await apply(populated,baseline);const po=uid(90),pw=uid(91);await populated.query("insert into organizations(id,name,slug) values($1,'Legacy','trust-legacy')",[po]);await populated.query("insert into workspaces(id,org_id,name,slug) values($1,$2,'Legacy','trust-legacy')",[pw,po]);await apply(populated,[trust]);await scenario('populated upgrade preserves tenant',async()=>assert.equal((await populated.query('select count(*)::int n from organizations where id=$1',[po])).rows[0].n,1));
 const dirty=await createDb(names[3]);await apply(dirty,baseline);await dirty.query('create table trust_claims(blocker int)');await scenario('dirty schema rejection is atomic',async()=>{await assert.rejects(tx(dirty,await readFile(join('supabase/migrations',trust),'utf8')));assert.equal((await dirty.query("select to_regclass('public.trust_evidence') r")).rows[0].r,null)});
 const db=await createDb(names[4]);await apply(db,migrations);const actors=[uid(1),uid(2),uid(3)],org=uid(10),workspace=uid(11),role=uid(12);await db.query('insert into auth.users(id) select unnest($1::uuid[])',[actors]);for(let i=0;i<actors.length;i++)await db.query('insert into profiles(id,email) values($1,$2)',[actors[i],`actor${i}@fixture.invalid`]);await db.query("insert into organizations(id,name,slug) values($1,'Trust','trust-fixture')",[org]);await db.query("insert into workspaces(id,org_id,name,slug) values($1,$2,'Trust','trust-fixture')",[workspace,org]);await db.query("insert into roles(id,org_id,name,slug,scope,permissions) values($1,$2,'Trust authority','trust-authority','organization','[]')",[role,org]);await db.query("insert into role_capabilities(role_id,capability_key) select $1,capability_key from capabilities where capability_key like 'trust.%'",[role]);for(const a of actors){await db.query("insert into organization_members(org_id,user_id,role_id,status) values($1,$2,$3,'active')",[org,a,role]);await db.query("insert into workspace_memberships(org_id,workspace_id,user_id,status) values($1,$2,$3,'active')",[org,workspace,a])}const av={};for(const a of actors)av[a]=Number((await db.query('select version from authorization_versions where org_id=$1 and user_id=$2',[org,a])).rows[0].version);
 let key=0;const command=async(actor,operation,payload,expected=null,idempotency=`key-${++key}`)=>{const request=uid(100+key),hash=(await db.query("select public.trust_assurance_hash($1::jsonb) h",[JSON.stringify({operation,payload,expected})])).rows[0].h;return(await db.query('select public.trust_assurance_command($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) result',[actor,org,workspace,operation,idempotency,request,hash,av[actor],expected,JSON.stringify(payload)])).rows[0].result};
 await scenario('forced RLS and service-only RPC ACL',async()=>{assert.equal((await db.query("select bool_and(relrowsecurity and relforcerowsecurity) ok from pg_class where relname like 'trust_%' and relkind='r'")).rows[0].ok,true);assert.equal((await db.query("select has_function_privilege('authenticated','public.trust_assurance_command(uuid,uuid,uuid,text,text,uuid,text,bigint,bigint,jsonb)','EXECUTE') a")).rows[0].a,false)});
 let claimId,claimVersion,evidenceId,evidenceVersion,snapshotId,publishedResult;await scenario('claim create server hash',async()=>{const r=await command(actors[0],'claim.create',{readinessDomain:'security',claimText:'Source controls are tested.',proposedProofStatus:'verified',proofBoundary:'verified_with_evidence',buyerSafeWording:'Source controls are tested.',limitationDisclosure:'Source-only evidence.',doesNotProve:['Hosted behavior']});claimId=r.resourceId;const row=(await db.query('select cv.id,cv.canonical_hash from trust_claims c join trust_claim_versions cv on cv.id=c.current_version_id where c.id=$1',[claimId])).rows[0];claimVersion=row.id;assert.match(row.canonical_hash,/^[0-9a-f]{64}$/)});
 await scenario('evidence register server hash',async()=>{const r=await command(actors[0],'evidence.register',{evidenceType:'source_test',referenceType:'test_report',referenceValue:'tests/trust-assurance',digest:null,summary:'Focused tests passed.',evidenceBoundary:'verified_with_evidence',result:'performed',observedAt:'2026-08-07T00:00:00Z',reviewDueAt:'2099-01-01T00:00:00Z',expiresAt:'2099-01-01T00:00:00Z'});evidenceId=r.resourceId;const row=(await db.query('select ev.id,ev.canonical_hash from trust_evidence e join trust_evidence_versions ev on ev.id=e.current_version_id where e.id=$1',[evidenceId])).rows[0];evidenceVersion=row.id;assert.match(row.canonical_hash,/^[0-9a-f]{64}$/)});
 await scenario('independent exact reviews and link',async()=>{await command(actors[1],'resource.review',{resourceType:'claim_version',resourceId:claimVersion,decision:'approved',rationale:'Reviewed current claim.'});await command(actors[1],'resource.review',{resourceType:'evidence_version',resourceId:evidenceVersion,decision:'approved',rationale:'Reviewed current evidence.'});await command(actors[0],'evidence.link',{claimVersionId:claimVersion,evidenceVersionId:evidenceVersion,relationship:'supports',rationale:'Supports exact claim.'})});
 await scenario('snapshot server hash and three-person publication',async()=>{const s=await command(actors[0],'snapshot.create',{claimIds:[claimId]});snapshotId=s.resourceId;const row=(await db.query('select canonical_hash,selection from trust_snapshots where id=$1',[snapshotId])).rows[0];assert.match(row.canonical_hash,/^[0-9a-f]{64}$/);await command(actors[1],'snapshot.review',{snapshotId,decision:'reviewed',rationale:'Snapshot reviewed.'},1);publishedResult=await command(actors[2],'snapshot.publish',{snapshotId},2,'publish-main');assert.equal((await db.query('select count(*)::int n from trust_current_publications where org_id=$1 and workspace_scope=$2',[org,workspace])).rows[0].n,1)});
 await scenario('exact replay and changed payload conflict',async()=>{const payload={snapshotId};const second=await command(actors[2],'snapshot.publish',payload,2,'publish-main');assert.deepEqual(second,publishedResult);await assert.rejects(command(actors[2],'snapshot.publish',{snapshotId:uid(999)},2,'publish-main'),/IDEMPOTENCY_CONFLICT/)});
 await scenario('buyer projection only current publication',async()=>assert.equal((await db.query('select public.trust_assurance_buyer_projection($1,$2,$3,$4) p',[actors[0],org,workspace,av[actors[0]]])).rows[0].p.mode,'published_snapshot'));
 await scenario('immediate revocation denies receipt replay and restored authority replays',async()=>{const old=av[actors[2]];await db.query("update organization_members set status='inactive' where org_id=$1 and user_id=$2",[org,actors[2]]);await assert.rejects(command(actors[2],'snapshot.publish',{snapshotId},2,'publish-main'),/PR1B_NOT_FOUND/);await db.query("update organization_members set status='active' where org_id=$1 and user_id=$2",[org,actors[2]]);const current=Number((await db.query('select version from authorization_versions where org_id=$1 and user_id=$2',[org,actors[2]])).rows[0].version);av[actors[2]]=old;await assert.rejects(command(actors[2],'snapshot.publish',{snapshotId},2,'publish-main'),/PR1B_AUTHORIZATION_STALE/);av[actors[2]]=current;assert.deepEqual(await command(actors[2],'snapshot.publish',{snapshotId},2,'publish-main'),publishedResult)});
 await scenario('audit failure rolls back state and receipt',async()=>{const before=(await db.query('select version from trust_evidence where id=$1',[evidenceId])).rows[0].version;await db.query("create function trust_fixture_audit_fail() returns trigger language plpgsql as $$begin raise exception 'AUDIT_FAIL';end$$;create trigger trust_fixture_audit_fail before insert on trust_audit_events for each row execute function trust_fixture_audit_fail()");await assert.rejects(command(actors[0],'evidence.withdraw',{evidenceId},Number(before),'audit-fail'),/AUDIT_FAIL/);await db.query('drop trigger trust_fixture_audit_fail on trust_audit_events;drop function trust_fixture_audit_fail()');assert.equal((await db.query('select version from trust_evidence where id=$1',[evidenceId])).rows[0].version,before);assert.equal((await db.query("select count(*)::int n from trust_command_receipts where idempotency_key='audit-fail'")).rows[0].n,0)});
 console.log(`Trust Assurance PostgreSQL executable scenarios: ${passed} passed, ${failed} failed.`);if(failed)process.exitCode=1;
}finally{for(const c of clients.reverse())if(c!==admin)await c.end().catch(()=>{});if(admin){for(const n of created.reverse())await admin.query(`DROP DATABASE IF EXISTS ${n} WITH (FORCE)`).catch(()=>{});for(const r of roles.reverse())await admin.query(`DROP ROLE IF EXISTS ${r}`).catch(()=>{});await admin.end().catch(()=>{})}}
