import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import pg from 'pg';
import {createApprovedStudioFixture} from './studioPrivateArtifactPostgresFixture.mjs';

const adminUrl=process.env.TRANSCRIPT_FLOW_PR_C_MIGRATION_DATABASE_URL;
if(!adminUrl){
  if(process.env.CI)throw Error('TRANSCRIPT_FLOW_PR_C_MIGRATION_DATABASE_URL is required');
  console.log('TRANSCRIPT_FLOW_PR_C_MIGRATION_DATABASE_URL not set; PR C PostgreSQL scenarios were not run locally.');
  process.exit(0);
}
const {Client}=pg;
const migrationName='20260831062024_governed_delivery_monitor_pr_c.sql';
const migrations=(await readdir('supabase/migrations')).filter(name=>name.endsWith('.sql')).sort();
const featureIndex=migrations.indexOf(migrationName);assert.ok(featureIndex>0);
const baseline=migrations.slice(0,featureIndex);const suffix=`${process.pid}_${Date.now()}`;
const names=Object.fromEntries(['fresh','upgrade','populated','dirty'].map(label=>[label,`delivery_monitor_pr_c_${label}_${suffix}`]));
const clients=[];const databases=[];const roles=[];
const urlFor=name=>{const url=new URL(adminUrl);url.pathname=`/${name}`;return url.toString()};
const connect=async connectionString=>{const client=new Client({connectionString});await client.connect();clients.push(client);return client};
const transaction=async(client,label,sql)=>{await client.query('BEGIN');try{await client.query(sql);await client.query('COMMIT');console.log(`APPLIED ${label}`)}catch(error){await client.query('ROLLBACK');throw new Error(`${label}: ${error.message}`,{cause:error})}};
const bootstrap=client=>transaction(client,'auth bootstrap',`CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULLIF(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;`);
const apply=async(client,list)=>{for(const name of list)await transaction(client,name,await readFile(join('supabase/migrations',name),'utf8'))};
const createDatabase=async(admin,name)=>{assert.match(name,/^[a-z0-9_]+$/);await admin.query(`CREATE DATABASE ${name}`);databases.push(name);const client=await connect(urlFor(name));await bootstrap(client);return client};
const persona={id:'30000013-0000-4000-8000-000000000013',state:'active',capabilities:[]};
const emit=(testId,assertionId,fixture,runtimeContext)=>console.log(`PR_C_ASSERTION ${JSON.stringify({testId,assertionId,fixture,owner:'postgres',result:'passed',runtimeContext:{persona,organizationId:runtimeContext.organizationId??'97000000-0000-4000-8000-000000000010',workspaceId:runtimeContext.workspaceId??'97000000-0000-4000-8000-000000000011',...runtimeContext}})}`);
const uuid=n=>`96000000-0000-4000-8000-${String(n).padStart(12,'0')}`;

let admin;
try{
 admin=await connect(adminUrl);
 for(const [role,attributes] of [['anon','NOLOGIN'],['authenticated','NOLOGIN'],['service_role','NOLOGIN BYPASSRLS']])if(!(await admin.query('SELECT 1 FROM pg_roles WHERE rolname=$1',[role])).rowCount){await admin.query(`CREATE ROLE ${role} ${attributes}`);roles.push(role)}

 const fresh=await createDatabase(admin,names.fresh);await apply(fresh,migrations);
 const tip=(await fresh.query('SELECT migration_tip FROM public.hosted_pilot_environment_identity WHERE singleton')).rows[0].migration_tip;assert.equal(tip,'20260831062024');
 const flags=(await fresh.query(`SELECT column_name,column_default,is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='enterprise_transcript_workspace_flags' AND column_name=ANY($1::text[]) ORDER BY column_name`,[['direct_delivery_planning_enabled','delivery_item_review_enabled','monitor_approved_baseline_enabled']])).rows;
 assert.equal(flags.length,3);assert.ok(flags.every(flag=>flag.column_default==='false'&&flag.is_nullable==='NO'));
 emit('DELIVERY-TR-006','FRESH-PG16-DEFAULT-OFF','fresh-pg16',{migration:migrationName,migrationTip:tip,sourcePackage:{modes:['studio_handoff','manual']},package:null,item:null,acceptedSet:null,baseline:null,classification:'not_assessed',flags:flags.map(flag=>flag.column_name)});

 const governed=['enterprise_delivery_handoffs','enterprise_delivery_handoff_target_items','enterprise_delivery_source_packages','enterprise_delivery_work_item_aggregates','enterprise_delivery_work_item_versions','enterprise_delivery_work_item_decisions','enterprise_delivery_package_review_events','enterprise_delivery_package_approval_events','enterprise_delivery_monitor_command_receipts','enterprise_delivery_monitor_command_attempts','enterprise_delivery_monitor_effects','enterprise_monitor_baseline_items'];
 const rls=(await fresh.query(`SELECT relname,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relnamespace='public'::regnamespace AND relname=ANY($1::text[]) ORDER BY relname`,[governed])).rows;
 assert.equal(rls.length,governed.length);assert.ok(rls.every(row=>row.relrowsecurity&&row.relforcerowsecurity));
 for(const table of governed){assert.equal((await fresh.query('SELECT has_table_privilege($1,$2,$3) allowed',['authenticated',`public.${table}`,'SELECT'])).rows[0].allowed,false)}
 assert.equal((await fresh.query("SELECT has_function_privilege('service_role','public.enterprise_delivery_monitor_command(jsonb)','EXECUTE') allowed")).rows[0].allowed,true);
 assert.equal((await fresh.query("SELECT has_function_privilege('authenticated','public.enterprise_delivery_monitor_command(jsonb)','EXECUTE') allowed")).rows[0].allowed,false);
 assert.equal((await fresh.query("SELECT has_function_privilege('authenticated','public.enterprise_delivery_workspace_projection(uuid,uuid,jsonb)','EXECUTE') allowed")).rows[0].allowed,true);
 assert.equal((await fresh.query("SELECT has_function_privilege('service_role','public.enterprise_commit_delivery_handoff(jsonb,jsonb,jsonb,jsonb,uuid,uuid,bigint,jsonb)','EXECUTE') allowed")).rows[0].allowed,false);
 assert.equal((await fresh.query("SELECT has_function_privilege('service_role','public.enterprise_commit_monitor_baseline(jsonb,uuid,uuid,uuid,uuid,uuid,bigint,jsonb)','EXECUTE') allowed")).rows[0].allowed,false);
 assert.equal((await fresh.query("SELECT has_function_privilege('authenticated','public.enterprise_delivery_package_projection(uuid,uuid,uuid)','EXECUTE') allowed")).rows[0].allowed,false);
 assert.equal((await fresh.query("SELECT has_function_privilege('authenticated','public.enterprise_monitor_projection(uuid,uuid,uuid)','EXECUTE') allowed")).rows[0].allowed,false);
 emit('AUTH-002','FRESH-PG16-RLS-ACL-TENANT-BOUNDARY','fresh-pg16',{tenantBoundary:{forcedRlsTables:rls.map(row=>row.relname),authenticatedDirectTables:false,serviceMutationRpc:true,safeProjection:true},sourcePackage:null,package:null,item:null,acceptedSet:null,baseline:null,classification:'assessed'});

 const upgrade=await createDatabase(admin,names.upgrade);await apply(upgrade,baseline);await apply(upgrade,[migrationName]);
 assert.equal((await upgrade.query("SELECT migration_tip FROM public.hosted_pilot_environment_identity WHERE singleton")).rows[0].migration_tip,'20260831062024');
 emit('DELIVERY-TR-003','EMPTY-UPGRADE-PG16-IMMUTABLE-ITEM-AUTHORITY','empty-upgrade-pg16',{migration:migrationName,sourcePackage:null,package:{preserved:true},item:{aggregateAndVersionTables:true},acceptedSet:null,baseline:null,classification:'assessed'});

 const populated=await createDatabase(admin,names.populated);await apply(populated,baseline);const studio=await createApprovedStudioFixture(populated);
 const ids={handoff:uuid(1),package:uuid(2),packageVersion:uuid(3),item:uuid(4),baseline:uuid(5),legacyReview:uuid(6),legacyApproval:uuid(7)};
 const delivery=(await populated.query(`SELECT public.enterprise_commit_delivery_handoff($1::jsonb,$2::jsonb,$3::jsonb,$4::jsonb) result`,[
  JSON.stringify({id:ids.handoff,org_id:studio.org,workspace_id:studio.workspace,studio_document_id:studio.artifactId,studio_version_id:studio.artifactVersionId,studio_version:Number(studio.version.version),studio_content_hash:studio.version.content_hash,created_by:studio.requester}),
  JSON.stringify({id:ids.package,created_by:studio.requester}),JSON.stringify({id:ids.packageVersion,created_by:studio.requester,content:{contractVersion:'legacy-delivery-fixture-1'}}),
  JSON.stringify([{id:'legacy-item-a',clientKey:'legacy-item-a',itemType:'Task',title:'Retained delivery task',description:'Retained history',acceptanceCriteria:['retained'],nonFunctionalRequirements:[],sourceSectionLocator:'sections.summary',idempotencyKey:'legacy-item-a',createdBy:studio.requester}]),
 ])).rows[0].result;
 assert.equal(delivery.workPackageId,ids.package);const legacyItemId=delivery.itemIds[0];
 await populated.query("INSERT INTO role_capabilities(role_id,capability_key) VALUES($1,'approvals.review') ON CONFLICT DO NOTHING",[studio.role]);
 const legacyAuth={reviewer:Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,studio.reviewer])).rows[0].version),approver:Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,studio.approver])).rows[0].version)};
 const legacyPackageHash=(await populated.query('SELECT content_hash FROM enterprise_delivery_work_package_versions WHERE id=$1',[ids.packageVersion])).rows[0].content_hash;
 await populated.query(`INSERT INTO enterprise_high_impact_review_events(id,org_id,workspace_id,resource_type,resource_id,reviewer_id,reviewer_authorization_version,resource_version,resource_hash,outcome,rationale)
  VALUES($1,$2,$3,'delivery_work_package',$4,$5,$6,1,$7,'approved','Legacy retained review')`,[ids.legacyReview,studio.org,studio.workspace,ids.package,studio.reviewer,legacyAuth.reviewer,legacyPackageHash]);
 await populated.query(`INSERT INTO enterprise_high_impact_approvals(id,org_id,workspace_id,resource_type,resource_id,created_by,reviewed_by,approved_by,review_event_id,reviewer_authorization_version,approver_authorization_version,resource_version,resource_hash,outcome,rationale)
  VALUES($1,$2,$3,'delivery_work_package',$4,$5,$6,$7,$8,$9,$10,1,$11,'approved','Legacy retained approval')`,[ids.legacyApproval,studio.org,studio.workspace,ids.package,studio.requester,studio.reviewer,studio.approver,ids.legacyReview,legacyAuth.reviewer,legacyAuth.approver,legacyPackageHash]);
 await populated.query("UPDATE enterprise_delivery_work_packages SET status='approved' WHERE id=$1",[ids.package]);await populated.query("UPDATE enterprise_delivery_work_package_versions SET status='approved' WHERE id=$1",[ids.packageVersion]);
 await populated.query(`INSERT INTO enterprise_monitor_baselines(id,org_id,workspace_id,work_package_id,work_package_version_id,studio_document_id,studio_version,studio_content_hash,approved_item_ids,milestones,dependencies,blockers,risks,readiness,status,live_telemetry_connected,version,resource_hash,created_by)
  VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,'[]','[]','[]','[]','review_required','approved',false,1,$10,$11)`,[ids.baseline,studio.org,studio.workspace,ids.package,ids.packageVersion,studio.artifactId,Number(studio.version.version),studio.version.content_hash,JSON.stringify([legacyItemId]),'b'.repeat(64),studio.requester]);
 const before={package:(await populated.query('SELECT id,handoff_id,current_version,status FROM enterprise_delivery_work_packages WHERE id=$1',[ids.package])).rows[0],item:(await populated.query('SELECT id,title,source_document_hash FROM enterprise_delivery_work_items WHERE id=$1',[legacyItemId])).rows[0]};
 await apply(populated,[migrationName]);
 await assert.rejects(populated.query(`INSERT INTO enterprise_high_impact_review_events(id,org_id,workspace_id,resource_type,resource_id,reviewer_id,reviewer_authorization_version,resource_version,resource_hash,outcome,rationale)
  VALUES($1,$2,$3,'delivery_work_package_version',$4,$5,$6,1,$7,'approved','Forbidden legacy PR C review')`,[uuid(8),studio.org,studio.workspace,ids.packageVersion,studio.reviewer,legacyAuth.reviewer,legacyPackageHash]),/ENTERPRISE_PR_C_CANONICAL_APPROVAL_REQUIRED/);
 await assert.rejects(populated.query(`INSERT INTO enterprise_high_impact_approvals(id,org_id,workspace_id,resource_type,resource_id,created_by,reviewed_by,approved_by,review_event_id,reviewer_authorization_version,approver_authorization_version,resource_version,resource_hash,outcome,rationale)
  VALUES($1,$2,$3,'delivery_work_package',$4,$5,$6,$7,$8,$9,$10,1,$11,'approved','Forbidden legacy PR C approval')`,[uuid(9),studio.org,studio.workspace,ids.package,studio.requester,studio.reviewer,studio.approver,ids.legacyReview,legacyAuth.reviewer,legacyAuth.approver,legacyPackageHash]),/ENTERPRISE_PR_C_CANONICAL_APPROVAL_REQUIRED/);
 assert.equal(Number((await populated.query("SELECT count(*) n FROM enterprise_high_impact_review_events WHERE id=$1 OR id=$2",[uuid(8),uuid(9)])).rows[0].n),0);
 const legacyBaseline=(await populated.query('SELECT baseline_contract,package_approval_id FROM enterprise_monitor_baselines WHERE id=$1',[ids.baseline])).rows[0];assert.deepEqual(legacyBaseline,{baseline_contract:'legacy-1',package_approval_id:null});
 const after={package:(await populated.query('SELECT id,handoff_id,current_version,status,source_package_id,source_package_hash,current_version_id FROM enterprise_delivery_work_packages WHERE id=$1',[ids.package])).rows[0],item:(await populated.query('SELECT id,title,source_document_hash FROM enterprise_delivery_work_items WHERE id=$1',[legacyItemId])).rows[0]};
 assert.deepEqual({id:after.package.id,handoff_id:after.package.handoff_id,current_version:after.package.current_version,status:after.package.status},before.package);assert.deepEqual(after.item,before.item);
 const source=(await populated.query('SELECT * FROM enterprise_delivery_source_packages WHERE work_package_id=$1',[ids.package])).rows[0];
 const itemAggregate=(await populated.query('SELECT aggregate.id,aggregate.current_version_id,version.version,version.status,version.content_hash FROM enterprise_delivery_work_item_aggregates aggregate JOIN enterprise_delivery_work_item_versions version ON version.id=aggregate.current_version_id WHERE aggregate.id=$1',[legacyItemId])).rows[0];
 assert.equal(source.source_mode,'studio_handoff');assert.equal(source.studio_artifact_version_id,studio.artifactVersionId);assert.equal(source.studio_artifact_hash,studio.version.content_hash);assert.equal(itemAggregate.status,'proposed');
 emit('DELIVERY-TR-001','POPULATED-UPGRADE-PRESERVES-LEGACY-AND-BACKFILLS-EXACT-STUDIO','populated-upgrade-pg16',{organizationId:studio.org,workspaceId:studio.workspace,handoff:{edge:'studio_to_delivery',id:ids.handoff,studioArtifactVersionId:studio.artifactVersionId,studioArtifactHash:studio.version.content_hash},sourcePackage:{id:source.id,version:Number(source.version),hash:source.package_hash},package:{id:ids.package,versionId:ids.packageVersion,version:1},item:{aggregateId:legacyItemId,versionId:itemAggregate.current_version_id,version:Number(itemAggregate.version),hash:itemAggregate.content_hash},acceptedSet:null,baseline:null,classification:source.lineage_classification});
 emit('DELIVERY-TR-002','POPULATED-UPGRADE-ITEM-EXACT-SOURCE-CITATION','populated-upgrade-pg16',{organizationId:studio.org,workspaceId:studio.workspace,handoff:{edge:'studio_to_delivery',id:ids.handoff},sourcePackage:{id:source.id,hash:source.package_hash},package:{id:ids.package,versionId:ids.packageVersion},item:{aggregateId:legacyItemId,versionId:itemAggregate.current_version_id,sourceArtifactVersionId:studio.artifactVersionId,sourceArtifactHash:studio.version.content_hash},acceptedSet:null,baseline:null,classification:source.lineage_classification});

 const targetWorkspace=uuid(200);
 const consumer=uuid(201),projectManager=uuid(202),projectManagerRole=uuid(203),sourceOnly=uuid(204);
 await populated.query('INSERT INTO auth.users(id) VALUES($1),($2),($3)',[consumer,projectManager,sourceOnly]);
 await populated.query("INSERT INTO profiles(id,email) VALUES($1,'consumer@fixture.invalid'),($2,'project-manager@fixture.invalid'),($3,'source-only@fixture.invalid')",[consumer,projectManager,sourceOnly]);
 await populated.query("INSERT INTO roles(id,org_id,name,slug,scope,permissions) VALUES($1,$2,'Project manager only','project-manager-only','organization','[]')",[projectManagerRole,studio.org]);
 await populated.query("INSERT INTO role_capabilities(role_id,capability_key) VALUES($1,'project.manage')",[projectManagerRole]);
 await populated.query("INSERT INTO organization_members(org_id,user_id,role_id,status) VALUES($1,$2,$3,'active')",[studio.org,consumer,studio.role]);
 await populated.query("INSERT INTO organization_members(org_id,user_id,role_id,status) VALUES($1,$2,$3,'active')",[studio.org,projectManager,projectManagerRole]);
 await populated.query("INSERT INTO organization_members(org_id,user_id,role_id,status) VALUES($1,$2,$3,'active')",[studio.org,sourceOnly,studio.role]);
 await populated.query("INSERT INTO workspaces(id,org_id,name,slug) VALUES($1,$2,'Delivery target','delivery-target')",[targetWorkspace,studio.org]);
 await populated.query("INSERT INTO workspace_memberships(org_id,workspace_id,user_id,status) SELECT $1,$2,actor,'active' FROM unnest($3::uuid[]) actor",[studio.org,targetWorkspace,[studio.requester,studio.reviewer,studio.approver,consumer]]);
 await populated.query("INSERT INTO workspace_memberships(org_id,workspace_id,user_id,status) VALUES($1,$2,$3,'active')",[studio.org,targetWorkspace,projectManager]);
 await populated.query("INSERT INTO workspace_memberships(org_id,workspace_id,user_id,status) VALUES($1,$2,$3,'active')",[studio.org,studio.workspace,sourceOnly]);
 await populated.query(`INSERT INTO role_capabilities(role_id,capability_key) SELECT $1,capability FROM unnest($2::text[]) capability ON CONFLICT DO NOTHING`,[studio.role,[
  'delivery.handoff.request','delivery.handoff.review','delivery.handoff.approve','delivery.handoff.consume','delivery.package.manage','delivery.package.review','delivery.package.approve',
  'monitor.baseline.create','project.read','monitor.read',
 ]]);
 await populated.query(`INSERT INTO enterprise_transcript_workspace_flags(org_id,workspace_id,module_handoffs_enabled,direct_delivery_planning_enabled,delivery_item_review_enabled,monitor_approved_baseline_enabled,updated_by)
  VALUES($1,$2,true,true,true,true,$3) ON CONFLICT(org_id,workspace_id) DO UPDATE SET module_handoffs_enabled=true,direct_delivery_planning_enabled=true,
   delivery_item_review_enabled=true,monitor_approved_baseline_enabled=true,updated_by=excluded.updated_by`,[studio.org,studio.workspace,studio.requester]);
 await populated.query(`INSERT INTO enterprise_transcript_workspace_flags(org_id,workspace_id,module_handoffs_enabled,direct_delivery_planning_enabled,delivery_item_review_enabled,monitor_approved_baseline_enabled,updated_by)
  VALUES($1,$2,true,true,true,true,$3) ON CONFLICT(org_id,workspace_id) DO UPDATE SET module_handoffs_enabled=true,direct_delivery_planning_enabled=true,
   delivery_item_review_enabled=true,monitor_approved_baseline_enabled=true,updated_by=excluded.updated_by`,[studio.org,targetWorkspace,studio.requester]);
 const authorizationVersions={};for(const actor of [studio.requester,studio.reviewer,studio.approver,consumer,projectManager,sourceOnly])authorizationVersions[actor]=Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,actor])).rows[0].version);
 let commandOrdinal=300;
 const makeCommand=(actor,workspace,action,payload,key)=>{const ordinal=commandOrdinal++;return {action,actorId:actor,organizationId:studio.org,workspaceId:workspace,
  authorizationVersion:authorizationVersions[actor],receiptId:uuid(ordinal),requestId:uuid(ordinal+1000),idempotencyKey:key,executionToken:uuid(ordinal+2000),executionFence:ordinal,...payload}};
 const invoke=async(client,command)=>(await client.query('SELECT public.enterprise_delivery_monitor_command($1::jsonb) result',[JSON.stringify(command)])).rows[0].result;

 const stale=makeCommand(studio.requester,targetWorkspace,'delivery.package.create.manual',{manualBrief:'Stale authority attempt',items:[{clientKey:'stale',itemType:'Task',title:'Stale',description:'denied',acceptanceCriteria:[],nonFunctionalRequirements:[]}]},'manual-stale-authority');
 stale.authorizationVersion--;
 await assert.rejects(invoke(populated,stale),/ENTERPRISE_DELIVERY_RESOURCE_STALE/);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_effects WHERE receipt_id=$1',[stale.receiptId])).rows[0].n),0);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_receipts WHERE id=$1',[stale.receiptId])).rows[0].n),0);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM privileged_audit_events WHERE request_id=$1',[stale.requestId])).rows[0].n),0);
 emit('AUTH-002','PG16-STALE-AUTHORIZATION-NO-EFFECT','command-authority-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,authority:{expectedVersion:authorizationVersions[studio.requester],presentedVersion:stale.authorizationVersion,effectCount:0},sourcePackage:null,package:null,item:null,acceptedSet:null,baseline:null,classification:'not_assessed'});

 const manual=makeCommand(studio.requester,targetWorkspace,'delivery.package.create.manual',{manualBrief:'Plan only delivery brief',items:[
  {clientKey:'a-root',itemType:'Epic',title:'Manual root',description:'Root scope',acceptanceCriteria:['root accepted'],nonFunctionalRequirements:[]},
  {clientKey:'b-child',parentClientKey:'a-root',itemType:'Task',title:'Manual child',description:'Child scope',acceptanceCriteria:['child accepted'],nonFunctionalRequirements:['audit']},
 ]},'manual-create-exact');
 const manualResult=await invoke(populated,manual);assert.equal(manualResult.planningOnly,true);assert.equal(manualResult.lineageClassification,'not_assessed');assert.equal(manualResult.items.length,2);
 const replayTransport=structuredClone(manual);replayTransport.receiptId=uuid(9000);replayTransport.executionToken=uuid(9002);replayTransport.executionFence=1;
 const replay=await invoke(populated,replayTransport);assert.deepEqual(replay,manualResult);assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_effects WHERE receipt_id=$1',[manual.receiptId])).rows[0].n),1);
 await populated.query('UPDATE authorization_versions SET version=version+1 WHERE org_id=$1 AND user_id=$2',[studio.org,studio.requester]);
 authorizationVersions[studio.requester]=Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,studio.requester])).rows[0].version);
 const advancedReplay=structuredClone(manual);advancedReplay.receiptId=uuid(9003);advancedReplay.requestId=uuid(9004);advancedReplay.executionToken=uuid(9005);advancedReplay.executionFence=2;advancedReplay.authorizationVersion=authorizationVersions[studio.requester];
 assert.deepEqual(await invoke(populated,advancedReplay),manualResult);
 await populated.query("UPDATE workspace_memberships SET status='suspended' WHERE org_id=$1 AND workspace_id=$2 AND user_id=$3",[studio.org,targetWorkspace,studio.requester]);
 authorizationVersions[studio.requester]=Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,studio.requester])).rows[0].version);
 const revokedReplay=structuredClone(manual);revokedReplay.receiptId=uuid(9006);revokedReplay.requestId=uuid(9007);revokedReplay.executionToken=uuid(9008);revokedReplay.executionFence=3;revokedReplay.authorizationVersion=authorizationVersions[studio.requester];
 await assert.rejects(invoke(populated,revokedReplay),/PERMISSION|RESOURCE_UNAVAILABLE|TENANT_ACCESS/);
 await populated.query("UPDATE workspace_memberships SET status='active' WHERE org_id=$1 AND workspace_id=$2 AND user_id=$3",[studio.org,targetWorkspace,studio.requester]);
 authorizationVersions[studio.requester]=Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,studio.requester])).rows[0].version);
 const restoredReplay=structuredClone(manual);restoredReplay.receiptId=uuid(9009);restoredReplay.requestId=uuid(9010);restoredReplay.executionToken=uuid(9011);restoredReplay.executionFence=4;restoredReplay.authorizationVersion=authorizationVersions[studio.requester];
 assert.deepEqual(await invoke(populated,restoredReplay),manualResult);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_effects WHERE receipt_id=$1',[manual.receiptId])).rows[0].n),1);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_attempts WHERE receipt_id=$1',[manual.receiptId])).rows[0].n),3);
 const storedTransport=(await populated.query('SELECT id,request_id,execution_token,execution_fence,resource_id,response FROM enterprise_delivery_monitor_command_receipts WHERE id=$1',[manual.receiptId])).rows[0];
 assert.deepEqual(storedTransport,{id:manual.receiptId,request_id:manual.requestId,execution_token:manual.executionToken,execution_fence:String(manual.executionFence),resource_id:manualResult.resourceId,response:manualResult});
 const changedManual=structuredClone(manual);changedManual.manualBrief='Changed binding must fail';changedManual.receiptId=uuid(9015);changedManual.requestId=uuid(9016);changedManual.executionToken=uuid(9017);changedManual.authorizationVersion=authorizationVersions[studio.requester];await assert.rejects(invoke(populated,changedManual),/ENTERPRISE_DELIVERY_IDEMPOTENCY_CONFLICT/);
 const changedRequest=structuredClone(manual);changedRequest.requestId=uuid(9012);changedRequest.receiptId=uuid(9013);changedRequest.executionToken=uuid(9014);changedRequest.authorizationVersion=authorizationVersions[studio.requester];assert.deepEqual(await invoke(populated,changedRequest),manualResult);
 const auditCardinality=(await populated.query("SELECT count(*) n FROM privileged_audit_events WHERE metadata->>'receiptId'=$1",[manual.receiptId])).rows[0].n;assert.equal(Number(auditCardinality),1);
 emit('IDEMP-003','PG16-RESPONSE-LOSS-AUTH-ADVANCE-REVOKE-RESTORE-AND-CONFLICT','manual-command-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,receipt:{id:manual.receiptId,resourceId:manualResult.resourceId,exactReplay:true,benignAuthorizationAdvanceReplay:true,revokeDeniedBeforeDisclosure:true,restoreReplay:true,transportRequestExcluded:true,changedBindingConflict:true,executionFence:manual.executionFence,effectCount:1,attemptCount:3},sourcePackage:{id:manualResult.sourcePackageId,hash:manualResult.sourcePackageHash},package:{id:manualResult.resourceId,versionId:manualResult.packageVersionId,version:1,hash:manualResult.packageHash},item:null,acceptedSet:null,baseline:null,classification:'not_assessed'});

 const reviewerSnapshotBeforeItemDecisions=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.reviewer,authorizationVersion:authorizationVersions[studio.reviewer]})])).rows[0].projection;
 const reviewerSnapshotPackage=reviewerSnapshotBeforeItemDecisions.packages.find(entry=>entry.id===manualResult.resourceId);assert.equal(reviewerSnapshotPackage.aggregateVersion,1);
 const acceptedItems=[];
 for(const [index,item] of manualResult.items.entries()){
  if(index===0){const forbiddenMutation=makeCommand(studio.requester,targetWorkspace,'delivery.item.review',{itemAggregateId:item.aggregateId,expectedAggregateVersion:1,expectedItemVersionId:item.versionId,outcome:'accepted',rationale:'Must not mutate.',item:{clientKey:'x',itemType:'Task',title:'Altered',description:'',acceptanceCriteria:[],nonFunctionalRequirements:[]}},'manual-item-accept-payload-denied');await assert.rejects(invoke(populated,forbiddenMutation),/INVALID_COMMAND/)}
  const reviewed=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.item.review',{itemAggregateId:item.aggregateId,expectedAggregateVersion:1,expectedItemVersionId:item.versionId,outcome:'accepted',rationale:`Accepted item ${index+1}.`},`manual-item-accept-${index+1}`));
  acceptedItems.push({aggregateId:item.aggregateId,versionId:reviewed.itemVersionId,version:reviewed.resourceVersion,hash:reviewed.itemHash});
 }
 const staleSnapshotReview=makeCommand(studio.reviewer,targetWorkspace,'delivery.package.review.resolve',{workPackageId:manualResult.resourceId,expectedPackageVersion:1,expectedPackageVersionId:manualResult.packageVersionId,expectedPackageAggregateVersion:reviewerSnapshotPackage.aggregateVersion,outcome:'approved',rationale:'A stale item snapshot must not be reviewed.'},'manual-package-stale-item-snapshot');
 await assert.rejects(invoke(populated,staleSnapshotReview),/ENTERPRISE_DELIVERY_RESOURCE_STALE/);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_package_review_events WHERE work_package_id=$1',[manualResult.resourceId])).rows[0].n),0);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_effects WHERE receipt_id=$1',[staleSnapshotReview.receiptId])).rows[0].n),0);
 const packageReview=await invoke(populated,makeCommand(studio.reviewer,targetWorkspace,'delivery.package.review.resolve',{workPackageId:manualResult.resourceId,expectedPackageVersion:1,expectedPackageVersionId:manualResult.packageVersionId,expectedPackageAggregateVersion:3,outcome:'approved',rationale:'Independent package review.'},'manual-package-review'));
 const packageApproval=await invoke(populated,makeCommand(studio.approver,targetWorkspace,'delivery.package.approval.resolve',{workPackageId:manualResult.resourceId,expectedPackageVersion:1,expectedPackageVersionId:manualResult.packageVersionId,expectedPackageAggregateVersion:3,outcome:'approved',rationale:'Separate package approval.'},'manual-package-approval'));
 assert.equal(packageReview.acceptedSetHash,packageApproval.acceptedSetHash);
 assert.equal(packageReview.acceptedItemCount,2);assert.equal(packageApproval.acceptedItemCount,2);
 await assert.rejects(populated.query('UPDATE enterprise_delivery_work_item_aggregates SET updated_at=now() WHERE id=$1',[acceptedItems[0].aggregateId]),/DELIVERY_ITEM_AGGREGATE_IMMUTABLE/);
 const reviewActorSeed=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.package.create.manual',{manualBrief:'Current item actor review separation',items:[{clientKey:'review-actor',itemType:'Task',title:'Reviewer-authored decision',description:'The current item decision actor cannot review the package.',acceptanceCriteria:[],nonFunctionalRequirements:[]}]},'review-actor-seed'));
 await invoke(populated,makeCommand(studio.reviewer,targetWorkspace,'delivery.item.review',{itemAggregateId:reviewActorSeed.items[0].aggregateId,expectedAggregateVersion:1,expectedItemVersionId:reviewActorSeed.items[0].versionId,outcome:'accepted',rationale:'Reviewer accepted this current item.'},'review-actor-item-decision'));
 const currentItemActorReview=makeCommand(studio.reviewer,targetWorkspace,'delivery.package.review.resolve',{workPackageId:reviewActorSeed.resourceId,expectedPackageVersion:1,expectedPackageVersionId:reviewActorSeed.packageVersionId,expectedPackageAggregateVersion:2,outcome:'approved',rationale:'Current item actor must not review.'},'current-item-actor-review-denied');
 await assert.rejects(invoke(populated,currentItemActorReview),/ENTERPRISE_DELIVERY_RESOURCE_UNAVAILABLE/);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_package_review_events WHERE work_package_id=$1',[reviewActorSeed.resourceId])).rows[0].n),0);

 const approvalActorSeed=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.package.create.manual',{manualBrief:'Current item actor approval separation',items:[{clientKey:'approval-actor',itemType:'Task',title:'Approver-authored decision',description:'The current item decision actor cannot approve the package.',acceptanceCriteria:[],nonFunctionalRequirements:[]}]},'approval-actor-seed'));
 await invoke(populated,makeCommand(studio.approver,targetWorkspace,'delivery.item.review',{itemAggregateId:approvalActorSeed.items[0].aggregateId,expectedAggregateVersion:1,expectedItemVersionId:approvalActorSeed.items[0].versionId,outcome:'accepted',rationale:'Approver accepted this current item.'},'approval-actor-item-decision'));
 await invoke(populated,makeCommand(studio.reviewer,targetWorkspace,'delivery.package.review.resolve',{workPackageId:approvalActorSeed.resourceId,expectedPackageVersion:1,expectedPackageVersionId:approvalActorSeed.packageVersionId,expectedPackageAggregateVersion:2,outcome:'approved',rationale:'Independent review for approval separation.'},'approval-actor-independent-review'));
 const currentItemActorApproval=makeCommand(studio.approver,targetWorkspace,'delivery.package.approval.resolve',{workPackageId:approvalActorSeed.resourceId,expectedPackageVersion:1,expectedPackageVersionId:approvalActorSeed.packageVersionId,expectedPackageAggregateVersion:2,outcome:'approved',rationale:'Current item actor must not approve.'},'current-item-actor-approval-denied');
 await assert.rejects(invoke(populated,currentItemActorApproval),/ENTERPRISE_DELIVERY_RESOURCE_UNAVAILABLE/);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_package_approval_events WHERE work_package_id=$1',[approvalActorSeed.resourceId])).rows[0].n),0);
 const reviewerActionProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.reviewer,authorizationVersion:authorizationVersions[studio.reviewer]})])).rows[0].projection;
 const approverActionProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.approver,authorizationVersion:authorizationVersions[studio.approver]})])).rows[0].projection;
 assert.equal(reviewerActionProjection.packages.find(entry=>entry.id===reviewActorSeed.resourceId).actions.includes('delivery.package.review.resolve'),false);
 assert.equal(approverActionProjection.packages.find(entry=>entry.id===approvalActorSeed.resourceId).actions.includes('delivery.package.approval.resolve'),false);
 emit('DELIVERY-TR-004','PG16-ITEM-DECISIONS-AND-THREE-PERSON-PACKAGE-APPROVAL','manual-review-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,sourcePackage:{id:manualResult.sourcePackageId,hash:manualResult.sourcePackageHash},package:{id:manualResult.resourceId,versionId:manualResult.packageVersionId,version:1,aggregateVersion:3,hash:manualResult.packageHash,reviewId:packageReview.resourceId,approvalId:packageApproval.resourceId,staleSnapshotDenied:true},item:{accepted:acceptedItems,currentItemActorReviewDenied:true,currentItemActorApprovalDenied:true},acceptedSet:{hash:packageApproval.acceptedSetHash},baseline:null,classification:'not_assessed'});

 const baselineOnly=uuid(220),baselineOnlyRole=uuid(221);
 await populated.query('INSERT INTO auth.users(id) VALUES($1)',[baselineOnly]);
 await populated.query("INSERT INTO profiles(id,email) VALUES($1,'baseline-only@fixture.invalid')",[baselineOnly]);
 await populated.query("INSERT INTO roles(id,org_id,name,slug,scope,permissions) VALUES($1,$2,'Baseline create only','baseline-create-only','organization','[]')",[baselineOnlyRole,studio.org]);
 await populated.query("INSERT INTO role_capabilities(role_id,capability_key) VALUES($1,'monitor.baseline.create')",[baselineOnlyRole]);
 await populated.query("INSERT INTO organization_members(org_id,user_id,role_id,status) VALUES($1,$2,$3,'active')",[studio.org,baselineOnly,baselineOnlyRole]);
 await populated.query("INSERT INTO workspace_memberships(org_id,workspace_id,user_id,status) VALUES($1,$2,$3,'active')",[studio.org,targetWorkspace,baselineOnly]);
 const baselineOnlyVersion=Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,baselineOnly])).rows[0].version);
 const baselineOnlyProjectionBeforeCreate=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:baselineOnly,authorizationVersion:baselineOnlyVersion})])).rows[0].projection;
 assert.equal(baselineOnlyProjectionBeforeCreate.packages.length,0);assert.equal(baselineOnlyProjectionBeforeCreate.handoffs.length,0);assert.equal(baselineOnlyProjectionBeforeCreate.eligibleStudioArtifacts.length,0);assert.ok(baselineOnlyProjectionBeforeCreate.baselineEligibility.some(entry=>entry.workPackageId===manualResult.resourceId));
 assert.doesNotMatch(JSON.stringify(baselineOnlyProjectionBeforeCreate),/"[^"]*(?:hash|actorId|requestedBy|sourceWorkspaceId|sourcePackageId|rationale|items|history)"/i);

 const eligibilitySeed=(await populated.query(`SELECT to_jsonb(package_row) AS package,to_jsonb(source_row) AS source,to_jsonb(version_row) AS version,to_jsonb(review_row) AS review,to_jsonb(approval_row) AS approval
  FROM enterprise_delivery_work_packages package_row
  JOIN enterprise_delivery_source_packages source_row ON source_row.id=package_row.source_package_id
  JOIN enterprise_delivery_work_package_versions version_row ON version_row.id=package_row.current_version_id
  JOIN enterprise_delivery_package_review_events review_row ON review_row.work_package_id=package_row.id AND review_row.package_version_id=version_row.id
  JOIN enterprise_delivery_package_approval_events approval_row ON approval_row.work_package_id=package_row.id AND approval_row.package_version_id=version_row.id
  WHERE package_row.id=$1`,[manualResult.resourceId])).rows[0];
 await populated.query('BEGIN');
 try{
  await populated.query('SET CONSTRAINTS ALL DEFERRED');
  const packageRows=[],sourceRows=[],versionRows=[],reviewRows=[],approvalRows=[];
  for(let index=0;index<100;index++){
   const packageId=uuid(20_000+index*5),sourceId=uuid(20_001+index*5),versionId=uuid(20_002+index*5),reviewId=uuid(20_003+index*5),approvalId=uuid(20_004+index*5);
   const createdAt=new Date(Date.UTC(2026,7,31,0,0,index)).toISOString();
   packageRows.push({...eligibilitySeed.package,id:packageId,source_package_id:sourceId,current_version_id:versionId,handoff_id:null,delivery_handoff_id:null,created_at:createdAt,updated_at:createdAt});
   sourceRows.push({...eligibilitySeed.source,id:sourceId,work_package_id:packageId,created_at:createdAt});
   versionRows.push({...eligibilitySeed.version,id:versionId,work_package_id:packageId,source_package_id:sourceId,created_at:createdAt});
   reviewRows.push({...eligibilitySeed.review,id:reviewId,work_package_id:packageId,package_version_id:versionId,created_at:createdAt});
   approvalRows.push({...eligibilitySeed.approval,id:approvalId,work_package_id:packageId,package_version_id:versionId,review_event_id:reviewId,created_at:createdAt});
  }
  for(const [table,rows] of [['enterprise_delivery_work_packages',packageRows],['enterprise_delivery_source_packages',sourceRows],['enterprise_delivery_work_package_versions',versionRows],['enterprise_delivery_package_review_events',reviewRows],['enterprise_delivery_package_approval_events',approvalRows]]){
   await populated.query(`INSERT INTO ${table} SELECT * FROM jsonb_populate_recordset(NULL::${table},$1::jsonb)`,[JSON.stringify(rows)]);
  }
  await populated.query('SET CONSTRAINTS ALL IMMEDIATE');
  const eligibilityPageOne=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:baselineOnly,authorizationVersion:baselineOnlyVersion,baselineEligibilityLimit:100})])).rows[0].projection;
  assert.equal(eligibilityPageOne.baselineEligibility.length,100);assert.equal(eligibilityPageOne.page.baselineEligibilityLimit,100);assert.equal(eligibilityPageOne.page.baselineEligibilityHasMore,true);assert.equal(eligibilityPageOne.page.baselineEligibilityCursorApplied,false);assert.ok(eligibilityPageOne.page.baselineEligibilityNextCursor);
  const eligibilityPageTwo=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:baselineOnly,authorizationVersion:baselineOnlyVersion,baselineEligibilityLimit:100,baselineEligibilityCursorUpdatedAt:eligibilityPageOne.page.baselineEligibilityNextCursor.updatedAt,baselineEligibilityCursorPackageId:eligibilityPageOne.page.baselineEligibilityNextCursor.workPackageId})])).rows[0].projection;
  assert.equal(eligibilityPageTwo.baselineEligibility.length,1);assert.equal(eligibilityPageTwo.page.baselineEligibilityHasMore,false);assert.equal(eligibilityPageTwo.page.baselineEligibilityCursorApplied,true);assert.equal(eligibilityPageTwo.page.baselineEligibilityNextCursor,undefined);
  assert.equal(new Set([...eligibilityPageOne.baselineEligibility,...eligibilityPageTwo.baselineEligibility].map(entry=>entry.workPackageVersionId)).size,101);
  assert.doesNotMatch(JSON.stringify({eligibilityPageOne,eligibilityPageTwo}),/"[^"]*(?:hash|actorId|requestedBy|sourceWorkspaceId|sourcePackageId|rationale|items|history)"/i);
  emit('MONITOR-TR-001','PG16-BASELINE-ELIGIBILITY-BOUNDED-100-WITH-101-CURSOR-CONTINUATION','baseline-eligibility-pagination-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,sourcePackage:null,package:{eligibleCount:101,pageSizes:[100,1]},item:null,acceptedSet:null,baseline:{selectorOnly:true,firstPageHasMore:true,secondPageComplete:true,publicHashesPresent:false},classification:'not_assessed'});
 }finally{await populated.query('ROLLBACK')}

 const forbiddenBaseline=makeCommand(studio.requester,targetWorkspace,'monitor.baseline.create',{workPackageId:manualResult.resourceId,expectedPackageVersion:1,expectedPackageVersionId:manualResult.packageVersionId,
  packageApprovalId:packageApproval.resourceId,expectedAcceptedSetHash:packageApproval.acceptedSetHash,acceptedItemAggregateIds:[acceptedItems[0].aggregateId,acceptedItems[0].aggregateId,acceptedItems[1].aggregateId]},'baseline-caller-selector-denied');
 await assert.rejects(invoke(populated,forbiddenBaseline),/INVALID_COMMAND/);
 const baselineInjection=makeCommand(studio.requester,targetWorkspace,'monitor.baseline.create',{workPackageId:manualResult.resourceId,expectedPackageVersion:1,expectedPackageVersionId:manualResult.packageVersionId,milestones:['Browser-authored milestone']},'baseline-authored-content-denied');
 await assert.rejects(invoke(populated,baselineInjection),/INVALID_COMMAND/);
 const baselineA=makeCommand(studio.requester,targetWorkspace,'monitor.baseline.create',{workPackageId:manualResult.resourceId,expectedPackageVersion:1,expectedPackageVersionId:manualResult.packageVersionId},'baseline-server-derived-a');
 const baselineB=makeCommand(studio.requester,targetWorkspace,'monitor.baseline.create',{workPackageId:manualResult.resourceId,expectedPackageVersion:1,expectedPackageVersionId:manualResult.packageVersionId},'baseline-server-derived-b');
 const concurrentA=await connect(urlFor(names.populated)),concurrentB=await connect(urlFor(names.populated));
 const sameKeyA=makeCommand(studio.requester,targetWorkspace,'delivery.package.create.manual',{manualBrief:'Concurrent same-key replay proof',items:[{clientKey:'same-key-item',itemType:'Task',title:'Exactly once',description:'One canonical effect.',acceptanceCriteria:[],nonFunctionalRequirements:[]}]},'manual-concurrent-same-key');
 const sameKeyB=structuredClone(sameKeyA);sameKeyB.receiptId=uuid(9020);sameKeyB.requestId=uuid(9021);sameKeyB.executionToken=uuid(9022);sameKeyB.executionFence=sameKeyA.executionFence+10_000;
 const sameKeySettled=await Promise.allSettled([invoke(concurrentA,sameKeyA),invoke(concurrentB,sameKeyB)]);
 assert.equal(sameKeySettled.filter(entry=>entry.status==='fulfilled').length,2,sameKeySettled.map(entry=>entry.status==='rejected'?entry.reason?.message:'fulfilled').join(' | '));
 assert.deepEqual(sameKeySettled[0].value,sameKeySettled[1].value);
 const sameKeyReceipt=(await populated.query("SELECT id FROM enterprise_delivery_monitor_command_receipts WHERE org_id=$1 AND workspace_id=$2 AND actor_id=$3 AND action='delivery.package.create.manual' AND idempotency_key=$4",[studio.org,targetWorkspace,studio.requester,sameKeyA.idempotencyKey])).rows[0];
 const eligibleSameKeyReceiptIds=[sameKeyA.receiptId,sameKeyB.receiptId].sort();assert.ok(sameKeyReceipt);assert.ok(eligibleSameKeyReceiptIds.includes(sameKeyReceipt.id));assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_effects WHERE receipt_id=$1',[sameKeyReceipt.id])).rows[0].n),1);assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_attempts WHERE receipt_id=$1',[sameKeyReceipt.id])).rows[0].n),2);
 emit('IDEMP-003','PG16-CONCURRENT-SAME-KEY-ONE-EFFECT-EQUIVALENT-REPLAY','same-key-concurrency-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,receipt:{id:sameKeyReceipt.id,eligibleReceiptIds:eligibleSameKeyReceiptIds,effectCount:1,attemptCount:2,concurrentCallers:2,equivalentReplay:true},sourcePackage:null,package:{id:sameKeySettled[0].value.resourceId},item:null,acceptedSet:null,baseline:null,classification:'not_assessed'});
 const baselineSettled=await Promise.allSettled([invoke(concurrentA,baselineA),invoke(concurrentB,baselineB)]);const successes=baselineSettled.filter(entry=>entry.status==='fulfilled');
 assert.equal(successes.length,1,baselineSettled.map(entry=>entry.status==='rejected'?entry.reason?.message:'fulfilled').join(' | '));const baselineResult=successes[0].value;assert.equal(baselineResult.packageApprovalId,packageApproval.resourceId);assert.equal(baselineResult.acceptedSetHash,packageApproval.acceptedSetHash);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_monitor_baselines WHERE work_package_version_id=$1',[manualResult.packageVersionId])).rows[0].n),1);
 const winningCommand=baselineSettled[0].status==='fulfilled'?baselineA:baselineB;assert.deepEqual(await invoke(populated,winningCommand),baselineResult);
 const baselineItems=(await populated.query('SELECT item_aggregate_id,item_version_id,item_hash FROM enterprise_monitor_baseline_items WHERE baseline_id=$1 ORDER BY ordinal',[baselineResult.resourceId])).rows;
 assert.equal(baselineItems.length,2);assert.deepEqual(baselineItems.map(row=>row.item_aggregate_id).sort(),acceptedItems.map(item=>item.aggregateId).sort());
 assert.equal(baselineResult.acceptedItemCount,2);assert.equal(baselineResult.readiness,'not_ready');assert.deepEqual(baselineResult.milestones,[]);assert.deepEqual(baselineResult.dependencies,[]);assert.deepEqual(baselineResult.risks,[]);
 emit('MONITOR-TR-001','PG16-SERVER-DERIVED-EXACT-ACCEPTED-SET-CONCURRENT-ONE-WINNER','monitor-baseline-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,sourcePackage:{id:manualResult.sourcePackageId,hash:manualResult.sourcePackageHash},package:{id:manualResult.resourceId,versionId:manualResult.packageVersionId,version:1,hash:manualResult.packageHash,approvalId:packageApproval.resourceId},item:{accepted:acceptedItems},acceptedSet:{hash:baselineResult.acceptedSetHash,itemCount:baselineItems.length,callerSelectorsRejected:true},baseline:{id:baselineResult.resourceId,version:baselineResult.resourceVersion,hash:baselineResult.resourceHash,concurrentWinners:1,responseLossReplay:true,authoredContentRejected:true,serverDerivedContent:true,readiness:'not_ready'},classification:'not_assessed'});

 const revisionSeed=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.package.create.manual',{manualBrief:'Partial revision exact snapshot',items:[
  {clientKey:'rev-a',itemType:'Task',title:'Revise me',description:'v1',acceptanceCriteria:['a'],nonFunctionalRequirements:[]},
  {clientKey:'rev-b',itemType:'Task',title:'Carry me',description:'v1',acceptanceCriteria:['b'],nonFunctionalRequirements:[]},
 ]},'revision-seed'));
 const revised=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.package.revision.commit',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:1,expectedPackageVersionId:revisionSeed.packageVersionId,
  itemRevisions:[{itemAggregateId:revisionSeed.items[0].aggregateId,expectedAggregateVersion:1,expectedItemVersionId:revisionSeed.items[0].versionId,rationale:'Scoped edit.',item:{itemType:'Task',title:'Revised item',description:'v2',acceptanceCriteria:['a2'],nonFunctionalRequirements:[]}}]},'revision-partial-full-snapshot'));
 assert.equal(revised.items.length,2);const revisionSnapshot=(await populated.query('SELECT version.package_version_id,version.status,version.parent_version_id FROM enterprise_delivery_work_item_aggregates aggregate JOIN enterprise_delivery_work_item_versions version ON version.id=aggregate.current_version_id WHERE aggregate.work_package_id=$1 ORDER BY aggregate.id',[revisionSeed.resourceId])).rows;
 assert.ok(revisionSnapshot.every(row=>row.package_version_id===revised.packageVersionId&&row.parent_version_id));assert.deepEqual(revisionSnapshot.map(row=>row.status).sort(),['edited','proposed']);
 const reviewedRevisionItems=[];for(const [index,item] of revised.items.entries())reviewedRevisionItems.push(await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.item.review',{itemAggregateId:item.itemAggregateId,expectedAggregateVersion:2,expectedItemVersionId:item.itemVersionId,outcome:'accepted',rationale:`Revision item ${index+1} accepted.`},`revision-v2-item-${index+1}`)));
 const changesRequested=await invoke(populated,makeCommand(studio.reviewer,targetWorkspace,'delivery.package.review.resolve',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:2,expectedPackageVersionId:revised.packageVersionId,expectedPackageAggregateVersion:4,outcome:'changes_requested',rationale:'Revise the first delivery item.'},'revision-v2-changes-requested'));
 assert.equal(changesRequested.status,'changes_requested');assert.equal((await populated.query('SELECT status FROM enterprise_delivery_work_packages WHERE id=$1',[revisionSeed.resourceId])).rows[0].status,'blocked');
 const openBlocker=(await populated.query("SELECT blocker_key,safe_summary FROM enterprise_delivery_package_blocker_events WHERE work_package_id=$1 AND action='opened'",[revisionSeed.resourceId])).rows[0];assert.match(openBlocker.safe_summary,/Revise the first/);
 const blockedBaseline=makeCommand(studio.requester,targetWorkspace,'monitor.baseline.create',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:2,expectedPackageVersionId:revised.packageVersionId},'blocked-baseline-denied');await assert.rejects(invoke(populated,blockedBaseline),/ENTERPRISE_DELIVERY_RESOURCE_UNAVAILABLE|ENTERPRISE_DELIVERY_COMMAND_BLOCKED/);
 const resolvedRevision=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.package.revision.commit',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:2,expectedPackageVersionId:revised.packageVersionId,itemRevisions:[{itemAggregateId:revised.items[0].itemAggregateId,expectedAggregateVersion:3,expectedItemVersionId:reviewedRevisionItems[0].itemVersionId,rationale:'Resolve requested change.',item:{itemType:'Task',title:'Revised item resolved',description:'v3',acceptanceCriteria:['a3'],nonFunctionalRequirements:[]}}]},'revision-v3-resolves-blocker'));
 assert.equal(Number((await populated.query("SELECT count(*) n FROM enterprise_delivery_package_blocker_events opened WHERE opened.work_package_id=$1 AND opened.action='opened' AND NOT EXISTS(SELECT 1 FROM enterprise_delivery_package_blocker_events newer WHERE newer.work_package_id=opened.work_package_id AND newer.blocker_key=opened.blocker_key AND newer.sequence>opened.sequence)",[revisionSeed.resourceId])).rows[0].n),0);
 const resolvedItems=[];for(const [index,item] of resolvedRevision.items.entries())resolvedItems.push(await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.item.review',{itemAggregateId:item.itemAggregateId,expectedAggregateVersion:4,expectedItemVersionId:item.itemVersionId,outcome:'accepted',rationale:`Resolved snapshot item ${index+1} accepted.`},`revision-v3-item-${index+1}`)));
 const selfReview=makeCommand(studio.requester,targetWorkspace,'delivery.package.review.resolve',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:3,expectedPackageVersionId:resolvedRevision.packageVersionId,expectedPackageAggregateVersion:7,outcome:'approved',rationale:'Self review denied.'},'revision-author-self-review');await assert.rejects(invoke(populated,selfReview),/ENTERPRISE_DELIVERY_RESOURCE_UNAVAILABLE/);
 await invoke(populated,makeCommand(studio.reviewer,targetWorkspace,'delivery.package.review.resolve',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:3,expectedPackageVersionId:resolvedRevision.packageVersionId,expectedPackageAggregateVersion:7,outcome:'approved',rationale:'Independent review after blocker resolution.'},'revision-v3-review'));
 const postReviewMutation=makeCommand(studio.requester,targetWorkspace,'delivery.item.review',{itemAggregateId:resolvedRevision.items[0].itemAggregateId,expectedAggregateVersion:5,expectedItemVersionId:resolvedItems[0].itemVersionId,outcome:'rejected',rationale:'Mutation after review denied.'},'revision-v3-post-review-mutation');await assert.rejects(invoke(populated,postReviewMutation),/ENTERPRISE_DELIVERY_RESOURCE_UNAVAILABLE/);
 const resolvedApproval=await invoke(populated,makeCommand(studio.approver,targetWorkspace,'delivery.package.approval.resolve',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:3,expectedPackageVersionId:resolvedRevision.packageVersionId,expectedPackageAggregateVersion:7,outcome:'approved',rationale:'Independent approval after blocker resolution.'},'revision-v3-approval'));
 const resolvedBaseline=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'monitor.baseline.create',{workPackageId:revisionSeed.resourceId,expectedPackageVersion:3,expectedPackageVersionId:resolvedRevision.packageVersionId},'revision-v3-baseline'));
 assert.equal(resolvedBaseline.packageApprovalId,resolvedApproval.resourceId);assert.equal(resolvedBaseline.acceptedItemCount,2);
 const raceSeed=await invoke(populated,makeCommand(studio.requester,targetWorkspace,'delivery.package.create.manual',{manualBrief:'Lock order race',items:[{clientKey:'race',itemType:'Task',title:'Race',description:'v1',acceptanceCriteria:[],nonFunctionalRequirements:[]}]},'lock-race-seed'));
 const raceReview=makeCommand(studio.requester,targetWorkspace,'delivery.item.review',{itemAggregateId:raceSeed.items[0].aggregateId,expectedAggregateVersion:1,expectedItemVersionId:raceSeed.items[0].versionId,outcome:'edited',rationale:'Concurrent edit.',item:{itemType:'Task',title:'Review won',description:'edit',acceptanceCriteria:[],nonFunctionalRequirements:[]}},'lock-race-review');
 const raceRevision=makeCommand(studio.requester,targetWorkspace,'delivery.package.revision.commit',{workPackageId:raceSeed.resourceId,expectedPackageVersion:1,expectedPackageVersionId:raceSeed.packageVersionId,itemRevisions:[{itemAggregateId:raceSeed.items[0].aggregateId,expectedAggregateVersion:1,expectedItemVersionId:raceSeed.items[0].versionId,rationale:'Concurrent package revision.',item:{itemType:'Task',title:'Revision won',description:'edit',acceptanceCriteria:[],nonFunctionalRequirements:[]}}]},'lock-race-revision');
 const lockRace=await Promise.allSettled([invoke(concurrentA,raceReview),invoke(concurrentB,raceRevision)]);assert.equal(lockRace.filter(entry=>entry.status==='fulfilled').length,1);assert.ok(lockRace.filter(entry=>entry.status==='rejected').every(entry=>!String(entry.reason?.message).includes('deadlock detected')));
 emit('DELIVERY-TR-003','PG16-PARTIAL-REVISION-FULL-SNAPSHOT-BLOCKER-RESOLUTION-AND-PACKAGE-FIRST-NO-DEADLOCK','revision-concurrency-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,sourcePackage:{id:revisionSeed.sourcePackageId,hash:revisionSeed.sourcePackageHash},package:{id:revisionSeed.resourceId,versionId:resolvedRevision.packageVersionId,version:3,hash:resolvedRevision.packageHash,changesRequestedReviewId:changesRequested.resourceId,approvalId:resolvedApproval.resourceId,authorSelfReviewDenied:true,postReviewMutationDenied:true,openBlockerCount:0},item:{snapshotCount:revisionSnapshot.length,allBoundToVersion:true,carriedStatus:'proposed',revisedStatus:'edited'},acceptedSet:{hash:resolvedBaseline.acceptedSetHash,itemCount:resolvedBaseline.acceptedItemCount},baseline:{id:resolvedBaseline.resourceId,hash:resolvedBaseline.resourceHash,blockedBeforeResolution:true},classification:'not_assessed',concurrency:{deadlocks:0,winners:1}});

 const targetInjection=makeCommand(sourceOnly,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,expectedApprovedVersionId:studio.artifactVersionId},'studio-delivery-target-membership-required');
 await assert.rejects(invoke(populated,targetInjection),/ENTERPRISE_DELIVERY_RESOURCE_UNAVAILABLE/);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_receipts WHERE id=$1',[targetInjection.receiptId])).rows[0].n),0);assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_attempts WHERE request_id=$1',[targetInjection.requestId])).rows[0].n),0);assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_effects WHERE receipt_id=$1',[targetInjection.receiptId])).rows[0].n),0);assert.equal(Number((await populated.query('SELECT count(*) n FROM privileged_audit_events WHERE request_id=$1',[targetInjection.requestId])).rows[0].n),0);
 emit('AUTH-002','PG16-HANDOFF-TARGET-WORKSPACE-AUTHORITY-BEFORE-RECEIPT','handoff-target-authority-pg16',{organizationId:studio.org,workspaceId:studio.workspace,edge:'studio_to_delivery',tenantBoundary:{sourceAuthorized:true,targetWorkspaceMembership:false,deniedBeforeReceipt:true,newReceipts:0,newAttempts:0,newEffects:0,newAuditEvents:0},sourcePackage:null,package:null,item:null,acceptedSet:null,baseline:null,classification:'assessed'});
 await populated.query('BEGIN');try{await populated.query('UPDATE workspaces SET deleted_at=now() WHERE id=$1',[targetWorkspace]);const deletedTarget=makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,expectedApprovedVersionId:studio.artifactVersionId},'studio-delivery-deleted-target');await assert.rejects(invoke(populated,deletedTarget),/ENTERPRISE_DELIVERY_RESOURCE_UNAVAILABLE/)}finally{await populated.query('ROLLBACK')}
 const invalidLocator=makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,
  studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,
  expectedApprovedVersionId:studio.artifactVersionId,proposedItems:[{clientKey:'altered',itemType:'Task',title:'Caller-authored',description:'Rejected',acceptanceCriteria:[],nonFunctionalRequirements:[],sourceSectionLocator:'brd.sections.999'}]},'studio-delivery-caller-proposal-denied');
 await assert.rejects(invoke(populated,invalidLocator),/INVALID_COMMAND/);
 const handoffRequest=makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,
  studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,
  expectedApprovedVersionId:studio.artifactVersionId},'studio-delivery-target-request');
 const handoffResult=await invoke(populated,handoffRequest);assert.equal(handoffResult.targetWorkspaceId,targetWorkspace);assert.equal(handoffResult.routePolicyVersion,1);
 const targetRows=(await populated.query('SELECT ordinal,item,item_hash FROM enterprise_delivery_handoff_target_items WHERE handoff_id=$1 ORDER BY ordinal',[handoffResult.resourceId])).rows;
 assert.equal(targetRows.length,handoffResult.proposedItemCount);assert.ok(targetRows.every(row=>row.item.sourceSectionLocator.startsWith('brd.sections.')));
 const handoffReview=await invoke(populated,makeCommand(studio.reviewer,targetWorkspace,'delivery.handoff.review.resolve',{handoffId:handoffResult.resourceId,expectedHandoffVersion:1,outcome:'approved',rationale:'Target reviewer accepted exact target.'},'studio-delivery-target-review'));
 const handoffApproval=await invoke(populated,makeCommand(studio.approver,targetWorkspace,'delivery.handoff.approval.resolve',{handoffId:handoffResult.resourceId,expectedHandoffVersion:2,outcome:'approved',rationale:'Target approver accepted exact target.'},'studio-delivery-target-approval'));
 const rejectedConsume=makeCommand(studio.requester,targetWorkspace,'delivery.handoff.consume',{handoffId:handoffResult.resourceId,expectedHandoffVersion:3,items:targetRows.map(row=>row.item)},'studio-delivery-consume-caller-items');
 await assert.rejects(invoke(populated,rejectedConsume),/INVALID_COMMAND/);
 const consumeCommand=makeCommand(consumer,targetWorkspace,'delivery.handoff.consume',{handoffId:handoffResult.resourceId,expectedHandoffVersion:3},'studio-delivery-consume-server-target');
 const requestDuringConsume=makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,expectedApprovedVersionId:studio.artifactVersionId},'studio-delivery-request-consume-race');
 const routeRace=await Promise.allSettled([invoke(concurrentA,consumeCommand),invoke(concurrentB,requestDuringConsume)]);assert.equal(routeRace[0].status,'fulfilled');assert.ok(routeRace.every(entry=>entry.status==='fulfilled'||!String(entry.reason?.message).includes('deadlock detected')));const consumed=routeRace[0].value;
 if(routeRace[1].status==='fulfilled')await invoke(populated,makeCommand(studio.requester,studio.workspace,'delivery.handoff.withdraw',{handoffId:routeRace[1].value.resourceId,expectedHandoffVersion:1},'studio-delivery-request-consume-race-withdraw'));
 const consumedItems=(await populated.query('SELECT version.title,version.source_artifact_version_id,version.source_artifact_hash FROM enterprise_delivery_work_item_aggregates aggregate JOIN enterprise_delivery_work_item_versions version ON version.id=aggregate.current_version_id WHERE aggregate.work_package_id=$1',[consumed.resourceId])).rows;
 assert.equal(consumedItems.length,targetRows.length);assert.equal(consumedItems[0].title,targetRows[0].item.title);assert.equal(consumedItems[0].source_artifact_version_id,studio.artifactVersionId);assert.equal(consumedItems[0].source_artifact_hash,studio.version.content_hash);
 const foreignItem=(await populated.query('SELECT aggregate.id aggregate_id,version.id version_id,version.item_type,version.content_hash FROM enterprise_delivery_work_item_aggregates aggregate JOIN enterprise_delivery_work_item_versions version ON version.id=aggregate.current_version_id WHERE aggregate.work_package_id=$1 ORDER BY aggregate.id LIMIT 1',[consumed.resourceId])).rows[0];
 await populated.query('BEGIN');try{await assert.rejects(async()=>{await populated.query('INSERT INTO enterprise_monitor_baseline_items(baseline_id,work_package_id,work_package_version_id,item_aggregate_id,item_version_id,org_id,workspace_id,ordinal,item_type,item_hash) VALUES($1,$2,$3,$4,$5,$6,$7,99,$8,$9)',[baselineResult.resourceId,consumed.resourceId,consumed.packageVersionId,foreignItem.aggregate_id,foreignItem.version_id,studio.org,targetWorkspace,foreignItem.item_type,foreignItem.content_hash]);await populated.query('SET CONSTRAINTS ALL IMMEDIATE')},/foreign key|MONITOR_BASELINE_ITEM_BINDING_INVALID/i)}finally{await populated.query('ROLLBACK')}
 const nextRequestA=makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,expectedApprovedVersionId:studio.artifactVersionId},'studio-delivery-active-race-a');
 const nextRequestB=makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,expectedApprovedVersionId:studio.artifactVersionId},'studio-delivery-active-race-b');
 const requestRace=await Promise.allSettled([invoke(concurrentA,nextRequestA),invoke(concurrentB,nextRequestB)]);assert.equal(requestRace.filter(entry=>entry.status==='fulfilled').length,1,requestRace.map(entry=>entry.status==='rejected'?entry.reason?.message:'fulfilled').join(' | '));const activeReplacement=requestRace.find(entry=>entry.status==='fulfilled').value;
 await invoke(populated,makeCommand(studio.requester,studio.workspace,'delivery.handoff.withdraw',{handoffId:activeReplacement.resourceId,expectedHandoffVersion:1},'studio-delivery-replacement-withdraw'));
 const terminalReplacement=await invoke(populated,makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,studioArtifactVersionId:studio.artifactVersionId,expectedAggregateVersion:studio.aggregateVersion,expectedCurrentVersionId:studio.artifactVersionId,expectedApprovedVersionId:studio.artifactVersionId},'studio-delivery-terminal-replacement'));
 assert.notEqual(terminalReplacement.resourceId,activeReplacement.resourceId);assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_handoffs WHERE studio_artifact_version_id=$1 AND target_workspace_id=$2',[studio.artifactVersionId,targetWorkspace])).rows[0].n),3+(routeRace[1].status==='fulfilled'?1:0));
 const originalSourceSnapshot=(await populated.query('SELECT id,studio_artifact_version_id,studio_artifact_hash,studio_source_package_id,studio_source_package_hash,package_hash FROM enterprise_delivery_source_packages WHERE id=$1',[consumed.sourcePackageId])).rows[0];
 const originalItemSnapshot=(await populated.query('SELECT source_artifact_version_id,source_artifact_hash,studio_source_package_id,studio_source_package_hash FROM enterprise_delivery_work_item_versions WHERE work_package_id=$1 ORDER BY version LIMIT 1',[consumed.resourceId])).rows[0];
 const laterVersionId=uuid(9800);const originalVersionJson=(await populated.query('SELECT to_jsonb(studio_artifact_versions) AS version_json FROM studio_artifact_versions WHERE id=$1',[studio.artifactVersionId])).rows[0].version_json;
 const originalStudioContent=typeof studio.version.content==='string'?JSON.parse(studio.version.content):studio.version.content;
 const laterContent=structuredClone(originalStudioContent);laterContent.sections[0].body=`${laterContent.sections[0].body} Later approved revision.`;
 const laterHash=(await populated.query('SELECT public.enterprise_sha256_jsonb($1::jsonb) hash',[JSON.stringify(laterContent)])).rows[0].hash;
 const laterVersionJson={...originalVersionJson,id:laterVersionId,version:Number(originalVersionJson.version)+1,parent_version_id:studio.artifactVersionId,generation_attempt_id:null,content:laterContent,content_hash:laterHash,lifecycle:'approved',created_at:new Date().toISOString()};
 await populated.query("SET session_replication_role='replica'");try{await populated.query('INSERT INTO studio_artifact_versions SELECT (jsonb_populate_record(NULL::studio_artifact_versions,$1::jsonb)).*',[JSON.stringify(laterVersionJson)]);await populated.query("UPDATE studio_artifact_versions SET lifecycle='superseded' WHERE id=$1",[studio.artifactVersionId]);await populated.query('UPDATE studio_artifact_aggregates SET current_version_id=$1,current_approved_version_id=$1,aggregate_version=aggregate_version+1,updated_at=now() WHERE id=$2',[laterVersionId,studio.artifactId])}finally{await populated.query("SET session_replication_role='origin'")}
 assert.equal((await populated.query('SELECT public.enterprise_pr_c_delivery_source_current($1,$2,$3,false) current',[consumed.sourcePackageId,studio.org,targetWorkspace])).rows[0].current,true);
 assert.deepEqual((await populated.query('SELECT id,studio_artifact_version_id,studio_artifact_hash,studio_source_package_id,studio_source_package_hash,package_hash FROM enterprise_delivery_source_packages WHERE id=$1',[consumed.sourcePackageId])).rows[0],originalSourceSnapshot);
 assert.deepEqual((await populated.query('SELECT source_artifact_version_id,source_artifact_hash,studio_source_package_id,studio_source_package_hash FROM enterprise_delivery_work_item_versions WHERE work_package_id=$1 ORDER BY version LIMIT 1',[consumed.resourceId])).rows[0],originalItemSnapshot);
 const staleHandoffReview=makeCommand(studio.reviewer,targetWorkspace,'delivery.handoff.review.resolve',{handoffId:terminalReplacement.resourceId,expectedHandoffVersion:1,outcome:'approved',rationale:'Must be denied after Studio advances.'},'studio-delivery-stale-review');await assert.rejects(invoke(populated,staleHandoffReview),/ENTERPRISE_DELIVERY_HANDOFF_STALE/);
 assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_handoff_review_events WHERE handoff_id=$1',[terminalReplacement.resourceId])).rows[0].n),0);assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_receipts WHERE id=$1',[staleHandoffReview.receiptId])).rows[0].n),0);assert.equal(Number((await populated.query('SELECT count(*) n FROM privileged_audit_events WHERE request_id=$1',[staleHandoffReview.requestId])).rows[0].n),0);
 const laterHandoff=await invoke(populated,makeCommand(studio.requester,studio.workspace,'delivery.handoff.request',{targetWorkspaceId:targetWorkspace,studioArtifactId:studio.artifactId,studioArtifactVersionId:laterVersionId,expectedAggregateVersion:studio.aggregateVersion+1,expectedCurrentVersionId:laterVersionId,expectedApprovedVersionId:laterVersionId},'studio-delivery-later-version-request'));
 assert.notEqual(laterHandoff.resourceId,terminalReplacement.resourceId);assert.equal(laterHandoff.studioArtifactVersionId,laterVersionId);
 assert.equal((await populated.query('SELECT resource_hash FROM enterprise_monitor_baselines WHERE id=$1',[baselineResult.resourceId])).rows[0].resource_hash,baselineResult.resourceHash);
 emit('HANDOFF-006','PG16-LATER-STUDIO-VERSION-PRESERVES-CONSUMED-LINEAGE-AND-ENABLES-NEW-HANDOFF','studio-delivery-later-version-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,edge:'studio_to_delivery',handoff:{edge:'studio_to_delivery',consumedId:handoffResult.resourceId,newId:laterHandoff.resourceId,originalStudioVersionId:studio.artifactVersionId,newStudioVersionId:laterVersionId,originalStudioHash:studio.version.content_hash,newStudioHash:laterHash},sourcePackage:{id:consumed.sourcePackageId,hash:originalSourceSnapshot.package_hash,immutable:true},package:{id:consumed.resourceId,versionId:consumed.packageVersionId,hash:consumed.packageHash},item:{sourceArtifactVersionId:originalItemSnapshot.source_artifact_version_id,sourceArtifactHash:originalItemSnapshot.source_artifact_hash},acceptedSet:{hash:baselineResult.acceptedSetHash,itemCount:baselineResult.acceptedItemCount},baseline:{id:baselineResult.resourceId,hash:baselineResult.resourceHash,immutable:true},classification:consumed.lineageClassification});
 emit('HANDOFF-004','PG16-TARGET-BOUND-SERVER-DERIVED-CONSUME','studio-delivery-handoff-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,edge:'studio_to_delivery',handoff:{edge:'studio_to_delivery',id:handoffResult.resourceId,sourceWorkspaceId:studio.workspace,targetWorkspaceId:targetWorkspace,requestVersion:1,reviewVersion:handoffReview.resourceVersion,approvalVersion:handoffApproval.resourceVersion,targetPackageHash:handoffResult.targetPackageHash,routePolicyHash:handoffResult.routePolicyHash,persistedTargetItemHash:targetRows[0].item_hash,callerItemsRejected:true,requestConsumeRaceDeadlocks:0,concurrentRequestOutcome:routeRace[1].status},sourcePackage:{id:consumed.sourcePackageId,hash:consumed.sourcePackageHash},package:{id:consumed.resourceId,versionId:consumed.packageVersionId,version:1,hash:consumed.packageHash},item:{versionId:consumedItems[0].source_artifact_version_id,sourceArtifactHash:consumedItems[0].source_artifact_hash},acceptedSet:null,baseline:null,classification:consumed.lineageClassification});

 const handoffOnly=uuid(222),handoffOnlyRole=uuid(223),handoffApproveOnly=uuid(224),handoffApproveOnlyRole=uuid(225);
 await populated.query('INSERT INTO auth.users(id) VALUES($1),($2)',[handoffOnly,handoffApproveOnly]);
 await populated.query("INSERT INTO profiles(id,email) VALUES($1,'handoff-only@fixture.invalid'),($2,'handoff-approve-only@fixture.invalid')",[handoffOnly,handoffApproveOnly]);
 await populated.query("INSERT INTO roles(id,org_id,name,slug,scope,permissions) VALUES($1,$3,'Handoff review only','handoff-review-only','organization','[]'),($2,$3,'Handoff approve only','handoff-approve-only','organization','[]')",[handoffOnlyRole,handoffApproveOnlyRole,studio.org]);
 await populated.query("INSERT INTO role_capabilities(role_id,capability_key) VALUES($1,'delivery.handoff.review'),($2,'delivery.handoff.approve')",[handoffOnlyRole,handoffApproveOnlyRole]);
 await populated.query("INSERT INTO organization_members(org_id,user_id,role_id,status) VALUES($1,$2,$3,'active'),($1,$4,$5,'active')",[studio.org,handoffOnly,handoffOnlyRole,handoffApproveOnly,handoffApproveOnlyRole]);
 await populated.query("INSERT INTO workspace_memberships(org_id,workspace_id,user_id,status) VALUES($1,$2,$3,'active'),($1,$2,$4,'active')",[studio.org,targetWorkspace,handoffOnly,handoffApproveOnly]);
 const handoffOnlyVersion=Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,handoffOnly])).rows[0].version);
 const handoffApproveOnlyVersion=Number((await populated.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[studio.org,handoffApproveOnly])).rows[0].version);
 const deliveryProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester],packageId:manualResult.resourceId,itemLimit:10})])).rows[0].projection;
 assert.equal(deliveryProjection.featureFlags.monitorApprovedBaselineEnabled,true);assert.ok(deliveryProjection.handoffs.some(entry=>entry.id===handoffResult.resourceId&&entry.direction==='inbox'&&entry.history.length===4&&entry.targetItems.length===1));
 assert.doesNotMatch(JSON.stringify(deliveryProjection),/"[^"]*(?:hash|actorId|requestedBy|sourceWorkspaceId|sourcePackageId)"/i);
 const manualProjection=deliveryProjection.packages.find(entry=>entry.id===manualResult.resourceId);assert.ok(manualProjection.items.every(item=>item.history.length===2&&item.history[1].diff.changedFields.length===0));
 const projectManagerProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:projectManager,authorizationVersion:authorizationVersions[projectManager],packageId:manualResult.resourceId})])).rows[0].projection;assert.equal(projectManagerProjection.packages.length,1);
 const handoffOnlyProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:handoffOnly,authorizationVersion:handoffOnlyVersion})])).rows[0].projection;
 assert.equal(handoffOnlyProjection.packages.length,0);assert.equal(handoffOnlyProjection.eligibleStudioArtifacts.length,0);assert.equal(handoffOnlyProjection.baselineEligibility.length,0);assert.ok(handoffOnlyProjection.handoffs.length>0);
 assert.doesNotMatch(JSON.stringify(handoffOnlyProjection),/"[^"]*(?:hash|actorId|requestedBy|sourceWorkspaceId|sourcePackageId)"/i);
 const handoffApproveOnlyProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:handoffApproveOnly,authorizationVersion:handoffApproveOnlyVersion})])).rows[0].projection;
 assert.equal(handoffApproveOnlyProjection.packages.length,0);assert.equal(handoffApproveOnlyProjection.eligibleStudioArtifacts.length,0);assert.equal(handoffApproveOnlyProjection.baselineEligibility.length,0);assert.ok(handoffApproveOnlyProjection.handoffs.length>0);
 assert.doesNotMatch(JSON.stringify(handoffApproveOnlyProjection),/"[^"]*(?:hash|actorId|requestedBy|sourceWorkspaceId|sourcePackageId)"/i);
 const enabledOutboxProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,studio.workspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester]})])).rows[0].projection;
 const enabledOutbox=enabledOutboxProjection.handoffs.find(entry=>entry.id===laterHandoff.resourceId&&entry.direction==='outbox');assert.ok(enabledOutbox);assert.ok(enabledOutbox.actions.includes('delivery.handoff.withdraw'));
 const monitorProjection=(await populated.query('SELECT public.enterprise_monitor_approved_baselines_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester]})])).rows[0].projection;
 assert.equal(monitorProjection.actions.length,0);assert.equal(monitorProjection.baselines[0].acceptedItems.length,2);assert.ok(monitorProjection.baselines.every(entry=>entry.contract==='delivery-monitor-2'));
 assert.doesNotMatch(JSON.stringify(monitorProjection),/"[^"]*(?:hash|actorId|packageApprovalId|sourcePackageId)"/i);
 await populated.query('BEGIN');try{await populated.query("UPDATE profiles SET status='suspended' WHERE id=$1",[studio.requester]);await populated.query('SET LOCAL ROLE authenticated');await populated.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[studio.requester]);await assert.rejects(populated.query("SELECT public.enterprise_delivery_workspace_projection($1,$2,'{}'::jsonb)",[studio.org,targetWorkspace]),/PR1B_NOT_FOUND/)}finally{await populated.query('ROLLBACK')}
 await populated.query('BEGIN');try{await populated.query('UPDATE profiles SET deleted_at=now() WHERE id=$1',[studio.requester]);await populated.query('SET LOCAL ROLE authenticated');await populated.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[studio.requester]);await assert.rejects(populated.query("SELECT public.enterprise_monitor_approved_baselines_projection($1,$2,'{}'::jsonb)",[studio.org,targetWorkspace]),/PR1B_NOT_FOUND/)}finally{await populated.query('ROLLBACK')}
 await assert.rejects(populated.query("UPDATE enterprise_delivery_work_item_versions SET title='mutated' WHERE id=$1",[acceptedItems[0].versionId]),/immutable|reject|mutation|append_only/i);
 const receiptIntegrity=(await populated.query(`SELECT count(*) n FROM enterprise_delivery_monitor_command_receipts receipt LEFT JOIN enterprise_delivery_monitor_effects effect ON effect.receipt_id=receipt.id LEFT JOIN privileged_audit_events audit ON audit.id=effect.audit_id WHERE receipt.status='committed' AND (effect.id IS NULL OR audit.id IS NULL OR receipt.resource_id IS DISTINCT FROM (receipt.response->>'resourceId')::uuid OR effect.result IS DISTINCT FROM receipt.response OR audit.metadata->>'receiptId'<>receipt.id::text)`)).rows[0].n;assert.equal(Number(receiptIntegrity),0);
 emit('MONITOR-TR-003','PG16-SAFE-HISTORY-DIFF-INBOX-AND-READONLY-MONITOR-PROJECTIONS','projection-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,edge:'studio_to_delivery',handoff:{edge:'studio_to_delivery',id:handoffResult.resourceId,inbox:true,historyVersions:4,targetItems:1},sourcePackage:{id:manualResult.sourcePackageId,hash:manualResult.sourcePackageHash},package:{id:manualResult.resourceId,versionId:manualResult.packageVersionId},item:{historyVersions:2,diffsPresent:true,immutableMutationRejected:true},acceptedSet:{hash:baselineResult.acceptedSetHash,itemCount:2},baseline:{id:baselineResult.resourceId,readOnly:true,liveTelemetryConnected:false},classification:'not_assessed'});

 const committedHistoryBeforeRollback={
  handoffs:Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_handoffs WHERE org_id=$1',[studio.org])).rows[0].n),
  itemVersions:Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_work_item_versions WHERE org_id=$1 AND workspace_id=$2',[studio.org,targetWorkspace])).rows[0].n),
  baselines:Number((await populated.query("SELECT count(*) n FROM enterprise_monitor_baselines WHERE org_id=$1 AND workspace_id=$2 AND baseline_contract='delivery-monitor-2'",[studio.org,targetWorkspace])).rows[0].n),
 };
 assert.ok(committedHistoryBeforeRollback.handoffs>0&&committedHistoryBeforeRollback.itemVersions>0&&committedHistoryBeforeRollback.baselines>0);
 await populated.query(`UPDATE enterprise_transcript_workspace_flags SET module_handoffs_enabled=false,direct_delivery_planning_enabled=false,delivery_item_review_enabled=false,monitor_approved_baseline_enabled=false,updated_by=$3 WHERE org_id=$1 AND workspace_id=ANY($2::uuid[])`,[studio.org,[studio.workspace,targetWorkspace],studio.requester]);
 const rollbackFlags=(await populated.query('SELECT workspace_id,module_handoffs_enabled,direct_delivery_planning_enabled,delivery_item_review_enabled,monitor_approved_baseline_enabled FROM enterprise_transcript_workspace_flags WHERE org_id=$1 AND workspace_id=ANY($2::uuid[]) ORDER BY workspace_id',[studio.org,[studio.workspace,targetWorkspace]])).rows;
 assert.equal(rollbackFlags.length,2);assert.ok(rollbackFlags.every(flag=>!flag.module_handoffs_enabled&&!flag.direct_delivery_planning_enabled&&!flag.delivery_item_review_enabled&&!flag.monitor_approved_baseline_enabled));
 const prCActions=['delivery.handoff.request','delivery.handoff.review.resolve','delivery.handoff.approval.resolve','delivery.handoff.withdraw','delivery.handoff.consume',
  'delivery.package.create.manual','delivery.item.review','delivery.package.revision.commit','delivery.package.review.resolve','delivery.package.approval.resolve','monitor.baseline.create'];
 const assertBlockedBeforePersistence=async(command,errorPattern)=>{
  await assert.rejects(invoke(populated,command),errorPattern);
  assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_receipts WHERE id=$1',[command.receiptId])).rows[0].n),0);
  assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_command_attempts WHERE request_id=$1',[command.requestId])).rows[0].n),0);
  assert.equal(Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_monitor_effects WHERE receipt_id=$1',[command.receiptId])).rows[0].n),0);
  assert.equal(Number((await populated.query('SELECT count(*) n FROM privileged_audit_events WHERE request_id=$1',[command.requestId])).rows[0].n),0);
 };
 const featureDisabledCommands=prCActions.map(action=>makeCommand(studio.requester,targetWorkspace,action,{},`rollback-feature-${action}`));
 for(const command of featureDisabledCommands)await assertBlockedBeforePersistence(command,/ENTERPRISE_DELIVERY_FEATURE_DISABLED/);
 const rollbackDeliveryProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester],packageId:manualResult.resourceId,itemLimit:10})])).rows[0].projection;
 const rollbackOutboxProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,studio.workspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester]})])).rows[0].projection;
 const rollbackHandoffReviewProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:handoffOnly,authorizationVersion:handoffOnlyVersion})])).rows[0].projection;
 const rollbackHandoffApproveProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:handoffApproveOnly,authorizationVersion:handoffApproveOnlyVersion})])).rows[0].projection;
 const rollbackMonitorProjection=(await populated.query('SELECT public.enterprise_monitor_approved_baselines_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester]})])).rows[0].projection;
 assert.deepEqual(rollbackDeliveryProjection.featureFlags,{directDeliveryPlanningEnabled:false,deliveryItemReviewEnabled:false,monitorApprovedBaselineEnabled:false,moduleHandoffsEnabled:false});assert.equal(rollbackDeliveryProjection.readOnly,false);assert.deepEqual(rollbackDeliveryProjection.actions,[]);assert.ok(rollbackDeliveryProjection.packages.some(entry=>entry.id===manualResult.resourceId));assert.ok(rollbackDeliveryProjection.packages.every(entry=>entry.actions.length===0));assert.deepEqual(rollbackDeliveryProjection.baselineEligibility,[]);
 assert.ok(rollbackOutboxProjection.handoffs.some(entry=>entry.id===laterHandoff.resourceId&&entry.direction==='outbox'));assert.ok(rollbackOutboxProjection.handoffs.every(entry=>entry.actions.length===0));
 for(const projection of [rollbackHandoffReviewProjection,rollbackHandoffApproveProjection]){assert.equal(projection.packages.length,0);assert.ok(projection.handoffs.length>0);assert.ok(projection.handoffs.every(entry=>entry.direction==='inbox'&&entry.actions.length===0))}
 assert.equal(rollbackMonitorProjection.featureFlags.monitorApprovedBaselineEnabled,false);assert.deepEqual(rollbackMonitorProjection.actions,[]);assert.ok(rollbackMonitorProjection.baselines.some(entry=>entry.id===baselineResult.resourceId));
 assert.doesNotMatch(JSON.stringify({rollbackDeliveryProjection,rollbackOutboxProjection,rollbackHandoffReviewProjection,rollbackHandoffApproveProjection,rollbackMonitorProjection}),/"[^"]*(?:hash|actorId|requestedBy|sourceWorkspaceId|sourcePackageId|packageApprovalId)"/i);

 await populated.query(`UPDATE enterprise_transcript_workspace_flags SET module_handoffs_enabled=true,direct_delivery_planning_enabled=true,delivery_item_review_enabled=true,monitor_approved_baseline_enabled=true,updated_by=$3 WHERE org_id=$1 AND workspace_id=ANY($2::uuid[])`,[studio.org,[studio.workspace,targetWorkspace],studio.requester]);
 await populated.query('UPDATE enterprise_intelligence_runtime_control SET read_only=true,updated_at=statement_timestamp() WHERE singleton');
 const readOnlyCommands=prCActions.map(action=>makeCommand(studio.requester,targetWorkspace,action,{},`rollback-read-only-${action}`));
 for(const command of readOnlyCommands)await assertBlockedBeforePersistence(command,/ENTERPRISE_DELIVERY_READ_ONLY/);
 const readOnlyDeliveryProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester],packageId:manualResult.resourceId,itemLimit:10})])).rows[0].projection;
 const readOnlyOutboxProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,studio.workspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester]})])).rows[0].projection;
 const readOnlyHandoffReviewProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:handoffOnly,authorizationVersion:handoffOnlyVersion})])).rows[0].projection;
 const readOnlyHandoffApproveProjection=(await populated.query('SELECT public.enterprise_delivery_workspace_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:handoffApproveOnly,authorizationVersion:handoffApproveOnlyVersion})])).rows[0].projection;
 const readOnlyMonitorProjection=(await populated.query('SELECT public.enterprise_monitor_approved_baselines_projection($1,$2,$3::jsonb) projection',[studio.org,targetWorkspace,JSON.stringify({actorId:studio.requester,authorizationVersion:authorizationVersions[studio.requester]})])).rows[0].projection;
 assert.equal(readOnlyDeliveryProjection.readOnly,true);assert.deepEqual(readOnlyDeliveryProjection.actions,[]);assert.ok(readOnlyDeliveryProjection.packages.some(entry=>entry.id===manualResult.resourceId));assert.ok(readOnlyDeliveryProjection.packages.every(entry=>entry.actions.length===0));assert.deepEqual(readOnlyDeliveryProjection.baselineEligibility,[]);assert.deepEqual(readOnlyDeliveryProjection.eligibleStudioArtifacts,[]);
 assert.ok(readOnlyOutboxProjection.handoffs.some(entry=>entry.id===laterHandoff.resourceId&&entry.direction==='outbox'));assert.ok(readOnlyOutboxProjection.handoffs.every(entry=>entry.actions.length===0));
 for(const projection of [readOnlyHandoffReviewProjection,readOnlyHandoffApproveProjection]){assert.equal(projection.readOnly,true);assert.equal(projection.packages.length,0);assert.ok(projection.handoffs.length>0);assert.ok(projection.handoffs.every(entry=>entry.direction==='inbox'&&entry.actions.length===0))}
 assert.deepEqual(readOnlyMonitorProjection.actions,[]);assert.ok(readOnlyMonitorProjection.baselines.some(entry=>entry.id===baselineResult.resourceId));
 assert.doesNotMatch(JSON.stringify({readOnlyDeliveryProjection,readOnlyOutboxProjection,readOnlyHandoffReviewProjection,readOnlyHandoffApproveProjection,readOnlyMonitorProjection}),/"[^"]*(?:hash|actorId|requestedBy|sourceWorkspaceId|sourcePackageId|packageApprovalId)"/i);
 const committedHistoryAfterRollback={
  handoffs:Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_handoffs WHERE org_id=$1',[studio.org])).rows[0].n),
  itemVersions:Number((await populated.query('SELECT count(*) n FROM enterprise_delivery_work_item_versions WHERE org_id=$1 AND workspace_id=$2',[studio.org,targetWorkspace])).rows[0].n),
  baselines:Number((await populated.query("SELECT count(*) n FROM enterprise_monitor_baselines WHERE org_id=$1 AND workspace_id=$2 AND baseline_contract='delivery-monitor-2'",[studio.org,targetWorkspace])).rows[0].n),
 };
 assert.deepEqual(committedHistoryAfterRollback,committedHistoryBeforeRollback);
 emit('DELIVERY-TR-006','PG16-ROLLBACK-FOUR-FLAG-MUTATIONS-FAIL-BEFORE-RECEIPT-OR-EFFECT','rollback-read-only-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,sourcePackage:{id:manualResult.sourcePackageId,hash:manualResult.sourcePackageHash},package:{id:manualResult.resourceId,versionId:manualResult.packageVersionId,preserved:true},item:{versionId:acceptedItems[0].versionId,preserved:true},acceptedSet:{hash:baselineResult.acceptedSetHash,itemCount:2},baseline:{id:baselineResult.resourceId,preserved:true},classification:'not_assessed',rollback:{moduleHandoffsEnabled:false,directDeliveryPlanningEnabled:false,deliveryItemReviewEnabled:false,monitorApprovedBaselineEnabled:false,featureDisabledActions:featureDisabledCommands.map(command=>command.action),globalReadOnlyActions:readOnlyCommands.map(command=>command.action),newReceipts:0,newAttempts:0,newEffects:0,newAuditEvents:0}});
 emit('MONITOR-TR-003','PG16-ROLLBACK-SAFE-PROJECTIONS-REMAIN-READABLE-AND-HASH-FREE','rollback-read-only-pg16',{organizationId:studio.org,workspaceId:targetWorkspace,sourcePackage:{id:manualResult.sourcePackageId,hash:manualResult.sourcePackageHash},package:{id:manualResult.resourceId,versionId:manualResult.packageVersionId,readable:true},item:{historyReadable:true},acceptedSet:{hash:baselineResult.acceptedSetHash,itemCount:2},baseline:{id:baselineResult.resourceId,readable:true,actions:[]},classification:'not_assessed',rollback:{deliveryProjectionReadable:true,monitorProjectionReadable:true,outboxHistoryReadable:true,inboxHistoryReadable:true,handoffOnlyReaders:['delivery.handoff.review','delivery.handoff.approve'],withdrawRequiresCurrentRequestAuthority:true,publicHashesPresent:false,historyPreserved:true}});

 const dirty=await createDatabase(admin,names.dirty);await apply(dirty,baseline);await dirty.query('CREATE TABLE public.enterprise_delivery_source_packages(id uuid)');
 const beforeColumns=Number((await dirty.query("SELECT count(*) n FROM information_schema.columns WHERE table_schema='public' AND table_name='enterprise_transcript_workspace_flags' AND column_name='direct_delivery_planning_enabled'")).rows[0].n);
 await assert.rejects(transaction(dirty,migrationName,await readFile(join('supabase/migrations',migrationName),'utf8')),/PR_C_DIRTY_SCHEMA/);
 const afterColumns=Number((await dirty.query("SELECT count(*) n FROM information_schema.columns WHERE table_schema='public' AND table_name='enterprise_transcript_workspace_flags' AND column_name='direct_delivery_planning_enabled'")).rows[0].n);assert.equal(beforeColumns,0);assert.equal(afterColumns,0);
 emit('DELIVERY-TR-005','DIRTY-PARTIAL-SCHEMA-ATOMIC-REJECTION','dirty-partial-pg16',{migration:migrationName,sourcePackage:{partialSchema:true},package:{mutationCount:0},item:null,acceptedSet:null,baseline:{mutationCount:0},classification:'not_assessed'});

 console.log('Governed Delivery/Monitor PR C PostgreSQL scenarios passed.');
}finally{
 for(const client of clients.reverse())if(client!==admin)await client.end().catch(()=>{});
 if(admin){for(const name of databases.reverse())await admin.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`).catch(error=>{console.error(`cleanup failed ${name}: ${error.message}`);process.exitCode=1});for(const role of roles.reverse())await admin.query(`DROP ROLE IF EXISTS ${role}`).catch(()=>{});await admin.end().catch(()=>{})}
}
