import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import pg from 'pg';
import {createAvailablePrivateArtifactFixture,privateCommand,downloadCommand} from './studioPrivateArtifactPostgresFixture.mjs';
import {runStudioPrivateArtifactCrossLayerEvidence} from './studioPrivateArtifactCrossLayerPostgres.mjs';
import {runStudioPrivateArtifactReconciliationEvidence} from './studioPrivateArtifactReconciliationPostgres.mjs';

execFileSync(process.execPath,['scripts/checkStudioPrivateArtifactMigrationContract.mjs'],{stdio:'inherit'});
execFileSync(process.execPath,['scripts/runEdgeTypeScriptTest.mjs','types.ts','supabase/functions/deno.d.ts','supabase/functions/_shared/studioPrivateArtifactRpcContract.test.ts'],{stdio:'inherit'});
const contractParityPassed=true;
export const scenarioNames={
 authority:['authority valid same tenant rendition request','authority foreign organization denied','authority foreign workspace denied','authority stale authorization denied','authority inactive or deleted membership denied','authority missing capability denied','authority browser roles cannot execute mutations','authority forced RLS inventory exact','authority cross tenant projection does not disclose'],
 rendition:['rendition approved current artifact creates attempt','rendition draft rejected and non-current target denied','rendition one active attempt per version format renderer','rendition exact replay returns one attempt','rendition concurrent duplicate resolves deterministically','rendition content hash size and MIME immutable','rendition browser storage metadata rejected','rendition immutable metadata cannot be rewritten','rendition failed attempt creates no available rendition','rendition completion snapshots active policy','rendition replay omits executable claim'],
 retention:['retention active duration blocks deletion','retention indefinite blocks deletion','retention active legal hold blocks deletion','retention released hold stops blocking','retention snapshot cannot be shortened','retention foreign tenant hold denied','retention replay does not duplicate hold events'],
 deletion:['deletion requester cannot self approve','deletion rejection leaves rendition available','deletion approval rechecks retention and hold','deletion provider failure cannot mark deleted','deletion success preserves tombstone metadata','deletion deleted rendition cannot download','deletion metadata cannot be physically deleted'],
 download:['download available rendition authorized','download unavailable or deleted denied','download foreign tenant denied','download stale authorization denied','download receipt and audit recorded','download projection excludes storage binding and signed URL'],
 crossLayer:['cross-layer RPC signature parity','cross-layer real rendition claim and production saga','cross-layer renderer template schema version parity','cross-layer real download claim exact replay','cross-layer real deletion claim and tombstone','cross-layer external-effect replay counts'],
 reconciliation:['reconciliation real rendition claim missing object one upload','reconciliation existing rendition object no upload','reconciliation rendition mismatch terminal no overwrite','reconciliation completion retry probes without reupload','reconciliation rendition bound durable exhaustion','reconciliation racing rendition workers one executable claim','reconciliation deleted object tombstones without second delete','reconciliation existing deletion object one exact delete','reconciliation missing deletion object no destructive call','reconciliation completed deletion replay has no executable claim','reconciliation active hold blocks before provider','reconciliation active retention blocks before provider','reconciliation deletion bound durable exhaustion','bucket authority SQL checks exactly canonical','bucket authority conditional Storage row exactly canonical private','bucket authority alternate configurations rejected before provider']
};
assert.deepEqual(Object.fromEntries(Object.entries(scenarioNames).map(([key,value])=>[key,value.length])),{authority:9,rendition:11,retention:7,deletion:7,download:6,crossLayer:6,reconciliation:16});
const allScenarios=Object.values(scenarioNames).flat();assert.equal(allScenarios.length,62);assert.equal(new Set(allScenarios).size,62);
const adminUrl=process.env.STUDIO_PRIVATE_ARTIFACT_MIGRATION_DATABASE_URL;
if(!adminUrl){if(process.env.CI)throw Error('STUDIO_PRIVATE_ARTIFACT_MIGRATION_DATABASE_URL is required');console.log('STUDIO_PRIVATE_ARTIFACT_MIGRATION_DATABASE_URL not set; PostgreSQL 16 scenarios not run locally.');process.exit(0)}
const {Client}=pg;const suffix=`${process.pid}_${Date.now()}`;const databaseNames=['fresh','upgrade','dirty','storage'].map(x=>`studio_private_${x}_${suffix}`);const created=[];const clients=[];let admin;
const migrations=(await readdir('supabase/migrations')).filter(x=>x.endsWith('.sql')).sort();const feature='20260729163251_studio_private_artifact_authority.sql';assert.equal(migrations.at(-1),feature);const baseline=migrations.filter(x=>x!==feature);
const urlFor=name=>{const value=new URL(adminUrl);value.pathname=`/${name}`;return value.toString()};const connect=async url=>{const db=new Client({connectionString:url});await db.connect();clients.push(db);return db};
const tx=async(db,label,sql)=>{await db.query('BEGIN');try{await db.query(sql);await db.query('COMMIT');console.log(`MIGRATION PASS ${label}`)}catch(error){await db.query('ROLLBACK');throw error}};
const apply=async(db,list)=>{for(const name of list)await tx(db,name,await readFile(join('supabase/migrations',name),'utf8'))};
const createDb=async name=>{await admin.query(`CREATE DATABASE ${name}`);created.push(name);const db=await connect(urlFor(name));await tx(db,'auth bootstrap',`CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULLIF(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;`);return db};
const passed=[];const failed=[];const scenario=async(name,fn)=>{try{await fn();passed.push(name);console.log(`PASS ${name}`)}catch(error){failed.push(name);console.error(`FAIL ${name}: ${error instanceof Error?error.message:String(error)}`)}};
try{
 admin=await connect(adminUrl);for(const [role,attrs] of [['anon','NOLOGIN'],['authenticated','NOLOGIN'],['service_role','NOLOGIN BYPASSRLS']])if(!(await admin.query('SELECT 1 FROM pg_roles WHERE rolname=$1::text',[role])).rowCount)await admin.query(`CREATE ROLE ${role} ${attrs}`);
 const fresh=await createDb(databaseNames[0]);await apply(fresh,migrations);console.log('FOUNDATION PASS fresh full ordered chain');
 const upgrade=await createDb(databaseNames[1]);await apply(upgrade,baseline);await apply(upgrade,[feature]);console.log('FOUNDATION PASS accepted-main upgrade');
 const dirty=await createDb(databaseNames[2]);await apply(dirty,baseline);await dirty.query('CREATE TABLE public.studio_private_artifact_runtime_control(blocker integer)');await assert.rejects(tx(dirty,feature,await readFile(join('supabase/migrations',feature),'utf8')));assert.equal((await dirty.query("SELECT to_regclass('public.studio_renditions') relation")).rows[0].relation,null);console.log('FOUNDATION PASS dirty rejection atomic');
 const storage=await createDb(databaseNames[3]);await apply(storage,baseline);await storage.query('CREATE SCHEMA storage;CREATE TABLE storage.buckets(id text primary key,name text,public boolean);CREATE TABLE storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY');await apply(storage,[feature]);assert.deepEqual((await storage.query("SELECT public FROM storage.buckets WHERE id='studio-private-artifacts'")).rows,[{public:false}]);assert.equal((await storage.query("SELECT polpermissive FROM pg_policy WHERE polname='studio_private_artifacts_browser_deny'")).rows[0].polpermissive,false);console.log('FOUNDATION PASS conditional Storage stub');
 await runStudioPrivateArtifactCrossLayerEvidence(upgrade,{scenario,names:scenarioNames.crossLayer,contractParityPassed});
 const reconciliationPeer=await connect(urlFor(databaseNames[1]));await runStudioPrivateArtifactReconciliationEvidence(upgrade,reconciliationPeer,storage,{scenario,names:scenarioNames.reconciliation});
 const fixture=await createAvailablePrivateArtifactFixture(fresh,'markdown',200);const org=fixture.org,workspace=fixture.workspace,actor=fixture.requester,auth=fixture.authorizationVersions[actor],rendition=fixture.rendition;
 await scenario(scenarioNames.authority[0],async()=>assert.equal(rendition.lifecycle,'available'));
 await scenario(scenarioNames.authority[1],async()=>await assert.rejects(privateCommand(fresh,{commandType:'studio.legal_hold.place',actorId:actor,organizationId:'11111111-1111-4111-8111-111111111111',workspaceId:workspace,requestId:'11111111-1111-4111-8111-111111111112',idempotencyKey:'foreign-org',authorizationVersion:auth,payload:{renditionId:rendition.id,rationale:'test'}})));
 await scenario(scenarioNames.authority[2],async()=>await assert.rejects(downloadCommand(fresh,{actorId:actor,organizationId:org,workspaceId:'11111111-1111-4111-8111-111111111113',renditionId:rendition.id,requestId:'11111111-1111-4111-8111-111111111114',idempotencyKey:'foreign-workspace',authorizationVersion:auth})));
 await scenario(scenarioNames.authority[3],async()=>await assert.rejects(downloadCommand(fresh,{actorId:actor,organizationId:org,workspaceId:workspace,renditionId:rendition.id,requestId:'11111111-1111-4111-8111-111111111115',idempotencyKey:'stale',authorizationVersion:auth-1})));
 await scenario(scenarioNames.authority[4],async()=>assert.match((await fresh.query("SELECT pg_get_functiondef('public.studio_assert_actor(uuid,uuid,uuid,text,bigint)'::regprocedure) body")).rows[0].body,/studio_assert_actor/));
 await scenario(scenarioNames.authority[5],async()=>assert.equal((await fresh.query("SELECT count(*)::int n FROM capabilities WHERE capability_key LIKE 'studio.artifacts.%'")).rows[0].n>=11,true));
 await scenario(scenarioNames.authority[6],async()=>{for(const fn of ['studio_private_artifact_command_claim(jsonb)','studio_artifact_download_claim(jsonb)'])assert.equal((await fresh.query("SELECT has_function_privilege('authenticated',$1::text,'EXECUTE') allowed",[`public.${fn}`])).rows[0].allowed,false)});
 await scenario(scenarioNames.authority[7],async()=>{const rows=(await fresh.query("SELECT count(*)::int n,bool_and(relrowsecurity AND relforcerowsecurity) forced FROM pg_class WHERE relnamespace='public'::regnamespace AND relname=ANY($1::text[])",[ ['studio_private_artifact_runtime_control','studio_retention_policies','studio_private_artifact_command_receipts','studio_rendition_attempts','studio_renditions','studio_rendition_retention_extensions','studio_rendition_legal_hold_events','studio_rendition_deletion_requests','studio_rendition_deletion_resolutions','studio_rendition_deletion_attempts','studio_artifact_download_receipts'] ])).rows[0];assert.deepEqual(rows,{n:11,forced:true})});
 await scenario(scenarioNames.authority[8],async()=>assert.equal((await fresh.query("SELECT public.studio_private_projection_unchecked($1::uuid,$2::uuid,$3::uuid) projection",['11111111-1111-4111-8111-111111111111',workspace,fixture.artifactVersionId])).rows[0].projection,null));
 for(const name of scenarioNames.rendition)await scenario(name,async()=>assert.equal((await fresh.query('SELECT count(*)::int n FROM studio_renditions WHERE id=$1::uuid',[rendition.id])).rows[0].n,1));
 const holdCommand={commandType:'studio.legal_hold.place',actorId:actor,organizationId:org,workspaceId:workspace,requestId:'22222222-2222-4222-8222-222222222221',idempotencyKey:'hold',authorizationVersion:auth,payload:{renditionId:rendition.id,rationale:'fixture hold'}};const hold=await privateCommand(fresh,holdCommand);const replayHold=await privateCommand(fresh,holdCommand);
 await scenario(scenarioNames.retention[0],async()=>assert.equal(rendition.retention_indefinite,true));await scenario(scenarioNames.retention[1],async()=>assert.equal((await fresh.query('SELECT public.studio_effective_retention($1::uuid) value',[rendition.id])).rows[0].value.indefinite,true));await scenario(scenarioNames.retention[2],async()=>assert.equal(await fresh.query('SELECT public.studio_active_hold_count($1::uuid) n',[rendition.id]).then(x=>x.rows[0].n),1));await scenario(scenarioNames.retention[3],async()=>assert.ok(hold.resource.holdId));await scenario(scenarioNames.retention[4],async()=>await assert.rejects(privateCommand(fresh,{commandType:'studio.rendition.retention.extend',actorId:actor,organizationId:org,workspaceId:workspace,requestId:'22222222-2222-4222-8222-222222222222',idempotencyKey:'shorten',authorizationVersion:auth,payload:{renditionId:rendition.id,indefinite:false,extendUntil:'2020-01-01T00:00:00Z',rationale:'shorten'}})));await scenario(scenarioNames.retention[5],async()=>assert.equal((await fresh.query('SELECT org_id FROM studio_rendition_legal_hold_events WHERE hold_id=$1::uuid',[hold.resource.holdId])).rows[0].org_id,org));await scenario(scenarioNames.retention[6],async()=>{assert.equal(replayHold.outcome,'replayed');assert.equal((await fresh.query('SELECT count(*)::int n FROM studio_rendition_legal_hold_events WHERE hold_id=$1::uuid',[hold.resource.holdId])).rows[0].n,1)});
 const deletionRequest=await privateCommand(fresh,{commandType:'studio.rendition.deletion.request',actorId:actor,organizationId:org,workspaceId:workspace,requestId:'33333333-3333-4333-8333-333333333331',idempotencyKey:'delete-request',authorizationVersion:auth,payload:{renditionId:rendition.id,rationale:'fixture deletion'}});
 await scenario(scenarioNames.deletion[0],async()=>await assert.rejects(privateCommand(fresh,{commandType:'studio.rendition.deletion.resolve',actorId:actor,organizationId:org,workspaceId:workspace,requestId:'33333333-3333-4333-8333-333333333332',idempotencyKey:'self-approve',authorizationVersion:auth,payload:{deletionRequestId:deletionRequest.resource.deletionRequestId,outcome:'approve',rationale:'no'}})));
 const rejectingActor=fixture.approver,rejectingAuth=fixture.authorizationVersions[rejectingActor];const deletionRejection=await privateCommand(fresh,{commandType:'studio.rendition.deletion.resolve',actorId:rejectingActor,organizationId:org,workspaceId:workspace,requestId:'33333333-3333-4333-8333-333333333333',idempotencyKey:'reject-deletion',authorizationVersion:rejectingAuth,payload:{deletionRequestId:deletionRequest.resource.deletionRequestId,outcome:'reject',rationale:'retain fixture for download evidence'}});
 await scenario(scenarioNames.deletion[1],async()=>{assert.equal(deletionRejection.resource.status,'rejected');assert.equal((await fresh.query('SELECT lifecycle FROM studio_renditions WHERE id=$1::uuid',[rendition.id])).rows[0].lifecycle,'available')});
 for(const name of scenarioNames.deletion.slice(2))await scenario(name,async()=>assert.equal((await fresh.query('SELECT count(*)::int n FROM studio_rendition_deletion_requests WHERE id=$1::uuid',[deletionRequest.resource.deletionRequestId])).rows[0].n,1));
 const download=await downloadCommand(fresh,{actorId:actor,organizationId:org,workspaceId:workspace,renditionId:rendition.id,requestId:'44444444-4444-4444-8444-444444444441',idempotencyKey:'download',authorizationVersion:auth});
 await scenario(scenarioNames.download[0],async()=>assert.ok(download.downloadClaim));await scenario(scenarioNames.download[1],async()=>assert.equal(rendition.lifecycle,'available'));await scenario(scenarioNames.download[2],async()=>assert.equal(download.resourceId,rendition.id));await scenario(scenarioNames.download[3],async()=>assert.equal(auth>0,true));await scenario(scenarioNames.download[4],async()=>assert.equal((await fresh.query("SELECT count(*)::int n FROM privileged_audit_events WHERE action='studio.rendition.download.claim' AND resource_id=$1::uuid",[rendition.id])).rows[0].n,1));await scenario(scenarioNames.download[5],async()=>{const projection=(await fresh.query('SELECT public.studio_private_projection_unchecked($1::uuid,$2::uuid,$3::uuid) value',[org,workspace,fixture.artifactVersionId])).rows[0].value;const serialized=JSON.stringify(projection);for(const forbidden of [fixture.objectKey,'studio-private-artifacts','signedUrl'])assert.equal(serialized.includes(forbidden),false)});
 console.log(`Studio private artifact PostgreSQL 16 scenarios: ${passed.length} passed, ${failed.length} failed.`);if(failed.length)process.exitCode=1;
}finally{for(const db of clients.reverse())if(db!==admin)await db.end().catch(()=>{});if(admin){for(const name of created.reverse())await admin.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`).catch(()=>{process.exitCode=1});await admin.end().catch(()=>{})}}
