import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {existsSync,lstatSync,mkdirSync,realpathSync,rmSync,writeFileSync} from 'node:fs';
import {readFile,readdir} from 'node:fs/promises';
import {basename,dirname,join,resolve} from 'node:path';
import pg from 'pg';
import {createEnterpriseIntelligenceFixture} from './enterpriseIntelligencePostgresFixture.mjs';
import {validateAssessImportDatabaseUrl} from './assessImportValidationContract.mjs';
import {approvedFullChainTip} from './prCMigrationTailContract.mjs';

const adminUrl=validateAssessImportDatabaseUrl(process.env.ASSESS_DOCUMENT_MAPPING_POSTGRES_ADMIN_URL);

const parsedAdmin=new URL(adminUrl);
assert.ok(['127.0.0.1','localhost','::1'].includes(parsedAdmin.hostname),'Only a loopback PostgreSQL admin endpoint is permitted.');
assert.equal(parsedAdmin.pathname,'/postgres','The PostgreSQL harness requires the disposable postgres admin database.');
const {Client}=pg;
const migrations=(await readdir('supabase/migrations')).filter(name=>name.endsWith('.sql')).sort();
const expectedFullChainTip=approvedFullChainTip(migrations);
const feature='20260916083814_assess_supporting_document_mapping.sql';
const finalIdentity='20260916151050_assess_document_mapping_identity_convergence.sql';
assert.equal(migrations.at(-1),finalIdentity,'Assess mapping must end at the exact approved identity-convergence tip.');
assert.equal(migrations.indexOf(finalIdentity),migrations.indexOf(feature)+1,'Identity convergence must immediately follow the frozen mapping migration.');
const databaseName=`assess_map_${process.pid}_${Date.now()}`;
assert.match(databaseName,/^[a-z0-9_]+$/);
const clients=[];
const urlFor=name=>{const value=new URL(adminUrl);value.pathname=`/${name}`;return value.toString()};
const connect=async connectionString=>{const client=new Client({connectionString});await client.connect();clients.push(client);return client};
const transaction=async(client,label,sql)=>{await client.query('BEGIN');try{await client.query(sql);await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw new Error(`${label}: ${error instanceof Error?error.message:String(error)}`)}};
const sha=value=>createHash('sha256').update(value).digest('hex');
const uuid=n=>`94000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const json=value=>JSON.stringify(value);
const passed=[];
const pass=(testId,detail)=>{passed.push(testId);console.log(`ASSESS_DOCUMENT_MAPPING_PG_ASSERTION ${JSON.stringify({testId,result:'passed',detail})}`)};
const expectDatabaseError=async(operation,pattern)=>{try{await operation();assert.fail(`Expected ${pattern}`)}catch(error){assert.match(error instanceof Error?error.message:String(error),pattern)}};
const runNativeParser=payload=>{
  const ownedRoot=resolve('output/test-runs/assess-mapping-native');mkdirSync(ownedRoot,{recursive:true});
  const payloadPath=join(ownedRoot,`payload-${process.pid}-${Date.now()}.json`);assert.equal(existsSync(payloadPath),false);writeFileSync(payloadPath,JSON.stringify(payload));
  try{execFileSync(process.execPath,['scripts/runEnterpriseIntelligenceTest.mjs','supabase/functions/_shared/assessV2Command.ts','scripts/testAssessSupportingDocumentMappingNativeParser.ts'],{stdio:'inherit',env:{...process.env,ASSESS_MAPPING_NATIVE_PAYLOAD_PATH:payloadPath}})}
  finally{if(existsSync(payloadPath)){const resolvedPayload=realpathSync(resolve(payloadPath));assert.equal(lstatSync(payloadPath).isSymbolicLink(),false);assert.equal(dirname(resolvedPayload),realpathSync(ownedRoot));assert.match(basename(resolvedPayload),/^payload-[0-9]+-[0-9]+\.json$/);rmSync(payloadPath)}}
};

let admin;let database;let fixture;
try{
  admin=await connect(adminUrl);
  const version=Number((await admin.query("SELECT current_setting('server_version_num')::int version")).rows[0].version);
  assert.ok(version>=160000&&version<170000,'The focused harness requires PostgreSQL 16.');
  assert.equal((await admin.query('SELECT 1 FROM pg_database WHERE datname=$1',[databaseName])).rowCount,0,`Refusing to overwrite ${databaseName}`);
  for(const [role,attributes] of [['anon','NOLOGIN'],['authenticated','NOLOGIN'],['service_role','NOLOGIN BYPASSRLS']])if(!(await admin.query('SELECT 1 FROM pg_roles WHERE rolname=$1',[role])).rowCount)await admin.query(`CREATE ROLE ${role} ${attributes}`);
  await admin.query(`CREATE DATABASE ${databaseName}`);
  database=await connect(urlFor(databaseName));
  await transaction(database,'Supabase auth bootstrap',`
    CREATE SCHEMA auth;
    CREATE TABLE auth.users(id uuid primary key);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULLIF(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
    GRANT USAGE ON SCHEMA auth TO authenticated;
    GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;
  `);
  for(const name of migrations){
    if(name===feature){
      fixture=await createEnterpriseIntelligenceFixture(database);
      await database.query(`INSERT INTO public.enterprise_transcript_workspace_flags(org_id,workspace_id,transcript_source_sets_enabled,assess_multisource_apply_enabled,unified_byok_gateway_enabled,governed_journeys_enabled,updated_by) VALUES($1,$2,true,true,true,true,$3)`,[fixture.org,fixture.workspace,fixture.requester]);
    }
    await transaction(database,name,await readFile(join('supabase/migrations',name),'utf8'));
  }
  assert.ok(fixture);
  assert.equal((await database.query('SELECT migration_tip FROM public.hosted_pilot_environment_identity WHERE singleton IS TRUE')).rows[0].migration_tip,expectedFullChainTip);
  assert.equal((await database.query(`SELECT pg_get_expr(conbin,conrelid,false) expression FROM pg_constraint
    WHERE conrelid='public.hosted_pilot_environment_identity'::regclass
      AND conname='hosted_pilot_environment_identity_migration_tip_check'`)).rows[0].expression,
    `(migration_tip = '${expectedFullChainTip}'::text)`);
  const upgradedFlag=(await database.query('SELECT assess_document_mapping_enabled FROM public.enterprise_transcript_workspace_flags WHERE org_id=$1 AND workspace_id=$2',[fixture.org,fixture.workspace])).rows[0];
  assert.equal(upgradedFlag.assess_document_mapping_enabled,false);
  pass('MAP-PG-001-populated-default-off','pre-existing workspace remains disabled after forward migration');

  await database.query(`INSERT INTO public.role_capabilities(role_id,capability_key) SELECT $1,unnest($2::text[]) ON CONFLICT DO NOTHING`,[fixture.routeRole,['assess.v2.read','assess.v2.draft.write','evidence.write','evidence.review','transcript.assess.apply','transcript.sources.read']]);
  const authorizationVersion=Number((await database.query('SELECT version FROM public.authorization_versions WHERE org_id=$1 AND user_id=$2',[fixture.org,fixture.requester])).rows[0].version);
  assert.ok(authorizationVersion>0);
  let sequence=1000;
  const nextUuid=()=>uuid(sequence++);
  const caseId=nextUuid(),versionId=nextUuid(),primitiveId=nextUuid(),assetId=nextUuid(),interactionId=nextUuid(),oldEvidenceId=nextUuid();
  const fact=(fieldId,value,evidenceIds=[])=>({fieldId,value,status:value===null?'unknown':'known',evidenceIds,source:'user'});
  const agentNecessity={irreducibleAmbiguity:fact('agent.irreducibleAmbiguity',null),adaptiveNextStep:fact('agent.adaptiveNextStep',null),toolOrPathSelection:fact('agent.toolOrPathSelection',null),incrementalValue:fact('agent.incrementalValue',null),controllable:fact('agent.controllable',null)};
  const primitive={id:primitiveId,type:'Investigate',name:'Manual review',description:'Review uncertain requests',inputs:[],outputs:[],volumeShare:null,manualEffort:null,rules:[],exceptionIds:[],evidenceIds:[oldEvidenceId],facts:{ambiguityCharacterized:fact('ambiguityCharacterized',null,[oldEvidenceId])},businessDisposition:'Human-Led'};
  const asset={id:assetId,name:'Case system',strategicLifespan:'unknown',technicalHealth:'unknown',businessCriticality:'high',ownershipModel:'shared',vendorRoadmap:'unknown',operatingStability:'stable',accountableOwner:null,evidenceIds:[]};
  const interaction={id:interactionId,assetId,primitiveId,operationName:'Read case',mode:'read',dataClassification:'Internal',facts:{interfaceAvailable:null,operationCovered:null,apiDocumented:null,machineIdentity:null,leastPrivilege:null,dataQuality:null,dataClassified:null,auditable:null,idempotent:null,compensatable:null,rollback:null,testEnvironment:null,monitored:null,uiStable:null,eventSemantics:null,errorContract:null,capacityKnown:null,accountableOwner:null,highImpact:false,financialAction:false,untrustedContentWithTools:false},evidenceIds:[]};
  const sourceSnapshot={fixture:'mapping-source-snapshot'};const importedFacts=[fact('fixture.imported','retained')];
  await database.query(`INSERT INTO public.assess_v2_cases(id,org_id,workspace_id,process_id,owner_id,status,version,head_version_id) VALUES($1,$2,$3,$4,$5,'draft',1,NULL)`,[caseId,fixture.org,fixture.workspace,fixture.process,fixture.requester]);
  await database.query(`INSERT INTO public.assess_v2_case_versions(id,case_id,org_id,workspace_id,version,name,description,agent_necessity,source_kind,source_snapshot,imported_facts,created_by) VALUES($1,$2,$3,$4,1,'Mapping fixture','Manual baseline description',$5::jsonb,'create',$6::jsonb,$7::jsonb,$8)`,[versionId,caseId,fixture.org,fixture.workspace,json(agentNecessity),json(sourceSnapshot),json(importedFacts),fixture.requester]);
  await database.query('UPDATE public.assess_v2_cases SET head_version_id=$1 WHERE id=$2',[versionId,caseId]);
  await database.query('INSERT INTO public.assess_v2_primitives(id,version_id,case_id,org_id,workspace_id,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[primitiveId,versionId,caseId,fixture.org,fixture.workspace,json(primitive)]);
  await database.query('INSERT INTO public.assess_v2_application_assets(id,version_id,case_id,org_id,workspace_id,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[assetId,versionId,caseId,fixture.org,fixture.workspace,json(asset)]);
  await database.query('INSERT INTO public.assess_v2_application_interactions(id,version_id,case_id,org_id,workspace_id,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[interactionId,versionId,caseId,fixture.org,fixture.workspace,json(interaction)]);
  await database.query('INSERT INTO public.assess_v2_evidence_links(id,version_id,case_id,org_id,workspace_id,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[oldEvidenceId,versionId,caseId,fixture.org,fixture.workspace,json({id:oldEvidenceId,claimIds:['primitive.ambiguityCharacterized'],sourceType:'document',status:'submitted',validated:false})]);

  const selected=[fixture.sources[0],fixture.sources[2]];const setId=nextUuid(),setVersionId=nextUuid(),bundleId=nextUuid(),bundleVersionId=nextUuid();
  await database.query(`INSERT INTO public.enterprise_source_sets(id,org_id,workspace_id,owner_module,display_label,description,current_version,status,created_by) VALUES($1,$2,$3,'assess','Mapping sources','Synthetic supporting documents',1,'locked',$4)`,[setId,fixture.org,fixture.workspace,fixture.requester]);
  await database.query(`INSERT INTO public.enterprise_source_set_versions(id,source_set_id,org_id,workspace_id,version,purpose,manifest_hash,source_count,extracted_character_count,status,created_by) VALUES($1,$2,$3,$4,1,'Synthetic mapping verification',$5,2,100,'locked',$6)`,[setVersionId,setId,fixture.org,fixture.workspace,sha('set'),fixture.requester]);
  for(let index=0;index<selected.length;index+=1){const source=selected[index];const row=(await database.query('SELECT content_hash,extracted_text_hash,extracted_character_count FROM public.enterprise_evidence_source_versions WHERE id=$1',[source.sourceVersionId])).rows[0];await database.query(`INSERT INTO public.enterprise_source_set_version_items(source_set_version_id,source_set_id,source_version_id,source_id,org_id,workspace_id,ordinal,semantic_role,content_hash,extracted_text_hash,extracted_character_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[setVersionId,setId,source.sourceVersionId,source.sourceId,fixture.org,fixture.workspace,index+1,index?'contradictory':'primary',row.content_hash,row.extracted_text_hash,Number(row.extracted_character_count)]);}
  await database.query(`INSERT INTO public.enterprise_module_input_bundles(id,org_id,workspace_id,owner_module,current_version,created_by) VALUES($1,$2,$3,'assess',1,$4)`,[bundleId,fixture.org,fixture.workspace,fixture.requester]);
  await database.query(`INSERT INTO public.enterprise_module_input_bundle_versions(id,input_bundle_id,org_id,workspace_id,version,bundle_hash,status,created_by) VALUES($1,$2,$3,$4,1,$5,'locked',$6)`,[bundleVersionId,bundleId,fixture.org,fixture.workspace,sha('bundle'),fixture.requester]);
  await database.query(`INSERT INTO public.enterprise_module_input_bundle_items(input_bundle_version_id,input_bundle_id,org_id,workspace_id,ordinal,item_kind,source_set_version_id,source_set_id,resource_hash,declared_purpose) VALUES($1,$2,$3,$4,1,'source_set',$5,$6,$7,'Assess mapping')`,[bundleVersionId,bundleId,fixture.org,fixture.workspace,setVersionId,setId,sha('set')]);
  const routeId=nextUuid();await database.query(`INSERT INTO public.enterprise_ai_capability_routes(id,org_id,workspace_id,provider_config_id,capability,model,enabled,allowed_roles,created_by,updated_by) VALUES($1,$2,$3,$4,'assess.evidence.extract','fixture-model',true,ARRAY[$5::text],$6,$6)`,[routeId,fixture.org,fixture.workspace,fixture.provider,fixture.routeRole,fixture.requester]);

  const receipt=async(commandType,label)=>{const requestId=nextUuid(),token=nextUuid();return (await database.query(`SELECT (public.enterprise_ai_claim_command($1,$2,$3,$4,$5,$6,$7,NULL,$8)).*`,[fixture.requester,fixture.org,fixture.workspace,commandType,`mapping-${label}`,requestId,sha(`${commandType}:${label}`),token])).rows[0]};
  const reclaimReceipt=async(commandType,label)=>{const requestId=nextUuid(),token=nextUuid();return (await database.query(`SELECT (public.enterprise_ai_claim_command($1,$2,$3,$4,$5,$6,$7,NULL,$8)).*`,[fixture.requester,fixture.org,fixture.workspace,commandType,`mapping-${label}`,requestId,sha(`${commandType}:${label}`),token])).rows[0]};
  const sourceBindings=selected.map((source,index)=>({sourceSetId:setId,sourceSetVersionId:setVersionId,expectedSourceSetVersion:1,sourceId:source.sourceId,sourceVersionId:source.sourceVersionId,parserVersion:index?'spreadsheet-grid-v1':'normalized-text:v1',normalizedHash:sha(`normalized-${index}`),extractedByteCount:40+index,sheetCount:index?1:0,cellCount:index?3:0,warnings:index?['blank_rows_omitted']:[]}));
  const target=(selectorId,values)=>({selectorId,catalogId:values.catalogId,caseId,caseVersion:1,assessSchemaVersion:'assess-v2-schema-2026-07',currentValueHash:'f'.repeat(64),...values});
  const claimRun=async({runId,catalogId,targets,claimReceipt})=>(await database.query(`SELECT public.enterprise_claim_assess_document_mapping_run_v1($1,$2,$3,1,'assess-v2-schema-2026-07',$4,$5::jsonb,$6,$7,1,$8::jsonb,$9,$10,'openai','fixture-model','assess-supporting-document-map-v1',$11,$12,$13,$14,$15,$16,$17) result`,[runId,catalogId,caseId,'f'.repeat(64),json(targets),bundleId,bundleVersionId,json(sourceBindings),routeId,fixture.provider,fixture.requester,fixture.org,fixture.workspace,authorizationVersion,claimReceipt.id,claimReceipt.execution_token,claimReceipt.execution_fence])).rows[0].result;

  const disabledReceipt=await receipt('assess.document-map.analyze','disabled');const disabledCatalog=nextUuid();
  await expectDatabaseError(()=>claimRun({runId:nextUuid(),catalogId:disabledCatalog,targets:[target(nextUuid(),{catalogId:disabledCatalog,targetKind:'evidence_only',operation:'link_evidence',fieldId:'evidence',label:'Evidence',contextLabel:'Fixture',valueType:'evidence',currentValue:null,manual:false})],claimReceipt:disabledReceipt}),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_FEATURE_DISABLED/);
  assert.equal(Number((await database.query('SELECT count(*) n FROM public.enterprise_assess_document_mapping_runs')).rows[0].n),0);
  await database.query('UPDATE public.enterprise_transcript_workspace_flags SET assess_document_mapping_enabled=true WHERE org_id=$1 AND workspace_id=$2',[fixture.org,fixture.workspace]);
  pass('MAP-PG-002-default-off-zero-effects','disabled claim rejects before mapping persistence');

  const zeroRun=nextUuid(),zeroCatalog=nextUuid(),zeroReceipt=await receipt('assess.document-map.analyze','zero');const zeroTargets=[target(nextUuid(),{catalogId:zeroCatalog,targetKind:'evidence_only',operation:'link_evidence',fieldId:'evidence',label:'Evidence only',contextLabel:'Fixture',valueType:'evidence',currentValue:null,manual:false})];
  const zeroClaim=await claimRun({runId:zeroRun,catalogId:zeroCatalog,targets:zeroTargets,claimReceipt:zeroReceipt});assert.notEqual(zeroClaim.catalogHash,'f'.repeat(64));
  const zeroAnalyzed=zeroClaim.sourceBindings.map(item=>({sourceId:item.sourceId,sourceVersionId:item.sourceVersionId,parserVersion:item.parserVersion,extractedByteCount:item.extractedByteCount,sheetCount:item.sheetCount,cellCount:item.cellCount,warnings:item.warnings}));
  const zeroSafe={resourceId:zeroRun,runId:zeroRun,catalogId:zeroCatalog,catalogHash:zeroClaim.catalogHash,targetCount:1,sourceCount:2,proposalCount:0,sourceBindings:zeroClaim.sourceBindings,analyzedSources:zeroAnalyzed,warnings:[`${selected[1].sourceVersionId}:blank_rows_omitted`]};
  await database.query(`SELECT public.enterprise_stage_assess_document_mapping_result_v1($1,$2,'[]'::jsonb,$3::jsonb,$4,0,0,1,$5,$6,$7,$8)`,[zeroRun,zeroCatalog,json(zeroSafe),sha('zero-output'),sha('zero-stage'),zeroReceipt.id,zeroReceipt.execution_token,zeroReceipt.execution_fence]);
  const zeroCommit=(await database.query('SELECT public.enterprise_commit_assess_document_mapping_result_v1($1,$2,$3,$4) result',[zeroRun,zeroReceipt.id,zeroReceipt.execution_token,zeroReceipt.execution_fence])).rows[0].result;assert.equal(zeroCommit.proposalCount,0);
  pass('MAP-PG-003-zero-proposals','grounded zero-candidate provider output commits without fabrication');

  const recoveryRun=nextUuid(),recoveryCatalog=nextUuid(),recoveryReceipt=await receipt('assess.document-map.analyze','staged-recovery');const recoveryTargets=[target(nextUuid(),{catalogId:recoveryCatalog,targetKind:'evidence_only',operation:'link_evidence',fieldId:'evidence',label:'Recovery evidence',contextLabel:'Fixture',valueType:'evidence',currentValue:null,manual:false})];
  const recoveryClaim=await claimRun({runId:recoveryRun,catalogId:recoveryCatalog,targets:recoveryTargets,claimReceipt:recoveryReceipt});const recoveryAnalyzed=recoveryClaim.sourceBindings.map(item=>({sourceId:item.sourceId,sourceVersionId:item.sourceVersionId,parserVersion:item.parserVersion,extractedByteCount:item.extractedByteCount,sheetCount:item.sheetCount,cellCount:item.cellCount,warnings:item.warnings}));const recoverySafe={resourceId:recoveryRun,runId:recoveryRun,catalogId:recoveryCatalog,catalogHash:recoveryClaim.catalogHash,targetCount:1,sourceCount:2,proposalCount:0,sourceBindings:recoveryClaim.sourceBindings,analyzedSources:recoveryAnalyzed,warnings:[`${selected[1].sourceVersionId}:blank_rows_omitted`]};
  await database.query(`SELECT public.enterprise_stage_assess_document_mapping_result_v1($1,$2,'[]'::jsonb,$3::jsonb,$4,0,0,1,$5,$6,$7,$8)`,[recoveryRun,recoveryCatalog,json(recoverySafe),sha('recovery-output'),sha('recovery-stage'),recoveryReceipt.id,recoveryReceipt.execution_token,recoveryReceipt.execution_fence]);
  await database.query(`UPDATE public.enterprise_ai_command_receipts SET lease_expires_at=statement_timestamp()-interval '1 second' WHERE id=$1`,[recoveryReceipt.id]);const reacquired=await reclaimReceipt('assess.document-map.analyze','staged-recovery');assert.equal(Number(reacquired.execution_fence),Number(recoveryReceipt.execution_fence)+1);const recoveryReplay=await claimRun({runId:recoveryRun,catalogId:recoveryCatalog,targets:recoveryTargets,claimReceipt:reacquired});assert.equal(recoveryReplay.recoveryMode,'finalize_staged');assert.equal(recoveryReplay.ownsExecution,false);assert.deepEqual(recoveryReplay.targets,recoveryClaim.targets);assert.deepEqual(recoveryReplay.sourceBindings,recoveryClaim.sourceBindings);const recovered=(await database.query('SELECT public.enterprise_commit_assess_document_mapping_result_v1($1,$2,$3,$4) result',[recoveryRun,reacquired.id,reacquired.execution_token,reacquired.execution_fence])).rows[0].result;assert.equal(recovered.status,'committed');assert.equal(Number((await database.query('SELECT count(*) n FROM public.enterprise_ai_effect_journal WHERE receipt_id=$1',[reacquired.id])).rows[0].n),1);pass('MAP-PG-010-staged-lease-recovery','expired staged lease resumes exact persisted targets and sources under the re-acquired fence without provider replay');

  const failedRun=nextUuid(),failedCatalog=nextUuid(),failedReceipt=await receipt('assess.document-map.analyze','terminal-failure');const failedTargets=[target(nextUuid(),{catalogId:failedCatalog,targetKind:'evidence_only',operation:'link_evidence',fieldId:'evidence',label:'Evidence only',contextLabel:'Fixture',valueType:'evidence',currentValue:null,manual:false})];
  await claimRun({runId:failedRun,catalogId:failedCatalog,targets:failedTargets,claimReceipt:failedReceipt});
  const failArgs=[failedRun,json({failureCode:'BUDGET_EXHAUSTED'}),fixture.requester,fixture.org,fixture.workspace,authorizationVersion,failedReceipt.id,failedReceipt.execution_token,failedReceipt.execution_fence];
  await expectDatabaseError(()=>database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9)',[failedRun,json({}),...failArgs.slice(2)]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_FAILURE_INVALID/);
  await expectDatabaseError(()=>database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9)',[failedRun,json({failureCode:'PROVIDER_UNAVAILABLE'}),...failArgs.slice(2)]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_FAILURE_INVALID/);
  await expectDatabaseError(()=>database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9)',[failedRun,json({failureCode:'BUDGET_EXHAUSTED',message:'must not persist'}),...failArgs.slice(2)]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_FAILURE_INVALID/);
  await expectDatabaseError(()=>database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9)',[failedRun,failArgs[1],...failArgs.slice(2,8),Number(failedReceipt.execution_fence)+1]),/ENTERPRISE_AI_STALE_EXECUTION_FENCE/);
  const failed=(await database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9) result',failArgs)).rows[0].result;assert.equal(failed.state,'blocked');assert.equal(failed.failureCode,'BUDGET_EXHAUSTED');assert.deepEqual((await database.query('SELECT status,failure_code,safe_result,updated_at IS NOT NULL updated FROM public.enterprise_assess_document_mapping_runs WHERE id=$1',[failedRun])).rows[0],{status:'blocked',failure_code:'BUDGET_EXHAUSTED',safe_result:failed,updated:true});
  await database.query('BEGIN');try{await database.query("UPDATE public.workspace_memberships SET status='disabled' WHERE org_id=$1 AND workspace_id=$2 AND user_id=$3",[fixture.org,fixture.workspace,fixture.requester]);await expectDatabaseError(()=>database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9)',failArgs),/PR1B_AUTHORIZATION_STALE|PR1B_AUTHORIZATION_DENIED|PR1B_NOT_FOUND/);await database.query('ROLLBACK')}catch(error){await database.query('ROLLBACK');throw error}
  assert.deepEqual((await database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9) result',failArgs)).rows[0].result,failed);
  await expectDatabaseError(()=>database.query('SELECT public.enterprise_fail_assess_document_mapping_run_v1($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9)',[failedRun,json({failureCode:'PROVIDER_UNAVAILABLE'}),...failArgs.slice(2)]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_FAILURE_INVALID/);
  assert.equal(Number((await database.query('SELECT count(*) n FROM public.enterprise_ai_effect_journal WHERE receipt_id=$1',[failedReceipt.id])).rows[0].n),0);
  pass('MAP-PG-009-terminal-failure','sanitized pre-effect failure is terminal, exact-replayable, authority-bound, and records no provider effect');

  const runId=nextUuid(),catalogId=nextUuid(),analyzeReceipt=await receipt('assess.document-map.analyze','main');
  const descriptionSelector=nextUuid(),factSelector=nextUuid(),missingFactSelector=nextUuid(),effortSelector=nextUuid(),createSelector=nextUuid(),createAssetSelector=nextUuid(),createInteractionSelector=nextUuid(),createDecisionSelector=nextUuid(),createExceptionSelector=nextUuid(),evidenceSelector=nextUuid();
  const targets=[
    target(descriptionSelector,{catalogId,targetKind:'case_field',operation:'set_field',fieldId:'case.description',label:'Description',contextLabel:'Mapping fixture',valueType:'text',currentValue:'Manual baseline description',manual:true}),
    target(factSelector,{catalogId,targetKind:'primitive_fact',operation:'set_fact',entityId:primitiveId,fieldId:'primitive.ambiguityCharacterized',label:'Ambiguity characterized',contextLabel:'Manual review',valueType:'boolean',currentValue:null,manual:false}),
    target(missingFactSelector,{catalogId,targetKind:'primitive_fact',operation:'set_fact',entityId:primitiveId,fieldId:'primitive.rulesStable',label:'Rules stable',contextLabel:'Manual review',valueType:'boolean',currentValue:null,manual:false}),
    target(effortSelector,{catalogId,targetKind:'primitive_field',operation:'set_field',entityId:primitiveId,fieldId:'primitive.manualEffort',label:'Manual effort',contextLabel:'Manual review',valueType:'number',currentValue:null,manual:false}),
    target(createSelector,{catalogId,targetKind:'create_primitive',operation:'create_entity',fieldId:'create.primitive:Validate',label:'New Validate primitive',contextLabel:'Mapping fixture',valueType:'primitive_constructor',allowedValues:['Validate'],currentValue:null,manual:false}),
    target(createAssetSelector,{catalogId,targetKind:'create_asset',operation:'create_entity',fieldId:'create.asset',label:'New asset',contextLabel:'Mapping fixture',valueType:'asset_constructor',currentValue:null,manual:false}),
    target(createInteractionSelector,{catalogId,targetKind:'create_interaction',operation:'create_entity',entityId:assetId,fieldId:`create.interaction:${assetId}:${primitiveId}`,label:'New interaction',contextLabel:'Case system / Manual review',valueType:'interaction_constructor',currentValue:null,manual:false}),
    target(createDecisionSelector,{catalogId,targetKind:'create_decision_point',operation:'create_entity',entityId:primitiveId,fieldId:`create.decision:${primitiveId}`,label:'New decision',contextLabel:'Manual review',valueType:'decision_constructor',currentValue:null,manual:false}),
    target(createExceptionSelector,{catalogId,targetKind:'create_exception_path',operation:'create_entity',entityId:primitiveId,fieldId:`create.exception:${primitiveId}`,label:'New exception',contextLabel:'Manual review',valueType:'exception_constructor',currentValue:null,manual:false}),
    target(evidenceSelector,{catalogId,targetKind:'evidence_only',operation:'link_evidence',fieldId:'evidence',label:'Evidence only',contextLabel:'Mapping fixture',valueType:'evidence',currentValue:null,manual:false}),
  ];
  const wrongOrg=nextUuid();await expectDatabaseError(()=>database.query(`SELECT public.enterprise_claim_assess_document_mapping_run_v1($1,$2,$3,1,'assess-v2-schema-2026-07',$4,$5::jsonb,$6,$7,1,$8::jsonb,$9,$10,'openai','fixture-model','assess-supporting-document-map-v1',$11,$12,$13,$14,$15,$16,$17)`,[runId,catalogId,caseId,'f'.repeat(64),json(targets),bundleId,bundleVersionId,json(sourceBindings),routeId,fixture.provider,fixture.requester,wrongOrg,fixture.workspace,authorizationVersion,analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence]),/ENTERPRISE_AI_STALE_EXECUTION_FENCE/);
  const wrongWorkspace=nextUuid();await expectDatabaseError(()=>database.query(`SELECT public.enterprise_claim_assess_document_mapping_run_v1($1,$2,$3,1,'assess-v2-schema-2026-07',$4,$5::jsonb,$6,$7,1,$8::jsonb,$9,$10,'openai','fixture-model','assess-supporting-document-map-v1',$11,$12,$13,$14,$15,$16,$17)`,[runId,catalogId,caseId,'f'.repeat(64),json(targets),bundleId,bundleVersionId,json(sourceBindings),routeId,fixture.provider,fixture.requester,fixture.org,wrongWorkspace,authorizationVersion,analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence]),/ENTERPRISE_AI_STALE_EXECUTION_FENCE/);
  assert.equal(Number((await database.query('SELECT count(*) n FROM public.enterprise_assess_document_mapping_runs WHERE id=$1',[runId])).rows[0].n),0);
  const mainClaim=await claimRun({runId,catalogId,targets,claimReceipt:analyzeReceipt});assert.notEqual(mainClaim.catalogHash,'f'.repeat(64));
  const storedTargets=(await database.query('SELECT field_id,current_value,current_value_hash,manual FROM public.enterprise_assess_document_mapping_targets WHERE catalog_id=$1 ORDER BY ordinal',[catalogId])).rows;assert.equal(storedTargets.length,10);assert.notEqual(storedTargets[0].current_value_hash,'f'.repeat(64));assert.deepEqual(storedTargets.filter(item=>['primitive.ambiguityCharacterized','primitive.rulesStable'].includes(item.field_id)).map(item=>[item.current_value,item.manual]),[[null,false],[null,false]]);
  const bounds=(await database.query(`SELECT public.enterprise_assess_document_mapping_payload_valid('create_primitive',$1::jsonb) primitive_name_201,public.enterprise_assess_document_mapping_payload_valid('create_primitive',$2::jsonb) primitive_trigger_501,public.enterprise_assess_document_mapping_payload_valid('create_decision_point',$3::jsonb) decision_rule_2001,public.enterprise_assess_document_mapping_payload_valid('create_exception_path',$4::jsonb) exception_trigger_2001,public.enterprise_assess_document_mapping_payload_valid('create_interaction',$5::jsonb) interaction_missing_risk`,[json({name:'n'.repeat(201),description:'valid'}),json({name:'valid',description:'valid',trigger:'t'.repeat(501)}),json({name:'valid',ruleDescription:'r'.repeat(2001),outcomeLabels:[]}),json({name:'valid',trigger:'e'.repeat(2001)}),json({operationName:'read',mode:'read',dataClassification:'Internal'})])).rows[0];assert.deepEqual(bounds,{primitive_name_201:false,primitive_trigger_501:false,decision_rule_2001:false,exception_trigger_2001:false,interaction_missing_risk:false});
  pass('MAP-PG-004-authoritative-catalog','wrong tenant rejects and server recomputes exact target values/manual/hash');

  const bindingA=mainClaim.sourceBindings.find(item=>item.sourceVersionId===selected[0].sourceVersionId),bindingB=mainClaim.sourceBindings.find(item=>item.sourceVersionId===selected[1].sourceVersionId);assert.ok(bindingA&&bindingB);
  const proposalA=nextUuid(),proposalB=nextUuid(),proposalFact=nextUuid(),proposalMissingFact=nextUuid(),proposalEffort=nextUuid(),proposalPrimitive=nextUuid(),proposalAsset=nextUuid(),proposalInteraction=nextUuid(),proposalDecision=nextUuid(),proposalException=nextUuid();
  const proposal=(id,selector,binding,value,excerpt)=>({id,version:1,targetSelectorId:selector,sourceId:binding.sourceId,sourceVersionId:binding.sourceVersionId,extractionBindingId:binding.extractionBindingId,extractionJobId:binding.extractionJobId,proposedValue:value,confidence:0.9,rationale:'Grounded synthetic fixture',sourceAnchor:{sourceVersionId:binding.sourceVersionId,parserVersion:binding.parserVersion,locator:`fixture:${id}`,anchorHash:sha(`anchor:${id}`),safeExcerpt:excerpt},relationship:'neutral'});
  const proposals=[
    proposal(proposalA,descriptionSelector,bindingA,'Provider suggestion A','Suggestion A'),proposal(proposalB,descriptionSelector,bindingB,'Provider suggestion B','Suggestion B'),
    proposal(proposalFact,factSelector,bindingA,true,'Ambiguity is characterized'),proposal(proposalMissingFact,missingFactSelector,bindingA,true,'Rules are stable'),proposal(proposalEffort,effortSelector,bindingA,125.5,'Manual effort is bounded'),
    proposal(proposalPrimitive,createSelector,bindingA,{name:'Validate request',description:'Validate the request deterministically',inputs:['request'],outputs:['validated request'],rules:['reject malformed input']},'A validation step exists'),
    proposal(proposalAsset,createAssetSelector,bindingA,{name:'Policy repository',accountableOwner:'Operations'},'A policy repository is used'),
    proposal(proposalInteraction,createInteractionSelector,bindingA,{operationName:'Read policy',mode:'read',dataClassification:'Internal',highImpact:false,financialAction:false,untrustedContentWithTools:true},'The case system reads policy'),
    proposal(proposalDecision,createDecisionSelector,bindingA,{name:'Route request',ruleDescription:'Route based on validation result',outcomeLabels:['approved','rejected']},'A routing decision exists'),
    proposal(proposalException,createExceptionSelector,bindingA,{name:'Malformed request',trigger:'Request validation fails'},'A malformed request is exceptional'),
  ];
  for(const item of proposals){
    const contract=(await database.query(`SELECT public.enterprise_assess_document_mapping_value_valid(t.value_type,$3::jsonb,t.allowed_values) value_valid,public.enterprise_assess_document_mapping_payload_valid(t.target_kind,$3::jsonb) payload_valid,(SELECT count(*)::int FROM public.enterprise_assess_document_mapping_run_sources s WHERE s.run_id=$1 AND s.extraction_binding_id=$4 AND s.extraction_job_id=$5 AND s.source_id=$6 AND s.source_version_id=$7) source_count FROM public.enterprise_assess_document_mapping_targets t WHERE t.catalog_id=$2 AND t.selector_id=$8`,[runId,catalogId,json(item.proposedValue),item.extractionBindingId,item.extractionJobId,item.sourceId,item.sourceVersionId,item.targetSelectorId])).rows[0];
    assert.deepEqual(contract,{value_valid:true,payload_valid:true,source_count:1});
  }
  const analyzed=mainClaim.sourceBindings.map(item=>({sourceId:item.sourceId,sourceVersionId:item.sourceVersionId,parserVersion:item.parserVersion,extractedByteCount:item.extractedByteCount,sheetCount:item.sheetCount,cellCount:item.cellCount,warnings:item.warnings}));
  const safe={resourceId:runId,runId,catalogId,catalogHash:mainClaim.catalogHash,targetCount:targets.length,sourceCount:2,proposalCount:proposals.length,sourceBindings:mainClaim.sourceBindings,analyzedSources:analyzed,warnings:[`${selected[1].sourceVersionId}:blank_rows_omitted`]};
  const substituted=structuredClone(safe);substituted.analyzedSources[0].extractedByteCount+=1;
  await expectDatabaseError(()=>database.query(`SELECT public.enterprise_stage_assess_document_mapping_result_v1($1,$2,$3::jsonb,$4::jsonb,$5,20,10,2,$6,$7,$8,$9)`,[runId,catalogId,json(proposals),json(substituted),sha('output'),sha('stage'),analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_STAGE_INVALID/);
  await expectDatabaseError(()=>database.query(`SELECT public.enterprise_stage_assess_document_mapping_result_v1($1,$2,$3::jsonb,$4::jsonb,$5,20,10,2,$6,$7,$8,$9)`,[runId,catalogId,json(proposals),json({...safe,rawProviderOutput:'must not persist'}),sha('output'),sha('stage'),analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_STAGE_INVALID/);
  const forgedProposals=structuredClone(proposals);forgedProposals[0].providerAuthoredPath='case.description';
  await expectDatabaseError(()=>database.query(`SELECT public.enterprise_stage_assess_document_mapping_result_v1($1,$2,$3::jsonb,$4::jsonb,$5,20,10,2,$6,$7,$8,$9)`,[runId,catalogId,json(forgedProposals),json(safe),sha('output'),sha('stage'),analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_PROPOSAL_INVALID/);
  await database.query(`SELECT public.enterprise_stage_assess_document_mapping_result_v1($1,$2,$3::jsonb,$4::jsonb,$5,20,10,2,$6,$7,$8,$9)`,[runId,catalogId,json(proposals),json(safe),sha('output'),sha('stage'),analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence]);
  const analyzeCommit=(await database.query('SELECT public.enterprise_commit_assess_document_mapping_result_v1($1,$2,$3,$4) result',[runId,analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence])).rows[0].result;const analyzeReplay=(await database.query('SELECT public.enterprise_commit_assess_document_mapping_result_v1($1,$2,$3,$4) result',[runId,analyzeReceipt.id,analyzeReceipt.execution_token,analyzeReceipt.execution_fence])).rows[0].result;assert.deepEqual(analyzeReplay,analyzeCommit);
  const staleReviewReceipt=await receipt('assess.document-map.proposal.review','stale-after-analyze');await database.query('BEGIN');try{const supersedingVersion=nextUuid();await database.query(`INSERT INTO public.enterprise_source_set_versions(id,source_set_id,org_id,workspace_id,version,purpose,manifest_hash,source_count,extracted_character_count,status,created_by) VALUES($1,$2,$3,$4,2,'Superseding after analyze',$5,2,100,'locked',$6)`,[supersedingVersion,setId,fixture.org,fixture.workspace,sha('set-v2-analyze'),fixture.requester]);await database.query('UPDATE public.enterprise_source_sets SET current_version=2 WHERE id=$1',[setId]);await expectDatabaseError(()=>database.query(`SELECT public.enterprise_review_assess_document_mapping_proposal_v1($1,1,'accepted',NULL,'Must reject stale source set',$2,$3,$4,1,$5,$6,$7,$8,$9,$10,$11)`,[proposals[0].id,proposals[0].targetSelectorId,catalogId,caseId,fixture.requester,fixture.org,fixture.workspace,authorizationVersion,staleReviewReceipt.id,staleReviewReceipt.execution_token,staleReviewReceipt.execution_fence]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_SOURCE_STALE/);await database.query('ROLLBACK')}catch(error){await database.query('ROLLBACK');throw error}
  pass('MAP-PG-005-stage-lineage-replay','substituted source metadata rejects and exact provider-result retry replays');

  const reviews=[];for(const [index,item] of proposals.entries()){const reviewReceipt=await receipt('assess.document-map.proposal.review',`review-${index+1}`);const result=(await database.query(`SELECT public.enterprise_review_assess_document_mapping_proposal_v1($1,1,'accepted',NULL,'Human accepted grounded suggestion',$2,$3,$4,1,$5,$6,$7,$8,$9,$10,$11) result`,[item.id,item.targetSelectorId,catalogId,caseId,fixture.requester,fixture.org,fixture.workspace,authorizationVersion,reviewReceipt.id,reviewReceipt.execution_token,reviewReceipt.execution_fence])).rows[0].result;assert.equal(result.version,2);reviews.push({proposalId:item.id,proposalVersion:2,targetSelectorId:item.targetSelectorId,effectiveValue:item.proposedValue});}
  const batchId=nextUuid(),previewReceipt=await receipt('assess.document-map.preview','preview');const preview=(await database.query(`SELECT public.enterprise_create_assess_document_mapping_preview_v1($1,$2,$3,$4,1,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14) result`,[batchId,catalogId,mainClaim.catalogHash,caseId,bundleId,bundleVersionId,json(reviews),fixture.requester,fixture.org,fixture.workspace,authorizationVersion,previewReceipt.id,previewReceipt.execution_token,previewReceipt.execution_fence])).rows[0].result;assert.equal(preview.materialConflictCount,2);
  const conflicts=(await database.query('SELECT id,kind,current_resolution_version FROM public.enterprise_assess_document_mapping_conflicts WHERE preview_batch_id=$1 ORDER BY kind',[batchId])).rows;assert.deepEqual(conflicts.map(item=>item.kind),['cross_source','manual']);
  let latestManifest=preview.previewManifest;for(const [index,conflict] of conflicts.entries()){const resolveReceipt=await receipt('assess.document-map.conflict.resolve',`resolve-${index}`);const resolved=(await database.query(`SELECT public.enterprise_resolve_assess_document_mapping_conflict_v1($1,0,'retain_manual',NULL,NULL,'Preserve explicit human-authored value',$2,$3,$4,$5,$6,$7,$8) result`,[conflict.id,fixture.requester,fixture.org,fixture.workspace,authorizationVersion,resolveReceipt.id,resolveReceipt.execution_token,resolveReceipt.execution_fence])).rows[0].result;latestManifest=resolved.previewManifest;}
  assert.equal(latestManifest.manifestVersion,3);assert.equal(latestManifest.unresolvedConflictCount,0);assert.notEqual(latestManifest.resolutionSetHash,preview.previewManifest.resolutionSetHash);const manifestHistory=(await database.query('SELECT manifest_version,jsonb_array_length(resolution_bindings) resolution_count FROM public.enterprise_assess_document_mapping_preview_manifests WHERE preview_batch_id=$1 ORDER BY manifest_version',[batchId])).rows;assert.deepEqual(manifestHistory.map(row=>[Number(row.manifest_version),row.resolution_count]),[[1,0],[2,1],[3,2]]);
  pass('MAP-PG-006-review-conflicts','review ownership creates both manual and cross-source conflicts and requires explicit resolution');

  let materialized={name:'Mapping fixture',description:'Manual baseline description',agentNecessity,primitives:[primitive],edges:[],decisionPoints:[],exceptionPaths:[],assets:[asset],interactions:[interaction],evidence:[{id:oldEvidenceId,claimIds:['primitive.ambiguityCharacterized'],sourceType:'document',status:'submitted',validated:false}]};
  await expectDatabaseError(()=>database.query(`SELECT public.enterprise_assess_document_normalize_primitive_facts($1::jsonb)`,[json({...materialized,primitives:[{...primitive,facts:{...primitive.facts,'primitive.ambiguityCharacterized':fact('primitive.ambiguityCharacterized',true)}}]})]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_FACT_ALIAS_CONFLICT/);
  assert.equal((await database.query('SELECT public.enterprise_assess_document_authoring_valid($1::jsonb) value',[json(materialized)])).rows[0].value,true,'Initial native fixture must satisfy database authoring validation');
  for(const item of proposals.slice(2)){
    materialized=(await database.query('SELECT public.enterprise_assess_document_apply_target($1::jsonb,t,$2::jsonb,$3) value FROM public.enterprise_assess_document_mapping_targets t WHERE t.catalog_id=$4 AND t.selector_id=$5',[json(materialized),json(item.proposedValue),nextUuid(),catalogId,item.targetSelectorId])).rows[0].value;
    const validation=(await database.query('SELECT public.enterprise_assess_document_authoring_valid($1::jsonb) value,public.pr1d_authoring_facts_valid($1::jsonb) facts',[json(materialized)])).rows[0];
    assert.equal(validation.value,true,`Server materialization invalid after ${item.targetSelectorId}; facts=${validation.facts}`);
  }

  const commitReceipt=await receipt('assess.document-map.commit','commit');const commitArgs=[batchId,catalogId,mainClaim.catalogHash,caseId,bundleId,bundleVersionId,json(latestManifest),fixture.requester,fixture.org,fixture.workspace,authorizationVersion,commitReceipt.id,commitReceipt.execution_token,commitReceipt.execution_fence];
  await expectDatabaseError(()=>database.query(`SELECT public.enterprise_commit_assess_document_mapping_preview_v1($1,$2,$3,$4,1,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14)`,[...commitArgs.slice(0,6),json({}),...commitArgs.slice(7)]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_COMMIT_STALE/);
  const substitutedManifest={...latestManifest,itemCount:latestManifest.itemCount+1};await expectDatabaseError(()=>database.query(`SELECT public.enterprise_commit_assess_document_mapping_preview_v1($1,$2,$3,$4,1,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14)`,[...commitArgs.slice(0,6),json(substitutedManifest),...commitArgs.slice(7)]),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_COMMIT_STALE/);
  await database.query('BEGIN');try{const supersedingVersion=nextUuid();await database.query(`INSERT INTO public.enterprise_source_set_versions(id,source_set_id,org_id,workspace_id,version,purpose,manifest_hash,source_count,extracted_character_count,status,created_by) VALUES($1,$2,$3,$4,2,'Superseding race',$5,2,100,'locked',$6)`,[supersedingVersion,setId,fixture.org,fixture.workspace,sha('set-v2'),fixture.requester]);await database.query('UPDATE public.enterprise_source_sets SET current_version=2 WHERE id=$1',[setId]);await expectDatabaseError(()=>database.query(`SELECT public.enterprise_commit_assess_document_mapping_preview_v1($1,$2,$3,$4,1,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14)`,commitArgs),/ENTERPRISE_ASSESS_DOCUMENT_MAPPING_SOURCE_STALE/);await database.query('ROLLBACK')}catch(error){await database.query('ROLLBACK');throw error}
  const committed=(await database.query(`SELECT public.enterprise_commit_assess_document_mapping_preview_v1($1,$2,$3,$4,1,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14) result`,commitArgs)).rows[0].result;assert.equal(committed.caseVersion,2);assert.deepEqual(committed.appliedProposalIds,[proposalFact,proposalMissingFact,proposalEffort,proposalPrimitive,proposalAsset,proposalInteraction,proposalDecision,proposalException]);
  const replayed=(await database.query(`SELECT public.enterprise_commit_assess_document_mapping_preview_v1($1,$2,$3,$4,1,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14) result`,commitArgs)).rows[0].result;assert.deepEqual(replayed,committed);
  const head=(await database.query('SELECT c.version,v.id,v.description,v.source_snapshot,v.imported_facts FROM public.assess_v2_cases c JOIN public.assess_v2_case_versions v ON v.id=c.head_version_id WHERE c.id=$1',[caseId])).rows[0];assert.equal(Number(head.version),2);assert.equal(head.description,'Manual baseline description');assert.deepEqual(head.source_snapshot,sourceSnapshot);assert.deepEqual(head.imported_facts,importedFacts);
  const appliedPrimitive=(await database.query('SELECT payload FROM public.assess_v2_primitives WHERE version_id=$1 AND id=$2',[head.id,primitiveId])).rows[0].payload;const appliedFact=appliedPrimitive.facts['primitive.ambiguityCharacterized'];assert.equal(appliedPrimitive.facts.ambiguityCharacterized,undefined);assert.equal(appliedFact.value,true);assert.equal(appliedFact.fieldId,'primitive.ambiguityCharacterized');assert.equal(appliedFact.source,'user');assert.ok(appliedFact.evidenceIds.includes(oldEvidenceId));assert.equal(new Set(appliedFact.evidenceIds).size,appliedFact.evidenceIds.length);assert.equal(appliedPrimitive.manualEffort,125.5);assert.deepEqual(appliedPrimitive.facts['primitive.rulesStable'],{fieldId:'primitive.rulesStable',value:true,status:'suggested',evidenceIds:[appliedPrimitive.facts['primitive.rulesStable'].evidenceIds[0]],source:'system'});
  assert.deepEqual((await database.query(`SELECT (SELECT count(*)::int FROM public.assess_v2_primitives WHERE version_id=$1) primitives,(SELECT count(*)::int FROM public.assess_v2_application_assets WHERE version_id=$1) assets,(SELECT count(*)::int FROM public.assess_v2_application_interactions WHERE version_id=$1) interactions,(SELECT count(*)::int FROM public.assess_v2_decision_points WHERE version_id=$1) decisions,(SELECT count(*)::int FROM public.assess_v2_exception_paths WHERE version_id=$1) exceptions`,[head.id])).rows[0],{primitives:2,assets:2,interactions:2,decisions:1,exceptions:1});
  const persisted=(await database.query(`SELECT v.name,v.description,v.agent_necessity,(SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_primitives WHERE version_id=v.id) primitives,(SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_edges WHERE version_id=v.id) edges,(SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_decision_points WHERE version_id=v.id) decisions,(SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_exception_paths WHERE version_id=v.id) exceptions,(SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_application_assets WHERE version_id=v.id) assets,(SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_application_interactions WHERE version_id=v.id) interactions,(SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_evidence_links WHERE version_id=v.id) evidence FROM public.assess_v2_case_versions v WHERE v.id=$1`,[head.id])).rows[0];
  const createdInteraction=persisted.interactions.find(item=>item.operationName==='Read policy');assert.deepEqual({highImpact:createdInteraction.facts.highImpact,financialAction:createdInteraction.facts.financialAction,untrustedContentWithTools:createdInteraction.facts.untrustedContentWithTools},{highImpact:false,financialAction:false,untrustedContentWithTools:true});
  const persistedDraft={caseId,name:persisted.name,description:persisted.description,primitives:persisted.primitives,edges:persisted.edges??[],decisionPoints:persisted.decisions??[],exceptionPaths:persisted.exceptions??[],applicationAssets:persisted.assets??[],interactions:persisted.interactions??[],evidenceLinks:persisted.evidence??[],agentNecessity:persisted.agent_necessity,candidateEvaluations:[],gateResults:[],controlRequirements:[],modernizationDispositions:[]};
  runNativeParser({draft:persistedDraft,persisted:{organizationId:fixture.org,workspaceId:fixture.workspace,processId:fixture.process,ownerId:fixture.requester,version:2,importedFacts,createdAt:'2026-09-16T00:00:00.000Z',updatedAt:'2026-09-16T00:00:00.000Z'}});
  assert.equal(await database.query('SELECT public.enterprise_assess_document_authoring_valid(jsonb_build_object(\'name\',v.name,\'description\',v.description,\'agentNecessity\',v.agent_necessity,\'primitives\',(SELECT jsonb_agg(payload) FROM public.assess_v2_primitives WHERE version_id=v.id),\'edges\',\'[]\'::jsonb,\'decisionPoints\',\'[]\'::jsonb,\'exceptionPaths\',\'[]\'::jsonb,\'assets\',(SELECT jsonb_agg(payload) FROM public.assess_v2_application_assets WHERE version_id=v.id),\'interactions\',(SELECT jsonb_agg(payload) FROM public.assess_v2_application_interactions WHERE version_id=v.id),\'evidence\',(SELECT jsonb_agg(payload) FROM public.assess_v2_evidence_links WHERE version_id=v.id))) valid FROM public.assess_v2_case_versions v WHERE v.id=$1',[head.id]).then(result=>result.rows[0].valid),true);
  pass('MAP-PG-007-atomic-native-reopen','one native case version commits atomically, preserves manual/imported/source/fact provenance, and exact retry reopens the same result');

  const staleReceipt=await receipt('assess.document-map.analyze','stale-authority');await database.query('BEGIN');try{await database.query("UPDATE public.workspace_memberships SET status='disabled' WHERE org_id=$1 AND workspace_id=$2 AND user_id=$3",[fixture.org,fixture.workspace,fixture.requester]);const staleCatalog=nextUuid();await expectDatabaseError(()=>claimRun({runId:nextUuid(),catalogId:staleCatalog,targets:[target(nextUuid(),{catalogId:staleCatalog,targetKind:'evidence_only',operation:'link_evidence',fieldId:'evidence',label:'Evidence',contextLabel:'Fixture',valueType:'evidence',currentValue:null,manual:false})],claimReceipt:staleReceipt}),/PR1B_AUTHORIZATION_STALE|PR1B_AUTHORIZATION_DENIED|PR1B_NOT_FOUND/);await database.query('ROLLBACK')}catch(error){await database.query('ROLLBACK');throw error}
  const beforeLegacy=Number((await database.query('SELECT count(*) n FROM public.assess_v2_case_versions WHERE case_id=$1',[caseId])).rows[0].n);await expectDatabaseError(()=>database.query(`SELECT public.enterprise_transcript_create_assess_apply_preview_batch_v2($1,$2,2,$3,$4,1,'[]'::jsonb,$5::jsonb,$6,$7,$8,$9,$10,$11,$12)`,[nextUuid(),caseId,bundleId,bundleVersionId,json([{intent:'create_primitive',target:'primitive'}]),fixture.requester,fixture.org,fixture.workspace,authorizationVersion,nextUuid(),nextUuid(),1]),/ENTERPRISE_TRANSCRIPT_TYPED_MAPPING_REQUIRED/);assert.equal(Number((await database.query('SELECT count(*) n FROM public.assess_v2_case_versions WHERE case_id=$1',[caseId])).rows[0].n),beforeLegacy);
  pass('MAP-PG-008-revoked-and-legacy','revoked/stale authority and legacy structural bypass reject with zero Assess effects');

  assert.equal(passed.length,10);console.log(`Assess supporting-document mapping PostgreSQL scenarios: ${passed.length}/${passed.length} passed.`);
}finally{
  for(const client of clients.slice().reverse())try{await client.end()}catch{}
  if(admin){const cleanup=new Client({connectionString:adminUrl});try{await cleanup.connect();await cleanup.query('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1 AND pid<>pg_backend_pid()',[databaseName]);await cleanup.query(`DROP DATABASE IF EXISTS ${databaseName}`)}finally{await cleanup.end().catch(()=>{})}}
}
