import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import pg from 'pg';
const{Client}=pg,adminUrl=process.env.PR1D_MIGRATION_DATABASE_URL||process.env.PR1C_MIGRATION_DATABASE_URL||process.env.PR1B_MIGRATION_DATABASE_URL;
if(!adminUrl){console.error('PR1D_MIGRATION_DATABASE_URL is required.');process.exit(1)}
const dbName='avalaos_pr1d_authority_test',createdRoles=[],all=fs.readdirSync('supabase/migrations').filter(x=>x.endsWith('.sql')).sort(),pr1b='20260712120000_pr1b_identity_rbac_rls_assess.sql',pr1c='20260713120000_pr1c_enterprise_assess_ui_govern_studio_handoff.sql',pr1d='20260714120000_pr1d_assess_v2_decision_intelligence.sql',baseline=all.slice(0,all.indexOf(pr1b));
const source=n=>fs.readFileSync(path.join('supabase/migrations',n),'utf8'),fixture=fs.readFileSync('supabase/tests/migration-harness/pr1b_legacy_assess_fixture.sql','utf8'),urlFor=n=>{const u=new URL(adminUrl);u.pathname=`/${n}`;return u.toString()},connect=async u=>{const c=new Client({connectionString:u});await c.connect();return c},tx=async(c,sql)=>{await c.query('BEGIN');try{await c.query(sql);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}},apply=async(c,names)=>{for(const n of names)await tx(c,source(n))};
const A='11000000-0000-4000-8000-000000000001',O='11000000-0000-4000-8000-000000000010',W='11000000-0000-4000-8000-000000000011',P='11000000-0000-4000-8000-000000000013',V1='11000000-0000-4000-8000-000000000014',B='22000000-0000-4000-8000-000000000002',OB='22000000-0000-4000-8000-000000000020',WB='22000000-0000-4000-8000-000000000022',CASE='31000000-0000-4000-8000-000000000001',CASE2='31000000-0000-4000-8000-000000000002',CLONE='31000000-0000-4000-8000-000000000003',req=n=>`41000000-0000-4000-8000-${String(n).padStart(12,'0')}`,value=r=>r.rows[0].value;
const asRole=async(c,r,fn)=>{await c.query(`SET ROLE ${r}`);try{return await fn()}finally{await c.query('RESET ROLE')}};
let admin,test;try{admin=await connect(adminUrl);for(const[r,a]of[['anon','NOLOGIN'],['authenticated','NOLOGIN'],['service_role','NOLOGIN BYPASSRLS'],['pr1d_unprivileged','NOLOGIN']])if(!(await admin.query('SELECT 1 FROM pg_roles WHERE rolname=$1',[r])).rowCount){await admin.query(`CREATE ROLE ${r} ${a}`);createdRoles.push(r)}await admin.query(`DROP DATABASE IF EXISTS ${dbName} WITH (FORCE)`);await admin.query(`CREATE DATABASE ${dbName}`);test=await connect(urlFor(dbName));await tx(test,`CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULLIF(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;`);await apply(test,baseline);await tx(test,fixture);await tx(test,source(pr1b));await tx(test,source(pr1c));await tx(test,source(pr1d));
 await test.query("INSERT INTO role_capabilities(role_id,capability_key) SELECT role_id,'govern.resolve' FROM organization_members WHERE org_id=$1 AND user_id=$2 ON CONFLICT DO NOTHING",[O,A]);
 const signatures=['pr1d_create_assess_v2_case(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,bigint)','pr1d_clone_assess_v2_from_v1(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,bigint)','pr1d_upsert_assess_v2_draft(uuid,uuid,uuid,uuid,bigint,jsonb,uuid,text,bigint)','pr1d_finalize_assess_v2_case(uuid,uuid,uuid,uuid,bigint,jsonb,jsonb,jsonb,text,text,text,text,text,timestamp with time zone,uuid,text,bigint)'];for(const s of signatures){for(const r of['anon','authenticated','pr1d_unprivileged'])assert.equal((await test.query('SELECT has_function_privilege($1,$2,\'EXECUTE\') ok',[r,s])).rows[0].ok,false);assert.equal((await test.query('SELECT has_function_privilege(\'service_role\',$1,\'EXECUTE\') ok',[s])).rows[0].ok,true)}
 for(const t of['assess_v2_cases','assess_v2_case_versions','assess_v2_decision_versions','assess_v2_decision_points','assess_v2_exception_paths','assess_v2_candidate_evaluations','assess_v2_gate_results','assess_v2_control_requirements','assess_v2_modernization_dispositions']){assert.equal((await test.query('SELECT relrowsecurity rls,relforcerowsecurity forced FROM pg_class WHERE oid=$1::regclass',[t])).rows[0].rls,true);assert.equal((await test.query('SELECT relforcerowsecurity forced FROM pg_class WHERE oid=$1::regclass',[t])).rows[0].forced,true);for(const p of['INSERT','UPDATE','DELETE'])assert.equal((await test.query('SELECT has_table_privilege(\'authenticated\',$1,$2) ok',[t,p])).rows[0].ok,false)}
 const version=Number((await test.query('SELECT version FROM authorization_versions WHERE org_id=$1 AND user_id=$2',[O,A])).rows[0].version),callCreate=(id,key,n)=>asRole(test,'service_role',()=>test.query('SELECT pr1d_create_assess_v2_case($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) value',[A,O,W,id,P,'V2 Case','',req(n),key,version]));
 const created=value(await callCreate(CASE,'create-v2-1',1));assert.equal(created.resource.status,'draft');assert.equal(Number(created.resource.version),1);assert.deepEqual(value(await callCreate(CASE,'create-v2-1',1)).resource,created.resource);assert.equal(value(await callCreate(CASE2,'create-v2-1',2)).errorCode,'IDEMPOTENCY_CONFLICT');
 await test.query("UPDATE assessments SET score_version='assess-core-2026-05' WHERE id=$1",[V1]);const cloned=value(await asRole(test,'service_role',()=>test.query('SELECT pr1d_clone_assess_v2_from_v1($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) value',[A,O,W,CLONE,V1,'Clone','',req(3),'clone-v1',version])));assert.equal(cloned.resource.status,'draft');assert.equal((await test.query('SELECT score_version FROM assessments WHERE id=$1',[V1])).rows[0].score_version,'assess-core-2026-05');assert.equal((await test.query('SELECT source_snapshot->>\'importedAs\' imported FROM assess_v2_case_versions WHERE case_id=$1',[CLONE])).rows[0].imported,'unverified-source-facts');
 const dp='51000000-0000-4000-8000-000000000001',xp='51000000-0000-4000-8000-000000000002',primitive='51000000-0000-4000-8000-000000000003';const authoring={caseId:CASE,name:'Edited',description:'',primitives:[{id:primitive}],edges:[],decisionPoints:[{id:dp,primitiveId:primitive,name:'Gate',ruleDescription:'Route',outcomeLabels:['continue','exception'],evidenceIds:[]}],exceptionPaths:[{id:xp,fromPrimitiveId:primitive,name:'Exception',trigger:'Failure',resolutionPrimitiveIds:[primitive],evidenceIds:[]}],assets:[],interactions:[],evidence:[],agentNecessity:{irreducibleAmbiguity:null,adaptiveNextStep:null,toolOrPathSelection:null,incrementalValue:null,controllable:null}};const raceA=await connect(urlFor(dbName)),raceB=await connect(urlFor(dbName));const upsert=(client,key,n)=>asRole(client,'service_role',()=>client.query('SELECT pr1d_upsert_assess_v2_draft($1,$2,$3,$4,$5,$6,$7,$8,$9) value',[A,O,W,CASE,1,authoring,req(n),key,version]));let race;try{race=await Promise.all([upsert(raceA,'race-a',4),upsert(raceB,'race-b',5)]).then(x=>x.map(value))}finally{await raceA.end();await raceB.end()};assert.equal(race.filter(x=>x.resource?.version===2).length,1);assert.equal(race.filter(x=>x.errorCode==='VERSION_CONFLICT').length,1);assert.equal(Number((await test.query('SELECT count(*) n FROM assess_v2_decision_points WHERE case_id=$1',[CASE])).rows[0].n),1);assert.equal(Number((await test.query('SELECT count(*) n FROM assess_v2_exception_paths WHERE case_id=$1',[CASE])).rows[0].n),1);const locked=value(await asRole(test,'service_role',()=>test.query('SELECT pr1d_load_assess_v2_case($1,$2,$3,$4) value',[CASE,O,W,2])));assert.equal(locked.decisionPoints.length,1);assert.equal(locked.exceptionPaths.length,1);const sourceCase={id:CASE,version:2},output={caseId:CASE,validationStatus:'reviewer-ready',candidateEvaluations:[{primitiveId:primitive,component:'Deterministic Rules',fit:'Strong Fit'}],gateResults:[{ruleId:'GATE-001',subjectId:primitive,status:'pass',reason:'evidenced'}],controlRequirements:[{id:'control-1',subjectId:primitive,control:'Audit',required:true,rationale:'required',ruleIds:['CTRL-001']}],modernization:[{assetId:'asset-1',dispositions:['Retain'],rationale:['stable']}]};
const finalized=value(await asRole(test,'service_role',()=>test.query('SELECT pr1d_finalize_assess_v2_case($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) value',[A,O,W,CASE,2,sourceCase,[],output,'0'.repeat(64),'1'.repeat(64),'2'.repeat(64),'assess-v2-rules-2026-07','assess-v2-decision-2026-07',new Date().toISOString(),req(9),'finalize-v2',version])));assert.equal(finalized.resource.status,'reviewer_ready');
for(const table of ['assess_v2_candidate_evaluations','assess_v2_gate_results','assess_v2_control_requirements','assess_v2_modernization_dispositions']){assert.equal(Number((await test.query(`SELECT count(*) n FROM ${table} WHERE case_id=$1`,[CASE])).rows[0].n),1);assert.equal(Number((await test.query(`SELECT count(*) n FROM ${table} child JOIN assess_v2_decision_versions decision ON decision.id=child.decision_id AND decision.case_id=child.case_id AND decision.workspace_id=child.workspace_id AND decision.org_id=child.org_id WHERE child.case_id=$1`,[CASE])).rows[0].n),1);}
await assert.rejects(test.query("UPDATE assess_v2_candidate_evaluations SET payload='{}' WHERE case_id=$1",[CASE]),/PR1D_IMMUTABLE/);

 await test.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[A]);await asRole(test,'authenticated',async()=>{assert.equal(Number((await test.query('SELECT count(*) n FROM assess_v2_cases')).rows[0].n),2);assert.equal((await test.query('SELECT id FROM assess_v2_cases WHERE org_id=$1',[OB])).rowCount,0)});await test.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[B]);await asRole(test,'authenticated',async()=>assert.equal(Number((await test.query('SELECT count(*) n FROM assess_v2_cases')).rows[0].n),0));
 await test.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[A]);await asRole(test,'authenticated',async()=>{for(const table of ['assess_v2_decision_points','assess_v2_exception_paths','assess_v2_candidate_evaluations','assess_v2_gate_results','assess_v2_control_requirements','assess_v2_modernization_dispositions'])assert.equal(Number((await test.query(`SELECT count(*) n FROM ${table}`)).rows[0].n),1)});
await test.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[B]);await asRole(test,'authenticated',async()=>{for(const table of ['assess_v2_decision_points','assess_v2_exception_paths','assess_v2_candidate_evaluations','assess_v2_gate_results','assess_v2_control_requirements','assess_v2_modernization_dispositions'])assert.equal(Number((await test.query(`SELECT count(*) n FROM ${table}`)).rows[0].n),0)});
await test.query('UPDATE assess_v2_runtime_control SET enabled=false');assert.equal(value(await callCreate(CASE2,'disabled-v2',6)).errorCode,'FEATURE_DISABLED');await test.query('UPDATE assess_v2_runtime_control SET enabled=true,read_only=true');assert.equal(value(await callCreate(CASE2,'readonly-v2',7)).errorCode,'READ_ONLY');await test.query('UPDATE assess_v2_runtime_control SET read_only=false');
 const atomicCase=value(await callCreate(CASE2,'atomic-create',10));assert.equal(atomicCase.resource.version,1);const atomicAuthoring={...authoring,caseId:CASE2};
 await test.query("CREATE FUNCTION pr1d_test_reject_audit() RETURNS trigger LANGUAGE plpgsql AS $audit$BEGIN IF NEW.action='assessment_v2.draft.upsert' THEN RAISE EXCEPTION 'PR1D_TEST_AUDIT_FAILURE';END IF;RETURN NEW;END$audit$;CREATE TRIGGER pr1d_test_reject_audit BEFORE INSERT ON privileged_audit_events FOR EACH ROW EXECUTE FUNCTION pr1d_test_reject_audit()");
 await assert.rejects(asRole(test,'service_role',()=>test.query('SELECT pr1d_upsert_assess_v2_draft($1,$2,$3,$4,$5,$6,$7,$8,$9) value',[A,O,W,CASE2,1,atomicAuthoring,req(11),'atomic-draft',version])),/PR1D_TEST_AUDIT_FAILURE/);
 await test.query('DROP TRIGGER pr1d_test_reject_audit ON privileged_audit_events;DROP FUNCTION pr1d_test_reject_audit()');
 assert.equal(Number((await test.query('SELECT version FROM assess_v2_cases WHERE id=$1',[CASE2])).rows[0].version),1);assert.equal(Number((await test.query('SELECT count(*) n FROM assess_v2_case_versions WHERE case_id=$1',[CASE2])).rows[0].n),1);assert.equal(Number((await test.query("SELECT count(*) n FROM assess_command_receipts WHERE idempotency_key='atomic-draft'")).rows[0].n),0);
 const updatedV1=await test.query("UPDATE assessments SET status='Changes Requested',version=1 WHERE id=$1 RETURNING id,org_id,workspace_id,status,version,deleted_at",[V1]);assert.equal(updatedV1.rowCount,1,`V1 row unavailable: ${JSON.stringify(updatedV1.rows)}`);const resubmitted=value(await asRole(test,'service_role',()=>test.query('SELECT pr1c_govern_resolve($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) value',[A,O,W,V1,'submit','resubmitted',1,req(8),'govern-resubmit',version])));assert.ok(resubmitted.resource,`V1 resubmission failed: ${JSON.stringify(resubmitted)}`);assert.equal(resubmitted.resource.status,'In Review');
 await assert.rejects(test.query("UPDATE assess_v2_case_versions SET name='mutated' WHERE case_id=$1",[CASE]),/PR1D_IMMUTABLE/);console.log('PR 1D disposable PostgreSQL ACL, RLS, clone, idempotency, concurrency, fallback, compatibility, and immutability tests passed.');
}finally{if(test)await test.end().catch(()=>{});if(admin){await admin.query(`DROP DATABASE IF EXISTS ${dbName} WITH (FORCE)`).catch(()=>{});for(const r of createdRoles.reverse())await admin.query(`DROP ROLE IF EXISTS ${r}`).catch(()=>{});await admin.end().catch(()=>{})}}
