import fs from 'node:fs';
const candidates=fs.readdirSync('supabase/migrations').filter(name=>/^\d{14}_trust_assurance_evidence_hub\.sql$/.test(name));
if(candidates.length!==1)throw new Error(`Expected exactly one Trust Assurance migration, found ${candidates.length}`);
if(candidates[0]!=='20260808190000_trust_assurance_evidence_hub.sql')throw new Error(`Trust migration must follow the accepted 20260808180000 main tip, found ${candidates[0]}`);
const ordered=fs.readdirSync('supabase/migrations').filter(name=>name.endsWith('.sql')).sort();
if(ordered.at(-1)!==candidates[0]||new Set(ordered.map(name=>name.slice(0,14))).size!==ordered.length)throw new Error('Trust migration chain must have unique ordered versions and the canonical Trust tip');
const file=`supabase/migrations/${candidates[0]}`;const sql=fs.readFileSync(file,'utf8');
const tables=['trust_claims','trust_claim_versions','trust_evidence','trust_evidence_versions','trust_claim_evidence_links','trust_review_events','trust_snapshots','trust_publication_events','trust_current_publications','trust_command_receipts','trust_audit_events'];
for(const table of tables){if(!sql.includes(`CREATE TABLE public.${table}`)||!sql.includes(`'${table}'`))throw new Error(`Missing governed table ${table}`)}
for(const token of ['FORCE ROW LEVEL SECURITY','SECURITY DEFINER','GRANT EXECUTE','TO service_role','IDEMPOTENCY_CONFLICT','VERSION_CONFLICT','PUBLICATION_BLOCKED','FEATURE_DISABLED','trust_assurance_immutable','trust_assurance_hash','trust_assurance_evidence_freshness','trust_assurance_effective_claim_law','trust_assurance_append_review_event','trust_assurance_current_review_disposition','review_ordinal','trust-review:','trust-current-publication:','publication_id=current_publication_id','trust_assurance_internal_projection','trust_assurance_buyer_projection','p_mutations_enabled boolean','pg_advisory_xact_lock','trust_assurance_lock_snapshot_selection','ORDER BY c.id FOR SHARE OF c','ORDER BY e.id,ev.id FOR SHARE OF e',"lifecycle IN('draft','under_review','changes_requested','reviewed')"])if(!sql.includes(token))throw new Error(`Missing migration contract ${token}`);
if(!/REVOKE ALL ON FUNCTION public\.trust_assurance_lock_snapshot_selection\(uuid,uuid,uuid\) FROM PUBLIC,anon,authenticated/.test(sql))throw new Error('Snapshot-selection lock helper must remain private');
if(!/REVOKE ALL ON FUNCTION public\.trust_assurance_append_review_event\([^)]+\),public\.trust_assurance_current_review_disposition\([^)]+\) FROM PUBLIC,anon,authenticated/.test(sql))throw new Error('Review disposition helpers must remain private');
if(/EXISTS\s*\(SELECT 1 FROM public\.trust_review_events[^)]*decision IN\('reviewed','approved'\)/is.test(sql))throw new Error('Historical-positive review authority is prohibited');
if(/INSERT INTO public\.trust_(claims|evidence|snapshots)[^;]+VALUES\s*\(\s*'[0-9a-f-]{36}'/is.test(sql))throw new Error('Tenant seed data prohibited');
console.log(`Trust Assurance migration contract passed (${tables.length} governed tables)`);
