import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import pg from 'pg';
import { approvedFullChainTip } from './prCMigrationTailContract.mjs';
import {validateAssessImportDatabaseUrl} from './assessImportValidationContract.mjs';
import {createEnterpriseIntelligenceFixture} from './enterpriseIntelligencePostgresFixture.mjs';
import {applySyntheticAiTerminalJournalMigrationForTest} from './syntheticAiTerminalJournalMigrationTestGuard.mjs';

const adminUrl=validateAssessImportDatabaseUrl(process.env.ASSESS_DOCUMENT_MAPPING_POSTGRES_ADMIN_URL);
const parsed=new URL(adminUrl);assert.ok(['127.0.0.1','localhost','::1'].includes(parsed.hostname));assert.equal(parsed.pathname,'/postgres');
const {Client}=pg;const uuid=()=>crypto.randomUUID();const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const one=async(db,sql,values=[])=>(await db.query(sql,values)).rows[0];
const count=async(db,table,predicate='true',values=[])=>Number((await one(db,`SELECT count(*)::int n FROM ${table} WHERE ${predicate}`,values)).n);
const expectedFailure=async(operation,pattern)=>{try{await operation();assert.fail('EXPECTED_FAILURE')}catch(error){assert.match(String(error?.message??error),pattern)}};
const transaction=async(db,label,sql)=>{await db.query('BEGIN');try{await db.query(sql);await db.query('COMMIT')}catch(error){await db.query('ROLLBACK');throw new Error(`${label}:${error?.code??'UNKNOWN'}:${error?.message??'failure'}`)}};
const pass=(testId,detail)=>console.log(`ASSESS_DOCUMENT_MAPPING_PG_ASSERTION ${JSON.stringify({testId,result:'passed',detail})}`);
const migrations=(await readdir('supabase/migrations')).filter(name=>name.endsWith('.sql')).sort();
const migration='20261003055918_synthetic_ai_terminal_effect_journal_reconciliation.sql';const predecessor='20261003015246_synthetic_ai_final_paid_validation_continuation.sql';
const featureMigration='20260916083814_assess_supporting_document_mapping.sql';
const migrationIndex=migrations.indexOf(migration);assert.ok(migrationIndex>0);
assert.equal(migrations[migrationIndex-1],predecessor);
assert.equal(migrations[migrationIndex+1],'20261003123459_studio_brd_prompt_v2_semantic_fidelity.sql');
assert.equal(migrations[migrationIndex+2],'20261003150800_synthetic_ai_brd_v2_quality_validation_allowance.sql');
assert.equal(approvedFullChainTip(migrations), '20261010051413');
const readMigration=async(name)=>(await readFile(join('supabase/migrations',name),'utf8')).replaceAll('\r\n','\n');
const migrationSql=await readMigration(migration);
const authBootstrap=`DO $$BEGIN CREATE ROLE anon NOLOGIN;EXCEPTION WHEN duplicate_object THEN NULL;END$$;
DO $$BEGIN CREATE ROLE authenticated NOLOGIN;EXCEPTION WHEN duplicate_object THEN NULL;END$$;
DO $$BEGIN CREATE ROLE service_role NOLOGIN;EXCEPTION WHEN duplicate_object THEN NULL;END$$;
CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key,email text);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULLIF(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;`;
const names=[`ai_final_fresh_${process.pid}_${Date.now()}`,`ai_final_upgrade_${process.pid}_${Date.now()}`];
const urlFor=name=>{const value=new URL(adminUrl);value.pathname=`/${name}`;return value.toString()};
const applyChain=async(db,through)=>{let fixture;for(const name of migrations){if(name===featureMigration)fixture=await createEnterpriseIntelligenceFixture(db,'frd');await applySyntheticAiTerminalJournalMigrationForTest(db,name,async()=>transaction(db,name,await readMigration(name)));if(name===through)break}assert.ok(fixture);return fixture};
const claimReceipt=async(db,fixture,command,label)=>{const request=uuid(),token=uuid(),requestHash=hash(`${command}:${label}`);const row=await one(db,`SELECT (public.enterprise_ai_claim_command($1,$2,$3,$4,$5,$6,$7,NULL,$8)).*`,[fixture.requester,fixture.org,fixture.workspace,command,`final-${label}`,request,requestHash,token]);return{...row,requestHash}};
const seedHistoricalReceipt=async(db,fixture,command,label)=>{const request=uuid(),requestHash=hash(`${command}:${label}`);const row=await one(db,`INSERT INTO public.enterprise_ai_command_receipts(org_id,workspace_id,actor_id,command_type,runtime_area,resource_type,idempotency_key,initial_request_id,last_request_id,request_hash,status,completed_at) VALUES($1,$2,$3,$4,'provider','synthetic_ai_campaign',$5,$6,$6,$7,'committed',statement_timestamp()-interval '9 days') RETURNING *`,[fixture.org,fixture.workspace,fixture.requester,command,`historic-${label}`,request,requestHash]);return{...row,requestHash}};

const admin=new Client({connectionString:adminUrl});const opened=[];
try{
 await admin.connect();const version=Number((await one(admin,"SELECT current_setting('server_version_num')::int version")).version);assert.ok(version>=160000&&version<180000);
 for(const name of names)await admin.query(`CREATE DATABASE ${name}`);
 const fresh=new Client({connectionString:urlFor(names[0])});opened.push(fresh);await fresh.connect();await transaction(fresh,'auth-bootstrap',authBootstrap);await applyChain(fresh,migration);
 assert.deepEqual(await one(fresh,`SELECT (SELECT migration_tip FROM public.hosted_pilot_environment_identity WHERE singleton) tip,
  (SELECT count(*)::int FROM public.synthetic_ai_mapping_no_effect_reconciliations) reconciliations,
  (SELECT count(*)::int FROM public.synthetic_ai_campaign_final_continuations) continuations,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='public.synthetic_ai_campaign_final_continuations'::regclass) forced_rls,
  has_table_privilege('service_role','public.synthetic_ai_campaign_final_continuations','SELECT') service_select,
  has_table_privilege('service_role','public.synthetic_ai_campaign_final_continuations','INSERT') service_insert,
  (SELECT count(*)::int FROM pg_attribute WHERE attrelid='public.synthetic_ai_mapping_no_effect_reconciliations'::regclass
    AND attname IN('effect_journal_id','effect_journal_row_hash') AND attnotnull AND NOT attisdropped) journal_columns`),
  {tip:'20261003055918',reconciliations:0,continuations:0,forced_rls:true,service_select:true,service_insert:false,journal_columns:2});
 pass('MAP-PG-FINAL-001-fresh-chain','fresh chain creates empty forced-RLS recovery and final-continuation authorities with exact journal binding at the new tip');

 const db=new Client({connectionString:urlFor(names[1])});opened.push(db);await db.connect();await transaction(db,'auth-bootstrap',authBootstrap);const fixture=await applyChain(db,predecessor);
 await db.query(`INSERT INTO public.role_capabilities(role_id,capability_key) SELECT $1,unnest($2::text[]) ON CONFLICT DO NOTHING`,[fixture.routeRole,['org.admin','admin.synthetic.users.manage','assess.v2.read','assess.v2.draft.write','evidence.write','studio.artifacts.generate']]);
 const authVersion=Number((await one(db,'SELECT version FROM public.authorization_versions WHERE org_id=$1 AND user_id=$2',[fixture.org,fixture.requester])).version);
 const projectRef='abcdefghijklmnopqrst',requestHost=`${projectRef}.supabase.co`,fingerprint=`sha256:${'b'.repeat(64)}`;
 await db.query("SELECT set_config('request.headers',$1,false)",[JSON.stringify({host:requestHost})]);
 await db.query(`UPDATE public.enterprise_intelligence_runtime_control SET enabled=true,read_only=false,provider_enabled=false WHERE singleton`);
 await db.query(`UPDATE public.studio_artifact_runtime_control SET enabled=true,read_only=false,provider_enabled=false WHERE singleton`);
 await db.query(`UPDATE public.ai_provider_key_refs SET secret_ref=$2,status='active' WHERE id=$1`,[fixture.keyRef,`AVALA_PROVIDER_SECRET_OPENAI_${fixture.org.replaceAll('-','').toUpperCase()}_QA`]);
 await db.query(`UPDATE public.ai_provider_configs SET default_model='gpt-4.1-mini-2025-04-14',model_allowlist=ARRAY['gpt-4.1-mini-2025-04-14'],endpoint_url='https://api.openai.com',last_validated_at=statement_timestamp()-interval '2 days',status='active' WHERE id=$1`,[fixture.provider]);
 const assessRoute=uuid(),studioRoute=uuid(),targetId=uuid();
 for(const [id,capability] of [[assessRoute,'assess.evidence.extract'],[studioRoute,'studio.document.generate']])await db.query(`INSERT INTO public.enterprise_ai_capability_routes(id,org_id,workspace_id,provider_config_id,capability,model,enabled,allowed_roles,version,created_by,updated_by) VALUES($1,$2,$3,$4,$5,'gpt-4.1-mini-2025-04-14',true,ARRAY[$6::text],1,$7,$7)`,[id,fixture.org,fixture.workspace,fixture.provider,capability,fixture.routeRole,fixture.requester]);
 await db.query(`INSERT INTO public.synthetic_admin_targets(id,target_fingerprint,org_id,workspace_id,operator_actor_id,organization_member_role_id,environment_class,enabled) VALUES($1,$2,$3,$4,$5,$6,'hosted_nonproduction_pilot',true)`,[targetId,fingerprint,fixture.org,fixture.workspace,fixture.requester,fixture.role]);
 const campaignId=(await one(db,`INSERT INTO public.synthetic_ai_campaign_authorities(target_id,target_fingerprint,project_ref,server_host,local_carry_seal_digest,org_id,workspace_id,operator_actor_id,provider_config_id,key_ref_id,assess_route_id,studio_route_id,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,statement_timestamp()-interval '20 days',statement_timestamp()-interval '19 days') RETURNING id`,[targetId,fingerprint,projectRef,requestHost,`sha256:${'c'.repeat(64)}`,fixture.org,fixture.workspace,fixture.requester,fixture.provider,fixture.keyRef,assessRoute,studioRoute])).id;
 const renewalId=uuid();await db.query(`INSERT INTO public.synthetic_ai_campaign_renewals(id,campaign_id,renewed_by,authorization_version,target_fingerprint,project_ref,server_host,org_id,workspace_id,provider_config_id,key_ref_id,assess_route_id,studio_route_id,binding_digest,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,statement_timestamp()-interval '10 days',statement_timestamp()-interval '9 days')`,[renewalId,campaignId,fixture.requester,authVersion,fingerprint,projectRef,requestHost,fixture.org,fixture.workspace,fixture.provider,fixture.keyRef,assessRoute,studioRoute,`sha256:${'d'.repeat(64)}`]);

 const setId=uuid(),setVersion=uuid(),bundleId=uuid(),bundleVersion=uuid(),source=fixture.sources[0];
 const sourceRow=await one(db,'SELECT content_hash,extracted_text_hash,extracted_character_count FROM public.enterprise_evidence_source_versions WHERE id=$1',[source.sourceVersionId]);
 await db.query(`INSERT INTO public.enterprise_source_sets(id,org_id,workspace_id,owner_module,display_label,current_version,status,created_by) VALUES($1,$2,$3,'studio','Final joined source',1,'locked',$4)`,[setId,fixture.org,fixture.workspace,fixture.requester]);
 await db.query(`INSERT INTO public.enterprise_source_set_versions(id,source_set_id,org_id,workspace_id,version,purpose,manifest_hash,source_count,extracted_character_count,status,created_by) VALUES($1,$2,$3,$4,1,'Final joined source',$5,1,$6,'locked',$7)`,[setVersion,setId,fixture.org,fixture.workspace,hash('final-set'),Number(sourceRow.extracted_character_count),fixture.requester]);
 await db.query(`INSERT INTO public.enterprise_source_set_version_items(source_set_version_id,source_set_id,source_version_id,source_id,org_id,workspace_id,ordinal,semantic_role,content_hash,extracted_text_hash,extracted_character_count) VALUES($1,$2,$3,$4,$5,$6,1,'primary',$7,$8,$9)`,[setVersion,setId,source.sourceVersionId,source.sourceId,fixture.org,fixture.workspace,sourceRow.content_hash,sourceRow.extracted_text_hash,Number(sourceRow.extracted_character_count)]);
 await db.query(`INSERT INTO public.enterprise_module_input_bundles(id,org_id,workspace_id,owner_module,current_version,created_by) VALUES($1,$2,$3,'studio',1,$4)`,[bundleId,fixture.org,fixture.workspace,fixture.requester]);
 await db.query(`INSERT INTO public.enterprise_module_input_bundle_versions(id,input_bundle_id,org_id,workspace_id,version,bundle_hash,status,created_by) VALUES($1,$2,$3,$4,1,$5,'locked',$6)`,[bundleVersion,bundleId,fixture.org,fixture.workspace,hash('final-bundle'),fixture.requester]);
 await db.query(`INSERT INTO public.enterprise_module_input_bundle_items(input_bundle_version_id,input_bundle_id,org_id,workspace_id,ordinal,item_kind,source_set_version_id,source_set_id,resource_hash,declared_purpose) VALUES($1,$2,$3,$4,1,'source_set',$5,$6,$7,'Final joined generation')`,[bundleVersion,bundleId,fixture.org,fixture.workspace,setVersion,setId,hash('final-set')]);

 await db.query(`UPDATE public.enterprise_intelligence_runtime_control SET provider_enabled=true WHERE singleton`);
 await db.query(`UPDATE public.studio_artifact_runtime_control SET provider_enabled=true WHERE singleton`);

 const historicalActor=fixture.reviewer,historicalVersion=authVersion+17,historicalFixture={...fixture,requester:historicalActor};assert.notEqual(historicalActor,fixture.requester);
 const failedReceipt=await claimReceipt(db,historicalFixture,'assess.document-map.analyze','historic-failed-mapping'),failedCatalog=uuid(),failedRun=uuid();
 await db.query(`INSERT INTO public.enterprise_assess_document_mapping_catalogs(id,org_id,workspace_id,assess_case_id,assess_case_version_id,case_version,assess_schema_version,contract_version,catalog_version,catalog_hash,status,receipt_id,created_by) VALUES($1,$2,$3,$4,$5,1,'assess-v2-schema-2026-07','assess-supporting-document-map-v1',1,$6,'current',$7,$8)`,[failedCatalog,fixture.org,fixture.workspace,fixture.caseId,fixture.sourceVersion,hash('failed-catalog'),failedReceipt.id,historicalActor]);
 await db.query(`INSERT INTO public.enterprise_assess_document_mapping_runs(id,org_id,workspace_id,catalog_id,assess_case_id,case_version,input_bundle_id,input_bundle_version_id,input_bundle_version,bundle_hash,route_id,provider_config_id,provider,model,prompt_version,authorization_version,status,claim_binding_hash,execution_token,execution_fence,receipt_id,created_by) VALUES($1,$2,$3,$4,$5,1,$6,$7,1,$8,$9,$10,'openai','gpt-4.1-mini-2025-04-14','assess-supporting-document-map-v1',$11,'claimed',$12,$13,$14,$15,$16)`,[failedRun,fixture.org,fixture.workspace,failedCatalog,fixture.caseId,bundleId,bundleVersion,hash('final-bundle'),assessRoute,fixture.provider,historicalVersion,hash('failed-claim'),failedReceipt.execution_token,failedReceipt.execution_fence,failedReceipt.id,historicalActor]);
 const failedResponse={ok:false,error:{code:'COMMAND_UNAVAILABLE'}};await db.query(`UPDATE public.enterprise_ai_command_receipts SET status='failed',response=$2::jsonb,response_hash=public.enterprise_sha256_jsonb($2::jsonb),completed_at=statement_timestamp() WHERE id=$1`,[failedReceipt.id,JSON.stringify(failedResponse)]);
 const failedJournal=uuid();await db.query(`INSERT INTO public.enterprise_ai_effect_journal(id,receipt_id,org_id,workspace_id,operation_type,effect_key,resource_id,terminal_status,safe_result,result_hash,execution_fence,committed_at) SELECT $1,id,org_id,workspace_id,'assess.document-map.analyze','command',NULL,'failed',response,response_hash,execution_fence,completed_at FROM public.enterprise_ai_command_receipts WHERE id=$2`,[failedJournal,failedReceipt.id]);
 const failedReservation=uuid();await db.query(`INSERT INTO public.enterprise_ai_budget_reservations(id,receipt_id,job_id,authority_kind,assess_mapping_run_id,org_id,workspace_id,actor_id,authorization_version,route_id,provider_config_id,provider,capability,model,state,estimated_input_tokens,maximum_output_tokens,failure_class,execution_token,execution_fence,day_bucket,month_bucket,reserved_at,updated_at) VALUES($1,$2,NULL,'assess_mapping',$3,$4,$5,$6,$7,$8,$9,'openai','assess.evidence.extract','gpt-4.1-mini-2025-04-14','uncertain',30505,4096,'provider_request_failed',$10,$11,date '2026-09-23',date '2026-09-01',timestamptz '2026-09-23 05:22:54.727991+00',timestamptz '2026-09-23 05:22:54.727991+00')`,[failedReservation,failedReceipt.id,failedRun,fixture.org,fixture.workspace,historicalActor,historicalVersion,assessRoute,fixture.provider,failedReceipt.execution_token,failedReceipt.execution_fence]);

 const operations=['provider.validate','provider.validate','assess.evidence.extract','studio.document.generate','studio.document.generate','studio.document.generate'];const retained=[];
 for(let i=0;i<operations.length;i+=1){const item=await seedHistoricalReceipt(db,fixture,operations[i],`retained-${i}`);const debit=uuid(),effect=uuid(),route=operations[i]==='provider.validate'?null:operations[i]==='assess.evidence.extract'?assessRoute:studioRoute;await db.query(`INSERT INTO public.synthetic_ai_campaign_effect_debits(id,campaign_id,renewal_id,receipt_id,effect_id,authority_kind,actor_id,org_id,workspace_id,authorization_version,execution_token,execution_fence,command_request_hash,effect_request_hash,maximum_output_tokens,operation,route_id,provider_config_id,key_ref_id,provider,endpoint,model,debit_usd_nanos,reserved_at,consumed_at) VALUES($1,$2,$3,$4,$5,'enterprise',$6,$7,$8,$9,$10,$11,$12,$13,4096,$14,$15,$16,$17,'openai','https://api.openai.com','gpt-4.1-mini-2025-04-14',471459200,statement_timestamp()-interval '9 days',statement_timestamp()-interval '9 days')`,[debit,campaignId,i===0?null:renewalId,item.id,effect,fixture.requester,fixture.org,fixture.workspace,authVersion,item.execution_token,item.execution_fence,item.requestHash,hash(`retained-effect-${i}`),operations[i],route,fixture.provider,fixture.keyRef]);retained.push({debit,item,effect,operation:operations[i],route})}
 await db.query(`UPDATE public.enterprise_intelligence_runtime_control SET provider_enabled=false WHERE singleton`);
 await db.query(`UPDATE public.studio_artifact_runtime_control SET provider_enabled=false WHERE singleton`);

 const artifactId=uuid(),packageId=uuid(),routePolicy=(await one(db,'SELECT public.enterprise_assess_studio_route_policy() value')).value,routeHash=(await one(db,'SELECT public.enterprise_sha256_jsonb($1::jsonb) value',[JSON.stringify(routePolicy)])).value;const upstream=await one(db,'SELECT package_hash,source_version_id FROM public.assess_v2_studio_handoffs WHERE id=$1',[fixture.handoff]);const candidateManifest=[];const candidateHash=(await one(db,'SELECT public.enterprise_sha256_jsonb($1::jsonb) value',[JSON.stringify(candidateManifest)])).value;const anchorManifest=(await one(db,'SELECT public.studio_pr_b_anchor_manifest($1::jsonb,$2,$3) value',[JSON.stringify(candidateManifest),upstream.source_version_id,upstream.package_hash])).value;const anchorHash=(await one(db,'SELECT public.enterprise_sha256_jsonb($1::jsonb) value',[JSON.stringify(anchorManifest)])).value;const packageHash=(await one(db,`SELECT public.enterprise_sha256_jsonb(jsonb_build_object('contractVersion','studio-source-package-1','sourceMode','assess_handoff','upstreamHandoffId',$1::uuid,'upstreamPackageHash',$2::text,'studioInputBundleVersionId',NULL,'studioBundleHash',NULL,'manualBriefHash',NULL,'candidateManifestHash',$3::text,'anchorManifestHash',$4::text,'artifactType','brd','routePolicyVersion',1,'routePolicyHash',$5::text)) value`,[fixture.handoff,upstream.package_hash,candidateHash,anchorHash,routeHash])).value;
 await db.query('BEGIN');try{await db.query('SET CONSTRAINTS ALL DEFERRED');await db.query(`INSERT INTO public.studio_artifact_aggregates(id,org_id,workspace_id,case_id,source_version_id,source_case_version,decision_id,decision_version,review_resolution_id,govern_resolution_id,handoff_id,source_package_hash,source_schema_version,rule_set_version,review_schema_version,review_sequence,artifact_type,aggregate_version,lifecycle,created_by,source_package_id,source_mode,lineage_classification,planning_only) VALUES($1,$2,$3,$4,$5,1,$6,'decision-1',$7,$8,$9,$10,'schema','rules','assess-v2-review-2026-07',1,'brd',0,'draft',$11,$12,'assess_handoff','assessed',false)`,[artifactId,fixture.org,fixture.workspace,fixture.caseId,fixture.sourceVersion,fixture.decision,fixture.resolution,fixture.govern,fixture.handoff,packageHash,fixture.requester,packageId]);await db.query(`INSERT INTO public.studio_artifact_source_packages(id,artifact_id,org_id,workspace_id,version,source_mode,assess_handoff_id,assess_package_hash,studio_input_bundle_id,studio_input_bundle_version_id,studio_input_bundle_version,studio_bundle_hash,lineage_classification,planning_only,route_policy_version,route_policy_snapshot,route_policy_hash,package_hash,created_by,candidate_manifest,candidate_manifest_hash,candidate_count,anchor_manifest,anchor_manifest_hash,anchor_count) VALUES($1,$2,$3,$4,1,'assess_handoff',$5,$6,NULL,NULL,NULL,NULL,'assessed',false,1,$7::jsonb,$8,$9,$10,'[]'::jsonb,$11,0,$12::jsonb,$13,$14)`,[packageId,artifactId,fixture.org,fixture.workspace,fixture.handoff,upstream.package_hash,JSON.stringify(routePolicy),routeHash,packageHash,fixture.requester,candidateHash,JSON.stringify(anchorManifest),anchorHash,anchorManifest.length]);await db.query('COMMIT')}catch(error){await db.query('ROLLBACK');throw error}

 const reconcileSql=`SELECT public.synthetic_ai_reconcile_mapping_no_effect_once($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) result`,reconcileArgs=[fixture.requester,fixture.org,fixture.workspace,authVersion,fingerprint,projectRef,campaignId,failedReservation,failedReceipt.id,failedRun];
 await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_UNSAFE/);
 assert.deepEqual(await one(db,'SELECT state,release_reason FROM public.enterprise_ai_budget_reservations WHERE id=$1',[failedReservation]),{state:'uncertain',release_reason:null});assert.equal(await count(db,'public.synthetic_ai_mapping_no_effect_reconciliations'),0);
 const before=await one(db,`SELECT md5(to_jsonb(authority)::text) campaign,(SELECT md5(COALESCE(jsonb_agg(to_jsonb(debit) ORDER BY debit.id),'[]'::jsonb)::text) FROM public.synthetic_ai_campaign_effect_debits debit WHERE debit.campaign_id=authority.id) debits FROM public.synthetic_ai_campaign_authorities authority WHERE authority.id=$1`,[campaignId]);
 await transaction(db,migration,migrationSql);const after=await one(db,`SELECT md5(to_jsonb(authority)::text) campaign,(SELECT md5(COALESCE(jsonb_agg(to_jsonb(debit) ORDER BY debit.id),'[]'::jsonb)::text) FROM public.synthetic_ai_campaign_effect_debits debit WHERE debit.campaign_id=authority.id) debits FROM public.synthetic_ai_campaign_authorities authority WHERE authority.id=$1`,[campaignId]);assert.deepEqual(after,before);
 pass('MAP-PG-FINAL-002-populated-upgrade','deployed recovery rejects the legitimate failed journal; forward upgrade preserves all charge history and binds the correction');

 const activationSql=`SELECT public.synthetic_ai_campaign_activate_final_continuation($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) result`;const releaseSha='a'.repeat(40),attestation=`sha256:${'e'.repeat(64)}`,activationArgs=[fixture.requester,fixture.org,fixture.workspace,authVersion,fingerprint,projectRef,campaignId,fixture.provider,fixture.keyRef,assessRoute,studioRoute,packageId,artifactId,releaseSha,attestation,300];
 const recoveryHistorySql=`SELECT to_jsonb(reservation)-ARRAY['state','release_reason','updated_at','settled_at'] snapshot FROM public.enterprise_ai_budget_reservations reservation WHERE id=$1`,recoveryHistoryBefore=(await one(db,recoveryHistorySql,[failedReservation])).snapshot;
 const originalHistorySql=`SELECT (SELECT to_jsonb(c) FROM public.enterprise_ai_command_receipts c WHERE id=$1) receipt,(SELECT to_jsonb(m) FROM public.enterprise_assess_document_mapping_runs m WHERE id=$2) mapping,(SELECT to_jsonb(j) FROM public.enterprise_ai_effect_journal j WHERE id=$3) journal`,originalHistoryBefore=await one(db,originalHistorySql,[failedReceipt.id,failedRun,failedJournal]);
 const journalMutations=[
  ['org_id=$2::uuid',[uuid()]],['workspace_id=$2::uuid',[uuid()]],
  ["operation_type='assess.document-map.commit'",[]],["effect_key='other-command'",[]],
  ['resource_id=$2::uuid',[uuid()]],["terminal_status='committed'",[]],
  ["safe_result='{}'::jsonb",[]],['result_hash=$2',[hash('wrong-journal-result')]],
  ['execution_fence=execution_fence+1',[]],["committed_at=committed_at+interval '1 second'",[]],
 ];
 const rejectJournalDrift=async(pattern)=>{for(const [assignment,args] of journalMutations){await db.query('BEGIN');try{await db.query('SET LOCAL session_replication_role=replica');await db.query(`UPDATE public.enterprise_ai_effect_journal SET ${assignment} WHERE id=$1`,[failedJournal,...args]);await db.query('SET LOCAL session_replication_role=origin');await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),pattern)}finally{await db.query('ROLLBACK')}}};
 const rejectHistoricalDrift=async()=>{for(const [query,args] of [
  ['UPDATE public.enterprise_assess_document_mapping_runs SET created_by=$2 WHERE id=$1',[failedRun,fixture.requester]],
  ['UPDATE public.enterprise_assess_document_mapping_runs SET authorization_version=authorization_version+1 WHERE id=$1',[failedRun]],
  ['UPDATE public.enterprise_ai_budget_reservations SET execution_token=$2 WHERE id=$1',[failedReservation,uuid()]],
  ['UPDATE public.enterprise_ai_budget_reservations SET execution_fence=execution_fence+1 WHERE id=$1',[failedReservation]],
 ]){await db.query('BEGIN');try{await db.query(query,args);await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_LINEAGE_MISMATCH/)}finally{await db.query('ROLLBACK')}}};
 await expectedFailure(()=>db.query('UPDATE public.enterprise_ai_effect_journal SET safe_result=safe_result WHERE id=$1',[failedJournal]),/ENTERPRISE_AI_EFFECT_JOURNAL_IMMUTABLE/);
 await rejectJournalDrift(/SYNTHETIC_AI_MAPPING_RECONCILIATION_(UNSAFE|LINEAGE_MISMATCH)/);
 await db.query('BEGIN');try{await db.query('SET LOCAL session_replication_role=replica');await db.query('DELETE FROM public.enterprise_ai_effect_journal WHERE id=$1',[failedJournal]);await db.query('SET LOCAL session_replication_role=origin');await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_UNSAFE/)}finally{await db.query('ROLLBACK')}
 await db.query('BEGIN');try{await db.query(`INSERT INTO public.enterprise_ai_effect_journal(id,receipt_id,org_id,workspace_id,operation_type,effect_key,resource_id,terminal_status,safe_result,result_hash,execution_fence,committed_at) SELECT $2,receipt_id,org_id,workspace_id,operation_type,'extra-command',resource_id,terminal_status,safe_result,result_hash,execution_fence,committed_at FROM public.enterprise_ai_effect_journal WHERE id=$1`,[failedJournal,uuid()]);await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_UNSAFE/)}finally{await db.query('ROLLBACK')}
 await rejectHistoricalDrift();
 await expectedFailure(()=>db.query(activationSql,activationArgs),/SYNTHETIC_AI_FINAL_CONTINUATION_HISTORY_UNSAFE/);
 await expectedFailure(()=>db.query(reconcileSql,[...reconcileArgs.slice(0,3),authVersion+1,...reconcileArgs.slice(4)]),/PR1B_AUTHORIZATION_STALE/);
 await db.query('BEGIN');try{await db.query(`UPDATE public.enterprise_intelligence_runtime_control SET provider_enabled=true WHERE singleton`);await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_RUNTIME_NOT_OFF/)}finally{await db.query('ROLLBACK')}
 await db.query('BEGIN');try{await db.query(`UPDATE public.enterprise_assess_document_mapping_runs SET staged_payload_hash=$2 WHERE id=$1`,[failedRun,hash('forbidden-stage')]);await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_UNSAFE/)}finally{await db.query('ROLLBACK')}
 await db.query('BEGIN');try{await db.query(`INSERT INTO public.synthetic_ai_campaign_effect_debits(campaign_id,receipt_id,effect_id,authority_kind,assess_mapping_run_id,actor_id,org_id,workspace_id,authorization_version,execution_token,execution_fence,command_request_hash,effect_request_hash,maximum_output_tokens,operation,route_id,provider_config_id,key_ref_id,provider,endpoint,model,debit_usd_nanos,reserved_at,consumed_at) VALUES($1,$2,$3,'assess_mapping',$3,$4,$5,$6,$7,$8,$9,$10,$11,4096,'assess.evidence.extract',$12,$13,$14,'openai','https://api.openai.com','gpt-4.1-mini-2025-04-14',471459200,statement_timestamp(),statement_timestamp())`,[campaignId,failedReceipt.id,failedRun,fixture.requester,fixture.org,fixture.workspace,authVersion,failedReceipt.execution_token,failedReceipt.execution_fence,failedReceipt.requestHash,hash('forbidden-mapping-debit'),assessRoute,fixture.provider,fixture.keyRef]);await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_UNSAFE/)}finally{await db.query('ROLLBACK')}
 pass('MAP-PG-FINAL-003-recovery-negatives','all terminal-journal fields, missing/extra journals, stale admin, runtime-on, staged output, and any matching debit fail closed');

 const reconciliationClients=[];try{for(let i=0;i<2;i++){const client=new Client({connectionString:urlFor(names[1])});reconciliationClients.push(client);await client.connect();await client.query("SELECT set_config('request.headers',$1,false)",[JSON.stringify({host:requestHost})])}const results=await Promise.all(reconciliationClients.map(client=>one(client,reconcileSql,reconcileArgs)));assert.deepEqual(results[0].result,results[1].result)}finally{await Promise.allSettled(reconciliationClients.map(client=>client.end()))}
 assert.deepEqual(await one(db,`SELECT state,release_reason,failure_class,reserved_at,reserved_tokens FROM public.enterprise_ai_budget_reservations WHERE id=$1`,[failedReservation]),{state:'released',release_reason:'reconciled_no_effect',failure_class:'provider_request_failed',reserved_at:new Date('2026-09-23T05:22:54.727Z'),reserved_tokens:34601});assert.deepEqual((await one(db,recoveryHistorySql,[failedReservation])).snapshot,recoveryHistoryBefore);assert.equal(await count(db,'public.synthetic_ai_mapping_no_effect_reconciliations'),1);assert.equal(await count(db,'public.synthetic_ai_campaign_effect_debits','receipt_id=$1 OR assess_mapping_run_id=$2 OR effect_id=$2',[failedReceipt.id,failedRun]),0);
 const boundJournal=await one(db,`SELECT effect_journal_id,effect_journal_row_hash,public.enterprise_sha256_jsonb(to_jsonb(journal)) canonical_hash FROM public.synthetic_ai_mapping_no_effect_reconciliations reconciliation JOIN public.enterprise_ai_effect_journal journal ON journal.id=reconciliation.effect_journal_id`);assert.equal(boundJournal.effect_journal_id,failedJournal);assert.equal(boundJournal.effect_journal_row_hash,boundJournal.canonical_hash);
 pass('MAP-PG-FINAL-004-exact-recovery','concurrent recovery binds one canonical terminal journal, replays exactly, releases only the reservation, and preserves full history');
 assert.deepEqual(await one(db,originalHistorySql,[failedReceipt.id,failedRun,failedJournal]),originalHistoryBefore);
 assert.deepEqual(await one(db,'SELECT actor_id,historical_actor_id,authorization_version,historical_authorization_version FROM public.synthetic_ai_mapping_no_effect_reconciliations'),{actor_id:fixture.requester,historical_actor_id:historicalActor,authorization_version:String(authVersion),historical_authorization_version:String(historicalVersion)});
 await rejectJournalDrift(/SYNTHETIC_AI_MAPPING_RECONCILIATION_(UNSAFE|LINEAGE_MISMATCH|REPLAY_MISMATCH)/);
 await db.query('BEGIN');try{await db.query('SET LOCAL session_replication_role=replica');await db.query('UPDATE public.enterprise_ai_effect_journal SET id=$2 WHERE id=$1',[failedJournal,uuid()]);await db.query('SET LOCAL session_replication_role=origin');await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_REPLAY_MISMATCH/)}finally{await db.query('ROLLBACK')}
 await rejectHistoricalDrift();
 await db.query('BEGIN');try{await db.query('UPDATE public.enterprise_assess_document_mapping_runs SET authorization_version=authorization_version+1 WHERE id=$1',[failedRun]);await db.query('UPDATE public.enterprise_ai_budget_reservations SET authorization_version=authorization_version+1 WHERE id=$1',[failedReservation]);await expectedFailure(()=>db.query(reconcileSql,reconcileArgs),/SYNTHETIC_AI_MAPPING_RECONCILIATION_REPLAY_MISMATCH/)}finally{await db.query('ROLLBACK')}

 const substitutedPackage=(await one(db,'SELECT id FROM public.studio_artifact_source_packages WHERE artifact_id=$1',[fixture.artifactId])).id;await expectedFailure(()=>db.query(activationSql,[...activationArgs.slice(0,11),substitutedPackage,fixture.artifactId,...activationArgs.slice(13)]),/SYNTHETIC_AI_FINAL_CONTINUATION_HISTORY_UNSAFE/);
 await db.query('BEGIN');try{await db.query(`UPDATE public.enterprise_intelligence_runtime_control SET provider_enabled=true WHERE singleton`);await expectedFailure(()=>db.query(activationSql,activationArgs),/SYNTHETIC_AI_FINAL_CONTINUATION_RUNTIME_NOT_OFF/)}finally{await db.query('ROLLBACK')}
 const activationClients=[];let activationResults;try{for(let i=0;i<2;i++){const client=new Client({connectionString:urlFor(names[1])});activationClients.push(client);await client.connect();await client.query("SELECT set_config('request.headers',$1,false)",[JSON.stringify({host:requestHost})])}activationResults=await Promise.all(activationClients.map(client=>one(client,activationSql,activationArgs)));assert.deepEqual(activationResults[0].result,activationResults[1].result)}finally{await Promise.allSettled(activationClients.map(client=>client.end()))}
 const continuation=await one(db,'SELECT * FROM public.synthetic_ai_campaign_final_continuations');assert.equal(await count(db,'public.synthetic_ai_campaign_final_continuations'),1);assert.equal(Number(activationResults[0].result.maximumAggregateUsdNanos),4640993600);await expectedFailure(()=>db.query(activationSql,[...activationArgs.slice(0,13),'b'.repeat(40),...activationArgs.slice(14)]),/SYNTHETIC_AI_FINAL_CONTINUATION_REPLAY_MISMATCH/);
 pass('MAP-PG-FINAL-005-activation-once','concurrent exact activation appends one immutable final window; exact replay matches and source substitution rejects');

 await db.query(`UPDATE public.enterprise_intelligence_runtime_control SET provider_enabled=true WHERE singleton`);
 const validation=await claimReceipt(db,fixture,'provider.validate','final-validation');const reserveValidationSql=`SELECT public.synthetic_ai_campaign_reserve_effect($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,NULL,$11,$12,'openai','https://api.openai.com','gpt-4.1-mini-2025-04-14','provider.validate',$13,4096) result`;const validationArgs=[fixture.requester,fixture.org,fixture.workspace,authVersion,fingerprint,projectRef,validation.id,uuid(),validation.execution_token,validation.execution_fence,fixture.provider,fixture.keyRef,hash('final-validation-effect')];const validationPermit=(await one(db,reserveValidationSql,validationArgs)).result;assert.equal(validationPermit.ownsProviderEffect,true);assert.equal((await one(db,'SELECT final_continuation_id FROM public.synthetic_ai_campaign_effect_debits WHERE id=$1',[validationPermit.reservationId])).final_continuation_id,continuation.id);
 await expectedFailure(()=>db.query(`SELECT public.synthetic_ai_campaign_consume_effect($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NULL,$12,$13,'openai','https://api.openai.com','gpt-4.1-mini-2025-04-14','provider.validate',$14,4096)`,[retained[0].debit,fixture.requester,fixture.org,fixture.workspace,authVersion,fingerprint,projectRef,retained[0].item.id,retained[0].effect,retained[0].item.execution_token,retained[0].item.execution_fence,fixture.provider,fixture.keyRef,hash('retained-effect-0')]),/SYNTHETIC_AI_CAMPAIGN_(PERMIT_INVALID_OR_REPLAYED|RECEIPT_STALE)/);
 await db.query(`SELECT public.synthetic_ai_campaign_consume_effect($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NULL,$12,$13,'openai','https://api.openai.com','gpt-4.1-mini-2025-04-14','provider.validate',$14,4096)`,[validationPermit.reservationId,fixture.requester,fixture.org,fixture.workspace,authVersion,fingerprint,projectRef,validation.id,validationArgs[7],validation.execution_token,validation.execution_fence,fixture.provider,fixture.keyRef,validationArgs[12]]);const replay=(await one(db,reserveValidationSql,validationArgs)).result;assert.equal(replay.replayed,true);assert.equal(replay.ownsProviderEffect,false);
 pass('MAP-PG-FINAL-006-validation-slot','one final validation permit consumes once, exact replay creates no debit, and an old renewal permit cannot cross windows');

 await db.query(`UPDATE public.studio_artifact_runtime_control SET provider_enabled=true WHERE singleton`);
 const studioReceipt=uuid(),studioAttempt=uuid(),studioToken=uuid(),template=await one(db,"SELECT id,template_version,template_hash FROM public.studio_system_template_versions WHERE artifact_type='brd' AND superseded_at IS NULL");await db.query(`INSERT INTO public.studio_artifact_command_receipts(id,org_id,workspace_id,actor_id,command_type,idempotency_key,request_id,request_hash,status,resource_id,response,completed_at) VALUES($1,$2,$3,$4,'studio.artifact.generation.request.v2','final-joined-generation',$5,$6,'committed',$7,$8::jsonb,statement_timestamp())`,[studioReceipt,fixture.org,fixture.workspace,fixture.requester,uuid(),hash('studio-receipt'),artifactId,JSON.stringify({attemptId:studioAttempt})]);await db.query(`INSERT INTO public.studio_artifact_generation_attempts(id,artifact_id,org_id,workspace_id,handoff_id,requested_by,request_id,template_id,input_hash,state,source_package_id,source_package_hash,template_kind,template_version,template_hash,expected_aggregate_version,requester_authorization_version,provider_plan_state,provider_route_id,provider_config_id,provider_name,provider_model,prompt_key,prompt_version,provider_plan_hash,execution_token,execution_fence,provider_effect_key,candidate_manifest_hash,candidate_count,anchor_manifest_hash,anchor_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'generating',$10,$11,'system',$12,$13,0,$14,'bound',$15,$16,'openai','gpt-4.1-mini-2025-04-14','studio-multisource-generation','studio-pr-b-1',$17,$18,1,$19,$20,0,$21,$22)`,[studioAttempt,artifactId,fixture.org,fixture.workspace,fixture.handoff,fixture.requester,uuid(),template.id,hash('studio-input'),packageId,packageHash,template.template_version,template.template_hash,authVersion,studioRoute,fixture.provider,hash('studio-plan'),studioToken,hash('studio-effect'),candidateHash,anchorHash,anchorManifest.length]);await db.query(`INSERT INTO public.enterprise_ai_budget_reservations(receipt_id,job_id,authority_kind,studio_receipt_id,studio_attempt_id,org_id,workspace_id,actor_id,authorization_version,route_id,provider_config_id,provider,capability,model,state,estimated_input_tokens,maximum_output_tokens,execution_token,execution_fence,day_bucket,month_bucket) VALUES(NULL,NULL,'studio',$1,$2,$3,$4,$5,$6,$7,$8,'openai','studio.document.generate','gpt-4.1-mini-2025-04-14','reserved',100,4096,$9,1,current_date,date_trunc('month',current_date)::date)`,[studioReceipt,studioAttempt,fixture.org,fixture.workspace,fixture.requester,authVersion,studioRoute,fixture.provider,studioToken]);
 const studioEffectHash=hash('studio-final-effect'),reserveStudioSql=`SELECT public.synthetic_ai_campaign_reserve_effect($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'openai','https://api.openai.com','gpt-4.1-mini-2025-04-14','studio.document.generate',$14,4096) result`,studioArgs=[fixture.requester,fixture.org,fixture.workspace,authVersion,fingerprint,projectRef,studioReceipt,studioAttempt,studioToken,1,studioRoute,fixture.provider,fixture.keyRef,studioEffectHash];
 await expectedFailure(()=>db.query(reserveStudioSql,studioArgs),/SYNTHETIC_AI_CAMPAIGN_(EFFECT_SLOT_NOT_AUTHORIZED|PROVIDER_STALE)/);await db.query('UPDATE public.ai_provider_configs SET last_validated_at=statement_timestamp() WHERE id=$1',[fixture.provider]);const studioPermit=(await one(db,reserveStudioSql,studioArgs)).result;assert.equal(studioPermit.ownsProviderEffect,true);await expectedFailure(()=>db.query(reserveStudioSql,[...studioArgs.slice(0,10),assessRoute,...studioArgs.slice(11)]),/SYNTHETIC_AI_CAMPAIGN_(PERMIT_INVALID_OR_REPLAYED|EFFECT_SLOT_NOT_AUTHORIZED|DOMAIN_STALE)/);const third=await claimReceipt(db,fixture,'provider.validate','forbidden-third'),thirdArgs=[fixture.requester,fixture.org,fixture.workspace,authVersion,fingerprint,projectRef,third.id,uuid(),third.execution_token,third.execution_fence,fixture.provider,fixture.keyRef,hash('forbidden-third-effect')];await expectedFailure(()=>db.query(reserveValidationSql,thirdArgs),/SYNTHETIC_AI_CAMPAIGN_EFFECT_LIMIT_REACHED/);await db.query('BEGIN');try{await db.query(`SET LOCAL session_replication_role=replica`);await db.query(`UPDATE public.synthetic_ai_campaign_final_continuations SET created_at=statement_timestamp()-interval '10 minutes',expires_at=statement_timestamp()-interval '5 minutes' WHERE id=$1`,[continuation.id]);await db.query(`SET LOCAL session_replication_role=origin`);await expectedFailure(()=>db.query(reserveValidationSql,thirdArgs),/SYNTHETIC_AI_CAMPAIGN_(EXPIRED|NOT_AUTHORIZED)/)}finally{await db.query('ROLLBACK')}assert.equal((await one(db,'SELECT expires_at FROM public.synthetic_ai_campaign_final_continuations WHERE id=$1',[continuation.id])).expires_at.getTime(),continuation.expires_at.getTime());const totals=await one(db,`SELECT count(*)::int debits,count(*) FILTER(WHERE final_continuation_id=$1)::int final_debits,869320000+sum(debit_usd_nanos)::bigint aggregate FROM public.synthetic_ai_campaign_effect_debits WHERE campaign_id=$2`,[continuation.id,campaignId]);assert.deepEqual({debits:totals.debits,final_debits:totals.final_debits,aggregate:Number(totals.aggregate)},{debits:8,final_debits:2,aggregate:4640993600});
 const consumeStudioSql=`SELECT public.synthetic_ai_campaign_consume_effect($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,'openai','https://api.openai.com','gpt-4.1-mini-2025-04-14','studio.document.generate',$15,4096)`;
 const consumeStudioArgs=[studioPermit.reservationId,...studioArgs];
 await db.query(consumeStudioSql,consumeStudioArgs);
 assert.ok((await one(db,'SELECT consumed_at FROM public.synthetic_ai_campaign_effect_debits WHERE id=$1',[studioPermit.reservationId])).consumed_at);
 await expectedFailure(()=>db.query(consumeStudioSql,consumeStudioArgs),/SYNTHETIC_AI_CAMPAIGN_PERMIT_INVALID_OR_REPLAYED/);
 assert.deepEqual(await one(db,`SELECT count(*)::int debits,count(*) FILTER(WHERE final_continuation_id=$1 AND consumed_at IS NOT NULL)::int consumed_final_debits FROM public.synthetic_ai_campaign_effect_debits WHERE campaign_id=$2`,[continuation.id,campaignId]),{debits:8,consumed_final_debits:2});
 pass('MAP-PG-FINAL-007-ordered-joined-generation','joined generation binds exact artifact/package and consumes once after fresh validation; replay, route substitution, expiry, and a third effect reject at the fixed ceiling');

 const snapshot=await one(db,`SELECT (SELECT count(*)::int FROM public.synthetic_ai_mapping_no_effect_reconciliations) recovery,(SELECT count(*)::int FROM public.synthetic_ai_campaign_final_continuations) continuation,(SELECT count(*)::int FROM public.synthetic_ai_campaign_effect_debits) debits,(SELECT md5(to_jsonb(journal)::text) FROM public.enterprise_ai_effect_journal journal WHERE id=$1) journal`,[failedJournal]);await expectedFailure(()=>transaction(db,'reapply',migrationSql),/SYNTHETIC_AI_JOURNAL_RECONCILIATION_MIGRATION_PRECONDITION_FAILED/);assert.deepEqual(await one(db,`SELECT (SELECT count(*)::int FROM public.synthetic_ai_mapping_no_effect_reconciliations) recovery,(SELECT count(*)::int FROM public.synthetic_ai_campaign_final_continuations) continuation,(SELECT count(*)::int FROM public.synthetic_ai_campaign_effect_debits) debits,(SELECT md5(to_jsonb(journal)::text) FROM public.enterprise_ai_effect_journal journal WHERE id=$1) journal`,[failedJournal]),snapshot);
 pass('MAP-PG-FINAL-008-reapply','migration reapply fails before mutation and preserves all reconciliation, continuation, and debit history');
 console.log('synthetic AI final continuation PostgreSQL: 8 sanitized scenarios passed; zero provider calls, zero secret reads, and zero hosted access');
}finally{
 await Promise.allSettled(opened.map(client=>client.end()));
 const failures=[];for(const name of names){try{await admin.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`);if(Number((await one(admin,'SELECT count(*)::int n FROM pg_database WHERE datname=$1',[name])).n)!==0)failures.push(`${name}:still_present`);else console.log(`ASSESS_DOCUMENT_MAPPING_PG_CLEANUP ${JSON.stringify({database:name,status:'dropped_and_absent'})}`)}catch(error){failures.push(`${name}:${error?.code??'UNKNOWN'}`)}}await admin.end();if(failures.length)throw new Error(`SYNTHETIC_AI_FINAL_DATABASE_CLEANUP_FAILED:${failures.join(',')}`);
}
