import assert from 'node:assert/strict'; import fs from 'node:fs'; import {spawnSync,execFileSync} from 'node:child_process'; import contract from '../config/v1-pilot-operations-contract.json' with {type:'json'};
const head=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(), runId='40000000001';
fs.mkdirSync('artifacts/pilot-operations-test',{recursive:true});
const postgresPath='artifacts/pilot-operations-test/postgres.json',recoveryPath='artifacts/pilot-operations-test/recovery.json';
fs.writeFileSync(postgresPath,JSON.stringify({kind:'executed_disposable_postgresql',head,runId,liveActivationAuthorized:false,freshApplied:true,acceptedBaselineUpgradeApplied:true,forcedRlsVerified:true,maintenanceDenied:true,concurrentReplayVerified:true,expectedVersionVerified:true,evidenceBindingVerified:true,separationOfDutyVerified:true,deprovisionRevocationVerified:true,crossTenantDisclosureDenied:true,rollbackEligibleVerified:true,rollbackReplayVerified:true,rollbackZeroHostedMutationVerified:true,recoveryRuntimeControlsVerified:true,recoveryZeroMutationOnDenialVerified:true,liveActivationStopVerified:true}));
fs.writeFileSync(recoveryPath,JSON.stringify({kind:'executed_disposable_postgresql_recovery',head,runId,liveActivationAuthorized:false,cleanRestoreVerified:true,corruptionRejected:true,incompleteBackupRejected:true,wrongVersionRejected:true,interruptedRetryVerified:true,canonicalReceiptVerified:true,syntheticOnly:true}));
const evidence=()=>Object.fromEntries(contract.requiredGates.map(id=>[id,{result:'passed',head,runId,job:`job-${id}`,command:`test:${id}`}]))
const run=(values=evidence(),extra={})=>spawnSync(process.execPath,['scripts/verify-pilot-operations.mjs','--authoritative'],{encoding:'utf8',env:{...process.env,GITHUB_ACTIONS:'true',GITHUB_WORKFLOW:'Pilot Operations',GITHUB_REPOSITORY:'APReddy-AutoBotz/AvalaOS-Core',GITHUB_RUN_ID:runId,PILOT_OPERATIONS_HEAD:head,PILOT_OPERATIONS_GATE_RESULTS:JSON.stringify(values),PILOT_OPERATIONS_POSTGRES_ARTIFACT:postgresPath,PILOT_OPERATIONS_RECOVERY_ARTIFACT:recoveryPath,...extra}});
assert.equal(run().status,0); let manifest=JSON.parse(fs.readFileSync('artifacts/pilot-operations/manifest.json')); assert.equal(manifest.result,'passed'); assert.equal(manifest.liveActivation.state,'LIVE_ACTIVATION_NOT_AUTHORIZED');
const absent=evidence();delete absent[contract.requiredGates[0]];assert.equal(run(absent).status,1);assert.equal(run(evidence(),{PILOT_OPERATIONS_HEAD:'a'.repeat(40)}).status,1);const stale=evidence();stale[contract.requiredGates[0]].runId='old';assert.equal(run(stale).status,1);
const tampered=JSON.parse(fs.readFileSync(postgresPath));tampered.head='a'.repeat(40);fs.writeFileSync(postgresPath,JSON.stringify(tampered));assert.equal(run().status,1);
fs.rmSync('artifacts/pilot-operations-test',{recursive:true,force:true});
console.log('Pilot Operations verifier: exact-head, missing/stale evidence, and live stop gate passed.');
