import React, { useEffect, useMemo, useRef, useState } from 'react';
import type { StudioArtifactSectionDto, StudioWorkspaceSelectedSourceDto } from '../../services/studioArtifacts/contracts';
import { contentToStructuredSections, structuredSectionsToContent, type StructuredStudioSection } from '../../services/studioArtifacts/workspaceModel';

interface Props {
  content: Record<string, unknown>;
  readOnly?: boolean;
  saving?: boolean;
  announceStatus?: boolean;
  projectedSections?: readonly StudioArtifactSectionDto[];
  selectedSources?: readonly StudioWorkspaceSelectedSourceDto[];
  onCommit: (content: Record<string, unknown>) => void;
}

export default function StructuredArtifactEditor({ content, projectedSections, selectedSources, readOnly = false, saving = false, announceStatus = true, onCommit }: Props) {
  const initial = useMemo(() => contentToStructuredSections(content, projectedSections, selectedSources), [content, projectedSections, selectedSources]);
  const [sections, setSections] = useState<StructuredStudioSection[]>(initial);
  const [selectedId, setSelectedId] = useState(initial[0]?.id || '');
  const [dirty, setDirty] = useState(false);
  const [errors, setErrors] = useState<string[]>([]);
  const errorRef = useRef<HTMLDivElement>(null);
  useEffect(() => { setSections(initial); setSelectedId(initial[0]?.id || ''); setDirty(false); }, [initial]);
  const selectedIndex = Math.max(0, sections.findIndex(section => section.id === selectedId));
  const selected = sections[selectedIndex];
  const update = (patch: Partial<StructuredStudioSection>) => { setSections(current => current.map((section, index) => index === selectedIndex ? { ...section, ...patch } : section)); setDirty(true); };
  const move = (delta: -1 | 1) => { const target = selectedIndex + delta; if (target < 0 || target >= sections.length) return; setSections(current => { const next = [...current]; [next[selectedIndex], next[target]] = [next[target], next[selectedIndex]]; return next; }); setDirty(true); };
  const remove = () => { if (sections.length <= 1) return; const next = sections.filter((_, index) => index !== selectedIndex); setSections(next); setSelectedId(next[Math.min(selectedIndex, next.length - 1)].id); setDirty(true); };
  const add = () => { const id = `section-${crypto.randomUUID()}`; setSections(current => [...current, { id, title: 'New section', body: '', sourceAnchors: [], labels: ['human_authored'] }]); setSelectedId(id); setDirty(true); };
  const commit = () => { const nextErrors = sections.flatMap((section, index) => section.title.trim() ? [] : [`Section ${index + 1} needs a title.`]); setErrors(nextErrors); if (nextErrors.length) { requestAnimationFrame(() => errorRef.current?.focus()); return; } onCommit(structuredSectionsToContent(content, sections)); };
  return <section aria-labelledby="structured-editor-title" className="mt-6 rounded-xl border border-[var(--av-color-border)] bg-[var(--av-color-surface)] p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h4 id="structured-editor-title" className="text-base font-bold text-[var(--av-color-text)]">Structured section editor</h4><p className="mt-1 text-xs leading-5 text-[var(--av-color-text-muted)]">Edit business sections and citations. Canonical JSON is validated by the server when you commit.</p></div><span role={announceStatus ? 'status' : undefined} aria-live={announceStatus ? 'polite' : undefined} className="text-xs font-bold text-[var(--av-color-text-muted)]">{saving ? 'Saving to server…' : dirty ? 'Local changes · not saved' : 'Durable version loaded'}</span></div>
    {errors.length > 0 && <div id="studio-editor-error-summary" ref={errorRef} tabIndex={-1} role="alert" aria-labelledby="studio-editor-error-title" className="mt-4 rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-900"><p id="studio-editor-error-title" className="font-bold">Fix these issues before committing</p><ul className="mt-2 list-disc pl-5">{errors.map(error => <li key={error}>{error}</li>)}</ul></div>}
    <div className="mt-4 grid min-w-0 gap-4 lg:grid-cols-[220px_minmax(0,1fr)_minmax(240px,0.8fr)]">
      <nav aria-label="Document outline" className="min-w-0"><p className="av-eyebrow">Outline</p><ol className="mt-2 max-h-72 space-y-1 overflow-y-auto">{sections.map((section, index) => <li key={section.id}><button type="button" onClick={() => setSelectedId(section.id)} aria-current={section.id === selectedId ? 'location' : undefined} className={`min-h-10 w-full rounded-lg px-3 py-2 text-left text-sm font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 ${section.id === selectedId ? 'bg-[var(--av-color-bg-subtle)] text-[var(--av-color-brand-primary)]' : 'text-[var(--av-color-text-muted)]'}`}>{index + 1}. {section.title || 'Untitled section'}</button></li>)}</ol><button type="button" disabled={readOnly || sections.length >= 100} onClick={add} className="btn-ghost mt-3 min-h-10 w-full text-xs font-bold disabled:opacity-50">Add section</button></nav>
      {selected && <div className="min-w-0 space-y-3"><label className="av-form-label">Section title<input value={selected.title} disabled={readOnly} aria-invalid={errors.length > 0 && !selected.title.trim()} aria-describedby={errors.length > 0 && !selected.title.trim() ? 'studio-editor-error-summary' : undefined} aria-errormessage={errors.length > 0 && !selected.title.trim() ? 'studio-editor-error-summary' : undefined} onChange={event => update({ title: event.target.value })} className="av-input mt-2" /></label><label className="av-form-label">Section body<textarea value={selected.body} disabled={readOnly} onChange={event => update({ body: event.target.value })} rows={8} className="av-input mt-2 resize-y" /></label><div className="flex flex-wrap gap-2"><button type="button" disabled={readOnly || selectedIndex === 0} onClick={() => move(-1)} className="btn-ghost min-h-10 px-3 text-xs font-bold disabled:opacity-50">Move up</button><button type="button" disabled={readOnly || selectedIndex === sections.length - 1} onClick={() => move(1)} className="btn-ghost min-h-10 px-3 text-xs font-bold disabled:opacity-50">Move down</button><button type="button" disabled={readOnly || sections.length <= 1} onClick={remove} className="btn-ghost min-h-10 px-3 text-xs font-bold disabled:opacity-50">Remove section</button></div></div>}
      {selected && <aside aria-label="Citation and coverage panel" className="min-w-0 rounded-lg border border-[var(--av-color-border)] bg-[var(--av-color-bg-subtle)] p-4"><p className="av-eyebrow">Coverage & citations</p><p className="mt-3 text-xs font-bold text-[var(--av-color-text-muted)]">{selected.sourceAnchors.length} source citation{selected.sourceAnchors.length === 1 ? '' : 's'}</p><ul className="mt-2 max-h-40 space-y-1 overflow-auto text-xs text-[var(--av-color-text-muted)]">{selected.sourceAnchors.length ? selected.sourceAnchors.map(anchor => <li key={`${anchor.sourceVersionId}:${anchor.locator}:${anchor.anchorHash}`} className="break-all rounded border border-[var(--av-color-border)] bg-[var(--av-color-surface)] p-2"><strong>{anchor.sourceLabel}{anchor.sourceVersion===null?'':` · v${anchor.sourceVersion}`}</strong><span className="mt-1 block">{anchor.locator} · {anchor.anchorHash}</span></li>) : <li>No source citation. This section is explicitly {selected.labels.map(label => label.replace('_', ' ')).join(', ')}.</li>}</ul>{selected.labels.length > 0 && <p className="mt-3 text-xs font-semibold text-[var(--av-color-text-muted)]">Labels: {selected.labels.map(label => label.replace('_', ' ')).join(', ')}</p>}<p className="mt-3 text-xs text-[var(--av-color-text-subtle)]">Canonical revisions preserve only exact source-version, locator and anchor-hash keys. Display labels and version numbers are read-only server projection enrichment.</p><div className="mt-5 border-t border-[var(--av-color-border)] pt-4"><p className="av-eyebrow">Safe preview</p><h5 className="mt-2 break-words text-lg font-bold text-[var(--av-color-text)]">{selected.title}</h5><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-[var(--av-color-text-muted)]">{selected.body}</p></div></aside>}
    </div>
    <div className="mt-4 flex justify-end"><button type="button" disabled={readOnly || saving || !dirty} onClick={commit} className="btn-primary min-h-10 px-4 text-sm font-bold disabled:opacity-50">Commit immutable revision</button></div>
  </section>;
}
