import React, { useRef, useState } from 'react';
import type { StudioHandoffSummary } from '../../services/studioArtifacts/workspaceModel';

type Action = 'request' | 'review-approve' | 'request-changes' | 'review-reject' | 'final-approve' | 'final-reject' | 'withdraw' | 'consume';
interface Props { inbox: readonly StudioHandoffSummary[]; outbox: readonly StudioHandoffSummary[]; disabled?: boolean; canAction?:(action:Action)=>boolean; onAction: (handoff: StudioHandoffSummary, action: Action, rationale: string) => Promise<void> | void }
const allowAllHandoffActions = () => true;

export default function StudioHandoffCenter({ inbox, outbox, disabled, canAction=allowAllHandoffActions, onAction }: Props) {
  const [tab,setTab]=useState<'inbox'|'outbox'>('inbox');
  const [pending,setPending]=useState<{item:StudioHandoffSummary;action:Action}|null>(null);
  const [processing,setProcessing]=useState(false);
  const [rationale,setRationale]=useState('');
  const returnFocus=useRef<HTMLButtonElement|null>(null);
  const items=tab==='inbox'?inbox:outbox;
  const choose=(event:React.MouseEvent<HTMLButtonElement>,item:StudioHandoffSummary,action:Action)=>{returnFocus.current=event.currentTarget;setRationale('');setPending({item,action});};
  const confirm=async()=>{if(!pending)return;setProcessing(true);try{await onAction(pending.item,pending.action,rationale.trim());setPending(null);requestAnimationFrame(()=>returnFocus.current?.focus());}finally{setProcessing(false);}};
  return <section aria-labelledby="studio-handoff-title" className="av-surface mt-4 p-4">
    <h3 id="studio-handoff-title" className="text-lg font-bold text-[var(--av-color-text)]">Assess → Studio handoffs</h3>
    <p className="mt-1 text-sm text-[var(--av-color-text-muted)]">Eligibility and actions are server projections. Approval never creates a document automatically.</p>
    <div role="tablist" aria-label="Handoff mailbox" className="mt-4 flex gap-2"><button role="tab" aria-selected={tab==='inbox'} onClick={()=>setTab('inbox')} className="btn-ghost min-h-10 px-3 text-sm font-bold">Inbox ({inbox.length})</button><button role="tab" aria-selected={tab==='outbox'} onClick={()=>setTab('outbox')} className="btn-ghost min-h-10 px-3 text-sm font-bold">Outbox ({outbox.length})</button></div>
    <div role="tabpanel" className="mt-3"><ul className="max-h-96 space-y-3 overflow-auto">{items.map(item=><li key={`${item.kind}:${item.handoffVersionId??item.upstreamHandoffId}`} className="rounded-xl border border-[var(--av-color-border)] p-4">
      <div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold text-[var(--av-color-text)]">{item.resourceLabel}{item.version!==null?` · v${item.version}`:item.sourceVersion!==null?` · source v${item.sourceVersion}`:''}</p><p className="mt-1 text-xs text-[var(--av-color-text-muted)]">{item.requestorLabel} · {item.lineageLabel?item.lineageLabel.replace('_',' '):'eligible Assess source'} · {item.targetWorkspaceLabel}</p></div><span className="rounded-full border border-[var(--av-color-border)] px-2 py-1 text-xs font-bold">{item.state.replace('_',' ')}</span></div>
      {item.expiresAt&&<p className="mt-2 text-xs font-semibold text-[var(--av-color-text-muted)]">Expires {item.expiresAt}</p>}
      <details className="mt-3 rounded-lg border border-[var(--av-color-border)] p-2 text-xs"><summary className="cursor-pointer font-bold">Preview exact lineage</summary><dl className="mt-2 grid gap-1"><div><dt className="inline font-bold">Upstream: </dt><dd className="inline break-all">{item.upstreamHandoffId}</dd></div><div><dt className="inline font-bold">Immutable version: </dt><dd className="inline">{item.handoffVersionId??'eligible only'}{item.version!==null?` · v${item.version}`:''}</dd></div><div><dt className="inline font-bold">Direction/status: </dt><dd className="inline">{item.direction} · {item.status??item.state}</dd></div><div><dt className="inline font-bold">Expiry: </dt><dd className="inline">{item.expiresAt??'not set'}</dd></div></dl></details><div className="mt-3 flex flex-wrap gap-2">{item.actions.includes('studio.handoff.request')&&<button type="button" disabled={disabled||!canAction('request')} onClick={event=>choose(event,item,'request')} className="btn-ghost min-h-10 px-3 text-xs font-bold">Request handoff</button>}{item.actions.includes('studio.handoff.review.resolve')&&<><button type="button" disabled={disabled||!canAction('review-approve')} onClick={event=>choose(event,item,'review-approve')} className="btn-ghost min-h-10 px-3 text-xs font-bold">Approve review</button><button type="button" disabled={disabled||!canAction('request-changes')} onClick={event=>choose(event,item,'request-changes')} className="btn-ghost min-h-10 px-3 text-xs font-bold">Request changes</button><button type="button" disabled={disabled||!canAction('review-reject')} onClick={event=>choose(event,item,'review-reject')} className="btn-ghost min-h-10 px-3 text-xs font-bold">Reject review</button></>}{item.actions.includes('studio.handoff.approval.resolve')&&<><button type="button" disabled={disabled||!canAction('final-approve')} onClick={event=>choose(event,item,'final-approve')} className="btn-primary min-h-10 px-3 text-xs font-bold">Final accept</button><button type="button" disabled={disabled||!canAction('final-reject')} onClick={event=>choose(event,item,'final-reject')} className="btn-ghost min-h-10 px-3 text-xs font-bold">Final reject</button></>}{item.actions.includes('studio.handoff.withdraw')&&<button type="button" disabled={disabled||!canAction('withdraw')} onClick={event=>choose(event,item,'withdraw')} className="btn-ghost min-h-10 px-3 text-xs font-bold">Withdraw</button>}{item.actions.includes('studio.handoff.consume')&&<button type="button" disabled={disabled||!canAction('consume')} onClick={event=>choose(event,item,'consume')} className="btn-primary min-h-10 px-3 text-xs font-bold">Start Studio draft</button>}</div>
    </li>)}{items.length===0&&<li className="rounded-xl border border-dashed border-[var(--av-color-border)] p-6 text-center text-sm text-[var(--av-color-text-muted)]">No {tab} handoffs are available.</li>}</ul></div>
    {pending&&<div role="dialog" aria-modal="true" aria-labelledby="handoff-confirm-title" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-lg rounded-2xl bg-[var(--av-color-surface)] p-5 shadow-2xl"><h4 id="handoff-confirm-title" className="text-lg font-bold text-[var(--av-color-text)]">Confirm {pending.action.replaceAll('-',' ')}</h4><p className="mt-3 text-sm leading-6 text-[var(--av-color-text-muted)]">This records a governed handoff decision for {pending.item.resourceLabel}. Only “Start Studio draft” may create one target draft after a fresh server check. No automatic future handoff will occur.</p>{!['request','consume'].includes(pending.action)&&<label className="av-form-label mt-4">Decision rationale<textarea autoFocus value={rationale} onChange={event=>setRationale(event.target.value)} rows={3} className="av-input mt-2 resize-y" /></label>}<div className="mt-5 flex justify-end gap-2"><button type="button" disabled={processing} onClick={()=>{setPending(null);requestAnimationFrame(()=>returnFocus.current?.focus());}} className="btn-ghost min-h-10 px-4 text-sm font-bold">Cancel</button><button autoFocus={['request','consume'].includes(pending.action)} type="button" disabled={processing||(!['request','consume'].includes(pending.action)&&!rationale.trim())} onClick={()=>void confirm()} className="btn-primary min-h-10 px-4 text-sm font-bold">{processing?'Committing…':'Confirm'}</button></div></div></div>}
  </section>;
}
