import React from 'react';
import type { StudioArtifactWorkspaceProjectionDto } from '../../services/studioArtifacts/contracts';
import type { StudioWorkspaceProjection } from '../../services/studioArtifacts/workspaceModel';

const legacyModeLabel = { unconfigured:'No committed source package',direct_studio:'Not assessed · planning only',accepted_assess_handoff:'Assessed',hybrid:'Assessed + Studio supplements',manual_brief:'Not assessed · planning only' } as const;
const exactModeLabel = { assess_handoff:'Assessed',direct_transcript_bundle:'Not assessed · planning only',assess_plus_transcript_bundle:'Assessed + Studio supplements',manual_brief:'Not assessed · planning only' } as const;
const providerReason = { available:'Available',feature_disabled:'Feature disabled',read_only:'Read-only maintenance',permission_denied:'Permission denied',route_unavailable:'Route unavailable',source_stale:'Source package stale',template_unavailable:'Template unavailable' } as const;

interface Props {
  projection: StudioWorkspaceProjection;
  artifactProjection?: StudioArtifactWorkspaceProjectionDto | null;
  onPage?: (page: number) => void;
}

export default function StudioSourceCoverage({ projection, artifactProjection, onPage }: Props) {
  if (artifactProjection) {
    const selected = artifactProjection.selectedSources;
    const page = Math.floor(selected.offset / selected.limit) + 1;
    const pageCount = Math.max(1, Math.ceil(selected.total / selected.limit));
    const coverage = artifactProjection.coverage;
    const unresolved = coverage.conflicts.filter(conflict => conflict.status === 'unresolved').length;
    return <section aria-labelledby="studio-source-coverage-title" className="av-surface mt-4 overflow-hidden">
      <header className="border-b border-[var(--av-color-border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="av-eyebrow">Exact server-projected generation inputs</p><h3 id="studio-source-coverage-title" className="mt-1 text-lg font-bold text-[var(--av-color-text)]">Source Coverage</h3></div><span className="rounded-full border border-[var(--av-color-border)] px-3 py-1 text-xs font-bold text-[var(--av-color-text)]">✓ {exactModeLabel[artifactProjection.sourcePackage.mode]}</span></div><p className="mt-3 text-sm font-semibold text-[var(--av-color-text-muted)]">Unselected sources have zero influence. This view contains only the exact immutable package, bundle, selected-source page, coverage, citations, conflicts, provider availability and artifact sections returned by the safe production projection.</p></header>
      <div className="grid gap-4 p-4 lg:grid-cols-2"><div><h4 className="text-sm font-bold text-[var(--av-color-text)]">Exact source package</h4><dl className="mt-2 space-y-1 text-xs text-[var(--av-color-text-muted)]"><div><dt className="inline font-bold">Package: </dt><dd className="inline break-all">{artifactProjection.sourcePackage.id} · v{artifactProjection.sourcePackage.version}</dd></div><div><dt className="inline font-bold">Hash: </dt><dd className="inline break-all">{artifactProjection.sourcePackage.hash}</dd></div><div><dt className="inline font-bold">Input bundle: </dt><dd className="inline break-all">{artifactProjection.sourcePackage.inputBundle ? `${artifactProjection.sourcePackage.inputBundle.versionId} · v${artifactProjection.sourcePackage.inputBundle.version}` : 'none'}</dd></div><div><dt className="inline font-bold">Lineage: </dt><dd className="inline">{artifactProjection.sourcePackage.lineageClassification}{artifactProjection.sourcePackage.planningOnly ? ' · planning only' : ''}</dd></div></dl></div><div><h4 className="text-sm font-bold text-[var(--av-color-text)]">Selected immutable sources</h4><ExactSourceList sources={selected.items} /></div></div>
      <dl className="grid gap-3 border-t border-[var(--av-color-border)] p-4 text-sm sm:grid-cols-2 xl:grid-cols-4"><Metric label="Coverage" value={`${coverage.coveredSourceVersionIds.length}/${coverage.selectedSourceVersionIds.length} sources · ${coverage.complete ? 'complete' : `${coverage.uncoveredSourceVersionIds.length} uncovered`}`} /><Metric label="Citations" value={`${coverage.citations.length} exact anchors across ${artifactProjection.artifact.sections.length} sections`} /><Metric label="Conflicts" value={`${coverage.conflicts.length} material · ${unresolved} unresolved`} /><Metric label="Provider" value={artifactProjection.providerAvailability.available ? '✓ Available' : `⚠ Provider unavailable · ${providerReason[artifactProjection.providerAvailability.reason]}`} /></dl>
      <div className="grid gap-3 border-t border-[var(--av-color-border)] p-4 text-sm lg:grid-cols-2"><div><p className="font-bold text-[var(--av-color-text)]">Artifact head</p><p className="mt-1 break-all text-[var(--av-color-text-muted)]">{artifactProjection.artifact.id} · aggregate v{artifactProjection.artifact.aggregateVersion} · {artifactProjection.artifact.lifecycle} · {artifactProjection.artifact.currentVersionId ?? 'no current version'}</p></div><div><p className="font-bold text-[var(--av-color-text)]">Projected actions</p><p className="mt-1 break-words text-[var(--av-color-text-muted)]">{artifactProjection.actions.length ? artifactProjection.actions.join(' · ') : 'Read projection only'}</p></div></div>
      {pageCount > 1 && <nav aria-label="Source coverage pages" className="flex items-center justify-between border-t border-[var(--av-color-border)] p-4"><button type="button" disabled={page <= 1} onClick={() => onPage?.(page - 1)} className="btn-ghost min-h-10 px-3 text-xs font-bold disabled:opacity-50">Previous sources</button><span className="text-xs font-bold text-[var(--av-color-text-muted)]">Page {page} of {pageCount} · {selected.total} selected</span><button type="button" disabled={!selected.hasMore} onClick={() => onPage?.(page + 1)} className="btn-ghost min-h-10 px-3 text-xs font-bold disabled:opacity-50">Next sources</button></nav>}
    </section>;
  }

  const accepted = projection.selectedSources.filter(source => source.suggestionStatus === 'accepted').length;
  const rejected = projection.selectedSources.filter(source => source.suggestionStatus === 'rejected').length;
  const unresolved = projection.selectedSources.filter(source => source.suggestionStatus === 'unresolved').length;
  const assess = projection.selectedSources.filter(source => source.family === 'assess');
  const studio = projection.selectedSources.filter(source => source.family === 'studio');
  return <section aria-labelledby="studio-source-coverage-title" className="av-surface mt-4 overflow-hidden">
    <header className="border-b border-[var(--av-color-border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="av-eyebrow">Exact generation inputs</p><h3 id="studio-source-coverage-title" className="mt-1 text-lg font-bold text-[var(--av-color-text)]">Source Coverage</h3></div><span className="rounded-full border border-[var(--av-color-border)] px-3 py-1 text-xs font-bold text-[var(--av-color-text)]">✓ {legacyModeLabel[projection.mode]}</span></div><p className="mt-3 text-sm font-semibold text-[var(--av-color-text-muted)]">Unselected sources have zero influence on generation, coverage, citations, conflicts, and the committed artifact.</p></header>
    <div className="grid gap-4 p-4 lg:grid-cols-2"><div><h4 className="text-sm font-bold text-[var(--av-color-text)]">Assess-approved input</h4>{assess.length ? <LegacySourceList sources={assess} /> : <p className="mt-2 text-sm text-[var(--av-color-text-muted)]">No Assess source is attached. No assessment ancestry is claimed.</p>}</div><div><h4 className="text-sm font-bold text-[var(--av-color-text)]">Studio-only transcript inputs</h4>{studio.length ? <LegacySourceList sources={studio} /> : <p className="mt-2 text-sm text-[var(--av-color-text-muted)]">No Studio transcript is selected.</p>}</div></div>
    <dl className="grid gap-3 border-t border-[var(--av-color-border)] p-4 text-sm sm:grid-cols-2 xl:grid-cols-4"><Metric label="Suggestion decisions" value={`${accepted} accepted · ${rejected} rejected · ${unresolved} unresolved`} /><Metric label="Coverage" value={`${projection.citations} citations · ${projection.uncoveredSections} uncovered sections`} /><Metric label="Conflicts" value={`${projection.conflicts} material conflict${projection.conflicts === 1 ? '' : 's'}`} /><Metric label="Provider" value={projection.provider.available ? `✓ ${projection.provider.label}` : `⚠ Provider unavailable · ${projection.provider.label}`} /></dl>
    <div className="grid gap-3 border-t border-[var(--av-color-border)] p-4 text-sm lg:grid-cols-2"><div><p className="font-bold text-[var(--av-color-text)]">Template identity</p><p className="mt-1 break-words text-[var(--av-color-text-muted)]">{projection.template ? `${projection.template.name} · v${projection.template.version} · ${projection.template.templateHash}` : 'No approved template selected'}</p></div><div><p className="font-bold text-[var(--av-color-text)]">Functional bounds & blockers</p><p className="mt-1 text-[var(--av-color-text-muted)]">{projection.provider.functionalBounds}</p>{projection.blockers.length > 0 && <ul className="mt-2 list-disc pl-5 text-amber-800 dark:text-amber-200">{projection.blockers.map(blocker => <li key={blocker}>{blocker}</li>)}</ul>}</div></div>
    {projection.sourcePageCount > 1 && <nav aria-label="Source coverage pages" className="flex items-center justify-between border-t border-[var(--av-color-border)] p-4"><button type="button" disabled={projection.sourcePage <= 1} onClick={() => onPage?.(projection.sourcePage - 1)} className="btn-ghost min-h-10 px-3 text-xs font-bold disabled:opacity-50">Previous sources</button><span className="text-xs font-bold text-[var(--av-color-text-muted)]">Page {projection.sourcePage} of {projection.sourcePageCount} · {projection.totalSelectedSourceCount} selected</span><button type="button" disabled={projection.sourcePage >= projection.sourcePageCount} onClick={() => onPage?.(projection.sourcePage + 1)} className="btn-ghost min-h-10 px-3 text-xs font-bold disabled:opacity-50">Next sources</button></nav>}
  </section>;
}

function ExactSourceList({ sources }: { sources: StudioArtifactWorkspaceProjectionDto['selectedSources']['items'] }) { return <ul className="mt-2 max-h-52 space-y-2 overflow-auto">{sources.map(source => <li key={source.sourceVersionId} className="rounded-lg border border-[var(--av-color-border)] p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span className="font-bold text-[var(--av-color-text)]">{source.label} · v{source.sourceVersion}</span><span className="text-xs font-bold text-[var(--av-color-text-muted)]">{source.sourceKind}</span></div><p className="mt-1 text-xs text-[var(--av-color-text-muted)]">{source.semanticRoles.join(' · ')} · exact version {source.sourceVersionId}</p></li>)}</ul>; }
function LegacySourceList({ sources }: { sources: StudioWorkspaceProjection['selectedSources'] }) { return <ul className="mt-2 max-h-52 space-y-2 overflow-auto">{sources.map(source => <li key={source.sourceVersionId} className="rounded-lg border border-[var(--av-color-border)] p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span className="font-bold text-[var(--av-color-text)]">{source.label} · v{source.version}</span><span className="text-xs font-bold text-[var(--av-color-text-muted)]">{source.suggestionStatus}</span></div><p className="mt-1 text-xs text-[var(--av-color-text-muted)]">{source.role} · {source.citationCount} citations · {source.conflictCount} conflicts</p></li>)}</ul>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="av-eyebrow">{label}</dt><dd className="mt-1 font-bold text-[var(--av-color-text)]">{value}</dd></div>; }
