import React, { useEffect, useState } from 'react';
import type { TenantContextProjection } from '../../types';
import { STUDIO_ARTIFACT_TYPES, type StudioArtifactProjectionDto, type StudioArtifactType, type StudioCommandType } from '../../services/studioArtifacts/contracts';
import { executeStudioArtifactCommand, readStudioArtifact, readStudioHandoffs, type StudioCommandCommit, type StudioHandoffOption } from '../../services/studioArtifacts/client';

interface Props { context: TenantContextProjection; capabilities: readonly string[]; online?: boolean }
type ViewState='loading'|'empty'|'ready'|'generating'|'generation_failed'|'offline'|'stale'|'version_conflict'|'authorization_revoked'|'command_failed'|'committed_reload_failed';
const labels:Record<StudioArtifactProjectionDto['lifecycle'],string>={draft:'Draft',reviewer_ready:'Reviewer ready',in_review:'In review',changes_requested:'Changes requested',review_rejected:'Review rejected',approval_ready:'Approval ready',approved:'Approved',approval_rejected:'Approval rejected',superseded:'Superseded'};
const capability:Record<StudioCommandType,string>={'studio.artifact.generation.request':'studio.artifacts.generate','studio.artifact.draft.revise':'studio.artifacts.edit','studio.artifact.review.submit':'studio.artifacts.edit','studio.artifact.review.assign':'studio.artifacts.review','studio.artifact.review.resolve':'studio.artifacts.review','studio.artifact.approval.resolve':'studio.artifacts.approve'};

export default function StudioArtifactWorkspace({context,capabilities,online=true}:Props){
  const [handoffs,setHandoffs]=useState<StudioHandoffOption[]>([]); const [handoffId,setHandoffId]=useState(''); const [artifactType,setArtifactType]=useState<StudioArtifactType>('brd');
  const [artifact,setArtifact]=useState<StudioArtifactProjectionDto|null>(null); const [state,setState]=useState<ViewState>('loading'); const [message,setMessage]=useState('Loading committed Studio sources.');
  const [receipt,setReceipt]=useState<StudioCommandCommit|null>(null); const [draft,setDraft]=useState(''); const [actorTarget,setActorTarget]=useState(''); const [rationale,setRationale]=useState('');
  const blocked=!online||state==='committed_reload_failed'||artifact?.readOnly;
  const load=async(selected=handoffId,type=artifactType)=>{ setState('loading'); try { const sources=handoffs.length?handoffs:await readStudioHandoffs(context); setHandoffs(sources); const id=selected||sources[0]?.id||''; setHandoffId(id); if(!id){setArtifact(null);setState('empty');setMessage('No accepted governed Studio handoffs are available.');return;} try{const value=await readStudioArtifact(context,id,type);setArtifact(value);setState('ready');setMessage('Current committed artifact loaded.');}catch{setArtifact(null);setState('empty');setMessage('No canonical artifact exists for this source and type.');} }catch{setArtifact(null);setState('stale');setMessage('Studio authority is unavailable. Reload the current committed state.');} };
  useEffect(()=>{void load();},[context.organizationId,context.workspaceId]); // eslint-disable-line react-hooks/exhaustive-deps
  const run=async(commandType:StudioCommandType,payload:Record<string,unknown>)=>{if(blocked)return;if(!online){setState('offline');setMessage('Offline. No command was submitted.');return;}setState(commandType==='studio.artifact.generation.request'?'generating':'loading');setMessage('Submitting. Success appears only after commit and projection reload.');try{const committed=await executeStudioArtifactCommand(context,commandType,artifact,payload,`${commandType}:${handoffId}:${artifactType}:${artifact?.aggregateVersion??0}`);setReceipt(committed);try{const value=await readStudioArtifact(context,handoffId,artifactType);setArtifact(value);setState('ready');setMessage(`${labels[value.lifecycle]} committed.`);}catch{setState('committed_reload_failed');setMessage(`Command committed (receipt ${committed.receiptId}), but projection reload failed. Mutations are blocked.`);}}catch{setState(commandType==='studio.artifact.generation.request'?'generation_failed':'command_failed');setMessage('Command failed before commit. No success was recorded.');}};
  const revise=()=>{try{const content=JSON.parse(draft) as unknown;if(!content||typeof content!=='object'||Array.isArray(content))throw new Error();void run('studio.artifact.draft.revise',{artifactId:artifact!.id,content});}catch{setState('command_failed');setMessage('Draft must be a structured JSON object. No command was submitted.');}};
  const can=(command:StudioCommandType)=>!blocked&&capabilities.includes(capability[command]);
  return <section data-testid="studio-artifact-workspace" aria-labelledby="studio-artifact-title" className="mt-6 rounded-3xl border-2 border-[#ffbc03]/50 p-4">
    <h2 id="studio-artifact-title" className="text-2xl font-black">Governed artifact workspace</h2><p className="mt-1 text-sm">Structured JSON is committed by server authority. Templates, schemas, ancestry and actors are never supplied by this browser.</p>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="font-bold">Committed Studio handoff<select value={handoffId} onChange={e=>{setHandoffId(e.target.value);void load(e.target.value,artifactType);}} className="mt-1 w-full rounded-xl border p-2">{handoffs.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="font-bold">Artifact type<select value={artifactType} onChange={e=>{const type=e.target.value as StudioArtifactType;setArtifactType(type);void load(handoffId,type);}} className="mt-1 w-full rounded-xl border p-2">{STUDIO_ARTIFACT_TYPES.map(type=><option key={type} value={type}>{type.toUpperCase()}</option>)}</select></label></div>
    {!online&&<p role="alert" className="mt-3 rounded-xl bg-amber-50 p-3">Offline. Committed content remains visible; mutations are blocked.</p>}{artifact?.readOnly&&<p role="status" className="mt-3 rounded-xl bg-blue-50 p-3">Read-only maintenance. Committed canonical artifacts remain available.</p>}
    <p role="status" aria-live="polite" className="mt-3 font-semibold">{message}</p>{state==='loading'&&<div aria-label="Loading Studio artifact" className="mt-3 animate-pulse rounded-xl bg-slate-100 p-8"/>}
    {state==='committed_reload_failed'&&<button onClick={()=>void load()} className="mt-3 rounded-xl bg-[#002C4B] px-3 py-2 font-bold text-white">Reload explicitly committed state</button>}
    {artifact&&<div className="mt-4 space-y-4"><header className="rounded-xl bg-[#002C4B] p-4 text-white"><strong>{artifact.artifactType.toUpperCase()} · {labels[artifact.lifecycle]}</strong><p>Aggregate v{artifact.aggregateVersion} · Content v{artifact.currentVersion.version}</p></header><pre className="max-h-80 overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-white">{JSON.stringify(artifact.currentVersion.content,null,2)}</pre><details><summary className="font-bold">Immutable history</summary><ol>{[...artifact.versions].reverse().map(v=><li key={v.id}>Version {v.version} · {labels[v.lifecycle]} · {v.contentHash}</li>)}</ol></details></div>}
    <div className="mt-4 grid gap-3"><label className="font-bold">Draft revision (strict structured JSON)<textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={5} className="mt-1 w-full rounded-xl border p-2"/></label><label className="font-bold">Assigned human actor ID<input value={actorTarget} onChange={e=>setActorTarget(e.target.value)} className="mt-1 w-full rounded-xl border p-2"/></label><label className="font-bold">Rationale and conditions<textarea value={rationale} onChange={e=>setRationale(e.target.value)} className="mt-1 w-full rounded-xl border p-2"/></label><div className="flex flex-wrap gap-2">
      <button disabled={!can('studio.artifact.generation.request')} onClick={()=>void run('studio.artifact.generation.request',{studioHandoffId:handoffId,artifactType})} className="btn-primary disabled:opacity-50">Generate server draft</button>
      <button disabled={!can('studio.artifact.draft.revise')||!artifact||!draft} onClick={revise} className="btn-ghost disabled:opacity-50">Commit immutable revision</button>
      <button disabled={!can('studio.artifact.review.submit')||artifact?.lifecycle!=='draft'} onClick={()=>void run('studio.artifact.review.submit',{artifactId:artifact!.id,artifactVersionId:artifact!.currentVersion.id})} className="btn-ghost disabled:opacity-50">Submit exact version for review</button>
      <button disabled={!can('studio.artifact.review.assign')||!actorTarget} onClick={()=>void run('studio.artifact.review.assign',{artifactId:artifact!.id,artifactVersionId:artifact!.currentVersion.id,reviewerId:actorTarget})} className="btn-ghost disabled:opacity-50">Assign independent reviewer</button>
      <button disabled={!can('studio.artifact.review.resolve')||!rationale} onClick={()=>void run('studio.artifact.review.resolve',{artifactId:artifact!.id,artifactVersionId:artifact!.currentVersion.id,outcome:'approved',rationale,conditions:[]})} className="btn-ghost disabled:opacity-50">Resolve independent review</button>
      <button disabled={!can('studio.artifact.approval.resolve')||!rationale} onClick={()=>void run('studio.artifact.approval.resolve',{artifactId:artifact!.id,artifactVersionId:artifact!.currentVersion.id,outcome:'approved',rationale,conditions:[]})} className="btn-ghost disabled:opacity-50">Resolve separate final approval</button>
    </div></div>
    <p className="mt-5 rounded-xl border p-3 font-bold">Private export and governed download are not available in this release.</p>{receipt&&<p className="sr-only">Last committed receipt {receipt.receiptId}</p>}
  </section>;
}
