import React, { useMemo, useState } from 'react';
import type { StudioArtifactType } from '../../services/studioArtifacts/contracts';
import type { StudioSourceAuthorityProjection } from '../../services/studioArtifacts/workspaceModel';

type SourceRole='primary'|'supporting'|'contradictory'|'reference';
export interface StudioSourceSetDraft {label:string;description?:string;members:Array<{sourceId:string;versionSelector:string;role:SourceRole;ordinal:number}>}
interface Props {
  projection:StudioSourceAuthorityProjection;artifactType:StudioArtifactType;disabled?:boolean;
  canManageSources:boolean;canCreatePackage:boolean;
  selectedBundleVersionId:string;onSelectBundle:(versionId:string)=>void;
  onCommitSourceSet:(draft:StudioSourceSetDraft)=>Promise<void>;
  onLockInputBundle:(sourceSetVersionIds:string[])=>Promise<void>;
  onCreatePackage:(input:{mode:'direct';bundleVersionId:string}|{mode:'manual';manualBrief:string})=>Promise<void>;
}

export default function StudioSourcePackageBuilder({projection,artifactType,disabled,canManageSources,canCreatePackage,selectedBundleVersionId,onSelectBundle,onCommitSourceSet,onLockInputBundle,onCreatePackage}:Props){
  const [selected,setSelected]=useState<string[]>([]);const [roles,setRoles]=useState<Record<string,SourceRole>>({});const [label,setLabel]=useState('');const [description,setDescription]=useState('');const [selectedSets,setSelectedSets]=useState<string[]>([]);const [manualBrief,setManualBrief]=useState('');const [page,setPage]=useState(1);const [state,setState]=useState<'ready'|'committing'>('ready');const [message,setMessage]=useState('Choose exact immutable source versions. No source is selected automatically.');
  const pageSize=20,pageCount=Math.max(1,Math.ceil(projection.sourceVersions.length/pageSize)),visible=projection.sourceVersions.slice((page-1)*pageSize,page*pageSize);const selectedOptions=useMemo(()=>selected.map(id=>projection.sourceVersions.find(item=>item.sourceVersionId===id)).filter((item):item is NonNullable<typeof item>=>Boolean(item)),[projection.sourceVersions,selected]);
  const act=async(work:()=>Promise<void>,success:string)=>{setState('committing');setMessage('Committing. Success appears only after the committed projection reloads.');try{await work();setMessage(success);}catch{setMessage('Command failed or reload was unavailable. No success is claimed; keep the current selection and retry after reload.');}finally{setState('ready');}};
  const locked=Boolean(disabled)||state==='committing';
  if(!projection.enabled)return <section aria-labelledby="studio-source-package-builder-title" className="av-surface mt-4 p-4"><h3 id="studio-source-package-builder-title" className="text-lg font-bold">Studio Source Package builder</h3><p role="status" className="mt-2 text-sm font-semibold">{projection.disabledReason||'Direct Studio source packages are disabled for this workspace.'}</p></section>;
  return <section aria-labelledby="studio-source-package-builder-title" className="av-surface mt-4 p-4">
    <p className="av-eyebrow">Studio-only source authority</p><h3 id="studio-source-package-builder-title" className="mt-1 text-lg font-bold">Studio Source Package builder</h3><p className="mt-2 text-sm font-semibold text-[var(--av-color-text-muted)]">Direct bundles and manual briefs are durable <strong>Not assessed · planning only</strong> inputs. Studio selections never change Assess sources. Unselected versions have zero influence.</p><p role="status" aria-live="polite" className="mt-3 rounded-lg bg-[var(--av-color-bg-subtle)] p-3 text-sm font-semibold">{message}</p>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><div><h4 className="font-bold">1. Select 1–20 immutable transcript versions</h4><ul className="mt-3 max-h-96 space-y-2 overflow-auto">{visible.map(source=><li key={source.sourceVersionId} className="rounded-lg border border-[var(--av-color-border)] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-bold">{source.label} · v{source.version}</span><button type="button" disabled={locked||(!selected.includes(source.sourceVersionId)&&selected.length>=20)} onClick={()=>setSelected(current=>current.includes(source.sourceVersionId)?current.filter(id=>id!==source.sourceVersionId):[...current,source.sourceVersionId])} className="btn-ghost min-h-10 px-3 text-xs font-bold">{selected.includes(source.sourceVersionId)?'Remove':'Use in Studio'}</button></div><p className="mt-1 text-xs text-[var(--av-color-text-muted)]">{source.mimeType} · {source.characterCount.toLocaleString()} characters · exact version {source.sourceVersionId}</p></li>)}</ul>{pageCount>1&&<nav aria-label="Studio source version pages" className="mt-3 flex items-center justify-between"><button type="button" disabled={page===1} onClick={()=>setPage(value=>value-1)} className="btn-ghost min-h-10 px-3 text-xs font-bold">Previous versions</button><span className="text-xs font-bold">Page {page} of {pageCount}</span><button type="button" disabled={page===pageCount} onClick={()=>setPage(value=>value+1)} className="btn-ghost min-h-10 px-3 text-xs font-bold">Next versions</button></nav>}</div>
      <div><h4 className="font-bold">2. Commit a Studio-owned source set</h4><label className="av-form-label mt-3">Source-set label<input value={label} onChange={event=>setLabel(event.target.value)} className="av-input mt-2" /></label><label className="av-form-label mt-3">Description<input value={description} onChange={event=>setDescription(event.target.value)} className="av-input mt-2" /></label><ol className="mt-3 space-y-2">{selectedOptions.map((source,index)=><li key={source.sourceVersionId} className="rounded-lg border border-[var(--av-color-border)] p-3 text-sm"><span className="font-bold">{index+1}. {source.label} · v{source.version}</span><label className="av-form-label mt-2">Semantic role<select aria-label={`Semantic role for ${source.label}`} value={roles[source.sourceVersionId]??(index===0?'primary':'supporting')} disabled={locked} onChange={event=>setRoles(current=>({...current,[source.sourceVersionId]:event.target.value as SourceRole}))} className="av-input mt-1"><option value="primary">Primary</option><option value="supporting">Supporting</option><option value="contradictory">Contradictory</option><option value="reference">Reference</option></select></label></li>)}</ol><button type="button" disabled={locked||!canManageSources||selectedOptions.length<1||!label.trim()} onClick={()=>void act(()=>onCommitSourceSet({label:label.trim(),...(description.trim()?{description:description.trim()}:{}),members:selectedOptions.map((source,index)=>({sourceId:source.sourceId,versionSelector:source.sourceVersionId,role:roles[source.sourceVersionId]??(index===0?'primary':'supporting'),ordinal:index+1}))}),'Immutable Studio source-set version committed and reloaded.')} className="btn-primary mt-3 min-h-10 px-4 text-sm font-bold disabled:opacity-50">Commit Studio source set</button></div></div>
    <div className="mt-5 border-t border-[var(--av-color-border)] pt-4"><h4 className="font-bold">3. Lock an exact Studio bundle</h4><div className="mt-3 grid gap-2">{projection.sourceSets.map(set=><label key={set.currentVersionId} className="flex items-start gap-3 rounded-lg border border-[var(--av-color-border)] p-3 text-sm"><input type="checkbox" className="mt-1" checked={selectedSets.includes(set.currentVersionId)} disabled={locked} onChange={()=>setSelectedSets(current=>current.includes(set.currentVersionId)?current.filter(id=>id!==set.currentVersionId):[...current,set.currentVersionId])}/><span><strong>{set.displayLabel} · v{set.currentVersion}</strong><span className="mt-1 block text-xs text-[var(--av-color-text-muted)]">{set.sourceCount} sources · {set.manifestHash}</span></span></label>)}</div><button type="button" disabled={locked||!canManageSources||selectedSets.length<1||selectedSets.length>20} onClick={()=>void act(()=>onLockInputBundle(selectedSets),'Exact Studio input bundle locked and reloaded.')} className="btn-primary mt-3 min-h-10 px-4 text-sm font-bold disabled:opacity-50">Lock Studio input bundle</button></div>
    <div className="mt-5 grid gap-4 border-t border-[var(--av-color-border)] pt-4 lg:grid-cols-2"><div><h4 className="font-bold">4A. Create direct planning package</h4><label className="av-form-label mt-3">Exact locked bundle<select aria-label="Exact locked Studio bundle" value={selectedBundleVersionId} onChange={event=>onSelectBundle(event.target.value)} className="av-input mt-2"><option value="">Select exact bundle</option>{projection.inputBundles.filter(bundle=>bundle.status==='locked').map(bundle=><option key={bundle.inputBundleVersionId} value={bundle.inputBundleVersionId}>Bundle v{bundle.currentVersion} · {bundle.inputBundleVersionId}</option>)}</select></label><button type="button" disabled={locked||!canCreatePackage||!selectedBundleVersionId} onClick={()=>void act(()=>onCreatePackage({mode:'direct',bundleVersionId:selectedBundleVersionId}),`Direct ${artifactType.toUpperCase()} source package committed and reloaded · Not assessed · planning only.`)} className="btn-primary mt-3 min-h-10 px-4 text-sm font-bold disabled:opacity-50">Create direct planning package</button></div><div><h4 className="font-bold">4B. Create bounded manual-brief package</h4><label className="av-form-label mt-3">Manual brief<textarea value={manualBrief} maxLength={20000} rows={5} onChange={event=>setManualBrief(event.target.value)} className="av-input mt-2 resize-y" /></label><p className="mt-1 text-xs font-semibold">{manualBrief.length.toLocaleString()}/20,000 characters.</p><p className="mt-1 text-xs font-semibold">Your browser sends raw text only when creating the source package. During an authorized generation, the server retrieves the committed private brief and sends it through the governed provider. Raw material is not returned in browser projections.</p><button type="button" disabled={locked||!canCreatePackage||!manualBrief.trim()} onClick={()=>void act(()=>onCreatePackage({mode:'manual',manualBrief:manualBrief.trim()}),`Manual ${artifactType.toUpperCase()} source package committed and reloaded · Not assessed · planning only.`)} className="btn-primary mt-3 min-h-10 px-4 text-sm font-bold disabled:opacity-50">Create manual planning package</button></div></div>
  </section>;
}
