export const ECONOMIC_MODEL_VERSION='assess-v2-economics-model-2026-07';
export const ECONOMIC_FORMULA_VERSION='assess-v2-economics-formulas-2026-07';
export const BENEFIT_CATEGORIES=['capacity_released','avoidable_cash_expenditure','revenue_protected','revenue_enabled','risk_avoided','quality_value','sla_cycle_time_value','safety_protection_value','other_typed_value'] as const;
export const COST_CATEGORIES=['discovery_design','engineering_integration','licences','workflow_rpa_ai_ocr_model_usage','cloud_infrastructure','testing_validation','security_governance','training_change_management','support_maintenance','monitoring_operations','contingency'] as const;
export type BenefitCategory=typeof BENEFIT_CATEGORIES[number]; export type CostCategory=typeof COST_CATEGORIES[number];
export type Confidence='Verified'|'Partially Evidenced'|'Assumption-Led'|'Insufficient Evidence';
export type Lifecycle='draft'|'reviewer_ready'|'in_review'|'approved'|'changes_requested'|'rejected'|'superseded';
export type Scenario='low'|'base'|'high';
export interface Range{low:number;base:number;high:number;unit:string;period:'one_time'|'monthly'|'quarterly'|'annual'}
export interface EvidenceRef{id:string;fresh:boolean;independent?:boolean;contradicts?:boolean;synthetic?:boolean}
export interface EconomicValue{id:string;category:BenefitCategory|CostCategory;range:Range;evidence:EvidenceRef[];owner:string;confidence:Confidence;includeInCash:boolean;nonOverlapExplanation?:string;risk?:{probability:Range;exposure:Range;controlEffectiveness:Range}}
export interface EconomicVersion{organizationId:string;workspaceId:string;caseId:string;sourceAuthoringVersionId:string;decisionVersionId:string;approvedReviewId:string;modelVersion:string;formulaVersion:string;status:Lifecycle;authorId:string;reviewerId?:string;currency:string;baselinePeriod:string;analysisHorizonYears:number;implementationHorizonMonths:number;discountRate?:number;benefits:EconomicValue[];costs:EconomicValue[];synthetic?:boolean}
export interface ScenarioResult{scenario:Scenario;capacityReleased:number;annualAvoidableCashBenefit:number;annualRevenueValue:number;annualExpectedRiskAdjustedValue:number;qualitySlaSafetyValue:number;oneTimeCost:number;annualRecurringCost:number;tco:number;netAnnualBenefit:number;cumulativeNetValue:number;paybackPeriodMonths:'not reached'|number;roi:number;npv?:number;trace:string[]}
const assert=(c:boolean,m:string)=>{if(!c)throw new Error(m)}; const pick=(r:Range,s:Scenario)=>r[s];
export function validateEconomicVersion(v:EconomicVersion){assert(v.modelVersion===ECONOMIC_MODEL_VERSION,'UNKNOWN_MODEL_VERSION');assert(v.formulaVersion===ECONOMIC_FORMULA_VERSION,'UNKNOWN_FORMULA_VERSION');assert(/^[A-Z]{3}$/.test(v.currency),'INVALID_CURRENCY');assert(!!v.baselinePeriod,'MISSING_PERIOD');assert(v.analysisHorizonYears>0&&v.implementationHorizonMonths>0,'INVALID_HORIZON');const ids=new Set<string>();const capacityCash=v.benefits.filter(b=>b.category==='capacity_released'&&b.includeInCash);for(const item of [...v.benefits,...v.costs]){assert(!ids.has(item.id),'DUPLICATE_VALUE');ids.add(item.id);assert(item.owner.trim().length>0,'MISSING_OWNER');assert(item.evidence.length>0,'MISSING_EVIDENCE');assert(item.range.unit.trim().length>0&&!!item.range.period,'MISSING_UNIT_OR_PERIOD');assert(item.range.low>=0&&item.range.base>=0&&item.range.high>=0,'NEGATIVE_VALUE');assert(item.range.low<=item.range.base&&item.range.base<=item.range.high,'RANGE_ORDER');if(item.category==='capacity_released')assert(!item.includeInCash||!!item.nonOverlapExplanation,'CAPACITY_CASH_NEEDS_NON_OVERLAP');if(item.category==='avoidable_cash_expenditure')assert(item.includeInCash&&item.evidence.some(e=>e.independent&&!e.synthetic),'CASH_SAVINGS_REQUIRE_EVIDENCE');}assert(capacityCash.every(b=>b.nonOverlapExplanation),'CAPACITY_NOT_AUTOMATIC_CASH');return true}
function annualize(r:Range,s:Scenario){const v=pick(r,s);return r.period==='monthly'?v*12:r.period==='quarterly'?v*4:v}
function riskValue(b:EconomicValue,s:Scenario){if(!b.risk)return annualize(b.range,s);return pick(b.risk.probability,s)*pick(b.risk.exposure,s)*pick(b.risk.controlEffectiveness,s)}
export function calculateScenarios(v:EconomicVersion):ScenarioResult[]{validateEconomicVersion(v);return(['low','base','high'] as Scenario[]).map(s=>{let capacity=0,cash=0,rev=0,risk=0,quality=0,one=0,rec=0;for(const b of v.benefits){if(b.category==='capacity_released')capacity+=annualize(b.range,s); if(b.category==='avoidable_cash_expenditure'&&b.includeInCash)cash+=annualize(b.range,s); if(b.category==='revenue_protected'||b.category==='revenue_enabled')rev+=annualize(b.range,s); if(b.category==='risk_avoided')risk+=riskValue(b,s); if(['quality_value','sla_cycle_time_value','safety_protection_value','other_typed_value'].includes(b.category))quality+=annualize(b.range,s)}for(const c of v.costs){if(c.range.period==='one_time')one+=pick(c.range,s);else rec+=annualize(c.range,s)}const annual=cash+rev+risk+quality-rec; const cumulative=annual*v.analysisHorizonYears-one; const tco=one+rec*v.analysisHorizonYears; const payback=annual<=0?'not reached':Math.ceil(one/(annual/12)); const roi=tco===0?0:round(cumulative/tco); const npv=v.discountRate==null?undefined:round(Array.from({length:v.analysisHorizonYears},(_,i)=>annual/Math.pow(1+v.discountRate!,i+1)).reduce((a,b)=>a+b,0)-one);return{scenario:s,capacityReleased:round(capacity),annualAvoidableCashBenefit:round(cash),annualRevenueValue:round(rev),annualExpectedRiskAdjustedValue:round(risk),qualitySlaSafetyValue:round(quality),oneTimeCost:round(one),annualRecurringCost:round(rec),tco:round(tco),netAnnualBenefit:round(annual),cumulativeNetValue:round(cumulative),paybackPeriodMonths:payback==='not reached'?payback:round(payback),roi,npv,trace:[`formula:${ECONOMIC_FORMULA_VERSION}`,`scenario:${s}`,`capacity hours are reported separately from cash`]}})}
export function deriveConfidence(v:EconomicVersion):Confidence{const items=[...v.benefits,...v.costs];if(!items.length||items.some(i=>!i.owner||!i.range.unit||!i.evidence.length))return'Insufficient Evidence';if(items.some(i=>i.evidence.some(e=>e.contradicts)))return'Insufficient Evidence';if(items.some(i=>i.evidence.some(e=>!e.fresh)||i.confidence==='Assumption-Led'))return'Assumption-Led';if(items.every(i=>i.evidence.some(e=>e.independent&&!e.synthetic)&&i.confidence==='Verified'))return'Verified';return'Partially Evidenced'}
export function approveEconomics(v:EconomicVersion,reviewerId:string,approvedReviewCurrent:boolean){validateEconomicVersion(v);assert(approvedReviewCurrent,'STALE_OR_MISSING_PR1E_REVIEW');assert(reviewerId!==v.authorId,'SEPARATION_OF_DUTIES');assert(deriveConfidence(v)!=='Insufficient Evidence','INSUFFICIENT_EVIDENCE');return{...v,status:'approved' as Lifecycle,reviewerId}}
export interface Outcome{economicVersionId:string;synthetic?:boolean;estimated?:boolean;reviewedBy?:string;owner:string;period:string;actuals:{netAnnualBenefit?:number;oneTimeCost?:number;paybackMonths?:number}}
export function qualifyOutcomesForCalibration(outcomes:Outcome[],policy={minSamples:5}){const qualified=outcomes.filter(o=>!o.synthetic&&!o.estimated&&o.reviewedBy&&o.reviewedBy!==o.owner);return{sampleCount:qualified.length,status:qualified.length>=policy.minSamples?'Indicative Only' as const:'Insufficient Data' as const,qualified}}
export function calibrationSnapshot(forecasts:ScenarioResult[],outcomes:Outcome[]){const q=qualifyOutcomesForCalibration(outcomes);return{sampleCount:q.sampleCount,status:q.status,formulaVersion:ECONOMIC_FORMULA_VERSION,syntheticExcluded:outcomes.length-q.qualified.length,missingDataRate:q.sampleCount===0?1:0,bias:0,meanAbsoluteError:null as number|null,benefitRealizationRatio:null as number|null,costOverrunRatio:null as number|null,paybackAccuracy:null as number|null,note:'Calibration reports variance only; it never changes formulas, thresholds, weights, or historical forecasts.'}}
export type Disposition='Proceed to controlled design'|'Validate assumptions first'|'Redesign process first'|'Monitor'|'Do not prioritize currently';
export function portfolioDisposition(input:{technicalReady:boolean;governanceApproved:boolean;confidence:Confidence;scenario:ScenarioResult;currency:string;complexity:'low'|'medium'|'high';dependencies:string[]}):{disposition:Disposition;reasons:string[];whatWouldChange:string[]}{const reasons:string[]=[]; if(!input.technicalReady){reasons.push('technical hard gate failed before economic priority');return{disposition:'Redesign process first',reasons,whatWouldChange:['Resolve technical suitability without using business value to raise fit']}} if(!input.governanceApproved){reasons.push('governance approval hard gate failed');return{disposition:'Monitor',reasons,whatWouldChange:['Complete required Govern approval']}} if(input.confidence==='Insufficient Evidence'||input.confidence==='Assumption-Led'){reasons.push(`economic confidence is ${input.confidence}`);return{disposition:'Validate assumptions first',reasons,whatWouldChange:['Add fresh independent evidence for material assumptions']}} if(input.scenario.netAnnualBenefit<=0){reasons.push('base net annual benefit is not positive');return{disposition:'Do not prioritize currently',reasons,whatWouldChange:['Reduce cost or increase evidenced benefit above break-even']}} reasons.push('hard gates passed before priority calculation');return{disposition:input.complexity==='high'?'Validate assumptions first':'Proceed to controlled design',reasons,whatWouldChange:['Material cost overrun, stale evidence, revoked approval, or incompatible currency would change disposition']}}
export function blockCrossCurrencyAggregation(currencies:string[]){assert(new Set(currencies).size<=1,'INCOMPATIBLE_CURRENCIES');return true}
function round(n:number){return Math.round(n*100)/100}
