-- PR 1D: additive Avala Assess V2 decision-intelligence authority.
-- V1 scoring and lifecycle remain unchanged. Rollback is feature disable/read-only plus forward fix.

INSERT INTO public.capabilities(capability_key,module,description) VALUES
 ('assess.v2.read','assess','Read workspace-scoped Assess V2 cases and decisions'),
 ('assess.v2.create','assess','Create Assess V2 cases'),
 ('assess.v2.clone','assess','Clone allowlisted V1 facts into a V2 case'),
 ('assess.v2.draft.write','assess','Append immutable Assess V2 authoring revisions'),
 ('assess.v2.finalize','assess','Finalize a server-evaluated Assess V2 decision')
ON CONFLICT(capability_key) DO UPDATE SET module=excluded.module,description=excluded.description;

CREATE TABLE public.assess_v2_runtime_control(
 singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton), enabled boolean NOT NULL DEFAULT true,
 read_only boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.assess_v2_runtime_control(singleton) VALUES(true) ON CONFLICT DO NOTHING;

CREATE TABLE public.assess_v2_cases(
 id uuid PRIMARY KEY, org_id uuid NOT NULL, workspace_id uuid NOT NULL, process_id uuid NOT NULL,
 owner_id uuid NOT NULL REFERENCES public.profiles(id), status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','reviewer_ready','superseded')),
 version bigint NOT NULL DEFAULT 1 CHECK(version>0), head_version_id uuid, schema_version text NOT NULL DEFAULT 'assess-v2-schema-2026-07',
 rule_set_version text NOT NULL DEFAULT 'assess-v2-rules-2026-07', source_v1_assessment_id uuid, source_v1_score_version text,
 deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(id,workspace_id,org_id), FOREIGN KEY(process_id,workspace_id,org_id) REFERENCES public.assess_processes(id,workspace_id,org_id),
 FOREIGN KEY(workspace_id,org_id) REFERENCES public.workspaces(id,org_id),
 CHECK((source_v1_assessment_id IS NULL)=(source_v1_score_version IS NULL))
);
CREATE TABLE public.assess_v2_case_versions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL, org_id uuid NOT NULL, workspace_id uuid NOT NULL,
 version bigint NOT NULL CHECK(version>0), name text NOT NULL CHECK(length(btrim(name)) BETWEEN 1 AND 200), description text NOT NULL DEFAULT '',
 agent_necessity jsonb NOT NULL DEFAULT '{"irreducibleAmbiguity":null,"adaptiveNextStep":null,"toolOrPathSelection":null,"incrementalValue":null,"controllable":null}',
 source_kind text NOT NULL CHECK(source_kind IN('create','v1_clone','draft_upsert')), source_snapshot jsonb,
 created_by uuid NOT NULL REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(case_id,version), UNIQUE(id,case_id,workspace_id,org_id),
 FOREIGN KEY(case_id,workspace_id,org_id) REFERENCES public.assess_v2_cases(id,workspace_id,org_id) ON DELETE RESTRICT
);
ALTER TABLE public.assess_v2_cases ADD CONSTRAINT pr1d_case_head_fkey FOREIGN KEY(head_version_id,id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE public.assess_v2_primitives(
 id uuid NOT NULL, version_id uuid NOT NULL, case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,
 PRIMARY KEY(version_id,id),FOREIGN KEY(version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_edges(
 id uuid NOT NULL,version_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,
 PRIMARY KEY(version_id,id),FOREIGN KEY(version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_application_assets(
 id uuid NOT NULL,version_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,
 PRIMARY KEY(version_id,id),FOREIGN KEY(version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_application_interactions(
 id uuid NOT NULL,version_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,
 PRIMARY KEY(version_id,id),FOREIGN KEY(version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_evidence_links(
 id uuid NOT NULL,version_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,
 PRIMARY KEY(version_id,id),FOREIGN KEY(version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_decision_versions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL,source_version_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,
 schema_version text NOT NULL,rule_set_version text NOT NULL,decision_version text NOT NULL,validation_status text NOT NULL CHECK(validation_status='reviewer-ready'),
 input_snapshot jsonb NOT NULL,evidence_snapshot jsonb NOT NULL,output_snapshot jsonb NOT NULL,
 input_hash text NOT NULL CHECK(input_hash~'^[0-9a-f]{64}$'),evidence_hash text NOT NULL CHECK(evidence_hash~'^[0-9a-f]{64}$'),output_hash text NOT NULL CHECK(output_hash~'^[0-9a-f]{64}$'),
 supersedes_decision_id uuid REFERENCES public.assess_v2_decision_versions(id) ON DELETE RESTRICT,receipt_id uuid NOT NULL UNIQUE REFERENCES public.assess_command_receipts(id) ON DELETE RESTRICT,
 created_by uuid NOT NULL REFERENCES public.profiles(id),created_at timestamptz NOT NULL,UNIQUE(case_id,source_version_id,rule_set_version,decision_version),UNIQUE(id,case_id,workspace_id,org_id),
 FOREIGN KEY(source_version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);

CREATE OR REPLACE FUNCTION public.pr1d_reject_immutable() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'PR1D_IMMUTABLE';END$$;
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['assess_v2_case_versions','assess_v2_primitives','assess_v2_edges','assess_v2_application_assets','assess_v2_application_interactions','assess_v2_evidence_links','assess_v2_decision_versions'] LOOP EXECUTE format('CREATE TRIGGER trg_pr1d_%I_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.pr1d_reject_immutable()',t,t);END LOOP;END$$;

CREATE OR REPLACE FUNCTION public.pr1d_assert_enabled() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE c public.assess_v2_runtime_control;BEGIN SELECT * INTO c FROM public.assess_v2_runtime_control WHERE singleton=true FOR SHARE;IF NOT c.enabled THEN RAISE EXCEPTION 'PR1D_FEATURE_DISABLED';END IF;IF c.read_only THEN RAISE EXCEPTION 'PR1D_READ_ONLY';END IF;END$$;
CREATE OR REPLACE FUNCTION public.pr1d_resource(p_case uuid,p_org uuid,p_workspace uuid) RETURNS public.assess_v2_cases LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$SELECT * FROM public.assess_v2_cases WHERE id=p_case AND org_id=p_org AND workspace_id=p_workspace AND deleted_at IS NULL$$;

CREATE OR REPLACE FUNCTION public.pr1d_create_assess_v2_case(p_actor_id uuid,p_org_id uuid,p_workspace_id uuid,p_case_id uuid,p_process_id uuid,p_name text,p_description text,p_request_id uuid,p_idempotency_key text,p_authorization_version bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r public.assess_command_receipts;c public.assess_v2_cases;v public.assess_v2_case_versions;h text:=encode(public.digest(concat_ws('|',p_org_id,p_workspace_id,p_case_id,p_process_id,p_name,p_description),'sha256'),'hex');result jsonb;BEGIN
 PERFORM public.pr1d_assert_enabled();PERFORM public.pr1b_assert_command_authority(p_actor_id,p_org_id,p_workspace_id,'assess.v2.create',p_authorization_version);
 IF NOT EXISTS(SELECT 1 FROM public.assess_processes WHERE id=p_process_id AND org_id=p_org_id AND workspace_id=p_workspace_id AND deleted_at IS NULL) THEN RETURN jsonb_build_object('errorCode','NOT_FOUND');END IF;
 r:=public.pr1b_claim_command(p_actor_id,p_org_id,p_workspace_id,'assessment_v2.create',p_idempotency_key,p_request_id,h);IF r.status='succeeded' THEN RETURN jsonb_build_object('outcome','replayed','resource',r.response);END IF;
 INSERT INTO public.assess_v2_cases(id,org_id,workspace_id,process_id,owner_id) VALUES(p_case_id,p_org_id,p_workspace_id,p_process_id,p_actor_id) RETURNING * INTO c;
 INSERT INTO public.assess_v2_case_versions(case_id,org_id,workspace_id,version,name,description,source_kind,created_by) VALUES(c.id,p_org_id,p_workspace_id,1,p_name,p_description,'create',p_actor_id) RETURNING * INTO v;
 UPDATE public.assess_v2_cases SET head_version_id=v.id WHERE id=c.id;result:=jsonb_build_object('id',c.id,'status','draft','version',1,'headVersionId',v.id);
 INSERT INTO public.privileged_audit_events(org_id,workspace_id,actor_id,request_id,action,resource_type,resource_id,outcome,resource_version) VALUES(p_org_id,p_workspace_id,p_actor_id,p_request_id,'assessment_v2.create','assess_v2_case',c.id,'succeeded',1);
 UPDATE public.assess_command_receipts SET status='succeeded',response=result,completed_at=now() WHERE id=r.id;RETURN jsonb_build_object('outcome','committed','resource',result);
EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('errorCode','VERSION_CONFLICT');WHEN OTHERS THEN IF SQLERRM LIKE '%PR1B_IDEMPOTENCY_CONFLICT%' THEN RETURN jsonb_build_object('errorCode','IDEMPOTENCY_CONFLICT');ELSIF SQLERRM LIKE '%PR1B_AUTHORIZATION_STALE%' THEN RETURN jsonb_build_object('errorCode','AUTHORIZATION_STALE');ELSIF SQLERRM LIKE '%PR1D_FEATURE_DISABLED%' THEN RETURN jsonb_build_object('errorCode','FEATURE_DISABLED');ELSIF SQLERRM LIKE '%PR1D_READ_ONLY%' THEN RETURN jsonb_build_object('errorCode','READ_ONLY');END IF;RAISE;END$$;

CREATE OR REPLACE FUNCTION public.pr1d_clone_assess_v2_from_v1(p_actor_id uuid,p_org_id uuid,p_workspace_id uuid,p_case_id uuid,p_source_assessment_id uuid,p_name text,p_description text,p_request_id uuid,p_idempotency_key text,p_authorization_version bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE a public.assessments;r public.assess_command_receipts;c public.assess_v2_cases;v public.assess_v2_case_versions;h text:=encode(public.digest(concat_ws('|',p_org_id,p_workspace_id,p_case_id,p_source_assessment_id,p_name,p_description),'sha256'),'hex');result jsonb;BEGIN
 PERFORM public.pr1d_assert_enabled();PERFORM public.pr1b_assert_command_authority(p_actor_id,p_org_id,p_workspace_id,'assess.v2.clone',p_authorization_version);SELECT * INTO a FROM public.assessments WHERE id=p_source_assessment_id AND org_id=p_org_id AND workspace_id=p_workspace_id AND deleted_at IS NULL FOR SHARE;IF a.id IS NULL OR a.score_version IS DISTINCT FROM 'assess-core-2026-05' THEN RETURN jsonb_build_object('errorCode','NOT_FOUND');END IF;
 r:=public.pr1b_claim_command(p_actor_id,p_org_id,p_workspace_id,'assessment_v2.clone_from_v1',p_idempotency_key,p_request_id,h);IF r.status='succeeded' THEN RETURN jsonb_build_object('outcome','replayed','resource',r.response);END IF;
 INSERT INTO public.assess_v2_cases(id,org_id,workspace_id,process_id,owner_id,source_v1_assessment_id,source_v1_score_version) VALUES(p_case_id,p_org_id,p_workspace_id,a.process_id,p_actor_id,a.id,a.score_version) RETURNING * INTO c;
 INSERT INTO public.assess_v2_case_versions(case_id,org_id,workspace_id,version,name,description,source_kind,source_snapshot,created_by) VALUES(c.id,p_org_id,p_workspace_id,1,p_name,p_description,'v1_clone',jsonb_build_object('assessmentId',a.id,'scoreVersion',a.score_version,'importedAs','unverified-source-facts','responses',COALESCE(a.responses,'{}')),p_actor_id) RETURNING * INTO v;
 UPDATE public.assess_v2_cases SET head_version_id=v.id WHERE id=c.id;result:=jsonb_build_object('id',c.id,'status','draft','version',1,'headVersionId',v.id);INSERT INTO public.privileged_audit_events(org_id,workspace_id,actor_id,request_id,action,resource_type,resource_id,outcome,resource_version,metadata) VALUES(p_org_id,p_workspace_id,p_actor_id,p_request_id,'assessment_v2.clone_from_v1','assess_v2_case',c.id,'succeeded',1,jsonb_build_object('sourceScoreVersion','assess-core-2026-05'));
 UPDATE public.assess_command_receipts SET status='succeeded',response=result,completed_at=now() WHERE id=r.id;RETURN jsonb_build_object('outcome','committed','resource',result);EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('errorCode','VERSION_CONFLICT');WHEN OTHERS THEN IF SQLERRM LIKE '%PR1B_IDEMPOTENCY_CONFLICT%' THEN RETURN jsonb_build_object('errorCode','IDEMPOTENCY_CONFLICT');ELSIF SQLERRM LIKE '%PR1B_AUTHORIZATION_STALE%' THEN RETURN jsonb_build_object('errorCode','AUTHORIZATION_STALE');ELSIF SQLERRM LIKE '%PR1D_FEATURE_DISABLED%' THEN RETURN jsonb_build_object('errorCode','FEATURE_DISABLED');ELSIF SQLERRM LIKE '%PR1D_READ_ONLY%' THEN RETURN jsonb_build_object('errorCode','READ_ONLY');END IF;RAISE;END$$;

CREATE OR REPLACE FUNCTION public.pr1d_upsert_assess_v2_draft(p_actor_id uuid,p_org_id uuid,p_workspace_id uuid,p_case_id uuid,p_expected_version bigint,p_authoring jsonb,p_request_id uuid,p_idempotency_key text,p_authorization_version bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE c public.assess_v2_cases;r public.assess_command_receipts;v public.assess_v2_case_versions;x jsonb;h text:=encode(public.digest(concat_ws('|',p_org_id,p_workspace_id,p_case_id,p_expected_version,p_authoring::text),'sha256'),'hex');result jsonb;BEGIN
 PERFORM public.pr1d_assert_enabled();PERFORM public.pr1b_assert_command_authority(p_actor_id,p_org_id,p_workspace_id,'assess.v2.draft.write',p_authorization_version);SELECT * INTO c FROM public.assess_v2_cases WHERE id=p_case_id AND org_id=p_org_id AND workspace_id=p_workspace_id AND deleted_at IS NULL FOR UPDATE;IF c.id IS NULL THEN RETURN jsonb_build_object('errorCode','NOT_FOUND');END IF;IF c.status<>'draft' OR c.version<>p_expected_version THEN RETURN jsonb_build_object('errorCode','VERSION_CONFLICT');END IF;
 r:=public.pr1b_claim_command(p_actor_id,p_org_id,p_workspace_id,'assessment_v2.draft.upsert',p_idempotency_key,p_request_id,h);IF r.status='succeeded' THEN RETURN jsonb_build_object('outcome','replayed','resource',r.response);END IF;
 INSERT INTO public.assess_v2_case_versions(case_id,org_id,workspace_id,version,name,description,agent_necessity,source_kind,created_by) VALUES(c.id,p_org_id,p_workspace_id,c.version+1,p_authoring->>'name',p_authoring->>'description',p_authoring->'agentNecessity','draft_upsert',p_actor_id) RETURNING * INTO v;
 FOR x IN SELECT * FROM jsonb_array_elements(p_authoring->'primitives') LOOP INSERT INTO public.assess_v2_primitives VALUES((x->>'id')::uuid,v.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(p_authoring->'edges') LOOP INSERT INTO public.assess_v2_edges VALUES((x->>'id')::uuid,v.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(p_authoring->'decisionPoints') LOOP INSERT INTO public.assess_v2_decision_points VALUES((x->>'id')::uuid,v.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(p_authoring->'exceptionPaths') LOOP INSERT INTO public.assess_v2_exception_paths VALUES((x->>'id')::uuid,v.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(p_authoring->'assets') LOOP INSERT INTO public.assess_v2_application_assets VALUES((x->>'id')::uuid,v.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(p_authoring->'interactions') LOOP INSERT INTO public.assess_v2_application_interactions VALUES((x->>'id')::uuid,v.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(p_authoring->'evidence') LOOP INSERT INTO public.assess_v2_evidence_links VALUES((x->>'id')::uuid,v.id,c.id,p_org_id,p_workspace_id,x);END LOOP;
 UPDATE public.assess_v2_cases SET version=v.version,head_version_id=v.id,updated_at=now() WHERE id=c.id;result:=jsonb_build_object('id',c.id,'status','draft','version',v.version,'headVersionId',v.id);INSERT INTO public.privileged_audit_events(org_id,workspace_id,actor_id,request_id,action,resource_type,resource_id,outcome,resource_version) VALUES(p_org_id,p_workspace_id,p_actor_id,p_request_id,'assessment_v2.draft.upsert','assess_v2_case',c.id,'succeeded',v.version);UPDATE public.assess_command_receipts SET status='succeeded',response=result,completed_at=now() WHERE id=r.id;RETURN jsonb_build_object('outcome','committed','resource',result);EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%PR1B_IDEMPOTENCY_CONFLICT%' THEN RETURN jsonb_build_object('errorCode','IDEMPOTENCY_CONFLICT');ELSIF SQLERRM LIKE '%PR1B_AUTHORIZATION_STALE%' THEN RETURN jsonb_build_object('errorCode','AUTHORIZATION_STALE');ELSIF SQLERRM LIKE '%PR1D_FEATURE_DISABLED%' THEN RETURN jsonb_build_object('errorCode','FEATURE_DISABLED');ELSIF SQLERRM LIKE '%PR1D_READ_ONLY%' THEN RETURN jsonb_build_object('errorCode','READ_ONLY');END IF;RAISE;END$$;

CREATE OR REPLACE FUNCTION public.pr1d_load_assess_v2_case(p_case_id uuid,p_org_id uuid,p_workspace_id uuid,p_expected_version bigint) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE c public.assess_v2_cases;v public.assess_v2_case_versions;BEGIN SELECT * INTO c FROM public.assess_v2_cases WHERE id=p_case_id AND org_id=p_org_id AND workspace_id=p_workspace_id AND deleted_at IS NULL FOR SHARE;IF c.id IS NULL THEN RETURN NULL;END IF;IF c.version<>p_expected_version OR c.status<>'draft' THEN RAISE EXCEPTION 'PR1D_VERSION_CONFLICT';END IF;SELECT * INTO v FROM public.assess_v2_case_versions WHERE id=c.head_version_id;RETURN jsonb_build_object('id',c.id,'organizationId',c.org_id,'workspaceId',c.workspace_id,'sourceProcessId',c.process_id,'ownerId',c.owner_id,'status','draft','version',c.version,'schemaVersion',c.schema_version,'ruleSetVersion',c.rule_set_version,'sourceV1',CASE WHEN c.source_v1_assessment_id IS NULL THEN NULL ELSE jsonb_build_object('assessmentId',c.source_v1_assessment_id,'scoreVersion',c.source_v1_score_version,'clonedAt',v.created_at,'importedAs','unverified-source-facts') END,'primitives',COALESCE((SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_primitives WHERE version_id=v.id),'[]'),'edges',COALESCE((SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_edges WHERE version_id=v.id),'[]'),'decisionPoints',COALESCE((SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_decision_points WHERE version_id=v.id),'[]'),'exceptionPaths',COALESCE((SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_exception_paths WHERE version_id=v.id),'[]'),'assets',COALESCE((SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_application_assets WHERE version_id=v.id),'[]'),'interactions',COALESCE((SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_application_interactions WHERE version_id=v.id),'[]'),'evidence',COALESCE((SELECT jsonb_agg(payload ORDER BY id) FROM public.assess_v2_evidence_links WHERE version_id=v.id),'[]'),'agentNecessity',v.agent_necessity,'createdAt',c.created_at,'updatedAt',c.updated_at);END$$;

CREATE OR REPLACE FUNCTION public.pr1d_finalize_assess_v2_case(p_actor_id uuid,p_org_id uuid,p_workspace_id uuid,p_case_id uuid,p_expected_version bigint,p_source_case jsonb,p_evidence_snapshot jsonb,p_output_snapshot jsonb,p_input_hash text,p_evidence_hash text,p_output_hash text,p_rule_set_version text,p_decision_version text,p_created_at timestamptz,p_request_id uuid,p_idempotency_key text,p_authorization_version bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE c public.assess_v2_cases;r public.assess_command_receipts;d public.assess_v2_decision_versions;x jsonb;h text:=encode(public.digest(concat_ws('|',p_org_id,p_workspace_id,p_case_id,p_expected_version,p_input_hash,p_evidence_hash,p_output_hash),'sha256'),'hex');result jsonb;BEGIN
 PERFORM public.pr1d_assert_enabled();PERFORM public.pr1b_assert_command_authority(p_actor_id,p_org_id,p_workspace_id,'assess.v2.finalize',p_authorization_version);SELECT * INTO c FROM public.assess_v2_cases WHERE id=p_case_id AND org_id=p_org_id AND workspace_id=p_workspace_id AND deleted_at IS NULL FOR UPDATE;IF c.id IS NULL THEN RETURN jsonb_build_object('errorCode','NOT_FOUND');END IF;IF c.status<>'draft' OR c.version<>p_expected_version THEN RETURN jsonb_build_object('errorCode','VERSION_CONFLICT');END IF;IF p_source_case->>'id'<>c.id::text OR (p_source_case->>'version')::bigint<>c.version OR p_rule_set_version<>c.rule_set_version OR p_output_snapshot->>'caseId'<>c.id::text OR p_output_snapshot->>'validationStatus'<>'reviewer-ready' THEN RETURN jsonb_build_object('errorCode','INVALID_COMMAND');END IF;
 r:=public.pr1b_claim_command(p_actor_id,p_org_id,p_workspace_id,'assessment_v2.finalize',p_idempotency_key,p_request_id,h);IF r.status='succeeded' THEN RETURN jsonb_build_object('outcome','replayed','resource',r.response);END IF;
 INSERT INTO public.assess_v2_decision_versions(case_id,source_version_id,org_id,workspace_id,schema_version,rule_set_version,decision_version,validation_status,input_snapshot,evidence_snapshot,output_snapshot,input_hash,evidence_hash,output_hash,receipt_id,created_by,created_at) VALUES(c.id,c.head_version_id,p_org_id,p_workspace_id,c.schema_version,p_rule_set_version,p_decision_version,'reviewer-ready',p_source_case,p_evidence_snapshot,p_output_snapshot,p_input_hash,p_evidence_hash,p_output_hash,r.id,p_actor_id,p_created_at) RETURNING * INTO d;
 FOR x IN SELECT * FROM jsonb_array_elements(COALESCE(p_output_snapshot->'candidateEvaluations','[]')) LOOP INSERT INTO public.assess_v2_candidate_evaluations VALUES(gen_random_uuid(),d.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(COALESCE(p_output_snapshot->'gateResults','[]')) LOOP INSERT INTO public.assess_v2_gate_results VALUES(gen_random_uuid(),d.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(COALESCE(p_output_snapshot->'controlRequirements','[]')) LOOP INSERT INTO public.assess_v2_control_requirements VALUES(gen_random_uuid(),d.id,c.id,p_org_id,p_workspace_id,x);END LOOP;FOR x IN SELECT * FROM jsonb_array_elements(COALESCE(p_output_snapshot->'modernization','[]')) LOOP INSERT INTO public.assess_v2_modernization_dispositions VALUES(gen_random_uuid(),d.id,c.id,p_org_id,p_workspace_id,x);END LOOP;
 UPDATE public.assess_v2_cases SET status='reviewer_ready',version=version+1,updated_at=now() WHERE id=c.id;result:=jsonb_build_object('id',c.id,'status','reviewer_ready','version',c.version+1,'headVersionId',c.head_version_id,'decisionId',d.id);INSERT INTO public.privileged_audit_events(org_id,workspace_id,actor_id,request_id,action,resource_type,resource_id,outcome,resource_version,metadata) VALUES(p_org_id,p_workspace_id,p_actor_id,p_request_id,'assessment_v2.finalize','assess_v2_case',c.id,'succeeded',c.version+1,jsonb_build_object('decisionId',d.id,'ruleSetVersion',p_rule_set_version,'decisionVersion',p_decision_version,'inputHash',p_input_hash,'evidenceHash',p_evidence_hash,'outputHash',p_output_hash));UPDATE public.assess_command_receipts SET status='succeeded',response=result,completed_at=now() WHERE id=r.id;RETURN jsonb_build_object('outcome','committed','resource',result);EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('errorCode','VERSION_CONFLICT');WHEN OTHERS THEN IF SQLERRM LIKE '%PR1B_IDEMPOTENCY_CONFLICT%' THEN RETURN jsonb_build_object('errorCode','IDEMPOTENCY_CONFLICT');ELSIF SQLERRM LIKE '%PR1B_AUTHORIZATION_STALE%' THEN RETURN jsonb_build_object('errorCode','AUTHORIZATION_STALE');ELSIF SQLERRM LIKE '%PR1D_FEATURE_DISABLED%' THEN RETURN jsonb_build_object('errorCode','FEATURE_DISABLED');ELSIF SQLERRM LIKE '%PR1D_READ_ONLY%' THEN RETURN jsonb_build_object('errorCode','READ_ONLY');END IF;RAISE;END$$;

DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['assess_v2_cases','assess_v2_case_versions','assess_v2_primitives','assess_v2_edges','assess_v2_application_assets','assess_v2_application_interactions','assess_v2_evidence_links','assess_v2_decision_versions','assess_v2_runtime_control'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);END LOOP;END$$;
CREATE POLICY pr1d_cases_read ON public.assess_v2_cases FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
CREATE POLICY pr1d_versions_read ON public.assess_v2_case_versions FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
CREATE POLICY pr1d_primitives_read ON public.assess_v2_primitives FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
CREATE POLICY pr1d_edges_read ON public.assess_v2_edges FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
CREATE POLICY pr1d_assets_read ON public.assess_v2_application_assets FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
CREATE POLICY pr1d_interactions_read ON public.assess_v2_application_interactions FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
CREATE POLICY pr1d_evidence_read ON public.assess_v2_evidence_links FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
CREATE POLICY pr1d_decisions_read ON public.assess_v2_decision_versions FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,'assess.v2.read'));
REVOKE ALL ON public.assess_v2_runtime_control,public.assess_v2_cases,public.assess_v2_case_versions,public.assess_v2_primitives,public.assess_v2_edges,public.assess_v2_application_assets,public.assess_v2_application_interactions,public.assess_v2_evidence_links,public.assess_v2_decision_versions FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.assess_v2_cases,public.assess_v2_case_versions,public.assess_v2_primitives,public.assess_v2_edges,public.assess_v2_application_assets,public.assess_v2_application_interactions,public.assess_v2_evidence_links,public.assess_v2_decision_versions TO authenticated;
REVOKE ALL ON FUNCTION public.pr1d_create_assess_v2_case(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,bigint),public.pr1d_clone_assess_v2_from_v1(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,bigint),public.pr1d_upsert_assess_v2_draft(uuid,uuid,uuid,uuid,bigint,jsonb,uuid,text,bigint),public.pr1d_load_assess_v2_case(uuid,uuid,uuid,bigint),public.pr1d_finalize_assess_v2_case(uuid,uuid,uuid,uuid,bigint,jsonb,jsonb,jsonb,text,text,text,text,text,timestamptz,uuid,text,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.pr1d_create_assess_v2_case(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,bigint),public.pr1d_clone_assess_v2_from_v1(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,bigint),public.pr1d_upsert_assess_v2_draft(uuid,uuid,uuid,uuid,bigint,jsonb,uuid,text,bigint),public.pr1d_load_assess_v2_case(uuid,uuid,uuid,bigint),public.pr1d_finalize_assess_v2_case(uuid,uuid,uuid,uuid,bigint,jsonb,jsonb,jsonb,text,text,text,text,text,timestamptz,uuid,text,bigint) TO service_role;

-- Forward PR 1C correction: use the canonical dotted command type on new Studio handoff receipts/audits.


-- Forward PR 1C defect fix: a request-changes decision can be resubmitted.
CREATE OR REPLACE FUNCTION public.pr1c_govern_resolve(
 p_actor_id uuid,p_org_id uuid,p_workspace_id uuid,p_assessment_id uuid,p_resolution text,p_reason text,p_expected_version bigint,p_request_id uuid,p_idempotency_key text,p_authorization_version bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE r public.assess_command_receipts;a public.assessments;v_target text;v_event text;v_reason text:=NULLIF(btrim(p_reason),'');v_restricted boolean;h text:=md5(concat_ws('|',p_org_id,p_workspace_id,p_assessment_id,p_expected_version,p_resolution,v_reason));result jsonb;
BEGIN
 PERFORM public.pr1b_assert_command_authority(p_actor_id,p_org_id,p_workspace_id,'govern.resolve',p_authorization_version);
 IF p_resolution NOT IN('submit','approve','request_changes','reject') OR p_expected_version IS NULL OR length(COALESCE(v_reason,''))>1000 OR (p_resolution IN('request_changes','reject') AND v_reason IS NULL) THEN RAISE EXCEPTION 'PR1B_INVALID_COMMAND';END IF;
 r:=public.pr1b_claim_command(p_actor_id,p_org_id,p_workspace_id,'govern.resolve',p_idempotency_key,p_request_id,h);IF r.status='succeeded' THEN RETURN r.response;END IF;
 SELECT * INTO a FROM public.assessments WHERE id=p_assessment_id AND org_id=p_org_id AND workspace_id=p_workspace_id AND deleted_at IS NULL FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'PR1B_NOT_FOUND';END IF;IF a.version<>p_expected_version THEN RAISE EXCEPTION 'PR1B_VERSION_CONFLICT';END IF;
 v_restricted:=COALESCE(a.scores#>>'{decisionPack,finalDecision}',a.scores->>'gateDecision','') IN('No-Go','Governance Review Required');
 IF p_resolution='submit' AND a.status IN('Ready for Review','Changes Requested') THEN v_target:='In Review';v_event:='Status Change';
 ELSIF p_resolution='approve' AND a.status IN('Ready for Review','In Review') THEN IF v_restricted AND v_reason IS NULL THEN RAISE EXCEPTION 'PR1B_INVALID_COMMAND';END IF;v_target:='Approved';v_event:='Approval';
 ELSIF p_resolution='request_changes' AND a.status IN('Ready for Review','In Review') THEN v_target:='Changes Requested';v_event:='Change Request';
 ELSIF p_resolution='reject' AND a.status IN('Ready for Review','In Review') THEN v_target:='Rejected';v_event:='Rejection';ELSE RAISE EXCEPTION 'PR1B_INVALID_COMMAND';END IF;
 UPDATE public.assessments SET status=v_target,version=version+1,updated_by=p_actor_id,approved_by=CASE WHEN v_target='Approved' THEN p_actor_id ELSE approved_by END,rejected_by=CASE WHEN v_target='Rejected' THEN p_actor_id ELSE rejected_by END,review=jsonb_set(COALESCE(review,'{}'::jsonb),'{governResolution}',jsonb_build_object('resolution',p_resolution,'reason',v_reason,'actorId',p_actor_id,'resolvedAt',now()),true),updated_at=now() WHERE id=a.id RETURNING * INTO a;
 INSERT INTO public.assessment_govern_provenance(org_id,workspace_id,assessment_id,process_id,actor_id,decision,assessment_version,result_status,request_id,receipt_id,reason) VALUES(p_org_id,p_workspace_id,a.id,a.process_id,p_actor_id,p_resolution,a.version,a.status,p_request_id,r.id,v_reason);
 INSERT INTO public.assessment_review_events(org_id,workspace_id,assessment_id,process_id,actor_id,event_type,status,reason,payload,correlation_id) VALUES(p_org_id,p_workspace_id,a.id,a.process_id,p_actor_id,v_event,v_target,v_reason,jsonb_build_object('resolution',p_resolution,'restrictedDecision',v_restricted,'resourceVersion',a.version),p_request_id::text);
 INSERT INTO public.privileged_audit_events(org_id,workspace_id,actor_id,request_id,action,resource_type,resource_id,outcome,resource_version,metadata) VALUES(p_org_id,p_workspace_id,p_actor_id,p_request_id,'govern.resolve','assessment',a.id,'succeeded',a.version,jsonb_build_object('resolution',p_resolution,'status',v_target));
 result:=jsonb_build_object('ok',true,'outcome','committed','resource',jsonb_build_object('assessmentId',a.id,'version',a.version,'status',a.status));UPDATE public.assess_command_receipts SET status='succeeded',response=result,completed_at=now() WHERE id=r.id;RETURN result;
EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE '%PR1B_%' THEN RAISE LOG 'PR1C_COMMAND_UNAVAILABLE function=pr1c_govern_resolve sqlstate=%',SQLSTATE;END IF;RETURN public.pr1b_error_envelope(SQLERRM);END$$;
REVOKE ALL ON FUNCTION public.pr1c_govern_resolve(uuid,uuid,uuid,uuid,text,text,bigint,uuid,text,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.pr1c_govern_resolve(uuid,uuid,uuid,uuid,text,text,bigint,uuid,text,bigint) TO service_role;


-- Existing Assess-author roles receive additive V2 capabilities; read-only roles receive only V2 read.
INSERT INTO public.role_capabilities(role_id,capability_key)
SELECT rc.role_id,m.v2 FROM public.role_capabilities rc JOIN (VALUES
 ('assess.read','assess.v2.read'),('assess.create','assess.v2.create'),('assess.create','assess.v2.clone'),
 ('assess.response.write','assess.v2.draft.write'),('assess.finalize','assess.v2.finalize')) m(v1,v2) ON m.v1=rc.capability_key
ON CONFLICT DO NOTHING;

CREATE TABLE public.assess_v2_decision_points(id uuid NOT NULL,version_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(version_id,id),FOREIGN KEY(version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_exception_paths(id uuid NOT NULL,version_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(version_id,id),FOREIGN KEY(version_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_case_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_candidate_evaluations(id uuid NOT NULL,decision_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(decision_id,id),FOREIGN KEY(decision_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_decision_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_gate_results(id uuid NOT NULL,decision_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(decision_id,id),FOREIGN KEY(decision_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_decision_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_control_requirements(id uuid NOT NULL,decision_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(decision_id,id),FOREIGN KEY(decision_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_decision_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
CREATE TABLE public.assess_v2_modernization_dispositions(id uuid NOT NULL,decision_id uuid NOT NULL,case_id uuid NOT NULL,org_id uuid NOT NULL,workspace_id uuid NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(decision_id,id),FOREIGN KEY(decision_id,case_id,workspace_id,org_id) REFERENCES public.assess_v2_decision_versions(id,case_id,workspace_id,org_id) ON DELETE RESTRICT);
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['assess_v2_decision_points','assess_v2_exception_paths','assess_v2_candidate_evaluations','assess_v2_gate_results','assess_v2_control_requirements','assess_v2_modernization_dispositions'] LOOP EXECUTE format('CREATE TRIGGER trg_pr1d_%I_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.pr1d_reject_immutable()',t,t);EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('CREATE POLICY pr1d_%I_read ON public.%I FOR SELECT TO authenticated USING(public.has_workspace_capability(workspace_id,org_id,''assess.v2.read''))',t,t);EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t);END LOOP;END$$;
