-- PR 1G additive Application Portfolio & AI-Assisted Modernization Assessment authority.
INSERT INTO public.capabilities(key,domain,description) VALUES
 ('assess.applications.read','assess','Read tenant-scoped application portfolio assessment records'),
 ('assess.applications.write','assess','Create and update draft application metadata'),
 ('assess.applications.import','assess','Import validated CSV/JSON application records'),
 ('assess.applications.finalize','assess','Finalize application assessment versions for review'),
 ('assess.applications.review','assess','Independently resolve application assessment reviews'),
 ('assess.applications.portfolio.read','assess','Read tenant-scoped application portfolio snapshots')
ON CONFLICT(key) DO NOTHING;
CREATE TABLE IF NOT EXISTS public.assess_application_assets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,name text NOT NULL,normalized_name text NOT NULL,description text,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(org_id,workspace_id,normalized_name));
CREATE TABLE IF NOT EXISTS public.assess_application_metadata_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,application_id uuid NOT NULL,version int NOT NULL CHECK(version>0),lifecycle text NOT NULL CHECK(lifecycle IN('draft','reviewer_ready','approved','changes_requested','rejected','superseded')),metadata jsonb NOT NULL,author_id uuid NOT NULL,receipt_id uuid REFERENCES public.assess_command_receipts(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(application_id,version),FOREIGN KEY(application_id) REFERENCES public.assess_application_assets(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS public.assess_process_application_links(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,process_id uuid NOT NULL,primitive_id text NOT NULL,application_id uuid NOT NULL,application_metadata_version_id uuid NOT NULL,interaction_type text NOT NULL,created_by uuid NOT NULL,receipt_id uuid REFERENCES public.assess_command_receipts(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(org_id,workspace_id,process_id,primitive_id,application_id,application_metadata_version_id),FOREIGN KEY(application_id) REFERENCES public.assess_application_assets(id) ON DELETE RESTRICT,FOREIGN KEY(application_metadata_version_id) REFERENCES public.assess_application_metadata_versions(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS public.assess_application_dependencies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,upstream_application_id uuid NOT NULL,downstream_application_id uuid NOT NULL,dependency_type text NOT NULL,metadata_version_id uuid NOT NULL,created_by uuid NOT NULL,receipt_id uuid REFERENCES public.assess_command_receipts(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),CHECK(upstream_application_id<>downstream_application_id));
CREATE TABLE IF NOT EXISTS public.assess_application_assessment_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,application_id uuid NOT NULL,metadata_version_id uuid NOT NULL,version int NOT NULL CHECK(version>0),decision_model_version text NOT NULL CHECK(decision_model_version='assess-v2-application-portfolio-2026-07'),lifecycle text NOT NULL CHECK(lifecycle IN('draft','reviewer_ready','approved','changes_requested','rejected','superseded')),author_id uuid NOT NULL,reviewer_id uuid,authorization_version bigint NOT NULL,receipt_id uuid REFERENCES public.assess_command_receipts(id) ON DELETE RESTRICT,audit_event_id uuid,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(application_id,version),CHECK(reviewer_id IS NULL OR reviewer_id<>author_id));
CREATE TABLE IF NOT EXISTS public.assess_application_dimension_results(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,assessment_version_id uuid NOT NULL,dimension text NOT NULL,readiness_band text NOT NULL,evidence_confidence text NOT NULL,hard_gates text[] NOT NULL DEFAULT '{}',evidence_refs jsonb NOT NULL DEFAULT '[]',missing_evidence text[] NOT NULL DEFAULT '{}',rationale text[] NOT NULL DEFAULT '{}',contradictions text[] NOT NULL DEFAULT '{}',remediation_requirements text[] NOT NULL DEFAULT '{}',what_would_change text[] NOT NULL DEFAULT '{}',FOREIGN KEY(assessment_version_id) REFERENCES public.assess_application_assessment_versions(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS public.assess_application_modernization_recommendations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,assessment_version_id uuid NOT NULL,disposition text NOT NULL,affected_processes jsonb NOT NULL DEFAULT '[]',affected_primitives jsonb NOT NULL DEFAULT '[]',why text[] NOT NULL DEFAULT '{}',alternatives_considered text[] NOT NULL DEFAULT '{}',alternatives_rejected text[] NOT NULL DEFAULT '{}',prerequisites text[] NOT NULL DEFAULT '{}',required_controls text[] NOT NULL DEFAULT '{}',migration_boundary text NOT NULL,dependency_impacts text[] NOT NULL DEFAULT '{}',rollback_strategy text NOT NULL,evidence_confidence text NOT NULL,open_evidence_gaps text[] NOT NULL DEFAULT '{}',what_would_change text[] NOT NULL DEFAULT '{}',FOREIGN KEY(assessment_version_id) REFERENCES public.assess_application_assessment_versions(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS public.assess_application_review_resolutions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,application_id uuid NOT NULL,metadata_version_id uuid NOT NULL,assessment_version_id uuid NOT NULL,reviewer_id uuid NOT NULL,authorization_version bigint NOT NULL,resolution text NOT NULL CHECK(resolution IN('approved','changes_requested','rejected')),rationale text NOT NULL,receipt_id uuid UNIQUE REFERENCES public.assess_command_receipts(id) ON DELETE RESTRICT,audit_event_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.assess_application_portfolio_snapshots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,snapshot jsonb NOT NULL,created_by uuid NOT NULL,receipt_id uuid UNIQUE REFERENCES public.assess_command_receipts(id) ON DELETE RESTRICT,audit_event_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.assess_application_import_receipts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,actor_id uuid NOT NULL,idempotency_key text NOT NULL,payload_hash text NOT NULL,success_count int NOT NULL DEFAULT 0,rejection_count int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(org_id,workspace_id,actor_id,idempotency_key));
CREATE TABLE IF NOT EXISTS public.assess_application_import_row_outcomes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL,workspace_id uuid NOT NULL,import_receipt_id uuid NOT NULL,row_number int NOT NULL,outcome text NOT NULL CHECK(outcome IN('success','rejected')),application_id uuid,error_code text,error_message text,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(import_receipt_id) REFERENCES public.assess_application_import_receipts(id) ON DELETE RESTRICT);
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['assess_application_assets','assess_application_metadata_versions','assess_process_application_links','assess_application_dependencies','assess_application_assessment_versions','assess_application_dimension_results','assess_application_modernization_recommendations','assess_application_review_resolutions','assess_application_portfolio_snapshots','assess_application_import_receipts','assess_application_import_row_outcomes'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t); END LOOP; END $$;
CREATE OR REPLACE FUNCTION public.pr1g_execute_application_command(p_org_id uuid,p_workspace_id uuid,p_actor_id uuid,p_request_id uuid,p_command_type text,p_expected_version bigint,p_authorization_version bigint,p_idempotency_key text,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN RAISE EXCEPTION 'PR1G_PRIVATE_RPC_REQUIRES_SERVICE_IMPLEMENTATION'; END; $$;
REVOKE ALL ON FUNCTION public.pr1g_execute_application_command(uuid,uuid,uuid,uuid,text,bigint,bigint,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.pr1g_execute_application_command(uuid,uuid,uuid,uuid,text,bigint,bigint,text,jsonb) TO service_role;
