import { handleOptions } from '../_shared/http.ts';
import { decodePilotOperationsCommand, authorizePilotOperationsCommand, canonicalPilotOperationsPayload, PilotOperationsCommandError } from '../_shared/pilotOperationsCommand.ts';
import { getAuthUser, supabaseEnv } from '../_shared/supabase.ts';
import { createTenantAuthorityDatabase } from '../_shared/tenantAuthorityDb.ts';
import { resolveTenantAuthority } from '../_shared/tenantAuthority.ts';
import { decodePilotOperationsFailure, pilotOperationsFailureStatus } from '../_shared/pilotOperationsErrors.ts';
declare const Deno:{env:{get:(key:string)=>string|undefined};serve:(handler:(request:Request)=>Response|Promise<Response>)=>void};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
Deno.serve(async request=>{const options=handleOptions(request);if(options)return options;if(request.method!=='POST')return json({code:'ACCESS_DENIED'},404);
  try{const actor=(await getAuthUser(request)).id;const command=decodePilotOperationsCommand(await request.json().catch(()=>null));
    const authority=await resolveTenantAuthority(actor,{organizationId:command.organizationId,workspaceId:command.workspaceId,expectedAuthorizationVersion:command.expectedAuthorizationVersion},createTenantAuthorityDatabase(request));authorizePilotOperationsCommand(command,authority);
    if(Deno.env.get('PILOT_OPERATIONS_ENABLED')!=='true')return json({code:'FEATURE_DISABLED'},503);
    const {url,serviceRoleKey}=supabaseEnv();const response=await fetch(`${url}/rest/v1/rpc/pilot_operations_command`,{method:'POST',redirect:'error',headers:{apikey:serviceRoleKey,Authorization:`Bearer ${serviceRoleKey}`,'content-type':'application/json'},body:JSON.stringify({p_actor:actor,p_org:command.organizationId,p_workspace:command.workspaceId,p_operation:command.operation,p_request:command.requestId,p_idempotency_key:command.idempotencyKey,p_request_payload:canonicalPilotOperationsPayload(command),p_authorization_version:command.expectedAuthorizationVersion,p_expected_version:command.expectedVersion??null,p_payload:command.payload})});
    if(!response.ok){const code=await decodePilotOperationsFailure(response);return code?json({code},pilotOperationsFailureStatus(code)):json({code:'PERSISTENCE_UNAVAILABLE'},503)}return json(await response.json());
  }catch(error){const code=error instanceof PilotOperationsCommandError?error.code:error instanceof Error&&error.message==='AUTHORIZATION_STALE'?'AUTHORIZATION_STALE':'ACCESS_DENIED';return json({code},code==='AUTHORIZATION_STALE'?409:code==='LIVE_ACTIVATION_NOT_AUTHORIZED'?403:400);}});
